### ISSUE TITLE
edit person record

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#10]
As a content editor, I want to create and edit person records so that I can document biographical details about people associated with Sylvia Beach's lending library.

Should include the following:
* first & last name, title
* profession
* Nationality
* Sex
* VIAF number
* notes

**Comment by elspethgreen** [comment]
I'm still having a little trouble with the VIAF stuff--might be just because I tried to re-load "Hilda Doolittle's" VIAF to check whether her dates auto populated.  The search function is now having a hard time finding her in VIAF: the record it found is bare-bones, and different from the one it found before, and has no dates associated with it.

If it works for other testers, it's probably just because I messed with the same record before/after RSK changed the auto-populate feature!

**Comment by rlskoeser** [comment]
@elspethgreen drat, I tested on your Hilda Dolittle record and got zeroes showing up for the dates. Still needs a little more clean-up on my end!

**Comment by rlskoeser** [comment]
Test site is updated now, so it's no longer setting zero dates for birth/death when VIAF doesn't have them.

**Comment by i-davis** [comment]
Here's a question to which I feel I should already know the answer: when we edit a person's record, is the "Notes" section a place where we could note the changes that we've made? I went ahead & changed "Miss Barney" to Natalie Clifford Barney, e.g. ("Miss Barney" is mentioned on Anna Wickham's & Dorothy Wilde's cards; Wilde was her partner for a long time, & Wickham loved her, so it seems like a safe bet Natalie Barney is Miss Barney.) I added her first name, VIAF, & address to her record.

Re VIAF (@rlskoeser): I've been having a problem where when I add someone's VIAF # I can save it & it stays there. But then if I edit that person's record again elsewhere (add a note or an address, for instance), the VIAF number disappears. Anyone else having this issue?

**Comment by rlskoeser** [comment]
@i-davis it's really up to you all how you want to use the notes.  You may want to come up with some guidelines for what kind of thing is worth documenting there.  That is the place to document any data reasoning or research you want to document - zenhub/github comments from now on should generally be related to the code and functionality, not the content.

When you have a specific resource that provides documentation or support for editing a name or associating addresses, I recommend you add that as a footnote rather than a note, so it's available in a more structured way.

Thanks for reporting the VIAF issue!  I must have introduced a new bug because I don't remember that happening before.  I don't think it matter what you do, if you load a record with a VIAF id and hit save (whether you have changed anything or not), the VIAF id disappears.  I'll look into it right away, I expect it's something simple.

**Comment by rlskoeser** [comment]
@elspethgreen sorry, somehow I think I missed this comment:
> I'm still having a little trouble with the VIAF stuff--might be just because I tried to re-load "Hilda Doolittle's" VIAF to check whether her dates auto populated. The search function is now having a hard time finding her in VIAF: the record it found is bare-bones, and different from the one it found before, and has no dates associated with it.

I switched to a different VIAP api search than the one I was using before because the other one didn't support search on numeric VIAF id.  It seems like maybe the search isn't as good?  Or maybe it just behaves differently because it's searching on more fields.  It's hard to tell, and the VIAF api documentation isn't super helpful in this regard.

**Comment by rlskoeser** [comment]
@elspethgreen I made some tweaks to the viaf search parameters; it looks to me like the results are much better now, so please test again.

**Comment by elspethgreen** [comment]
Yes!  The VIAF record for Hilda Doolittle with her dates came up this time, so whatever you did worked!
