### ISSUE TITLE
As a global admin, I want a CSV export of bibliographic item data so that I can track data work and explore bulk data enhancements.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#100]
## Notes for testing
- Go to bibliography -> items.  You should see a link to download csv at the top right.
- Download should include db id, admin edit link, title, mep id, author, notes (editor and translator have been omitted for now because they were making the download too slow)
- Test adding authors to at least one record to ensure they are included in the export

## Notes for development
- should include an admin edit link
- include basic item data currently available for editing (title, year, mep id, author, ~editor, translator,~ notes)

**Comment by elspethgreen** [comment]
This looks great!!
