### ISSUE TITLE
restrict people-accounts relationship to foreign key

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#101]
- person has exactly one account
- accounts can belong to multiple people

this means `Person` should have a foreign key relationship to `Account` rather than a many-to-many. if this is hard, we can try to enforce it using frontend validation, but if not, we can go ahead and restrict it to a FK.

**Comment by jkotin** [comment]
I don't think the constraint is a priority.  Am I correct in assuming that the constraint is mainly to help us avoid introducing errors?

J
