### ISSUE TITLE
Bug-- auto-populate sort-name function acting up

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#102]
If I type in more than two words ("Ellie Green," for example) the sort name displays "ellie-green" rather than blanking out.  If I type "Green," the sort name comes out lowercase "green," where it should be upper case.

**Comment by elspethgreen** [comment]
This seems to be working now on the test site, but not on the production site.

**Comment by rlskoeser** [comment]
Ah. It's working on test because we're running the site in DEBUG mode (which we don't do in production).  I'll update the test site so it matches production better.

**Comment by rlskoeser** [comment]
@elspethgreen but thanks for letting me know - that helped me figure out what the problem was much faster than I might have otherwise!

**Comment by rlskoeser** [comment]
Site is now running with DEBUG mode turned off (to more closely mirror production), and I have a fix in place.

**Comment by elspethgreen** [comment]
@clmahoney would you take a look at this on the test site?  When you type a single word, it should autopopulate in the sort-name field (capitalized!).  When you type more than one word, the sort-name field should blank out, requiring you to enter the sort name manually.

**Comment by i-davis** [comment]
This is also looking good to me!
