### ISSUE TITLE
As a content editor, I want the option of merging people without accounts so that I can merge records for creators who were accidentally entered twice.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#109]
## notes for testing
- if you merge people into someone without an account, you shouldn't receive an error
- if you merge multiple people with accounts into someone without an account, the first merged account will become the primary person's new account, and all subsequent merged accounts will have their events and addresses transferred to the "new" primary account
- if you merge people and no one involved has an account, you should get a success message saying that the person merge was completed but no accounts were merged
- if you merge someone who is a creator into someone else, the primary person should become the creator instead, and you should be notified in the success message

## Notes for development
Currently person merge function errors if person has no account; relax that restriction to allow merging even if either or both do not.

**Comment by thatbudakguy** [comment]
@elspethgreen  OK, this is finally ready...apologies for slowness.

**Comment by elspethgreen** [comment]
I've tested each of these scenarios and they seem to be working fine--I love the dialogue it produces in the top describing what's happened.  Good to go I think!
