### ISSUE TITLE
As a content editor, I want to enter negative birth and death years so I can track biographical data for authors like Euripides.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#111]
## testing notes
- you should be able to enter a negative year in either part of the date range
- if a negative year was entered, it should display in the system with "BCE" next to it
- ranges that are entirely BCE should say "BCE" at the end rather than repeating it
- ranges that span from BCE to CE should include "CE" for clarity
- zero shouldn't be BCE

## Notes for development
- switch from `PositiveIntegerField` to an integer field that allows negatives
- unfortunately, this type is set in our common `DateRange` model, so we'll have to decide whether to change this for _everything_ that uses it or override just for people

**Comment by thatbudakguy** [comment]
as far as I can tell, `DateRange` is only ever used on `Person` anyway, so that makes the change easier. 

I'll alter it to use `SmallIntegerField` (sadly, this means `DateRange`s won't be effective for people born after the year 32,767, but I think we can live with that).

**Comment by elspethgreen** [comment]
This looks great!

A question--right now, there doesn't seem to be any error message if I put in a death date that's earlier than the birth date.  We didn't ask for this (didn't occur to me until just now) but it might be a good thing to add in the future, just to stave off any careless typing errors.

**Comment by rlskoeser** [comment]
@elspethgreen thanks for letting us know about the lack of date validation! Nick pointed out to me that we had code for this, but it wasn't ever getting run. I'll correct that.
