### ISSUE TITLE
As a content editor, I want to see and sort on the date an item or person record was last updated so I can easily find recently edited records.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#112]
## notes for testing
- there should be an "updated at" field in the list view of the admin site for `Item`s and `Person`s
- you should be able to sort by this field
- for now, they'll all be set to whatever date/time at which the tracking initially took effect. as more changes occur, the timestamp will automatically be updated.

## Notes for development
- add an updated field with `auto_now` to `Item` and `Person`
- add updated field to list view for both `Item` and `Person`

**Comment by clmahoney** [comment]
This looks good to me!
