### ISSUE TITLE
Merging into a logbook only person deletes associated bibliography if present

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#119]
## Notes for testing
- On the test site, select two people from the list view. You should select one person with a card and one person without.  Choose "merge selected people" from the dropdown menu at the bottom of the page.  
- On the review page, choose the person who does _not_ have a card as the primary record, and then merge.
- The card associated with the merged account should now be associated with the primary account.

## Notes for development
When merging two people, if the account of the person being merged in has an associated card bibliography (`Account.card`), it is deleted along with the account, which also removes any (`Footnote`) objects associated with the bibliography.

To reproduce: merge any account with a card association into a logbook account. The account and its associated bibliography will be deleted.

N.B. This would also result in merging two card accounts losing that information for the merged account, but that may be intentional and out of scope.

**Comment by rlskoeser** [comment]
In addition to moving the card over from one account to the other, the account foreign key to bibliography should be configured so that the bibliography record isn't removed if the account is deleted.  (Since it could be referenced by other things, and removing it necessarily removes all associated footnotes.)

**Comment by elspethgreen** [comment]
I think this is working--I ended up with a record that contained both subscription events and had "has card" checked, which I think is correct--but I'm wondering if, as a failsafe, there could be an indication on the review page that a record has or doesn't have a card?  I found it surprisingly easy to forget which record I wanted to set as primary.

**Comment by rlskoeser** [comment]
@elspethgreen good point! Just updated the merge review page to display the card reference if there is one, or indicate no associated card if there is an account but no card.

**Comment by clmahoney** [comment]
This looks good to me!
