### ISSUE TITLE
content editor group

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#12]
Create a fixture & migration to create a content editor group and assign the appropriate permissions.

**Comment by elspethgreen** [comment]
I've created a "content editor" group with appropriate permissions and added Ian to it.  When I click on the group, though, it doesn't display its members--just offers the option to revise permissions.  Would it be possible to display current members of a group, or maybe even have a column on the list of users that says which group they're affiliated with?

**Comment by rlskoeser** [comment]
There should have already been a content editor group loaded with the appropriate permissions already defined.  When I look on the test site, it doesn't look like Ian is a member of that group - not sure what went wrong.

I did customize the user listing to display group memberships for people, so hopefully that will help with managing user accounts and permissions.

**Comment by elspethgreen** [comment]
I've now added Ian and Cate to the group, and it shows up in the list of people!  Does it look right on your end now?

Also, how exactly does group membership interact with permissions?  When I added Ian and Cate to the group, it didn't seem to change anything about their listed "permissions" at the bottom--even when I tested removing their "superuser" status.  I don't really want to rob them of permissions, so I don't want to un-toggle superuser for too long, so it's possible I just didn't save it right.

**Comment by rlskoeser** [comment]
@elspethgreen anyone in a group gets all the permissions associated with that group, although they won't appear in the user permissions list.  You can also combine group and user permissions if you ever want to.  The predefined group was meant to be an easy way to add new researchers to the team so you don't have to manually go through and assign permissions to everyone or make everyone superusers.

If you want to play with the permissions a bit more so you're comfortable with managing accounts and can see exactly what a non-superuser member of the group will be able to access, you can create a test user account and trying out some different permissions.  (I recommend using two different browsers so you don't have to keep logging in and logging out.)
