### ISSUE TITLE
Footnote editing causes a server error

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#120]
## Notes for testing
- Try editing a borrow event and adding a footnote. You should be able to add a new footnote without problems.  
- Footnote checkbox for "supports" now defaults to true.
- You'll also note that the display is slightly different than production: I've added more fields, that were previously suppressed with the goal of simplifying things, but that was actually contributing to this problem.

## Notes for development
Noticed this when trying to add a footnote to a borrow event, but probably happening everywhere.  

```
IntegrityError at /admin/accounts/borrow/31121/change/
(1048, "Column 'is_agree' cannot be null")
```

Should probably set a default value for the boolean `is_agree` field.

**Comment by clmahoney** [comment]
This looks good! It saves.
