### ISSUE TITLE
As a content editor, I want to add partial start-end date information for addresses so I can document the dates when only the month or year is known.

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#121]
## Notes for testing
When editing addresses on either accounts or persons, start and end dates should support partial date entry (works the same way as elsewhere).

---
Hello everyone!  Just something to think about whenever we do another update: I was playing around with entering some addresses for James Joyce today, and noticed that the start-end dates require complete day-month-year info to be valid.  In many of these cases, we'll be lucky to know the month, so it would be great to have the same partial date capability as for the borrowing events.  Thanks!

**Comment by rlskoeser** [comment]
Previous work to generalize partial date logic made this trivial to add. Re-estimating from 2 to 0.

**Comment by clmahoney** [comment]
I've tested this and I can add partial dates: I did this with John Abbe's address. The only problem is that I put in an address at random, but now when I try to delete it I can't save the page without an address, so Abbe is associated with a false address! How do I fix this?

**Comment by rlskoeser** [comment]
@clmahoney it doesn't really matter if we have junk data in the test database (we wipe it out and update with a fresh copy from production every so often anyway). However, we should make sure that you are still able to delete addresses! Did you use the X on the right side of the row for the address you want to remove? You should be able to click X to select the row to remove and then save the record to confirm the removal (and any other changes).

**Comment by clmahoney** [comment]
I clicked the X but it won't let me save without a location! I'll put in a screenshot of what's happening.

**Comment by clmahoney** [comment]
![Screen Shot 2019-04-23 at 5 07 09 PM](https://user-images.githubusercontent.com/16673934/56616021-7b7c3100-65ea-11e9-9f9a-ff01d1ee3bb3.png)

**Comment by rlskoeser** [comment]
Confirmed in person with @clmahoney that the address could be removed. Closing based on previous testing comments.
