### ISSUE TITLE
As a content admin, I want to export information about people in the database so I can work with it in other systems such as OpenRefine.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#123]
## testing notes
**note:** because this export functionality was also retroactively applied to the books export tool, we need to test both tools. repeat these steps on both the [items list page](https://test-mep.cdh.princeton.edu/admin/books/item/) and [people list page](https://test-mep.cdh.princeton.edu/admin/people/person/).

1. From the list page, check that a "Download all as CSV" button appears in the upper right (near "Add Item"). Click it.
2. You should get a prompt to download a CSV file. Accept and wait while the file is streamed - this could take a while! If it takes more than 1-2 minutes, something is wrong.
3. Check that the filename of the CSV matches what you were downloading and contains a timestamp, e.g. `mep-people-20180920...` etc.
4. Open Excel (but don't open the file itself yet!). Create a new workbook, then choose File -> Import and pick CSV file. Choose the file you downloaded.
5. Leave the data on the "Delimited" setting. Under "File origin", choose "Unicode (UTF-8)", towards the bottom of the list.
6. On the next screen, ensure only "comma" is checked as a delimiter. The preview should look like a normal spreadsheet. You can click through and finish the wizard without changing anything else - import the data into your existing sheet in the new workbook.
7. Skim through the imported data and check that item titles, person names, etc. appear correct, including special characters (for example, Tolstoy's name includes Cyrillic text). Ensure that all the relevant fields are present.
8. If everything looks right, go back to the admin interface for the model you're testing (books or people).
9. Select a subset of your results. You can do this using a combination of the checkboxes in the list and the filters at the top right (for example, try filtering people to just Creators, then clicking the top-left checkbox to select the whole page, and finally clicking "Select all 2443 people" at the bottom left to select all Creators).
10. At the lower left, find the dropdown that says `-------------` and from it choose "Export selected to CSV". Click "Go".
11. From this point, you can repeat steps 2-7. Everything about the process should be identical, except the data included in the download, which should match what you selected. Smaller subsets (a few to a few hundred items) should download much more quickly.

## notes for development
- Create a new view to generate a CSV export of people. Include the following fields:
  - name
  - sort name
  - mep id
  - birth year
  - death year
  - sex
  - title
  - profession
  - is organization
  - updated at
  - notes
  - is creator (author or other creator of items in the library)
  - has account (is a library member)
  - in logbooks (has subscription or reimbursement events)
  - has card (account has an associated library lending card)
- Add a button to people admin view to download the report

**Comment by elspethgreen** [comment]
Should we include the new "is verified" field in this export?  If it would be easy to add, maybe we might as well--just in case we find a use for it in a later workflow.

**Comment by rlskoeser** [comment]
@elspethgreen I wondered about that when I added the new verified field. It is indeed easy to include - just updated the test site with a change to include that field in the CSV export.

**Comment by clmahoney** [comment]
I think this looks good!
