### ISSUE TITLE
As an admin, I want to generate a report of library members with large time gaps between events in their account history to identify records that may need demerging.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#124]
## Notes for testing
Generated report includes:
 - admin link to view all person(s) associated with account
  - account id and account holder's name
  - account date range overview
  - number of gaps found (to allow sorting)
  - duration of the longest gap in days (to allow sorting)
  - detailed note documenting the length of gaps and the event before and after that gap

## Notes for development
- Write a custom manage command to find people who match these criteria. Should take an option to set the time gap in months, maybe set the default to 6 months.  Iterate over generic events by date checking for timedelta larger than our configured gap.
- SQL queries can't do sophisticated timedelta calculations, so that logic should be implemented in python. If we have performance issues, we could possibly filter to find accounts with a timespan that is longer than our gap.
- We'll have to take care with partially known dates on borrowing events when calculating time gaps.

**Comment by rlskoeser** [comment]
Generated two reports, one with 6 months gap minimum and one with 12 months.  

[timegap-reports.zip](https://github.com/Princeton-CDH/mep-django/files/2402693/timegap-reports.zip)

**Comment by thatbudakguy** [comment]
note: added admin URLs to the export and temporarily ignored all borrowing events in: https://github.com/Princeton-CDH/mep-django/commit/be77f0a0ef1691d015ce32004340221e4bcacae9

**Comment by clmahoney** [comment]
This looks good!
