### ISSUE TITLE
account earliest_date and last_date methods don't account for partially known dates

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#129]
## Notes for testing
On the member list in production, some members show with 1900 as their earliest date (this is how we are internally storing dates with unknown year, based on the team's previous convention). For example, search for Louis Aragon and compare production with the test site.

Note that right now, results for people who _only_ have unknown dates will display the membership dates heading with no dates. I'd like to hold off on addressing the display issue until we have more data work done, because I'm not sure if this will still be a problem after personography merges and known dates are entered.

---

Not sure the best way to handle this. It's calculated based on generic `Event` dates; seems like it shouldn't have to be aware of borrow-specific event behavior. Should all events have partial dates, for consistency? But that probably makes date logic a lot more complicated in places where we don't need it....

Might be simplest to exclude partial dates based on the partial date flag, but not sure how to implement it elegantly.

**Comment by clmahoney** [comment]
This looks good! I looked up a couple (Joyce Reeves, Hamilton, and Aragon) and they are not displaying 1900 in the membership dates field, just a blank!
