### ISSUE TITLE
VIAF dates on import

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#14]
As a global admin, when personography data is imported I want birth and death dates populated from the XML if available or else from VIAF if an id is available, so that dates will be complete and corrected dates will not be lost on import.

- birth/death date in the xml should take precedence
- if birth/death dates are not in the xml but VIAF id is set, lookup dates and add them

**Comment by rlskoeser** [comment]
@jabauer data question: should we flag or track if we are overriding VIAF dates (i.e. when they are inaccurate or the record lists multiple conflicting values)?

**Comment by jabauer** [comment]
If it's a one time import: Drop something in the notes field along the lines of "correct dates from VIAF import"
If we plan on pulling from VIAF on a regular basis, then a flag would be necessary to make sure we don't overwrite corrections

**Comment by rlskoeser** [comment]
@jabauer documenting in a note sounds perfect, thanks for the suggestion.  I'll plan to document either way, e.g. something along the lines of "dates imported from personography.xml" or "dates added based on VIAF id".

**Comment by elspethgreen** [comment]
Quick question--when adding a new person record (I added Hilda Doolittle as Richard Adlington's wife), the birth/death dates didn't seem to auto populate even though H.D. has a VIAF record.  Is this right?

**Comment by rlskoeser** [comment]
It didn't autopopulate because I hadn't yet completed that feature - #16.  I just now had the time to do that, so I'll update the test site and mark it as ready for review soon.

For this story, you should only check that viaf ids and dates are populated properly on import.

**Comment by i-davis** [comment]
I just added George Antheil's VIAF id, & the dates automatically popped up; correctly, too. I'll try a few others too.
