### ISSUE TITLE
As a user, I want to see available demographic and library information (birth/death dates, nationality, membership dates, link to VIAF if available) for an individual library member, so that I can find out more about the person.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#141]
# testing notes
## background
we'll design test this whole page later when more parts of it (the address map, membership timeline, etc.) have been designed and implemented. for now, if you notice anything flagrantly wrong with the design, feel free to add a comment.
## instructions
- visit the [members list page](https://test-shakespeareandco.cdh.princeton.edu/members/) and pick a member.
- you should see the member's membership dates, birth/death date (if available), VIAF (if available), and nationality information (if available).
- try repeating with some members with more information and verify that everything looks right. you can use <kbd>ctrl</kbd><kbd>f</kbd> (or <kbd>⌘cmd</kbd><kbd>f</kbd> on mac) to search for a member's name on the list page since it's so long.

**Comment by clmahoney** [comment]
This is looking great!
