### ISSUE TITLE
As a user, I want to search for library members by name or partial name so that I can find specific people I’m interested in.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#142]
## notes for testing
Member list page now has a keyword search field. Supports standard solr query syntax, so recommend you try several things:
- searches on both name and sort name; check that you can find people by both (esp. those whose regular and sort names differ, e.g. Bryher
- currently matches any term you enter, so if you enter multiple different names you should get all of the people that match any of them
- by default, matches on whole word only; use wildcards * and ?. e.g.: `be*` should find anyone with a name starting with be; `a???` will find all the people with a four-letter name starting with a
- will search for exact phrase when you use quotes, e.g. `"gertrude stein"`
- you can use boolean operators in upper case (AND, OR, NOT); e.g. `beach AND sylvia` , `beach NOT sylvia`
- search is not case-sensitive

## dev notes
- configure solr config to add a name query field that searches both name and sort name (see PPA for an example)
- create simple search form with optional keyword input
- use form in the member list view, filter the queryset if keyword is set

**Comment by clmahoney** [comment]
This looks good! 
- searches on both name and sort name; check that you can find people by both (esp. those whose regular and sort names differ, e.g. Bryher --> YES this works (Tried Bryher) 
- currently matches any term you enter, so if you enter multiple different names you should get all of the people that match any of them --> YES this works (Tried james sylvia anne and got results for all members with these individual names) 
- by default, matches on whole word only; use wildcards * and ?. e.g.: be* should find anyone with a name starting with be; a??? will find all the people with a four-letter name starting with a --> YES this works (and I didn't even know what this search option was before this!)
- will search for exact phrase when you use quotes, e.g. "gertrude stein" --> YES works 
- you can use boolean operators in upper case (AND, OR, NOT); e.g. beach AND sylvia , beach NOT sylvia --> YES tried this with Joyce NOT James 
- search is not case-sensitive --> YES works
