### ISSUE TITLE
As a user, I want to browse a list of library members sorted alphabetically by last name so that I can see all the names of people known to have patronized the library.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#143]
## notes for testing
- navigate to test site url + `/members/` (or click 'members' link in main navigation)
- should list all library members from the database, based on associated account
- should be alpha by last name
- should include account membership dates
- people with known birth and death dates should have them listed also
- should link to detail page
- this does not include styles or pagination; those will be handled separately
- does not currently auto-update based on database edits (that will also be added later), but if you want to make a change and have us reindex to test, please let us know.

## dev notes
- this is pulling from solr.
- not sure how the pagination will ultimately interact with the rolodex; probably need to get more project team input on how the rolodex should behave.

**Comment by rlskoeser** [comment]
Should we separate pagination into a different story since we don't have a design for it yet?

**Comment by clmahoney** [comment]
All the info is here but under each name it just says "Account Dates" without data. Is that what you mean to add later? But everything is alphabetical and I see birth/death years where we have the info. Everything is a bit hard on the eyes right now, just in terms of the layout. 
![screen shot 2019-02-21 at 12 15 38 pm](https://user-images.githubusercontent.com/16673934/53188015-6d9e3580-35d2-11e9-93b0-6c435ee77ded.png)

**Comment by clmahoney** [comment]
Also they do link to detail page

**Comment by clmahoney** [comment]
Never you mind, I just realized I was testing wrong. This looks good!

**Comment by rlskoeser** [comment]
Thanks @clmahoney ! I can see how the layout I used without the actual styles would be confusing for testing, glad you figured it out.
