### ISSUE TITLE
Pagination design for interaction with members list rolodex

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#145]
there's no pagination in the old design, so we'll need to come up with something.

**Comment by thatbudakguy** [comment]
The idea I had for this is to just make the rolodex work like a filter, i.e.

- when you initially come to the page, you see a list of all the people, and the pagination just pages through them in pages of whatever size we want (say, 50)
- if you click one of the letters in the rolodex, you only see people whose last names start with that letter. the pagination pages through those people (there probably won't be more than one or two pages for each letter, in this scenario).
- if you click other filters, those get applied on top of the rolodex filter, narrowing down the current list of people even further.
- if for some reason we wanted to, it wouldn't be that difficult in this scenario to allow having multiple active rolodex filters that would use OR ("names starting with D _or_ F").

we would need to have a little bit of logic to translate the rolodex's letter into what solr would expect for that filter ("text field must start with this letter"), but I feel like that's probably doable?

**Comment by rlskoeser** [comment]
I think pagination design is complete now
