### ISSUE TITLE
Set up webpack for static asset management

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#147]
We'll need to pool our respective webpack configs to make something workable.

Webpack should:
- [x] extract scss from `<style>` blocks inside Vue SFCs to css (I have this working locally)
- [x] compile non-component related scss to css (e.g. header & footer snippets)
- [x] run autoprefixer on all styles
- [x] compile Vue SFCs to es5
- [x] compile non-Vue es6+ to es5 (there will likely be some, probably for menus and such)
- [x] let us unit test Vue components (ideally with Jest?)
- [x] let us unit test non-Vue JS with the same setup
- [x] report test coverage
- [x] bundle sourcemaps
- [x] create separate bundles for the main js (non-search pages) and the search page js (vue)
- [x] run a dev server (with hot reload?)
- [x] minify bundled assets

**Comment by thatbudakguy** [comment]
|                              | **dev**                      | **qa**         | **prod**         |
|------------------------------|------------------------------|----------------|------------------|
| command                      | `npm start` or `npm run dev` | `npm build:qa` | `npm build:prod` |
| hot reload                   | ✅                            |                |                  |
| generates files in `/static` |                              | ✅              | ✅                |
| minifies files               |                              | ✅              | ✅                |
| generates sourcemaps         | ✅                            | ✅              |                  |
| autoprefixes css             | ✅                            | ✅              | ✅                |

**Comment by rlskoeser** [comment]
This is done, yes? Should we wait to close until we've confirmed it works in QA?

**Comment by thatbudakguy** [comment]
Closing since it works in QA.
