### ISSUE TITLE
Site header markup & styles

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#149]
## testing notes
- includes the header styles that appear on the about/analysis/sources pages (with the center "ribbon"). you can test this by going to the about or members pages from the main menu.
- also includes the header styles that appear on the homepage.
- also includes the header styles that appear on members, cards, and books list pages.
- doesn't include the main navigation or its behavior.

**Comment by wafaisfahany** [comment]
Looks good
