### ISSUE TITLE
Site footer markup & styles

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#150]
### designs
[desktop](https://zpl.io/brWKKRO) / [tablet](https://zpl.io/2jvLq0p) / [mobile](https://zpl.io/V1z44gm)

- footer should be "sticky" (pushed to the bottom of the page on short pages, but accommodates longer pages normally). try going to the [homepage](https://test-mep.cdh.princeton.edu/) vs the [about page](https://test-mep.cdh.princeton.edu/about/) to see this in action.
- links in the footer should go to the correct places, if those places exist (accessibility links, clicking on the logos, etc).
- arrangement of items won't be pixel-perfect; I used flexbox to come up with a reasonably spaced approximation. trying to make it match spec exactly would have taken far too much time and css.
- order of items in the last line doesn't match spec; there's no way to reorder them without using grid and doing a lot of extra stuff that we don't need. I think we can live with this order.

## dev notes
- includes the main site nav, which isn't user-editable (first column in the footer)
- includes a mocked version of the user-editable secondary nav (second column in the footer)

**Comment by wafaisfahany** [comment]
looks good!
