### ISSUE TITLE
Site main navigation markup, styles & interaction

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#151]
## testing notes
**designs**
[desktop](https://zpl.io/awWwe1j) / [tablet](https://zpl.io/agP5dND) / [mobile](https://zpl.io/2jvdxwm)
[desktop expanded](https://zpl.io/aNppOZk) / [tablet expanded](https://zpl.io/29ZPdoA) / [mobile expanded](https://zpl.io/aMmmXBK)
- the menu should appear/disappear when you expect it to (clicking the buttons).
- the home button and "members" and "about" links should work.
- ~I added a slight opacity change when you hover over the menu or home buttons (they have a filled-in white background). this isn't super perceptible but I think it helps a little to know when you're in the right place. @gissoo might have input on this.~ confirmed this is OK.
- everything should function normally if you turn off javascript - [instructions for various browsers](https://www.computerhope.com/issues/ch000891.htm), with the exception that `#main-menu` might get added to the URL, and the page might be scrollable when it shouldn't (this is acceptable).

**Comment by wafaisfahany** [comment]
The menu page on the tablet version does not scroll all the way to the bottom - cannot click on "About" option

**Comment by thatbudakguy** [comment]
after playing with this a little more, I think we need to test it on an actual tablet to verify - I don't think any "real" device screen sizes will display this problem, since it has to do with the page height on load being much smaller than the width.

**Comment by thatbudakguy** [comment]
confirmed this isn't an issue on a real iPad, so going to close it.
