### ISSUE TITLE
As a content editor, I want to create and edit content pages on the site so that I can update text on the site when information changes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#157]
# testing notes
## background
this feature adds a new content management system (CMS) section to the site. you can access it at <https://test-shakespeareandco.cdh.princeton.edu/cms/>; and when in production the URL will be similar (it will have `/cms`) at the end. The CMS handles "content pages", i.e. those that have text written and edited by the users of the site (you) instead of the developers. This includes the homepage, "about" and "sources" pages, and eventually all of the posts in the "analysis" section as well. we are using Wagtail CMS, which has [a guide for content editors](http://docs.wagtail.io/en/v2.4/editor_manual/index.html) if you want to read more about it.

## instructions
to log into the system, click the orange "log in with princeton CAS" button and log in using your netid and password. your user account should already be in the system.

click "pages" on the left sidebar to navigate through the page hierarchy of the site. you should see that all pages are grouped under the homepage; click the arrow next to a page to move further down in the hierarchy.

if you click the pencil next to any of the pages, you'll arrive at the page editing interface, where you can add new content for the page. you can use this "stream field" interface to add blocks of different types of content to the page - see [the wagtail guide](http://docs.wagtail.io/en/v2.4/editor_manual/new_pages/creating_body_content.html) for more info. trying adding some blocks with different types of content!

to create a new page, find the page in the hierarchy that you'd like to create it under and click it. this will bring you to a list of child pages for the page you selected, and you can choose "create child page" at the top. currently, "landing pages" ("sources", "about") are always under the homepage, and regular content pages (e.g. "contact") are always under a landing page. wagtail should select the right type of page for you automatically.

when you're done working on a page, you can save it as a draft, or publish it to be live on the web using the controls at the bottom. you can also preview a page as you're editing it by clicking the "preview" button.

ultimately, you should be able to:
- log into the system
- edit a page
- create a page
- publish your changes and see them on the site

# dev notes
Basic wagtail functionality for content pages (not including analysis section)

- [x] undo mezzanine + grappelli harmonization
- [x] remove mezzanine as a dependency
- [x] create new app with wagtail page model and basic template

**Comment by clmahoney** [comment]
OK this is what happens when I try to log-in: 

![screen shot 2019-02-15 at 12 20 14 pm](https://user-images.githubusercontent.com/16673934/52873290-9f1f8880-311c-11e9-8831-88977b78167d.png)

**Comment by clmahoney** [comment]
I can't get past the login page

**Comment by clmahoney** [comment]
![screen shot 2019-02-15 at 12 25 06 pm](https://user-images.githubusercontent.com/16673934/52873340-bfe7de00-311c-11e9-9b05-b99819b2176f.png)

**Comment by clmahoney** [comment]
Yes this is great! Lookin' fly. 
(perhaps "fly" is inappropriate but that's what came to mind)
