### ISSUE TITLE
Template & styles: content pages

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#158]
# testing notes
### homepage
[desktop](https://zpl.io/bzAOe48) / [tablet](https://zpl.io/VQKNYom) / [mobile](https://zpl.io/2G9jQzW)
### landing page
[desktop](https://zpl.io/25G4qwQ) / [tablet](https://zpl.io/and3KQO) / [mobile](https://zpl.io/V4QN1xQ)
### content page
[desktop](https://zpl.io/VxR3YJw)
## instructions
for testing the smaller screen sizes on a content page, text styles should look the same as on a landing page. currently the landing pages are "about" and "sources", and the content pages live under those, e.g. "cards" under "sources".
# dev notes
- [x] link style: green underline, green darkens on hover
- [x] paragraph and footnote styles (use the * one on the homepage)
- [x] styles for the "intro" on all pages -> this is actually the main content, oops!
- [x] template for content pages
- [ ] uploaded images are used as header image for landing pages (& homepage?)

**Comment by wafaisfahany** [comment]
-Text under Sources page :"Learn about the lending library cards and logbooks." italicised on test site - not italicised in Zeplin copy 

Desktop:
- Does it matter that the text directly under "about" page is different on Zeplin and test site? 
-Contents under "About" landing page different from Zeplin Copy. 

Rest is all good!

**Comment by thatbudakguy** [comment]
@gissoo updated the zeplin styles to reflect that these should all be italic. I think the text content is just for example purposes mostly, so differences are ok. going to close this.
