### ISSUE TITLE
As a content editor, when I edit a person and add or change the VIAF ID, I want the birth and death dates in the system populated from data available in VIAF in order to make data entry more efficient.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#16]
~- [ ] display viaf number in autocomplete results~
- [x] fix interface so viaf uri displays after being selected
- [x] allow search/entry by viaf number
- [x] make it possible to clear a selected viaf uri

Testing suggestions:
- [ ] Add a VIAF entry to a person
- [ ] Clear it and then set it again

**Comment by elspethgreen** [comment]
Yes looks good

**Comment by i-davis** [comment]
looks good to me too!

**Comment by elspethgreen** [comment]
The VIAF search still seems a little funky.  I tried looking up "Armstrong" (while in the "Miss Armstrong," #arms record) and got results for "Alexander the Great" and "Baha u Ilah" before "Louis Armstrong."

**Comment by rlskoeser** [comment]
@bwhicks please take a brief look at the VIAF search and see if you can duplicate this or easily improve it any beyond what I did.  I switched it from the standard VIAF lookup to support searching by VIAF number, and I think maybe the search sorting isn't as good.  (The documentation isn't great either.)

**Comment by bwhicks** [comment]
@elspethgreen @rlskoeser I can't get the SRU search to produce any better search results. If it were without the VIAF number, autosuggest makes great suggestions, but they don't document how it produces this. If VIAF number lookup is crucial, this is the best solution I can see right now.

**Comment by bwhicks** [comment]
@rlskoeser @elspethgreen Closing this one because I think it's as good as it's going to get.
