### ISSUE TITLE
add/edit countries

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#17]
As a content editor, I want to add and edit countries so I can manage the list of countries available for documenting people’s nationalities.

**Comment by elspethgreen** [comment]
Successfully added country (Mexico), which then turned up in the list of available nationalities.

Two questions:
1.  If the ISO code is necessary, should we think about automatically generating it?  The application demanded that I input a two-letter code, but I entered "it" for Mexico and was able to save the entry.
2.  What is the logic behind the order of the dropdown nationalities?  Should it be alphabetical?

**Comment by rlskoeser** [comment]
@elspethgreen good questions.

I think I didn't specify any order on nationalities; alphabetical sounds sensible.

Regarding country code: I thought about loading all the countries, but didn't want to clutter the database and interface with countries that aren't relevant.  What if we made this an autocomplete so you type the beginning of the name, select from a list, and country name and code are automatically populated?

We could also make country code not required; but having some kind of code or identifier makes it much easier to do things with the data and helps ensure we keep things standard (i.e. might be harder to standardize later).

**Comment by elspethgreen** [comment]
The autocomplete idea sounds good to me!

**Comment by rlskoeser** [comment]
@elspethgreen I revised the country edit form after your feedback, the new version is on the test site - please check it out and see if it works better for what you need.  It still doesn't validate the country name and code, so you _could_ put something in wrong if you wanted, but I thought we might want some flexibility to handle things we're not thinking of right now, or to adjust a display label.

**Comment by rlskoeser** [comment]
@elspethgreen drat, I think maybe the new version is _not_ yet on the site because I had to rework some things and forgot.  I'll let you know when it is!

**Comment by elspethgreen** [comment]
Tried adding Mongolia--auto-populating country ID worked great!

One question, though: I had to type in the whole name ("Mongolia") before it would recognize it as a valid country.  "Mong" turned up no results.  This doesn't seem super intuitive, but we could easily get used to it.

**Comment by rlskoeser** [comment]
I noticed that too...  When I make the small fix for the viaf lookup, I'll see if there's a slightly different geonames query that would get better results on partial matches.  (I have the query set so it will only return countries, but I don't know why that would affect partial name searching!).  Otherwise, I'll add help text to indicate you need to type the full name.

**Comment by rlskoeser** [comment]
The test site is updated, now the geonames lookup is doing a name starts-with search and it seems to be getting much better results.

**Comment by elspethgreen** [comment]
Looks great!  Tried "tuv" and got Tuvalu, "mont" and got "Montenegro," etc.
