### ISSUE TITLE
As a content editor, I want to see a list of subscription events for people in the csv export so that I can make more informed decisions about merging people

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#171]
## dev notes
- this is a blocker for the person merge work.

## testing notes

In the admin people list, generate a new CSV (either with the button or via selecting only library members in filter, selecting that group via the check box on the upper left, then selecting all in lower left and choosing the CSV export from the dropdown). 

It should have a field called 'Subscription Dates' that lists a person's subscription start/end dates in chronological order.

**Comment by clmahoney** [comment]
Unfortunately when I do the export I still can't see subscription dates. I'm going to tag Ian in this too to see what he comes up with. @i-davis

**Comment by i-davis** [comment]
Afraid I can't see the sub dates either!

**Comment by clmahoney** [comment]
This is great! We can start our merge work!
