### ISSUE TITLE
As data editor I want there to be an autocomplete for footnote bibliography so that I can more easily enter purchasing events

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#172]
## Testing Notes

Look at the change/detail views for:

- Borrow
- Purchase
- Footnotes

In either the inline footnote panel at the bottom (or for Footnotes on their main editing page), you should see an autocomplete for Bibliography. 

Please choose one and test setting and saving a footnote with bibliography from the autocomplete (should be a case insensitive match for any word in the bibliography's note field). For the inline, you may also wish to add an extra inline footnote and set using that one.

**Comment by i-davis** [comment]
Hi! I'm afraid I can't see any difference in the footnotes functions; but I'm on the mep2/admin site. Should I be working from a different one?

**Comment by clmahoney** [comment]
Yes I'm with Ian on this. Should we be using a different site?

**Comment by clmahoney** [comment]
UNDERSTOOD! This works great.
