### ISSUE TITLE
TypeError on empty index: object of type 'SolrQuerySet' has no len()

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#179]
based on the trace it looks like parasol's L119 in `query.py` is hitting a `KeyError`:
```python
        return self.solr.query(**query_opts, wrap=False)['response']['numFound']
```
and then falling back to `len()`, which also fails.

**Comment by rlskoeser** [comment]
This should be resolved by the update to parasolr (released in 0.5.1) and error handling in the members list view.
