### ISSUE TITLE
add/edit professions

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#18]
As a content editor, I want to add and edit professions so I can categorize people associated with the library by their work.

**Comment by elspethgreen** [comment]
It took me a weirdly long amount of time to notice the "Save" feature at the bottom, but I think that's just me.  Function seems to work well!

**Comment by rlskoeser** [comment]
Great!  Yes, it may take a bit to get familiar with the interface and learn where the various buttons are and how things work.

**Comment by jkotin** [comment]
This looks good to me!  I have to think about how to delimit the number of professions.  Does CDH know about guidelines that might help me address this question?

**Comment by rlskoeser** [comment]
@jkotin you could use terms from an existing vocabulary, e.g. [marc relator](https://www.loc.gov/marc/relators/relaterm.html) - but that's limited to professions that relate to something that would be described in a bibliographic record, so may not be exactly what you want.

Using terms from an existing vocabulary could be beneficial for making the MEP content available as linked open data, but we don't have to do that (esp. if we can't find one that's a good fit).

**Comment by jkotin** [comment]
This is perfect!  I wanted something that was compatible.

Thank you,

Josh

**Comment by i-davis** [comment]
Both Cate & I have found the functionality utterly solid. We're wondering if we can start putting up some profession names, just to see how they stick & to start a conversation there? Guessing that's not a part of this functionality-testing period, tho?

**Comment by rlskoeser** [comment]
Feel free to put in some profession names and try them out, but be aware that the data in the test site isn't guaranteed to stick around (we may need to clear it out to test something).
