### ISSUE TITLE
 As a user, I want to browse a list of books so that I can see all the books known to have circulated through the library.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#182]
## dev notes
not sure what the default sort is, but likely it's alpha by book title?
## testing notes
- pagination will display what page you're on (e.g. `50-100`), but you currently can't use the controls. to test going to the next page, you can manually add `?page=2` (or any number) at the end of the url in the browser.
- styles for this are tested on #186 .

**Comment by clmahoney** [comment]
Looks great!
