### ISSUE TITLE
Books list: results template & styles

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#186]
### designs

[desktop](https://zpl.io/2p4ppWN) / [tablet](https://zpl.io/adp6QlK) / [mobile](https://zpl.io/a7OjmBR)

<s>as noted below, the search form and the pagination/sorting controls aren't ready to be tested yet - this is just for the styles of the list of results. to view a different page of results (you can try a few at random), add `?page=3` (or any page) to the end of the url in your browser.</s>

pagination is now working; you can use the "next" and "previous" buttons to page through results and check that they look right. to go to a particular page, select it from the dropdown and click the "go" button.

note that we also don't have data in the database yet for publishers or item formats ("Book", "Periodical", etc), so although those appear in the design they won't appear on any of the results yet.

## dev notes
- includes the template partial for search results, as well as the styles for each search result.
- doesn't include the search form.
- doesn't include sorting controls.
- doesn't include the separate view that serves this partial.

**Comment by wafaisfahany** [comment]
The 'next' and 'previous' buttons aren't showing on any screens ( desktop/tablet/mobile) 
Checked on both Safari and chrome. 

Also additionally: the "Sorted By" and "Displaying" tabs are overlapping weirdly. 
<img width="375" alt="Screenshot 2019-03-25 at 15 45 28" src="https://user-images.githubusercontent.com/47332262/54949265-0945fd00-4f15-11e9-92f8-ab762e496a7a.png">

**Comment by thatbudakguy** [comment]
agh, I updated this incorrectly - the next/previous buttons and stuff appear on the _members_ list, not here (yet). they should be on this page soon though!! sorry @wafaisfahany I'll just mark this ready once #191 is completed

**Comment by thatbudakguy** [comment]
ok @wafaisfahany this is ready now - sorry for the confusion. note that technically it isn't testing the page controls - just the search results. feel free to use/test the pagination stuff to get different results though.
