### ISSUE TITLE
As a user, I want to see and toggle my active search filters so that I can see how they affect my search.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#187]
# testing notes
## designs
[tablet & desktop](https://zpl.io/V1NEdXX) / [mobile](https://zpl.io/aR9O3PE)

**test this on both the members search and books search.**

1. visit the search page. there are no filters active by default, so the active filters list shouldn't be shown.
2. activate a few filters on the page. in particular, try:
- the "has card" checkbox on members
- any text facets like gender, arrondissement, etc.
- any range filter, like circulation date on books
3. when you activate filters, the active filters area should appear, including the "Selected Filters" text and "Clear All" buttons.
4. if you uncheck a filter or clear out an input, the buttons in the active filters area should go away.
5. if you click one of the filter buttons in the "selected filters" list, it should do the same thing as if you unchecked that option or cleared out that input.
6. if there are no more active filters, the selected filters list should hide itself again.
7. if you enter a number into one part of a range filter, the button in the selected filters list should show only that part of the range.
8. if you then enter a number into the _other_ part, the button should update its text to show both parts of the range on the same button.
9. clicking the button for a range filter should clear _both_ parts of the range.
10. clicking the "clear all" button should do what it says (and also hide the filters list).

if you load the page using a URL that already has some filters active, they should already be displayed in the active filters list, and they should work exactly the same as if you added them yourself. you can try this by:

1. toggling on a bunch of filters/ranges
2. copy-pasting the URL from the URL bar (it will be long, with a lot of options in it)
3. pasting that URL into a new window and hitting enter
4. the page should now load, with the same exact filters you had active when you copied the URL.
5. try some of the steps above to confirm that everything still works as expected.

# dev notes
- this includes the designed "clear all" button that removes all active filters
- note that it does _not_ clear any of the text inputs; just filters

**Comment by thatbudakguy** [comment]
upgrading this to a 5 since I hadn't been thinking about how to implement it to work without js - which it will need to do, so that the correct options are already rendered when the page is initially loaded.

**Comment by thatbudakguy** [comment]
bumping to 8 since we broke 1k lines of code on this feature!

**Comment by clmahoney** [comment]
Desktop: Members 
- YES, when I'm on the member search page without ANY filters selected, I don't see the "selected features" section underneath the filters
- YES, when I selected filters like "has card," "membership dates," "birth year," "gender," "nationality," and/or "Arrondissement," I see the "Selected Features" area appear and show what filters I have checked. I tried many combos, including: 
![Screen Shot 2020-05-14 at 10 22 03 AM](https://user-images.githubusercontent.com/16673934/81946005-d2c1ba80-95cc-11ea-8d09-5b0ce97089dd.png)
- YES, if I hit "clear all" OR if I X out the filters within the "Selected Filters" area OR if I uncheck the filter within the filter box itself, the results revert as expected 
- and YES, when I clear the filters, the "Selected Filters" area disappears 
- YES, if I enter in a number only in the first part of the range, the Selected Filters shows only the first part. But if I add to the latter part of the range, the filter shows that!

**Comment by clmahoney** [comment]
Desktop: Book search
- YES, when I'm on the book browse page without ANY filters selected, I don't see the "selected features" section
- YES, if I enter in a circulation date range, I see that appear in the "Selected Filters" area
- YES, if I enter only part of the date range, I see only part of it in the "Selected Filters"
- YES, if I clear the range, the filter disappears, DITTO if I hit "Clear All"

**Comment by clmahoney** [comment]
Tablet: Members
- YES, when I'm on the member search page without ANY filters selected, I don't see the "selected features" section underneath the filters
- YES, when I selected filters like "has card," "membership dates," "birth year," "gender," "nationality," and/or "Arrondissement," I see the "Selected Features" area appear and show what filters I have checked. 
- YES, if I hit "clear all" OR if I X out the filters within the "Selected Filters" area OR if I uncheck the filter within the filter box itself, the results revert as expected
- YES, when I clear the filters, the "Selected Filters" area disappears
- YES, if I enter in a number only in the first part of the range, the Selected Filters shows only the first part. But if I add to the latter part of the range, the filter shows that too. 

Tablet: Book search

- YES, when I'm on the book browse page without ANY filters selected, I don't see the "selected features" section
- YES, if I enter in a circulation date range, I see that appear in the "Selected Filters" area
- YES, if I enter only part of the date range, I see only part of it in the "Selected Filters"
- YES, if I clear the range, the filter disappears, DITTO if I hit "Clear All"

**Comment by clmahoney** [comment]
Mobile: Members
- YES, when I'm on the member search page without ANY filters selected, I don't see the "selected features" section underneath the filters
- YES, when I selected filters like "has card," "membership dates," "birth year," "gender," "nationality," and/or "Arrondissement," I see the "Selected Features" area appear and show what filters I have checked: 
![Image from iOS (13)](https://user-images.githubusercontent.com/16673934/81951251-ecfe9700-95d2-11ea-8f57-958ef212cdf9.png)
- YES, if I hit "clear all" OR if I X out the filters within the "Selected Filters" area OR if I uncheck the filter within the filter box itself, the results revert as expected
- YES, when I clear the filters, the "Selected Filters" area disappears
- YES, if I enter in a number only in the first part of the range, the Selected Filters shows only the first part. But if I add to the latter part of the range, the filter shows that too.


Mobile: Books: 
- YES, when I'm on the book browse page without ANY filters selected, I don't see the "selected features" section
- YES, if I enter in a circulation date range, I see that appear in the "Selected Filters" area
- YES, if I enter only part of the date range, I see only part of it in the "Selected Filters"
- YES, if I clear the range, the filter disappears
- YES, the filter disappears if I hit "clear all"

**Comment by clmahoney** [comment]
Loading a new page with lots of filters: 
- YES, if I had a lot of filters set and then copied and pasted that URL into a new window, the page loaded with all the filters I had already selected. I then toggled through different filters and all worked as expected!

**Comment by jkotin** [comment]
This is beautiful.
