### ISSUE TITLE
As a user, I want to view and navigate by breadcrumbs so I know where I am in the site hierarchy and can navigate to pages above the one I'm on.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#188]
# testing notes
this feature needs both design testing and acceptance testing; as such it **shouldn't be closed** until both @gissoo and @clmahoney sign off.

it is currently active on the test site on these pages:
- [members list](https://test-shakespeareandco.cdh.princeton.edu/members/)
- [books list](https://test-shakespeareandco.cdh.princeton.edu/books/)
- [member detail page](https://test-shakespeareandco.cdh.princeton.edu/members/2244/) (biography)

## acceptance testing (@clmahoney)
we're looking for a few things:
- the breadcrumb "trail" should be complete (everything is there).
- the breadcrumbs should be clickable links that take you to the page you would expect.
- the _last_ (active) crumb should **not** be a link; this is a usability thing.
- for the member detail page, we use a short form of the member's name as the label for the crumb. try a few members with long or weird names to see how it works. does this work the way you'd expect?

## design testing (@gissoo)
feel free to try as many combinations of the following as you have time for (but no worries if you only try one or a few!)

_browsers_: safari, chrome, firefox, edge
_devices_: mobile, tablet, small desktop (e.g. macbook air), large desktop (any large monitor)

you can leave notes as a comment at the bottom, please feel free to write anything that comes to mind, even if it's not something that is broken/wrong

# dev notes
- issue includes template, styles, and logic
- templates/styles are written and available in feature branch `feature/breadcrumb-nav` (may need to be fastforwarded)
- current page shouldn't be a link! this is a usability thing
- won't work on wagtail pages for now.
- tracking work on wagtail pages on #302 

```python
class RdfViewMixin():
rdf_type = schema:webPage
breadcrumbs = OrderedDict({ 'members': reverse() .... })
def as_rdf() -> rdflib graph
def get_breadcrumbs() -> self. breadcrumbs + ('any unique parts here')
def get_context_data():
   context['graph'] = self.as_rdf()
   context['breadcrumbs'] = self.get_breadcrumbs()
```

eventually this should respond to an `Accept: application/ld+json` header, perhaps added by middleware that itself responds to URLs like `/members.jsonld`. that work is tracked on #303

**Comment by thatbudakguy** [comment]
just an fyi that template styles for this are ready; they're in a feature branch `feature/breadcrumb-nav` waiting for someone to take it over & add functionality.

**Comment by rlskoeser** [comment]
Thanks for noting that. I started looking at the implementation but I thought it probably wasn't our highest priority. It would be nice to fold in sooner than later, so maybe we can suggest/request we do it in the next iteration?

I can't remember what we decided about user story + acceptance testing for this. Should we have an issue for the functionality or is it part of this issue?

**Comment by thatbudakguy** [comment]
I'm OK with it being part of this issue, and whoever tests it does both design and acceptance testing, since it's so small...but maybe we don't want to do that?

**Comment by clmahoney** [comment]
- Something really bizarre is happening with the Books page: large green triangles. Everything is huge. 
![Screen Shot 2019-05-23 at 12 15 55 PM](https://user-images.githubusercontent.com/16673934/58269004-8f839180-7d54-11e9-9b1a-942a27949c91.png)

**Comment by clmahoney** [comment]
- the breadcrumb trail all works 
- the breadcrumbs are clickable and take me back to the page I expect, although when I click backwards it does not retain the search I had made. For example, I narrowed members by gender, but when I clicked back it did not retain the gender search, I had to start again. Is there a way to retain the search I had made? 
- the last (active) crumb is NOT a link - as you explained
- tried a few long names (Alajouanine, Antoine-May, Baillon de Wailly) and I see them entirely in the breadcrumb - not shortened - but that looks good to me

**Comment by thatbudakguy** [comment]
you bring up an interesting point - to me, the breadcrumbs should work differently from the back button, in that they take you to that page but don't necessarily remember exactly what you did before (fwiw if you clicked the back button, it should go back to the search that you had).

not sure what other folks think though.

**Comment by thatbudakguy** [comment]
@rlskoeser ? @gissoo ?

**Comment by rlskoeser** [comment]
Agree: breadcrumb should take you to the canonical version of that page, whatever it is - members list with no filters or searches active, in the case of the members list. Your browser back button should take you back to your search with filters active, but the breadcrumb should not.

**Comment by gissoo** [comment]
I agree as well, they are normally not expected to preserve the user's modifications of search and filter

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser Ok I am done with design testing using Safari, Chrome, and Firefox on the office desktop screen, the office iPad Air 2, and my iPhone SE. 
**Desktop**: please center all the breadcrumb text horizontally on the chevron containers on **Chrome and Safari**  - They are centered on Firefox. 
![Desktop Problem](https://user-images.githubusercontent.com/44615389/58271931-44b94800-7d5b-11e9-8c66-8bdbe7c3d9d0.png)

**Tablet**: All browsers are fine, however on all browsers only when zoomed into the breadcrumb a green border appears on the green/active breadcrumb. Please fix on **Safari, Firefox, and Chrome** if you can, doesn't feel urgent to me, but a bit odd. 
![Tablet Problem](https://user-images.githubusercontent.com/44615389/58272100-b5606480-7d5b-11e9-91b6-ff6ab38cb262.png)

**Mobile**: on all browsers the breadcrumb looks broken with a white "e" appearing in the middle. Please fix on **Safari, Firefox, and Chrome**. 
![Mobile Problem](https://user-images.githubusercontent.com/44615389/58272105-ba251880-7d5b-11e9-819e-d2447a4ba20f.png)

**Comment by rlskoeser** [comment]
I checked on my phone, the display problem does not occur in Chrome or Firefox on Android.

**Comment by thatbudakguy** [comment]
@gissoo this is ready for another look. Only thing that isn't an easy fix is that thin green line; it's a browser rendering thing...I could probably fix it but would take a lot of tinkering.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser Ok I am done with design testing using Safari, Chrome, and Firefox on the office desktop screen, the office iPad Air 2, and my iPhone SE.
**Desktop**: All text is centered horizontally on all browsers, except on Chrome. please center all the breadcrumb text horizontally on the chevron containers on **Chrome**. 
![Chrome Desktop Problem.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/d56d37cd-555d-498c-884d-2b7ffefd25f0)

**Tablet**: All text is centered horizontally just enough on all browsers. (I may be tired, but they look just a bit off, I may be wrong, but it's enough centered I think) 

**Mobile**: All text is centered horizontally on all browsers. (FYI the line does show on mobile, except it's not green its white, please disregard as it isn't an easy fix)

**Comment by thatbudakguy** [comment]
think this might legitimately be a browser rendering bug if it's off-center only on chrome and only on one screen size. will come back to it later since I'm at a loss for what to try without messing up the other browsers. going to close
