### ISSUE TITLE
add/edit footnotes

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#19]
As a content editor, I want to add a new or edit an existing footnote and associate it with any other kind of record in the system so that I can document evidence related to assertions made elsewhere in the data.

As part of this, please also test add/create source type and add/create bibliography (which are required to create footnotes).

**Comment by jkotin** [comment]
This looks good to me. I expanded the note for Bertha Edel.

**Comment by rlskoeser** [comment]
Wanted to clarify this one.  Most records in the system have a general 'notes' field for adding whatever notes you need.  In addition to that, we have a footnote system that will let you document things in a more scholarly way.  For example, you can use this to document the source that you used to confirm someone's identity or address (e.g., for the link and note in the XML for Kaopeitzer, you can now cite the book that lists the Chinese student's name).

There is a whole section for footnotes on the main admin page, where you can define your source types, add bibliographies, and then associate footnotes from those items with other records in the systems.  I've also added footnotes directly to the person and address edit forms, because I was guessing those are the kinds of records you are most likely to footnote at this point.  You should see it if you scroll down to the bottom of the edit page.

**Comment by jkotin** [comment]
Excellent -- thanks -- this is a good system.

**Comment by rlskoeser** [comment]
@elspethgreen did anyone test adding footnotes? I don't see any in the test site.
