### ISSUE TITLE
As a user, I want to filter library members by nationality so that I can find all library members from a particular country.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#195]
# testing notes
this issue needs both design and acceptance (functionality) testing.

## design
[desktop, with tab open](https://zpl.io/2yOxvq9)
[tablet, with tab open](https://zpl.io/beAgLXD)
[mobile, with filter closed](https://zpl.io/2GyD4mj)
[mobile, with filter expanded](https://zpl.io/aRz0A9E)

to test the design on desktop or tablet, go to the [members list](https://test-shakespeareandco.cdh.princeton.edu/members/) and open the "demographics" tab so you can see the new facet (issues related to functioning/design of the "demographics" tab itself are separate; they will be tested on #287). note that the original designs have different spacing inside this tab to allow for "profession"; we're no longer implementing that facet so the spacing will be different. you want to look **only** at the nationality facet.

when testing on mobile, you should see the facet collapsed into its own "nationality" button. when you click the button, the facet will expand and show its contents.

check the spacing and sizing against all designs for any major discrepancies. make sure the interaction feels "normal" to you - if something feels off, leave a comment.

## functionality

- on mobile, clicking the facet's button should expand/collapse it, showing all the options.
- on mobile, you should be able to scroll both "inside" the facet (when open) and outside it on the page.
- you should be able to select multiple options, and you should see all the people who have _any_ of the nationalities you selected.
- if you activate another facet ("has card", membership dates, etc) you should see the counts in the nationality facet change.
- the facet shouldn't show nationalities with count zero: that is, it should only show the available nationalities of the people you've searched for (and it should be empty if there are no results).
- if you choose a nationality, it shouldn't have any effect on the available nationalities (counts shouldn't change).

**Comment by clmahoney** [comment]
Design: 
- I tested the design on my laptop: I can go to the members list and open the "demographics" tab so I can see the nationality tab. Is the missing column on the right the missing "profession" column?

![Screen Shot 2019-10-22 at 1 24 20 PM](https://user-images.githubusercontent.com/16673934/67312680-bb579e80-f4cf-11e9-9db6-9d1c509949d1.png)

- I tested on my cell, and I see the "nationality" facet collapsed and I can expand and collapse it to show or hide its contents. This feels like a super normal interaction with the site. 
![IMG_0719](https://user-images.githubusercontent.com/16673934/67312903-17222780-f4d0-11e9-9fe8-3cda6e3bf1fb.PNG)

**Comment by clmahoney** [comment]
Functionality: 
- YES, on mobile I can open and close the nationality facet, showing or hiding the country options
- YES, on mobile I can scroll in the facet from Argentina to [no country], and I can scroll outside the facet even when it's still open
- YES, I can select multiple nationalities and all show up. For example, I picked Martinique (1) and the Netherlands (2) and got 3 results. Then I tried Ireland (4) and Spain (2) and got 6 results. 
- YES, when I select "has card" I see the France count go down from 118 to 110. Same with Canada goes down from 6 to 5 when I hit "has card." When I select a specific date range, 1919-1940, I see the count go down: France goes from having 118 total to 96 displayed. 
- YES, the nationality count does not show a 0. For example, I set the date from 1919-1923, and the China count (which is 1 when there is no limit) disappears entirely, not showing something like China 0. 
- YES, when I choose a nationality the other counts remain the same. For example, when I select "Germany," the counts for the other nationalities stay the same. They only change when I limit more, like adding in "female" - as they should.

**Comment by thatbudakguy** [comment]
@clmahoney if you think it looks close enough to the designs (the links I put in the top comment) and it feels natural, I'd say you tested it correctly. feel free to close the issue and remove the "question" tag if this is the case. thank you!

re: the empty column - it's where the "arrondissement" facet will go (probably pretty soon). we decided not to do the "profession" one at all since there's not enough data, iirc.
