### ISSUE TITLE
As a user, I want to filter library members by gender so that I can see the gender composition of library members.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#198]
# testing notes:
## designs
[desktop](https://zpl.io/2yOxvq9) / [tablet](https://zpl.io/beAgLXD) / [mobile, with selected choice](https://zpl.io/aMWOnzd)
## notes
- this is currently called "sex" in some places; it's likely that it will change to "gender" everywhere very shortly.
- note that we haven't done the styles for the tabs ("demographics", "books", etc) that group the different filters on desktop and tablet; that will be tracked on #287 . right now you'll just see the facets in a white box below where the tabs would be.
- make sure the style on mobile looks right, since it's unique to this type of filter.
-  try clicking one or two choices and you should see the results change automatically, without the page reloading.
-  if you enable a different filter, like "has card", the counts for each of the choices should change. however, selecting more than one choice shouldn't change the counts.
- if you enter a keyword search, that should update the counts too.

**Comment by clmahoney** [comment]
- On desktop/laptop: gender count changed when try "male" or "female," and changes when I click "has card" 
- adjust itself without reloading when I release the "male" "female" "unknown"

**Comment by clmahoney** [comment]
On Mobile: filter DOES NOT work. I am able to click "has card" and the results narrow right away, including gender numbers. But then when I try to press "male," "female," "unknown," nothing changes - I am still getting all results for all genders down below - in spite of the green check

**Comment by rlskoeser** [comment]
Was able to confirm the problem on an iPad; have tested again after @thatbudakguy's fix and can confirm it's working.
