### ISSUE TITLE
As a user, I want to filter library members to those with a lending card available on the site so that I can focus on members with cards and borrowing activity.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#199]
# Testing Notes

The functional for filtering by whether a member has a card is in place, and it should:

- [x] toggle when clicked (with hover effects, etc. to indicate it has been clicked)
- [x] Upon hitting enter to submit the form, should filter to the only card holders for current query
- [x] If search is filtered by name query (i.e. `Ab*`), should reflect a count of how many card holders there are in the current search.

**Comment by rlskoeser** [comment]
Increasing to 2pt since, as @bwhicks noted yesterday, this requires faceting for displaying a count.

**Comment by clmahoney** [comment]
This looks great! 
1) it does toggle when clicked (with hover effects, etc. to indicate it has been clicked) - when I click, it looks like I have and has the check mark; when I click again to release it the check mark becomes the question mark with info effect
2) when I enter, the member count is dropped from 6000+ to 637, the members with cards 
3) When I search with name query (i.e. Ab*), it shows how many card holders are in that search
