### ISSUE TITLE
As a user I want members automatically sorted by relevance if I have a keyword search term active and otherwise by member name, so that I see best matches first for keyword searches.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#200]
## Notes for testing
- when no keyword search is entered, relevance sort option should be disabled
- when a keyword search term is present, should automatically sort by relevance and sort by name should be disabled

**Comment by clmahoney** [comment]
Yes this looks good! When I don't have a keyword, relevance search is disabled. When I do (say, "Joyce") it is sorted by relevance.
