### ISSUE TITLE
As a user, I want to switch to a map view of the members list so that I discover proximity of members based on documented addresses.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#201]
## dev notes
- [x] index addresses in solr, add signals to reindex when new addresses are added
- [x] add a new view that returns solr response of all addresses as JSON, minimally including the member's name and membership dates. this view should support all the same filters as the member search result view.
- [ ] use the new JSON response to populate a leaflet map on the members list page that is initially hidden but shown when the user clicks "map view"
- [ ] update the data powering the leaflet map when the user changes facets by requesting a new JSON response from solr
- [ ] make the pins shown on the map open a leaflet sidebar showing html content about the member's address when they are clicked
- [ ] cluster the pins when zoomed out so that they don't overlap
- [ ] show the member's name on the pin anytime the pin would be displayed (i.e. not clustered)
- [ ] hide the sidebar when a part of the map without a pin is clicked
- [ ] make the placeholder text for the search input say "search members with addresses" when the map view is active
- [ ] make the total results count say "X total addresses and Y total members" when the map view is active

### next steps/additional features
- [ ] support using `/members#map` style URL to load the page with the map view already active
- [ ] show the user all of the other addresses associated with a member when a pin is active
- [ ] overlay shapefiles corresponding to arrondissements, perhaps when corresponding filters are active
- [ ] make the map scrollable to zoom once the user interacts with it

**Comment by rlskoeser** [comment]
@gissoo there's a question from @thatbudakguy in the issue description, I'm not sure if this was ever answered:
> what happens when you click a member on the list? currently has to go to their detail page. is this ok.

**Comment by thatbudakguy** [comment]
whoa, we said this would be infinite scroll. that's not going to play nice with the currently paginated version...

**Comment by rlskoeser** [comment]
@thatbudakguy I don't actually know how infinite scroll is usually implemented, but can't we just autoload the next section of results as needed?

**Comment by gissoo** [comment]
@rlskoeser Thanks for flagging the question! From the conversations @thatbudakguy and I had before we agreed that it will need to go to the member's biography page. 

Please come here #606 to read fully about it all.

**Comment by rlskoeser** [comment]
@thatbudakguy this is at least 8pts, right?

**Comment by rlskoeser** [comment]
Closing this as a wontfix since if I think we'll want to start fresh with clearer planning and goals. (We should have probably converted to a prototyping chore to track the work that was done in May, but too late now.)
