### ISSUE TITLE
view address map

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#21]
As a content editor, when I edit an address with latitude and longitude I want to see a map so I can easily check that the coordinates.

**Comment by elspethgreen** [comment]
Would it be possible to link the "street address" field with the coordinates?  When I change a street address, the coordinates and the map do not automatically update--and it seems we would be more likely to be manually changing street addresses than coordinates.

**Comment by rlskoeser** [comment]
I'm not sure what you mean by linking the street address to coordinates.  Do you mean doing a reverse geo-coding lookup to calculate the new coordinates if the street address changes?  That might be possible, but it's definitely out of scope for the current release.

I don't know how the coordinates were gathered and calculated before, so I'm not sure the best way to improve the workflow going forward.  I think this would be a good feature for the team to keep an eye on as you use the interface so you can get a sense of how often you're editing addresses and how you might want to improve the process of getting coordinates.

**Comment by jkotin** [comment]
Sorry not to be a more active tester.  I'll rectify that asap.  To answer RSK's question below: I found the geo-coordiates by looking up the addresses here: http://www.latlong.net/.  I would then often confirm by searching for the coordinates in Google Maps.

J

**Comment by rlskoeser** [comment]
Thanks for the explanation.  So, in the current implementation, you an use the embedded map as a confirmation of the coordinates you've looked up.  In a later version, maybe we can add the lookup directly in the interface, although you all will have to tell me how and when it should be triggered.

Would it be helpful to add help text and a link to latlong.net to the edit form to make this clearer?

**Comment by rlskoeser** [comment]
I went ahead and added help text with a link to latlong.net

**Comment by elspethgreen** [comment]
Thanks for adding link to latlong!  That should be fine for now, although an auto-lookup feature might be good to keep in mind.

But working in Safari just now, the maps are loading somewhat patchily--is anyone else having that problem?

**Comment by i-davis** [comment]
I've just looked at quite a few in safari without any problems, far as I can see!

**Comment by elspethgreen** [comment]
Looks fine now, must have just been my computer!
