### ISSUE TITLE
VIAF - display number, allow number entry

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#22]
I tried to enter a VIAF number for Stephen Benet, but the number wouldn't save. A related point: Users should be able to see the saved VIAF number. Searching solely by name is inadequate. Sometimes individuals have multiple VIAF numbers -- Stephen Benet, for example. It may ultimately be more efficient to have a field in which user can manually enter VIAF numbers.

**Comment by rlskoeser** [comment]
Thanks for this clarification.  We don't get a lot of information back from the VIAF api call, but we can certainly display the number with the name in the suggested results to help distinguish.  We can also support searching by number so you can just enter the number in.

Once a VIAF id has been added, you should see a link to the record, which you can then click to check that it's the correct person - but I see now that the link isn't showing up!  So I'll fix that.

Needs to be addressed to finish #16

**Comment by elspethgreen** [comment]
Link is showing up now!  Great!
