### ISSUE TITLE
As an admin, I want to see a report of OCLC work and edition URI matches for all items so that I can review and determine the criteria for acceptable matches.

### ISSUE THREAD

**Issue by rgmunson** [Princeton-CDH/mep-django#220]
## dev notes
Generate a CSV report that includes:
- from database: title, date of publication, authors, notes (put notes last)
- from OCLC: title, author, dates, URI

Skip items based on the following criteria
- PROBLEM, GENERIC, OBSCURE in the notes
- possibly also exclude items with PERIODICAL in the notes
- may also want to exclude items with an asterisk after the title (another generic book indicator)

**Comment by clmahoney** [comment]
@jkotin what is all the criteria?

**Comment by jkotin** [comment]
I don't understand the question.

I want to see the report to determine whether the matches are accurate.  E.g. that the item in our book database is the same item in the OCLC record.

**Comment by rlskoeser** [comment]
@jkotin @clmahoney what item data from the S&co database do you need included in the report to be able to review and assess it efficiently? Can we just include the OCLC URIs or do you want more information from OCLC?

**Comment by jkotin** [comment]
From the database, we should have the title, date of publication, author/s, and notes.  (The notes can be the last field in the spreadsheet.)  From the OCLC records, we should have the title, author, and dates.  If we just have the URI, we'll have to check each match by following a link.  I worry that would be too time intensive, and we wouldn't be able to get a bird's eye view of the reconciliation.

**Comment by rlskoeser** [comment]
Thanks @jkotin, that sounds like a very logical and useful list to me. Agreed that we want you to be able to review the results quickly and efficiently but with enough information to see how well it's working.

Another question, sorry I didn't think of it sooner: are there any records we should skip and not even attempt to reconcile? e.g. things tagged with **GENERIC** in the notes, or other things like that?

**Comment by jkotin** [comment]
Yes, good idea!  Skip items with any of the following in the notes field: "problem," "generic," "obscure."  A lot of those titles are fixable -- I'll start working on that this month.  But you can ignore them for the time being.

**Comment by jkotin** [comment]
You could also exclude items with PERIODICAL in the notes.

**Comment by jkotin** [comment]
On more thought: some items are marked with an * [asterisk] after the title to indicate what might be called a "generic book" -- e.g. Works by William Shakespeare or Essays by Henry David Thoreau.  For these items, we don't know the specific edition or the specific contents and there might not be a relevant work ID, we'd have to do research.

You may want to exclude them as well.

**Comment by rlskoeser** [comment]
More complex than we estimated, increasing to 8.

**Comment by clmahoney** [comment]
Wonderful!
