### ISSUE TITLE
As a content editor, I want a URL field on library Items so I can add a link to a full-text version.

### ISSUE THREAD

**Issue by rgmunson** [Princeton-CDH/mep-django#223]
# testing notes

- if you go to the admin interface and choose an item, you should see a new field called "Ebook URL" in the "additional metadata" section.
- you can try writing something meaningless in here (not a URL) and verify that you aren't allowed to save the item; you should get an error message saying it needs to be a valid URL.

# dev notes
- suggested field name and label ebook or ebook_link 
- this will be a link to the project gutenberg (or other open ebook source) web page for items where available, to be manually added by the project team.
- help text in the admin interface doesn't need to be extensive, but should direct content editors to provide a link to the project gutenberg landing page so they can choose which version to download. "Link to a webpage where one or more ebook versions can be downloaded, e.g. Project Gutenberg page for this item"
- cf #345 which is for adding internet archive links for titles, and will be done automatically where information can be taken from OCLC.

**Comment by rlskoeser** [comment]
@jkotin @clmahoney does it matter to you what we call this field? Do you want to suggest help text for us to include on the admin edit form?

**Comment by thatbudakguy** [comment]
updated issue notes with answers to the above.

**Comment by clmahoney** [comment]
This looks great! I can see the Ebook URL (which seems like a fine title to me) in the box with other metadata. And if I try to fill it with something else (non URL) it does not save and tells me that I need a URL.
