### ISSUE TITLE
As a content editor, I want to view and edit item format so I can designate item type.

### ISSUE THREAD

**Issue by rgmunson** [Princeton-CDH/mep-django#224]
## notes for testing
- admin should now have a section for item format; should be prepopulated with book, periodical, article
- should be able to create a new type
- when you edit an item, you should be able to assign an existing format

**Comment by clmahoney** [comment]
- can see prepopulated with book, periodical, article
- can create a new type 
- when you edit an item, you should be able to assign an existing format

**Comment by clmahoney** [comment]
- I see the new item format prepopulated with book, periodical, article
- I can create a new type 
- I can edit!
