### ISSUE TITLE
As a user, I want to filter library items by circulation dates so that I can see items that circulated in the library in a particular time period.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#230]

**Comment by rlskoeser** [comment]
@jkotin similar question to the one I just asked on #231 . This story references "borrowing activity" and in the design the filter is labeled "Borrowing Dates". Should I only include dates from borrowing events, or should it include all book related events? And if the latter, do we need to change the label?

**Comment by jkotin** [comment]
All book related events is my view.

**Comment by clmahoney** [comment]
- YES, when I filter by circulation dates (like 1919-1920), I get a list of books that circulated in that time period. If I click through to a certain book, I see that the top results will be for those circulation dates, and then I see when else the book circulated (who borrowed it and when). I also tried 1930-1940.
