### ISSUE TITLE
As a user, I want to sort works by title, author, publication date, or borrow count so that I can view and investigate by author, chronologically, or by popularity.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#231]
## notes for testing
- Work now has a read-only sort title that is autogenerated on save. Please check that:
   - Work edit form in django admin displays read-only sort title
   - sort title is updated when you change the title and save
   - On the work list page, when you sort by title, it should display the full title but order by sort title
- On the public books page (remember, login still required), please try each sort option
   - check that sort appears to be correct (as much as you can tell / sanity check)
   - when you sort by title, it should ignore punctuation and definite/indefinite articles; check that "[unclear]" or titles with quotes sort based on first letter instead of by punctuation
   - check that records without the sort field are sorted last (e.g. books with no author when you sort by author)
   - check that the drop-down page labels are populated correctly with alpha or numeric labels for title, author, publication date, and circulation date
    - check that sort interacts the way you expect with other form behaviors (pagination, keyword search)

Ignore relevance sort for now - that will be refined as part of a separate issue
 

## dev notes
- add sort to book search form
- make sure all sort fields are indexed in solr; use isort solr field already defined for text fields
- handle sort param in view 
- add sort to card display templates & style
- implement async sort
- title sort should strip out leading [ so that unclear titles sort with the us

**Comment by rlskoeser** [comment]
Not sure why this is 3pts, flagging for re-estimation

**Comment by rlskoeser** [comment]
@jkotin the story as written indicates we should use "borrow count" for sorting, and the designs in Zeplin list this sort option as "Borrowing Frequency". Should I only count borrowing events, or should I count any events that related to books (i.e., include purchases and generic book events)? If the latter, should we change the sort label?

**Comment by jkotin** [comment]
I think we should count all events and change the sort label.

The Project, as it has developed, has become increasingly about the cards as they are -- we are no longer deleting material, e.g. We now try to capture every book event, member name, and address.  I don't think it makes sense now to exclude non-borrow book events from the tally.  That's my reasoning.

**Comment by gissoo** [comment]
@rlskoeser could you please remind me how "popularity" is communicated with the user? – does it have any implications on designs? (I was first confused about this which caused me to create a separate issue for the sort options)

**Comment by rlskoeser** [comment]
@gissoo sorry for the confusion - we used "popularity" in the user story to help convey the _why_ of this feature, but it's not a term we'd planned to use in the interface.

**Comment by gissoo** [comment]
@rlskoeser Thanks!

**Comment by clmahoney** [comment]
Admin: 
- YES, I see the sort title and if I chance the title, the sort title changes too: 
![Screen Shot 2020-04-24 at 6 02 15 PM](https://user-images.githubusercontent.com/16673934/80260483-06f12d80-8656-11ea-821a-1ee8eddd811f.png)
and 
![Screen Shot 2020-04-24 at 6 02 34 PM](https://user-images.githubusercontent.com/16673934/80260488-09ec1e00-8656-11ea-9979-6078d33a5d7b.png)
- YES, when I sort by title I see that it's sorting by the sort title but that the full title is displayed 

Public books: 
- YES, the sort looks correct
- YES, the title sort ignores both punctuation and definite/indefinite articles. For example, the sort starts with The 12:30 from Croydon and the second book is 12:30 from Heaven. I also see that "18th Century Drama" is after 170 Chinese Poems, meaning that the quotes are not getting in the way. The [unclear] works are also sorting alphabetically: 
![Screen Shot 2020-04-24 at 6 09 12 PM](https://user-images.githubusercontent.com/16673934/80260809-b7f7c800-8656-11ea-854e-d09652d8f3ca.png)
- YES, when I sort by author the books that are without authors are last in the sort: 
![Screen Shot 2020-04-24 at 6 10 56 PM](https://user-images.githubusercontent.com/16673934/80260928-05743500-8657-11ea-9288-f1b971b2a99d.png)
- YES, the title sort displays alphabetically; YES, the author sort displays alphabetically; YES, the pub date displays numerically; YEs, the circulation date displays numerically; YES, the circulation displays numerically
- YES, the sort interacts with my queries as I expect it to!

**Comment by jkotin** [comment]
This looks great! Let me know if the following is useful/relevant for this issue.  When I search for "James" and sort by publication date, the results are off.  See screen shot.
<img width="966" alt="Screen Shot 2020-04-27 at 2 08 49 PM" src="https://user-images.githubusercontent.com/12616674/80405560-c6c9bf00-8890-11ea-887f-2f974670dada.png">

**Comment by jkotin** [comment]
Search for "russia" and then order by author, also off:
<img width="796" alt="Screen Shot 2020-04-27 at 2 12 24 PM" src="https://user-images.githubusercontent.com/12616674/80405853-3049cd80-8891-11ea-9ab1-92f016b976d2.png">

**Comment by jkotin** [comment]
In admin on the test site, we can no longer sort/search titles by punctuation mark. This isn't a problem, but I'm using title sort a lot right now to isolate the titles in quotation marks as I recheck them.

**Comment by rlskoeser** [comment]
@jkotin good catch on the sort, it looks like none of them are working with keyword search (I suspect the relevance is overriding them).

For the admin comment: will it work to use the data exports (either admin or public) to sort or search by punctuation in titles for this data work?

**Comment by jkotin** [comment]
Yes, data exports are OK.  I'm hoping that once I get through the generic titles and @clmahoney finishes the majorauthors, there won't be many stray quotation titles left.

**Comment by rlskoeser** [comment]
@jkotin I'll mark this tested needs attention and work on a fix. Ok for Cate to sign off by checking the problems you identified once I have a fix?

**Comment by jkotin** [comment]
I'm happy to text again once this is fixed.

**Comment by rlskoeser** [comment]
@jkotin this is ready for retesting.

**Comment by jkotin** [comment]
Looks great!

I think I now have a better sense of the stakes of an earlier conversation about showing the circulation numbers and dates.  (It's a little strange to sort on information you can't see.)  @clmahoney  would you make a note of this when we discuss wishlist/enhancement priorities?
