### ISSUE TITLE
As a user I want items automatically sorted by relevance if I have a keyword search term active and otherwise by title (by default), so that I see best matches first for keyword searches.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#232]
# testing notes

this needs to be tested on the books search page. check that:
- if you haven't typed anything the keyword search box, you shouldn't be allowed to select the "relevance" option
- as soon as you type in a keyword search, the sort should switch to relevance automatically
- after that, if you want, you can pick any of the search options and they should work
- if you have relevance selected and you delete everything in the search box, you should be switched off of relevance and it should become disabled again.

## dev notes
- [x] disable relevance sort option if no keyword search (django form)
- [x] default to relevance sort if there is a keyword search term (django view)
- [x] switch to relevance sort after user types keyword search term (js reactive search)
- [x] disable relevance sort and switch to default if keyword search is cleared (reactive search)

**Comment by clmahoney** [comment]
- YES, if the search box remains unfilled, I cannot sort by relevance (it's greyed out): 
![Screen Shot 2020-04-29 at 4 10 48 PM](https://user-images.githubusercontent.com/16673934/80642247-23191400-8a34-11ea-8d3f-d5780834eb3a.png)
- YES, when I typed in the search bar, the sort went to relevance without me doing anything (I searched for "Whitman")
- YES, once I searched for Whitman, I was able to change the sort from "relevance" to any of the other options; I tried a couple and the search always shifted depending on each option. Surprising no one, Leaves of Grass has the highest circulation! 
- YES, if I have the relevance sort selected but then delete my keyword in the search bar, I get kicked off "relevance" sort and back to "Title A-Z" and Relevance is once again greyed out. 

I tried this with a couple of more keywords (like Dickinson! So cool--and surprising!--to see that her letters had a higher circulation than her poetry!)
