### ISSUE TITLE
As a user, I want to see a chronological list of circulation activity for a single library item so that I can see which library members interacted with it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#235]
# testing notes
## designs
initial view - [desktop](https://zpl.io/bzq54A4) / [tablet](https://zpl.io/VDAkeq3) / [mobile](https://zpl.io/VxZd6JJ)
scrolled down - [desktop](https://zpl.io/2G0llxW) / [tablet](https://zpl.io/25B8BZo)

you should be able to visit any book's page via the books search to test this. make sure to check:
- member's names should be links to their member page
- dates should be right
- sorting the table should work

the designs for mobile include sorting controls that stick to the top; this isn't implemented for any of the tables (like borrowing or membership activity on members) but is a wishlist feature.

# dev notes
this page parallels the member borrowing activities page, but for a book instead of a person. most of the design/behavior should be identical.

**Comment by rlskoeser** [comment]
Will need to include issue number/date or volume if known.

**Comment by clmahoney** [comment]
Desktop: I tested with Pilgrimage (tons of circulation, as well as different volumes) and The Autobiography of Alice B. Toklas: 
- YES, I am able to click on the name of the members who borrowed the book and it takes me to the individual member detail page
- YES, all the dates look correct
- YES, I am able to sort by: start date, end date, status, and vol/issue (tried the latter with Pilgrimage's many volumes)

**Comment by clmahoney** [comment]
Mobile: I tested with Dubliners (lots of circulation) and The Adventures of Peregrine Pickle (multivol)
- YES, I am able to click on the name of the members who borrowed the book and it takes me to the individual member detail page
- YES, dates are all correct, and if the book has multi volumes then I see them on the right side of the screen: 
![IMG_1971](https://user-images.githubusercontent.com/16673934/80623804-be03f500-8a18-11ea-9f2e-6488812a0419.PNG)
- I don't see any sorting options but I understand this is a wishlist item for mobile

**Comment by clmahoney** [comment]
Tablet: Tried with Ulysses 
- YES, I am able to click on the name of the members who borrowed the book and it takes me to the individual member detail page
- YES, all the dates look correct
- YES, I am able to sort by: start date, end date, status, and vol/issue

**Comment by jkotin** [comment]
This looks fantastic. It's amazing seeing the data in a whole new way.
