### ISSUE TITLE
As an admin, I want library items to have unique identifiers that can be included for use in URLs in the public site.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#236]
## notes for testing
- When editing a work with multiple creators of one type, you should now be able to specify the order within that creator type (i.e. first author) with an optional numeric order field.  Test editing creators without specifying order to make sure it is optional; test setting the order and confirm that the order is changed on the bibliographic detail page for that work.
- Works should now have a "slug" field for use in public urls. You should see them in the admin site work edit view; if you create a new work and save it, the slug should get created for you (per the help text).
- I added the slugs to the CSV export for books; might want to download and sort by slug just to scan through them and see if they look ok, if anything weird jumps out.
- Test changing a multi-author work: change the author order, clear out the slug, save the record; slug should regenerate with the new first author last name.
- When you use the book search and browse and click through to a single book detail page, it should use the book slug instead of the numeric database id.

## dev notes
Should not be implemented until book merge work is done.

- [x] add creator order field (optional)
- [x] make order editable in admin
- [x] default creator sort by creator type, then creator order, then last name
- [x] add slug field to work
- [x] add migration to generate slugs and enforce uniqueness
- [x] add slug generation logic to model save when slug is not set
- [x] update book view, url, and `get_absolute_url` method to use slugs
- [x] handle apostrophes in titles

**Comment by rlskoeser** [comment]
Need to know status of book merge data work before we can schedule this.

Will also need to decide on short identifier format we want to use (some combination of author/title/date? how to keep short?).

**Comment by rlskoeser** [comment]
@jkotin as I mentioned at our last meeting, the book slugs for Derrida's Margins are generated based on first author last name, title, and year. Title is truncated to the first 10 words.  In that project we used letters to differentiate slugs that are exactly the same (-A, -B, -C). It came up on that project because Derrida owned multiple copies of the exact same books; I think it's going to be less of a problem for us.

You said you didn't think we need to include year, and I agree.

I propose we use author last name + title as our primary slug.  Some examples of what this looks like:
- joyce-a-portrait-of-the-artist-as-a-young-man
- forster-a-room-with-a-view
- woolf-a-room-of-ones-own
- conrad-lord-jim
- jerome-three-men-in-a-boat-to-say-nothing-of-the-dog
- hemingway-three-stories-and-ten-poems
- dos-passos-three-soldiers
- stein-three-lives

Periodical titles will be short, but I think that's ok. They seem to be unique. Some examples:
- time-and-tide
- hound-horn (the & in Hound & Horn gets lost)
- the-new-english-weekly
- the-new-yorker
- transition
- time

For consistency with member slugs, I recommend we use numbers to distinguish slugs that are otherwise exactly the same. I think this is mostly going to come up with the unclear titles and maybe some of the generics.  (unclear-1, unclear-2, etc...)

Questions
1. Do you want to do anything different for generic or unclear titles? The quotes and brackets are removed when generating slugs.  (I think this is ok, but wanted to check).
2. Many of the generic titles repeat the author name, resulting in slugs that look redundant. Examples: yeats-yeats-essays, yeats-yeats-plays. Would it be logical to omit author name for generics titles?
3. Should we use editor last name if there is no author, or is it fine to just use title? 
4. How do you want to handle long titles? Truncate to a certain number of words? Truncate to words if slug is over a certain length? A fair number seem to have semicolons or other punctuation markers we might be able to use to truncate more meaningfully, but I don't know if there are cases where that will be problematic. Some example long slugs without any truncation logic:
   - lockhart-a-great-sea-mystery-the-true-story-of-the-mary-celeste
   - beers-a-history-of-english-romanticism-in-the-nineteenth-century
   - carroll-a-selection-from-the-letters-of-lewis-carroll-the-rev-charles-lutwidge-dodgson-to-his-child-friends
   - hatch-a-selection-of-the-letters-of-lewis-carroll-to-his-child-friends
   - anderson-a-storytellers-story-the-tale-of-an-american-writers-journey-through-his-own-imaginative-world-and-through-the-world-of-facts-with-many-of-his-experiences-and-impressions-among-other-writers-told-in-many-notes-in-four-books
   - schiff-a-true-story-in-three-parts-and-a-postscript-all-of-them-facile-rubbish
   - graham-a-vagabond-in-the-caucasus-with-some-notes-of-his-experiences-among-the-russians
   - frazier-adonis-attis-osiris-studies-in-the-history-of-oriental-religion
   - roosevelt-african-game-trail-an-account-of-the-african-wanderings-of-an-american-hunter-naturalist
   - wilson-all-alone-the-life-and-private-history-of-emily-jane-bronte
   - maugham-altogether-being-the-collected-stories-of-w-somerset-maugham

**Comment by jkotin** [comment]
@rlskoeser This looks great.  To try to answer your questions:

1. Maintaining the rules for unclear is fine with me. We will have a lot of unclear-1, unclear-17, but that doesn't bother me.

2. I'm planning to get rid of all the GENERIC labels (and PROBLEM labels, etc) and either resolve them or replace them with UNCERTAINTYICON.  Cate is also going to develop a plan to deal with the generic titles by famous writers—Yeats, Chaucer, etc. I expect fewer author names will appear in titles. So we should just follow the rules, I think.

3. I have a slight preference for using editor name, but I defer to you. If there are multiple authors or editors, will we only use the first? Which one is the first? The top one in the database?

4. My preference would be to truncate after author and two or three full title words, so: joyce-a-portrait-of or joyce-a-portrait. But if you think that's too short, I defer to you. I like short slugs.

**Comment by rlskoeser** [comment]
@jkotin thanks for the helpful responses. 

2. How quickly do you expect to finish the work getting rid of generic and problem titles, and should the task to generate slugs be delayed until after that is completed, or should we come up with a workflow/plan  to handle generating/updating slugs as you edit and merge titles?  (We probably need to do that for merges anyway.)

3. I looked again at my test output, I think using editor last name when there's no author would be valuable.  I was planning to only use the first author or editor; first by alpha on sort name. Are there instances where that will be a problem? 

4. Short is definitely better! Your suggestion bothered me because of the trailing -of, but it gave me an idea to try a simple solution to strip out stop words so we get more significant words in our limited set. I think three title words is getting good results.

New question: if a truncated title results in a duplicate slug, should I use a number or the next title word to differentiate?  I think I saw a couple cases of this, but right now I'm only finding one (and perhaps it is a merge candidate?):

- Love and Mr. Lewisham, Author: Wells, H. G. (Herbert George)
wells-love-mr-lewisham
Love and Mr. Lewisham: The Story of a Very Young Couple, Author: Wells, H. G. (Herbert George)
wells-love-mr-lewisham-story-young-couple

If we truncate to two title words instead of three I think this will come up more. But willing to try that and only add the third word if needed for uniqueness.

**Comment by jkotin** [comment]
2. I think it will take a while and might carry into the summer.  I'm almost done the handwriting tag.  I've asked @clmahoney to develop a plan for the major authors (Chaucer, Yeats, etc.) — if that works, getting rid of the generic and problem tags should be much faster.  We'll know that soon.  But yes, we should have a way to generate and update slugs as we learn more about the books.

3. Alpha for slugs is fine with me. This reminds me to ask @gissoo about order for the bibliography page. Alpha is acceptable, but it would be ideal if we could follow the order in the original publication. We could follow that order in the database with the top name being first. Or we could have different contributor types, e.g. "author 1"

4. Great!

New Question: that's a good merge!  But the problem will come up, you're right. E.g. Plays by August Strindberg: First Series. I think the next title word is best, but numbers are fine with me too.

**Comment by rlskoeser** [comment]
I checked, and it looks like you all have already merged that title! I'll make sure to get a fresh copy of the data before I test this again, since I know you and Cate have done a lot of book work lately!

I'm not sure what the author order in the database is, although I can check — order on a many-to-many relationship isn't guaranteed unless we explicitly add order information. We could add an optional author order field; any idea how many records are impacted?  That's a much better solution than adding different contributor types.

**Comment by jkotin** [comment]
Re: author order and impact: we could see how many items have either 1/ multiple authors or 2/ multiple editors and no authors.  We could then reorder all these manually.

**Comment by rlskoeser** [comment]
@jkotin some numbers for you on multiple author/editor:
- 157 works with more than one author
- 22 works with no author and more than one editor

Documenting my queries for myself:
```
Work.objects.filter(creator__creator_type__name='Author').annotate(author_count=Count('creator')).filter(author_count__gt=1).count()
Work.objects.exclude(creator__creator_type__name='Author').filter(creator__creator_type__name='Editor').annotate(editor_count=Count('creator')).filter(editor_count__gt=1).count()
```

**Comment by rlskoeser** [comment]
@jkotin also: if author/editor order matters for generating the slugs then whoever does the ordering will need to regenerate slugs too. I think that's fine, though. And this seems like a manageable number.

**Comment by jkotin** [comment]
@rlskoeser Yes, I agree, this seems a manageable number.  What's the best way to order authors/editors?  Is it possible to just put them in the right order (top to bottom) in the database?

**Comment by rlskoeser** [comment]
@jkotin I'm going to add an optional numeric order field as part of this feature and make it editable in the admin. (That's why the slugs can't use the order until after someone makes the edits)

**Comment by jkotin** [comment]
@rlskoeser I can make the edits quickly.  Let me know when the option is ready.

**Comment by rlskoeser** [comment]
Increasing to 3pts since there was more work here than we anticipated.

**Comment by clmahoney** [comment]
- YES, when I went to a book detail page of a work that had multiple authors, I was able to assign order to each and save it; the order was changed per my numbering. Tried with "A History of Sculpture" and "The Lover, and Other Papers of Steele and Addison" 
- YES, when when I went to a book detail page of a work that had multiple authors and added another creator without numbering them, I was able to save them all and the order didn't change since I didn't assign any order (it was just alphabetical) 
- YES, I see the each work has a slug
- YES, when I create a new work and save it, I see that a slug is generated based on what I wrote: 
![Screen Shot 2020-04-07 at 2 17 55 PM](https://user-images.githubusercontent.com/16673934/78704895-9c609380-78da-11ea-9159-2393965a8a20.png)
- YES, I downloaded the CSV that now includes the title slugs, and glanced through them--they look good! For works that don't have authors or are just titles like "Castle," the slug is merely castle, which makes sense. All others have an author name then part of the title, as expected. 

- I'd like clarification on how to tell that the book detail page is sorting by the slug and not the ID - so I just look to the address bar to see the slug? 
- NO, when I changed the order of a multi-author work, deleted the slug, then saved again, the slug remained the same as when the order was not changed. I tried with "Liberal Points of View," where the slug remained "heathcote-williams-liberal-points-view" even though I put Nathan first and Heathcote-Williams second. I tried again with ""Beaumont & Fletcher Plays" with slug "beaumont-beaumont-fletcher-plays" and made Fletcher first, but the slug remained the same.

**Comment by rlskoeser** [comment]
@clmahoney yes, sorry for being unclear - the url in the location/address bar of your browser should use slugs for individual book pages instead of database ids. You can compare book pages in production and test if you want to see what's changed.

**Comment by clmahoney** [comment]
- OK I re-tested this with RSK's help, and found that YES, the slug order updates when change the creator order, but you need to do a two-step workflow: 1) change author order, delete slug, and save. The slug will remain the same but the author order will have changed. 2) Delete the slug and save again; the slug will then change to reflect the new order. 

- YES, I reviewed the book detail page and see that there is a SLUG now in the address bar, not a book ID number!

**Comment by jkotin** [comment]
Looks good to me!
