### ISSUE TITLE
As a user, I want to browse a list of card images so that I can see digitized lending cards belonging to library members.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#237]
## Notes for testing 
Navigate to /cards/ to view the new lending card browse. If you're not logged in, you should get a 404. If you are logged in you should see a list of cards with images.
- cards should be sorted alphabetically by card holder last name
- card should display date holder if dates are known or unknown if no dates
FYI, cards are displaying the designated thumbnail from the Figgy manifest (probably the first image by default)

Please check that display looks ok on tablet and mobile as well as desktop.

**Comment by clmahoney** [comment]
On desktop: 
- YES, if I am not logged in and go to the CARDS, I get a 404 "Not found/absent on business"
- YES, if I am logged in and go to the CARDS, I see them! they look great! 
- YES, the cards are sorted alphabetically by card holder last name 
- YES, the cards show date ranges or date displayed. For example, Cyrille Arvanon's dates are there from the cards (1937-1940), while Baker's one card is simply 1939. And if the date is not on the card, the site displays "unknown" below like cards for Louis Aragon or Richard Aldington

**Comment by clmahoney** [comment]
On mobile: 
- YES, if I am not logged in and go to CARDS, I get a 404 
- YES, if I AM logged in I see the cards in alphabetical order by card holder last name! 
- YES, the cards show date ranges or dates under the names too. If unknown dates, it displays unknown. 


* I just saw that the "Alexandre" image is upside down, so I'm going to try to fix that in Figgy
![IMG_0731](https://user-images.githubusercontent.com/16673934/67506031-567c7f80-f65a-11e9-87cd-966b3effa413.PNG)

**Comment by clmahoney** [comment]
On tablet: 
- YES, if I'm not logged in and try to access cards, I get a 404
- YES, if I am logged in, I can see them! They're displaying great. 
- YES, they are in last name alphabetical order
- YES, the dates are listed and if unknown, I see "unknown"
![IMG_0218](https://user-images.githubusercontent.com/16673934/67507722-88431580-f65d-11e9-9bd1-098afae1ced1.PNG)

**Comment by clmahoney** [comment]
Re-opening this because I just saw something strange with the Havelock Ellis card display: it's HUGE compared to the other card images. 
![Screen Shot 2019-10-24 at 1 18 44 PM](https://user-images.githubusercontent.com/16673934/67509367-d574b680-f660-11e9-82d6-c9179dae7bbb.png)

**Comment by rlskoeser** [comment]
Good catch! Updated to address that, additional testing notes:
- long images like the one you found should now be shortened in height to match the others
- for cards with shorter images (there's one on the same page), on desktop and tablet the text should line up with cards that are the normal size; on mobile it should follow the image without additional space

**Comment by clmahoney** [comment]
- YES, I re-checked the Havelock Ellis "card" (really book) and the image is now lined up with the rest of them, and not huge 
![Screen Shot 2019-10-24 at 2 46 54 PM](https://user-images.githubusercontent.com/16673934/67515776-533ebf00-f66d-11e9-8c1b-73c291f75d4d.png)

- YES, a short card like Jean Duren fits in, with the text lining up with the regular size card texts on my desktop and tablet: 
![Screen Shot 2019-10-24 at 2 46 27 PM](https://user-images.githubusercontent.com/16673934/67515647-1377d780-f66d-11e9-8400-c7d80a726399.png)
 
- YES, on mobile the shorter image of Jean Duren looks normal and doesn't take up additional space

**Comment by jkotin** [comment]
Should the Havelock Ellis image be present at all?
