### ISSUE TITLE
VIAF - help text to clarify format and entry options

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#24]
Should the VIAF ID field be a link to the VIAF page (as it is now) or the VIAF number?

**Comment by rlskoeser** [comment]
The VIAF URI is the canonical linked data identifier for that VIAF entity, so it's more meaningful than a bare number.  We can get the number when and if we need to, and we can revise the interface so your team can find VIAF records and enter numbers if that's important for how you and your team need to work with the data, but I'm going to keep the field as the URI.

I will add some help text to make that clearer and to explain the various options for input.

Related to #16 .

**Comment by jkotin** [comment]
Perfect.  This makes sense!

**Comment by elspethgreen** [comment]
Having the VIAF link show up is fantastic!
