### ISSUE TITLE
As a user, I want the card image list page updated as soon as I change search terms, filters, or results page so that I can refine my search without losing my place in the form and have results load more quickly.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#242]
## Notes for testing
If you use the next and previous links or change the pagination drop down, you should see new results without the whole page reloading.

**Comment by clmahoney** [comment]
Desktop: 
- YES, when I click "next" or "previous," the page does a partial reload with that zippy blue bar flashing across to show the updated screen 
- YES, the zippy blue bar happens again when I use the display dropdown menu to change thru name groupings

**Comment by clmahoney** [comment]
Mobile: 
- YES, I see the zippy blue bar when I press the "next" or "previous" arrows, signifying a partial reload 
- YES, I see that bar also when I use the display dropdown menu too

**Comment by clmahoney** [comment]
Tablet: 
- YES, the see the blue bar that signals a partial reload when I click the "next" or "previous" buttons, and also when I hit the drop down display
