### ISSUE TITLE
As a user, I want to see a rights statement for card images so that I know what I can do with them.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#250]
# testing notes
## design links
[card viewer](https://zpl.io/VqkLYgN) / [card gallery](https://zpl.io/25oW0mW)

this is visible in two places listed above - the card detail viewer (#248) and the member card gallery (#247). check the lower-right corner and make sure that the rights statement image ("no known copyright") is visible in both places. it should be clickable, and clicking it should take you to the rightsstatement.org page explaining the statement. try loading the pages on smaller screens (tablet/mobile) and make sure the image is still there and still clickable.

**Comment by jkotin** [comment]
Comment on the Zeplin images:

Could the "No know copyright" logo be less conspicuous?  Both smaller and grey to closer match the background?

**Comment by jkotin** [comment]
This works well on my laptop. Could we set the link to open in a new window? My only other suggestions concern the design issues in my last comment.

@clmahoney would you test on mobile and tablet? You can close this issue once the design suggests have been discussed/addressed.

**Comment by clmahoney** [comment]
Tablet: 
- I tested this on Chambrillac's cards: I see the "No Known Copyright" image in the bottom right of the card gallery, and if I click to the individual card I see the copyright in the bottom right also.

**Comment by clmahoney** [comment]
Mobile: 
I tested this on Alderman's cards. 
- YES, in the card gallery I see "No Known Copyright" in the bottom right corner and if I click it, it takes me to the rightsstatement site. 
- YES, if I click on an individual card in Alderman's gallery, I still see the copyright in the bottom right corner and I can click it through to rightsstatement.

**Comment by rlskoeser** [comment]
Having the link open in a new window is probably reasonable here; @gissoo, any opinion on that?

@gissoo what do you think about the size & color of the copyright logo? We want to make sure it's readable, but maybe it could go a little smaller. Right now it looks much bigger than the PU logo in the footer (should that be bigger?).

**Comment by gissoo** [comment]
@rlskoeser @jkotin @clmahoney I have revised the sizing and the visibility of the "No known copyright", "PUL", and "PU" logos on all devices in this issue I have created that is waiting to be design reviewed, issue #457. "https://app.zenhub.com/workspaces/mep-django-5931d39e341d0d6c7318d56f/issues/princeton-cdh/mep-django/457" The sizes have been revised to reflect the recommended minumum logo size on screens. I highly recommend we do not make the "PUL" and "No known copyright" logos smaller than what you see in the updated designs in issue #457. 

I also agree with the link opening in a new window as well!

**Comment by rlskoeser** [comment]
@gissoo I agree that it's currently not obvious they are clickable. Do you want the green underlines to be always visible or only on hover?  Having an updated design with the underline you propose would be helpful.

**Comment by gissoo** [comment]
@rlskoeser Great! I'll update designs now, wanted to make sure it's ok to do that before I update designs.

**Comment by rlskoeser** [comment]
@clmahoney @jkotin test site updated with smaller and lighter versions of the logos, PUL logo links to the finding aid version of the card, and links open in a new tab/window.

**Comment by jkotin** [comment]
Looks great to me.

**Comment by gissoo** [comment]
@jkotin Just to make sure this is documented, there is a small change in the design for when the logos are hovered on desktop, or selected on tablet and mobile. You can view it here: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5de686bfd9cb7d4889f57ba7"

**Comment by gissoo** [comment]
These are now updated on the card image viewer and the card gallery pages for desktop, tablet, and mobile. Here are the links:
1. Card image viewer
a. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b5030eb3b183b25b9200"
b. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b503f3d79e57b28a00e1"
c. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b50350731722a4809521"
2. Card gallery
a. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841d517762c27b91ed6"
b. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841e9d98c2c63dd8c30"
c. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841e9d98c2c63dd8c30"
