### ISSUE TITLE
As a content editor, I want to add new or edit existing editorial content so that I can publish and promote scholarly work related to the project.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#252]
# testing notes
## designs
[desktop](https://zpl.io/brPzWW3)

these are the new analysis essays. to add one, go [into wagtail](https://test-shakespeareandco.cdh.princeton.edu/cms/), navigate through the "pages" hierarchy on the left, and open the analysis landing page (looks like a folder). then click "add child page" at the top.

- try pasting in some content from somewhere else in the body of your new analysis essay.
- try adding footnotes. how do they look?
- try adding several Person snippets as authors or editors (note that you need to create the Person first, that issue is tested on #370). do they display when you look at the page on the site?
- try adding an image as the featured image. does it show in the preview on the analysis landing page?
- can you see the essay's publish date on the landing page, and on the essay page itself?

## dev notes
- editorial page is a subclass of main content page
- generate urls based on publication date (maybe just year) - see PPA for example

**Comment by rlskoeser** [comment]
No longer needed, since editorial pages will be treated the same as other site content pages.

**Comment by rlskoeser** [comment]
Re-opening to track work to customize analysis page urls.

**Comment by clmahoney** [comment]
- YES I can add in text to the body and it looks good
- YES, I can add in footnotes by adding in footnote section, however we can't use superscript, right? So my footnote looks like this: 
![Screen Shot 2019-11-15 at 3 21 31 PM](https://user-images.githubusercontent.com/16673934/68973200-a531bb00-07bb-11ea-9204-1036b0a65641.png)
- Question: why are the footnotes a different font than the body text? I can't see how to change that text. 
- Question: in the design mockup, the footnotes fall UNDER the "Cite this document" text - and I can't see that on Wagtail

**Comment by clmahoney** [comment]
- YES, when I add in a featured image and publish it, I can see it preview on the analysis landing page - but there's preview text there too and I don't know how to get rid of it, since it fits above the featured image

**Comment by clmahoney** [comment]
- YES, as shown above I can see the essay's publish date on the landing page 
- but NO, I can't see it on essay page itself! Was it supposed to be at the top? This is what I see right now: 
![Screen Shot 2019-11-15 at 3 28 48 PM](https://user-images.githubusercontent.com/16673934/68973592-b29b7500-07bc-11ea-9a76-47bd1a442124.png)

**Comment by rlskoeser** [comment]
@clmahoney footnotes are a different font based on Gissoo's design. I hadn't caught that they were under the "cite this document" in the design before, I don't think that's very easy for us to do (and I'm not sure it's preferable either - interested in @jkotin's opinion).

The preview text on the landing page will pull from the beginning of the text content unless you set your own description for the page - it's one of the fields in the wagtail editor.

**Comment by clmahoney** [comment]
Thanks @rlskoeser for letting me know, and for the info about how to alter the preview text

**Comment by clmahoney** [comment]
- YES, I can add in a "person" as author and/or as editor 
- and YES I can now see the published date on the essay page itself; it's under the author now - I think the date appears when the author is noted
Here's my little Frankenstein page with Josh's logbook text, and I added Ian as author and editor :) 
![Screen Shot 2019-11-15 at 3 40 02 PM](https://user-images.githubusercontent.com/16673934/68974239-3a35b380-07be-11ea-81c8-f3ff5724fc7d.png)

and here's the preview: 
- 
![Screen Shot 2019-11-15 at 3 40 28 PM](https://user-images.githubusercontent.com/16673934/68974262-4457b200-07be-11ea-9774-e983dd79f671.png)

**Comment by rlskoeser** [comment]
The publication date should display - it's not showing right now because the logic is conditional on author & editor being set. Thanks for catching - we will fix that, but it raises a question for content pages: attribution currently displays at the bottom instead of the top if there any authors or editors set; are we ok with always displaying publication date and last updated? It seems like nice information to include, but it may need more context or a label if there is no author/editor with it.

**Comment by clmahoney** [comment]
hmm I feel like there should be a name associated with each piece of writing, even if it's just editor? Or could there be a way to write in a name that represents all of us?

**Comment by clmahoney** [comment]
also is there a way to make the preview text center with the author/date? The alignment looks a bit wonky if it's like this: 
![Screen Shot 2019-11-15 at 3 58 16 PM](https://user-images.githubusercontent.com/16673934/68975275-d1036f80-07c0-11ea-8d2f-59aeb23b9b35.png)

**Comment by clmahoney** [comment]
- YES, this all looks good too - footnotes working well: 
![Screen Shot 2019-11-18 at 4 23 15 PM](https://user-images.githubusercontent.com/16673934/69095154-be3aa600-0a1f-11ea-9b66-ee71cd1a8265.png)
