### ISSUE TITLE
As a user, I want to browse a list of published editorial content so that I can see what analytical and scholarly content is available to read.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#254]
# testing notes
## designs
[desktop](https://zpl.io/aBdReXL) / [tablet](https://zpl.io/bzjqvQA) / [mobile](https://zpl.io/awgJ98N)

this is the new [analysis landing page](https://test-shakespeareandco.cdh.princeton.edu/analysis/). 

- check that it matches the designs on all screen types.
- try adding and publishing a new analysis essay and check that it appears correctly on this page (if you run into problems creating a new analysis essay, note that on #252).
- check that the order of published items on the page is logical.

## dev notes
- new editorial landing page 
  - similar to sources and also PPA Editorial
  - customize page method to get children (see PPA)
- variable height layout
- sort most recent first, by publication date

**Comment by clmahoney** [comment]
Desktop: 
- YES, the design matches what the landing page looks like
- YES, I added two new analysis essays and they appear correctly 
- YES, the order of the published items is logical and follows the order in which I published them. Tried with 3 new essays, looks like this: 
![Screen Shot 2019-11-15 at 4 29 25 PM](https://user-images.githubusercontent.com/16673934/68976970-1e81db80-07c5-11ea-8bc3-df24fda713ad.png)

**Comment by clmahoney** [comment]
Tablet: 
- YES, the design matches what the landing page looks like: looks sleek and straightforward! 
![77083656_2133904663582819_5193211628094488576_n](https://user-images.githubusercontent.com/16673934/68977210-b8498880-07c5-11ea-8b36-78709538659c.png)

- YES, the new analysis essays appear correctly 
- YES, the order of the published items is logical and follows the order in which I published them

**Comment by clmahoney** [comment]
Mobile: 
- YES, the design matches what the landing page looks like: 

![Image from iOS (4)](https://user-images.githubusercontent.com/16673934/68977372-1e361000-07c6-11ea-8587-3328fe734ef2.png)

- YES, the new analysis essays appear correctly
- YES, the order of the published items is logical and follows the order in which I published them

**Comment by clmahoney** [comment]
Question: what is this - a new footnote? 
![Screen Shot 2019-11-18 at 4 07 30 PM](https://user-images.githubusercontent.com/16673934/69094016-9ba78d80-0a1d-11ea-80ab-df5f366253b9.png)

**Comment by thatbudakguy** [comment]
@clmahoney correct - there are two footnote blocks added, if you look in the wagtail editor, so there are two footnote sections. not sure this would ever happen, but it is something you can do.

**Comment by clmahoney** [comment]
Desktop: 
- YES, the design matches the Analysis landing page
- YEs, I can add a new Analysis essay no problem: see screenshot
![Screen Shot 2019-11-18 at 4 11 21 PM](https://user-images.githubusercontent.com/16673934/69094515-7cf5c680-0a1e-11ea-97bd-df5ee3b79a11.png)
- YES, the order of the published items is correct

**Comment by clmahoney** [comment]
Tablet:
- YES, everything is still working here too! 
Mobile: 
- YES, everything is looking good here
