### ISSUE TITLE
As an admin, I want to generate a data download for books so that I can deposit and version the data for others to use.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#266]
## testing notes
I will generate and share fresh data exports for you to review for testing. As with the member and event exports, data is available in both CSV and JSON; recommend using OpenRefine to review and explore the data.

Test exports are in S&co drive: development & design > data exports > test 2020-04-08

- check a variety of records to confirm that all fields listed below are included and populated correctly
   - check at least one item marked as uncertain
   - check a few items with volumes or issues
    - check a few items with multiple creators of different types
    - check a few items with multiple creators of the same type

There are small changes to the member and event exports, so please check:
- member export should now include updated timestamp
- event export should include book urls based on the new slugs

## dev notes

- [x] new manage command to export book data
- [x] update members export to include date updated
- [x] update events export to include new book urls with slugs

book export should include the following fields:

* url (s&co book url)
* title 
* author (list of sort names in same order used for website)
* editor
* illustrator
* preface
* translator
* contributor
* year
* format
* identified (true/false; default is true, false if marked as uncertain)
* work uri
* edition uri
* ebook url
* volumes/issues (list in the same format displayed on the website, but without formatting)
* public notes
* event count
* borrow count
* purchase count
* updated

**Comment by rlskoeser** [comment]
Re-estimating to 3pts to account for complexity added by work/volume.

**Comment by rlskoeser** [comment]
Increasing this from 3 to 5 now that we know more about issue/volume data.

**Comment by rlskoeser** [comment]
Book data should exclude subject and genre for now (they are not MVP / not 1.0 release).

**Comment by rlskoeser** [comment]
@jkotin proposed list of fields for book data export:

* s&co book url
* title 
* author 
* editor
* illustrator
* preface
* translator
* contributor
* year
* format
* uncertain
* work uri
* edition uri
* ebook url
* volumes/issues
* public notes
* event count
* borrow count
* purchase count
* updated 

Notes:
- I think it's easiest to break creators out the same way we do on the website; if you add new creator types they'll be included in the order you specify for the website. I propose including creators as a list of sort names.
- Based on conversation with @gissoo, I suggest we include a true/false uncertainty indicator corresponding to the uncertainty icon on the website. Open to suggestions for the field name.
- For volumes/issue, I suggest a list in the same format displayed on the site (no structured data for editions).
- I noticed we have an updated field in the database and think it might be nice to include in the dataset; we have it for people as well and should also add it to the member export if you agree.

**Comment by rlskoeser** [comment]
Since we're generating slugs and including S&co book uris in this export, we should update the events export to use site book uris as well.

**Comment by jkotin** [comment]
The fields of the book data look great!

**Comment by rlskoeser** [comment]
@jkotin thank you! I apologize for not being explicit about my questions.
- Do you agree with including the updated date for each record? If so: 
   - Should we also include it on the members data export?
   - Does 'updated' seem clear as a field name? Alternatives: modified, last modified
- Are you fine with 'uncertain' for the name of the uncertainty yes/no field?

**Comment by jkotin** [comment]
@rlskoeser re: dates—yes, good to include them, and yes would be good to include on the members export as well.

re: name of field, why not "unidentified"? Or better: "identified" and the default is "yes"

**Comment by rlskoeser** [comment]
Great. I like "identified" with default yes and no only for items that are marked as uncertain.

**Comment by rlskoeser** [comment]
@jkotin are there any Works in the database that should be excluded from the export?

**Comment by jkotin** [comment]
@rlskoeser No I don't think so.  You mean books/items that haven't been identified yet, e.g.?  There are mistakes in the database, but all good faith ones: I don't mind including all the works in this preliminary export.

**Comment by rlskoeser** [comment]
@jkotin great, that makes sense to me. I didn't think there was anything to exclude but thought I should check!

**Comment by rlskoeser** [comment]
@jkotin sorry, another question: does it matter to you how we order the books in the export? For member export, they are sorted by sort name; for events, sorted by first known date. We don't have a default sort configured for works at the moment and I'm not sure what an easy solution is for sorting based on the database (i.e. without Solr).

**Comment by jkotin** [comment]
@rlskoeser ideally, the sorting would be by author and then by title or date of publication. But I'm happy to do whatever is easiest. I defer to you on this.

**Comment by rlskoeser** [comment]
@jkotin sorting by first author with our database structure is complicated. Thanks for suggesting date of publication. I'm going to sort by year (oldest to newest, books with no year last) and then by title, although the title sort will be a "dumb" sort that doesn't ignore punctuation or leading stop words.

**Comment by rlskoeser** [comment]
Simpler than we expected when we estimated as a 5, because we were able to take advantage of a lot of work done on other stories (base export class, volume/issue display list, uncertainty method).

**Comment by clmahoney** [comment]
CSV: 
- All looks good here! I see all the correct fields: URI, Title, Author, Editor, Illustrator, Introduction, Preface, Translator, Contributor, Year, Format, Identified, Work URI, Edition URI, Ebook URI, Volume/Issues, Notes, Event Count, Borrow Count, Purchase Count, Updated
- I checked a couple of the "False" Identified works (the ones that should have the uncertainty icon) and it all seems to line up on the backend. Checked with "The Note Books," "The Pleasures of Innocence"
- I checked works with multivol or issues: "The Adventures of Peregrine Pickle" (multivol) and "The Enemy" (periodical with issues) and they're correct
- I checked "The Phoenix Nest" - multiple creators that are the same (authors) and also "Anabasis" - multiple creators of a different type (author and translator)

**Comment by clmahoney** [comment]
JSON: 
- All looks right as rain here too! Opened up on Oxygen

**Comment by clmahoney** [comment]
- Checked the member export and YES, I see the timestamp (the "Updated" column)

**Comment by clmahoney** [comment]
- Checked the event export and YES, I see the new book slugs in the "Item URI" column
