### ISSUE TITLE
As a non-sighted user, I want the member timeline visualization available as a textual alternative so I can learn about a member's activity range.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#269]
# dev notes
draws on [this article](https://www.sarasoueidan.com/blog/accessible-data-charts-for-khan-academy-2018-annual-report/)

need to add an invisible text `<p>` that `aria-describe`s the member timeline visualization that says something like "Member activity timeline from [year] to [year]. See the activities tab for more details."

**Comment by rlskoeser** [comment]
@thatbudakguy looking at this again, it looks like the `<object>` requires an external svg file, not an inline svg. I don't see how that works with our current implementation, since we don't currently have a way to generate the svg server side.

**Comment by thatbudakguy** [comment]
sorry - neglected to clarify on this one. this can't use `<object>` (and doesn't need to) for that reason. the other one does use `<object>` because the content it needs isn't already in context.

**Comment by thatbudakguy** [comment]
all we need to do is what's described in the issue text - add the `aria-describe` text (and maybe make sure that the browser correctly describes the svg as "image - member timeline" or something by quickly checking in VO and editing the `aria-label` or `role` if necessary).

**Comment by rlskoeser** [comment]
Forgot to mark this one as delivered, but it's on the test site. @thatbudakguy could you test?  (If you can ignore the fact that we have two charts right now, there will only be one displayed.)

**Comment by thatbudakguy** [comment]
VO + Safari: correctly announce as image, correctly announces description, no problems.
Edge + Narrator: announces chart as image, but proceeds to read every date label (year) _inside_ the chart, for both charts. we might need to add aria-hidden=true or role=presentation or something to the svg `<text>` elements inside the d3, unfortunately. why does this happen? I have no idea.
Firefox + NVDA: same as Edge + Narrator, annoyingly.

**Comment by rlskoeser** [comment]
Updated to set `aria-hidden="true"` on `<text>` elements created by the d3 axis

**Comment by thatbudakguy** [comment]
@rlskoeser this is working the way it should now. I also just noticed that NVDA is reading all of the text in the chart _legend_, too, but we aren't showing that to most users yet, so it's probably fine for now. you could just throw on `aria-hidden=true` there also.

**Comment by thatbudakguy** [comment]
going to close.
