### ISSUE TITLE
Optional start/end dates for person addresses

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#27]
In the future will there be a way to associate addresses with specific dates. For example, if we know how long Hemingway lived at 6 rue Ferou?

**Comment by rlskoeser** [comment]
Yes, we could add optional start/end dates to the person/address association.

**Comment by rlskoeser** [comment]
This is supported by the revised address/location data model included in #44.

@elspethgreen do you want to test this feature as part of testing #44?

**Comment by clmahoney** [comment]
This looks good to me!
