### ISSUE TITLE
Styles: card filter

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#274]
## testing notes
this is for the "has card" filter on the members search page.

**n.b.** by "tooltip", i'm referring to the blue question mark icon, which should show a popup when you hover over it. 

there are a couple of things going on here to check:
- on mobile, the button should span the whole width of the page. on larger screens, it should collapse to a smaller size, fitting its content.
- in general, it should behave like a checkbox (uses the `pointer` cursor, responds when clicked, has a highlight state and a checked state). see the linked design below for what it looks like when the filter is on (checkbox is checked).
- when you hover over the tooltip, it should display information about what the filter does: see the linked design below.

note also that on mobile this filter technically is part of the "advanced" pullout section; we don't have that implemented yet so it will just show up regardless.

[deskop](https://zpl.io/a7OL8gq) /  [mobile](https://zpl.io/2GyD4mj)
[tablet, with active filter](https://zpl.io/2ZL8eGq) / [tablet, with active tooltip](https://zpl.io/2jQNE8m)

## dev notes
this issue was originally for style edits to the "has card" filter (#199), but came to encompass a rewrite of the tooltip functionality as well.

**Comment by thatbudakguy** [comment]
updated estimate to reflect work on the accessible tooltip functionality.

**Comment by wafaisfahany** [comment]
all good
