### ISSUE TITLE
flash of unstyled content on page reloads

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#278]
# testing notes

i've anecdotally confirmed this is resolved, but another set of eyes wouldn't hurt. you can see the difference if you compare production (has bug) vs test (should be fixed):

https://shakespeareandco.princeton.edu/members/
https://test-shakespeareandco.cdh.princeton.edu/members/

basically when the page reloads, unstyled content appears _very_ briefly. sometimes this looks like the main menu appearing and disappearing; sometimes it's just a flash of blue (unstyled) links and other texts before the page correctly formats itself.

**Comment by thatbudakguy** [comment]
this is something to do with using `<script defer>`, which I had tried for performance reasons. it feels to me like the css is being deferred too for some reason, but it's probably more complicated than that.

solution is just to stop deferring it. our pageloads should be fast enough that it isn't a big deal anyway; can revisit if need be.

**Comment by clmahoney** [comment]
This looks good to me! I can't see any unstyled content or blue flashes.
