### ISSUE TITLE
As an admin, I want to generate a data download for events so that I can deposit and version the data for others to use.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#282]
## Notes for testing
Data is available in both CSV and JSON formats. Please check both. The files are pretty large, and importing in Excel might apply formatting which could be confusing; perhaps OpenRefine would be a good tool to use for opening and reviewing these.
- All fields listed below should be included (as appropriate for the event type)
- In addition to general review, please check the following specific cases
  - every event should have event type and start date and end date (if dates are known)
  - check events associated with shared accounts; member names, sort names, and urls should be listed for both members
- check events with no associated member: should display all event information but no member data
  - check that events with partial dates are handled properly (note that importing into Excel may break these)
  - test subscription events including some that have a category specified, number of volumes, subtype (supplement, renewal), price paid, deposit price
  - reimbursement event should include refund amount
  - borrow event should include item status if set (brought back/lost/etc)
  - purchase event should include price
  - public notes should be included as 'notes' if set
  - events with book associated should include book title; check at least one with work only and one with work and edition (note that edition display is provisional)
  - events with footnotes should include citation for the source, IIIF manifest if there is one (e..g. for a lending card), IIIF image if there is one (e.g. borrow/purchase on a card)

The volume/issue information format is provisional, I didn't want it to hold up the first round of testing on this export.

---

Adding this because it's probably our most interesting data and seems like something that could possibly be used in Palladio or RAW to generate interesting results; it should support generating a network diagram of library members and books.

## data fields to include
* account member name(s)*
* account member sort name(s)*
* S&co member URLs*
* event type (subscription, renewal, reimbursement, borrow, purchase, etc)
* start date 
* end date 
* subscription category
* subscription volumes
* subscription duration 
* subscription duration (days) 
* price paid
* refund
* deposit
* work title
* [work URL ‡]
* edition title/label
* borrow status (returned/bought/missing)
* Notes
* Source 
* Source IIIF Manifest
* Source IIIF Image

**Comment by rlskoeser** [comment]
Needs to include events that are not associated with people (name missing from logbooks).

**Comment by rlskoeser** [comment]
Increasing from 2 to 3 because this needs to include issue number and date (for periodical) or volume number (for multivolume books) for items where that information is known.

**Comment by rlskoeser** [comment]
@jkotin here's an initial draft of fields to be included in the event data export, with several questions and notes.

* account member name(s)*
* account member sort name(s)*
* S&co member URLs*
* event type (subscription, renewal, reimbursement, borrow, purchase, etc)†
* start date §
* end date §
* subscription category
* subscription volumes
* subscription duration (human readable) ¶
* subscription duration (days) ¶
* price paid
* refund
* deposit
* currency
* work title 
* work URL ‡
* edition title/label 
* borrow status (returned/bought/missing)
* source (footnote info)

## Notes
- * can be multiple (although not very common)
- † I think this should use the new notation terminology in #522; should we do that work in tandem so we can use those terms?
- ‡ We haven't generated slugs for the public work URIs; I propose leaving this out until we do that work
- § dates will be in ISO / partial date format (YYYY-MM-DD, YYYY-MM, YYYY, --MM-DD)
- ¶  I think it would be valuable to include duration in both human-readable form and actual days; not sure how best to label them to differentiate

## Questions
- Do we need to include both name and sort name for members, or is sort name sufficient?
- What details should be included from the footnotes? My current thought:
  - bibliographic note for associated lending card
  - IIIF Manifest URI for the digital object associated with the card (if available)
  - IIIF Image URI for the specific card image (if available)
- Do we want to combine price paid/refund/currency into a single field, equivalent to the "Amount" field in the membership activities table on the public site? What about deposit?

**Comment by rlskoeser** [comment]
My mistake, #522 was dropped from the 1.0 release. I'll make a note there that when it's added to the public site it should also be used in the event data download.

**Comment by jkotin** [comment]
Re: questions:

1. Re: name/sort name -- I think we need both. The name includes important information not included in the sort name.

2. Re: footnotes -- what you suggest is good. Are there other reasonable options?

3. Re: $ -- my initial response is to keep them separate, at least paid and refund. Would currency show up in amount anyway?

**Comment by rlskoeser** [comment]
@jkotin do you think the name and sort name are both important to have in the context of the events data? My thought is that people who want to look at member details (e.g. demographics) in tandem with event data would work with the two exports together. (This is one reason I'm including member URLs, as a stable identifier that will work across datasets).

For the footnotes: we could also include the source type, but I think almost all of them will be lending library card, so I don't think that's useful. I don't know if including the IIIF manifest is too much, but otherwise I don't think there will be an easy way for people to discover it. We could also include the "rendering" link from the IIIF manifest, which in the case of the lending cards will be an ARK that resolves to the finding aid page for that object (this is the PUL link on the card viewer on the public site). 

I'm fine with keeping paid, refund and deposit as separate fields and including the currency in the notation so that it doesn't need to be a separate field (e.g., `50 ₣` or `$50`).

**Comment by jkotin** [comment]
Sometimes the name and sort name are very different -- e.g. Elisabeth de Roos.  I worry about confusion.  But I defer to you on this.

**Comment by rlskoeser** [comment]
Ok, let's keep them in since they can be so different — people might need the additional context even if they are just looking at the events.

**Comment by rlskoeser** [comment]
@jkotin couple more questions about the fields that came up in implementation:
- I want to include the OCLC work URI as a a unique identifier in tandem with title; we _could_ remove that once we have S&co project URIs
- What field label do you want for edition title? (Possibly relates to conversation on #319 but we need a single label for data exports)
- What content do you want for edition title and how do I generate it from volume/issue data? (Also relates to conversation #319)

**Comment by rlskoeser** [comment]
@jkotin Another question — we don't currently have public notes for events, and I'm not sure whether you want to share the notes we do have. I'm going to leave them in the export for now so you can see them; it looks like some of them may be good to review.

**Comment by jkotin** [comment]
@rlskoeser Re: field label -- "volume" seems best, IMO. Re: notes for events. I agree would be good to review, but I don't think we will want to include them in the export.  

Re: content for edition title—I don't understand the question.

**Comment by rlskoeser** [comment]
@jkotin sorry about the lack of clarity on edition title: I mean, what text should I display to identify the volume/issue. Should it be the same as the text that Gissoo is including in her bibliography page designs?

**Comment by jkotin** [comment]
@rlskoeser this question overlaps with my discussion with @gissoo on 319. Yes, I think we should use the same text as in the designs.

**Comment by rlskoeser** [comment]
@clmahoney Test export files have been uploaded to drive for review (development & design > data exports > test 2020-02-26 )

**Comment by clmahoney** [comment]
I opened this all in OpenRefine. 
CSV: 
1) YES - I see all the categories listed. See below: 
![Screen Shot 2020-02-27 at 1 44 57 PM](https://user-images.githubusercontent.com/16673934/75475893-9edcde80-5967-11ea-9197-8afb2787f607.png)
![Screen Shot 2020-02-27 at 1 45 10 PM](https://user-images.githubusercontent.com/16673934/75475897-a13f3880-5967-11ea-87f8-9c986d104f6d.png)
![Screen Shot 2020-02-27 at 1 45 21 PM](https://user-images.githubusercontent.com/16673934/75475899-a1d7cf00-5967-11ea-820f-78b71d308416.png)

2) YES, if dates are known, each event has an event type and start date and end date 
![Screen Shot 2020-02-27 at 1 59 15 PM](https://user-images.githubusercontent.com/16673934/75476882-5d4d3300-5969-11ea-8fef-a25a5164ee23.png)


3) YES, if an event is shared then we see both members names, sort names, and urls. I used the Edels (Bertha and Leon) as an example: 
![Screen Shot 2020-02-27 at 1 57 22 PM](https://user-images.githubusercontent.com/16673934/75477229-faa86700-5969-11ea-8c13-e328c104b2a9.png)


4) YES, events with no associated member displays all relevant info without a member name: 
![Screen Shot 2020-02-27 at 2 02 55 PM](https://user-images.githubusercontent.com/16673934/75477207-f1b79580-5969-11ea-82cf-0201de673a5f.png)

**Comment by clmahoney** [comment]
- YES, events with partial dates are good: 
![Screen Shot 2020-02-27 at 2 06 29 PM](https://user-images.githubusercontent.com/16673934/75477457-5e329480-596a-11ea-9ab7-65e3df2129b7.png)

- YES, subscription events including some that have a category specified, number of volumes, subtype (supplement, renewal), price paid, deposit price: 
![Screen Shot 2020-02-27 at 2 08 06 PM](https://user-images.githubusercontent.com/16673934/75477614-976b0480-596a-11ea-8c9d-3aa7a977a4f9.png)

- YES, reimbursement events include refund amount: 
![Screen Shot 2020-02-27 at 2 09 37 PM](https://user-images.githubusercontent.com/16673934/75477769-ce411a80-596a-11ea-811f-fbdfceb18366.png)

- YES, borrow events include item status if set (brought back/lost/etc): 
![Screen Shot 2020-02-27 at 2 12 00 PM](https://user-images.githubusercontent.com/16673934/75478317-c2a22380-596b-11ea-8e5e-af7e8946f53a.png)

- YES, purchase events include price
- YES, events with book associated should include book title; check at least one with work only and one with work and edition (note that edition display is provisional): 
![Screen Shot 2020-02-27 at 2 33 16 PM](https://user-images.githubusercontent.com/16673934/75479791-20376f80-596e-11ea-9978-9c096e0b3ab4.png)

**Comment by clmahoney** [comment]
Question: where do footnotes show up? And where do public notes for events show up?

**Comment by clmahoney** [comment]
ALSO: I don't know how to upload the JSON format in OpenRefine.

**Comment by rlskoeser** [comment]
@clmahoney the bibliographic note for the footnote source should be included as **source citation**, and if it has a IIIF manifest/image, those should be in **source manifest** and **source image**.

Events don't have public notes; the export currently is including notes because I thought it might be helpful to look at them (a saw a few that seem to have data we haven't incorporated), but our thought is that the final export should probably not include the notes field. Your input would be helpful on that.

**Comment by rlskoeser** [comment]
@clmahoney to test the JSON in OpenRefine, start a new project, choose the json file, and then when prompted to select record path, use your mouse to select the first chunk of data starting with **{** (it should highlight the record for the first event with start date, member info, etc).

**Comment by clmahoney** [comment]
- YES, if there is a footnote it shows up in the source citation, with accompanying source manifest and source image: 
![Screen Shot 2020-02-27 at 3 10 12 PM](https://user-images.githubusercontent.com/16673934/75482682-49a6ca00-5973-11ea-9672-09e6a994a791.png)

- YES, I see the notes. I agree that we needn't include them on an export; it's better for us to just see them internally.

**Comment by clmahoney** [comment]
Trying with JSON now. 
Things look good here!
