### ISSUE TITLE
Member keyword search should sort most relevant items first instead of last

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#285]
## Notes for testing
- Try searching for a member with two names where at least one name matches other members (e.g. Gertrude Stein or Leo Stein). The best match should show up at the top of the list rather than at the end. (Compare with production site to see former behavior).
- If you're logged in, you should see a relevance score in the search results. If you're not logged in, you shouldn't see it.

**Comment by clmahoney** [comment]
Yes this looks good! I tried "James Joyce" and he was at the top, with James behind him, Stanislaus Joyce after that. I then tried Gertrude Stein and she was at the top.
