### ISSUE TITLE
As a user, I want my filter options on the search page to be grouped into collapsible tabs so that I can find relevant filters more quickly.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#287]
# testing notes
### desktop
[collapsed tab](https://zpl.io/VKPxBrJ) / [expanded tab](https://zpl.io/2yOxvq9)
### mobile
[collapsed accordions](https://zpl.io/2GyD4mj)

this issue is about the tabs that appear on search pages; you can test it by going to the [members search](https://test-shakespeareandco.cdh.princeton.edu/members/). note that there is currently only one tab that you can test with ("demographics"); the "books" tab should be greyed out and unclickable since we aren't adding any content to it until after the November release.

check the design links above to see what the demographics tab should look like when open & closed on desktop & tablet. try opening and closing the tab, scrolling the facets inside it, and clicking on things inside it. check that:

- spacing and sizing looks right
- on tablet, the size of the tabs changes slightly (they get taller).
- on mobile, there _should be no tab_; just a heading that says "demographics". you can see this in the mobile design link.

# dev notes
it looks like we would be implementing something pretty similar to [this example from deque](https://dequeuniversity.com/library/aria/tabpanels-accordions/tabbed-accordion#), where the tabs collapse into an accordion on mobile. however, on mobile there actually aren't any tabs at all - instead the fields themselves become accordions.

![IMG_20191016_102134](https://user-images.githubusercontent.com/4924494/66928289-26503380-efff-11e9-8380-e4a0a1deed67.jpg)

note also #288, which is for a show/hide toggle for all of the advanced fields on mobile only.

**Comment by clmahoney** [comment]
Mobile: 
- YES, there is no "tab" for demographics, just the "demographics" heading and under it the "Birth Year" option with dates fields and also a "Gender" option under that, where I can click through to "Female," "Male," and "Unknown"
- Design on mobile looks exactly like it should in Zeplin, with the exception that in Zeplin I see there's an "Advanced Search" dropdown and I don't see that on current mobile. See screenshot: 
![IMG_0732](https://user-images.githubusercontent.com/16673934/67512698-62bb0980-f667-11e9-99e3-1245ae4c2f00.PNG)

**Comment by clmahoney** [comment]
Desktop: 
- YES, the collapsed tab looks like the Zeplin design: when closed, it fits in smoothly with the rest of that bar 
- YES, when I open the tab the three columns underneath look very clean: Birth Year and Gender on the far left, Nationality in the middle, and Blank (to be filled) on the left. I am able to scroll through the Nationality filter without moving or scrolling through the rest of the page; when I change the Birth Year the rest of the filters update accordingly 
- The spacing here looks natural and intuitive
- Sizing of font looks good: clear, not too large, definitely not too small

**Comment by clmahoney** [comment]
Tablet: 
- YES, I see that the tabs for filtering (Membership Dates, Card, Demographics, Books* - which is greyed out) are all a little taller than on desktop, and "Membership Dates" instead of being on one line is broken into two (Membership/Dates)
- YES, the closed tab looks good, as per the design
- YES, when I open the demographics tab I see the filters for Birth Year, Gender (both on left column) and Nationality in middle column. 
- I can scroll down through the Nationality column without moving the rest of the page
- Spacing and size looks really natural
