### ISSUE TITLE
VIAF disappears when resaving the record

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#29]
I saved the VIAF number for Stephen Vincent Benet, and then returned to the record and the VIAF number was no longer there.  I was adding "relationships" at the same time, if that matters.

**Comment by jkotin** [comment]
I added the VIAF number again and saved.  Everything worked properly. Then I added a nationality and saved, and the VIAF disappeared.

**Comment by rlskoeser** [comment]
I'm pretty sure this is the same issue Ian identified in his recent comments on #16.  I'll look into it right away.

**Comment by rlskoeser** [comment]
Thanks @i-davis @jkotin for your careful testing!  This was a problem that was affecting both viaf and geonames autocomplete fields, and it somehow snuck past testers on other teams and even managed to make it into production for the other projects.  (We'll be fixing that soon!)

Please test viaf and geonames to confirm my changes resolve the problem.

**Comment by i-davis** [comment]
VIAF numbers stick around for me now, after saving a variety of other things. Geonames seem to be working too, tho I'm not quite sure how to test those: is that just adding countries, @rlskoeser?

**Comment by rlskoeser** [comment]
@i-davis the error was only happening when you saved an existing country, and not when you first added a new one.
