### ISSUE TITLE
As a content editor, I want to view and edit item work URI, edition URI, and view subject and genre information so that I can review and correct the information.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#292]
## testing notes
- admin should now include a section for subjects; subjects should have a name and uri
- when you edit an item, you should see work uri, edition uri, subject, and genre; subject and genre should be read only
- fields (work uri, edition uri, subject, genre) should be included in the CSV download for items
- admin item list view should have a check indicator for items with/without a work URI

## dev notes
- [x] update model with additional fields to store oclc data
- [x] make them available in admin interface; subject & genre should be read only
- [x] include in additional fields in item csv download
- [x] add check indicator for has uri in item list view

**Comment by rlskoeser** [comment]
@jkotin @clmahoney do you want of these (or maybe indicators for them) in the list view? Maybe just a checkbox if they have a URI?

**Comment by jkotin** [comment]
Checkboxes in the list view would be ideal -- thank you for asking.

**Comment by clmahoney** [comment]
- I see the section for subjects and they do indeed have a name and uri
- I can edit work uri, edition uri, but subject and genre are read-only (I think we may want to change that)
- fields are all included in a CSV download
- I see the check indicator for items with/without a work URI
