### ISSUE TITLE
Write view to serve member facet data as json

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#294]
# dev notes
- we can look at winthrop for an initial implementation of this.
- going to try having the `ListView` just respond with facet json if the `Accept:` header is set to `application/json`, as a preliminary attempt

**Comment by thatbudakguy** [comment]
reopening until it gets deployed/used by #295 .

**Comment by thatbudakguy** [comment]
this is deployed, so I think it's OK to close now. if there are any issues they should likely be tested on #295 .
