### ISSUE TITLE
As a user, I want the count of members with cards to update as soon as I change search terms or filters so that I can see an accurate number for my current search.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#295]
# testing notes
does what it says! try typing in a keyword query like "smith" and check that the count of members with card updates. then delete your query and watch it update again.

note that the gender filter may or may not be working when you test this; it's better to test using the keyword.

**Comment by thatbudakguy** [comment]
bumping this to a 2 because i made a bunch of convenience improvements as part of it that require tests, e.g.:
- split out `RxFacetedSearchForm` from`RxSearchForm`
- add `animateElementContent()` and `getTransitionDuration()` convenience functions
- create `RxBooleanFacet`

**Comment by clmahoney** [comment]
- typed in "Smith" and it showed me all smiths, no cards (which is right)
- deleted "smith" and the count went up again to all members 
- did the same with "Stein" and all seems to be working well
- Worked in Firefox
- worked in Safari (iPad)
