### ISSUE TITLE
Neither delete nor save

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#30]
While editing a record, is there a way to return to the main list of members without saving? The options that I see are "delete," "save and continue editing," "save and add another," and "save."  What if I make changes, but then change my mind and just want to "stet."

**Comment by rlskoeser** [comment]
@jkotin you can just leave the page without saving if you've made edits that you decide you don't want to keep.  Use your browser back button or the breadcrumb navigation at the top of the page to get to whichever part of the admin site you want.
