### ISSUE TITLE
Breadcrumb navigation on essay content

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#302]

**Comment by thatbudakguy** [comment]
@rlskoeser sanity check: this is done, right?

**Comment by rlskoeser** [comment]
@thatbudakguy I don't think we actually have an essay content type yet? (I guess it depends how different source pages are from analysis.)

**Comment by thatbudakguy** [comment]
ah, makes sense. so we can leave this open and say it applies to analysis, presuming analysis is different enough (has authors, etc) to be our "essay" type.

**Comment by rlskoeser** [comment]
Yes, that sounds right to me - either it's done or almost done, but I'd like to leave it open in case we need to do anything for analysis content.

**Comment by rlskoeser** [comment]
Looks to me like this is working properly. We might want to allow customizing breadcrumb labels for essays with long titles, but that seem like a future refinement.
