### ISSUE TITLE
Membership/subscription chart for the entire library

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#309]

**Comment by gissoo** [comment]
The designs proposed for this are located in the S&Co drive > Development & Design > Data Visualizations > 2019-08-28 – SVG > Issue #309 – Membership/subscription chart for the entire library

The data visualizations consist of,
bar charts that show the total number of members:
- with subscriptions in each year from 1919-1941
- with subscriptions in each year from 1919-1963
- with subscriptions in each month from 1919-1941
- with borrowing events in each year from 1919-1941
- with borrowing events in each month from 1919-1963
- with borrowing events in each month from 1919-1941
- with subscription and borrowing events in each year from 1919-1941 (with a second version to show the hover state)
- with subscription and borrowing events in each month from 1919-1941
- with subscription and borrowing events in each year from 1919-1963 (with a second version to show the hover state)


Total of 11 visualizations.
