### ISSUE TITLE
result list styles are broken on books list

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#313]
the styles for the results list on the books search page are broken. have a look [at production](https://shakespeareandco.princeton.edu/books/) and you can see the problem immediately: giant green triangles, everything out of place, etc.

they should look like [the design](https://zpl.io/2p4ppWN). note that the search form isn't built on this page; we're just dealing with the actual list of results currently.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser Ok I am done with design testing the test site using Safari, Chrome, and Firefox on the office desktop screen, the office iPad Air 2, and my iPhone SE.

*Desktop*: All browsers are fine. However, no publisher and content format information on the right column is showing and some names are in parenthesis, noting FWIW. 
![Desktop Book Results.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/5e3cc251-cbbc-4b0a-bbf5-f9b27bb82ce9)

*Tablet*: All browsers are fine. However, no publisher and content format information on the right column is showing and some names are in parenthesis, noting FWIW. 
![Tablet Book Results.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/fa024775-e9c4-4f21-87d8-12a8fff4e202)

*Mobile*: All browsers are fine. However, no publisher and content format information on the right column is showing and some names are in parenthesis, noting FWIW. 
![Mobile Book Results.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/605c5211-0443-4eae-895b-0218f475363d)

**Comment by thatbudakguy** [comment]
I don't think we actually have that information in the database now, so it's not supposed to appear yet. Think this is OK to close.
