### ISSUE TITLE
As a user, I want sorting and search on member names to ignore case and work with or without accents so that I can find people more easily.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#316]
## Notes for testing
- on the members list, the "displaying" pagination drop-down should not have lower case and accented names at the end (compare with production)
- on the members list, lower case names should sort with upper case names of the same letter - check the V section for vans and vons
- on the members list, try searching for names with and without accents (I was testing with René / Rene); you should be able to find accented names *both* ways

# dev notes
currently the members list sorts names that start with accented characters (`Éditions "Les Revues"`) and those that start with lowercase letters after all of the capital letters. this can be resolved by:
- [x] implementing unicode & case folding for sort names
- [x] implementing unicode and case folding for searching names

there is also the case of people with names like:
`von Hefsten`
`van den Bruck`
`de Houdeby`
etc.

should these be sorted according to their first capital letter/name? left as is?

**Comment by clmahoney** [comment]
Desktop: 
- YES, the drop down "displaying" name pagination does not end in lowercase anything. I compared the production site, which ends in "vo-É" to the test site, which currently ends in "Zet-Zw." To confirm: there are still lowercase names occasionally starting on the drop down menu (like "du Li-Edwards"). 
- YES, on the members list when I go to an area like the Vs where lowercase and uppercase last names would be intermixed, I see them both there. So 78 is von Hefsten while 79 is Vondel in the list order. 
- YES, names appear with and without accents. I did similar testing for this on partial names. "Rene" will yield Renés and vice versa.

**Comment by rlskoeser** [comment]
Confirming: yes, we will occasionally see lower case variants in the drop down depending on how things get chunked. I don't see a way around that at the moment.

**Comment by clmahoney** [comment]
Mobile: 
- YES, the drop down "displaying" name pagination does not end in lowercase, it ends now in the uppercase "Zet-Zw"
- YES, on the members list lower case names do sort with upper case names of the same letter, so the order might read "du Perron," then "Dublansky"
- YES, names appear with and without accents. Tried with Rene again and all the accents appear too!

**Comment by clmahoney** [comment]
Tablet: 
- Everything looks perfect here too!

**Comment by clmahoney** [comment]
Ready to hear from @jkotin if this is OK to close.
