### ISSUE TITLE
Admin interface adjustments

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#32]
- in the person list: add columns for nationality, # addresses #33
- on the person edit form: 
   - convert nationality & address to autocompletes to improve page load time and take up less space on the page #34 #35 
   - default all inlines to collapsed

- on the address edit form:
   - default the footnote inline to collapsed
  -  add help text on address name field to clarify what it is for: "Name of the place if there is one, e.g. Savoy Hotel, British Embassy, Villa Trianon"
  - change name verbose label to Name of Location

**Comment by bwhicks** [comment]
Closing the collection issue so that users test individual stories.
