### ISSUE TITLE
Books search form

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#323]
# dev notes
- [x] create `books/forms.py`
- [x] move shared classes and their tests from `people/forms.py` to `common/`
- [x] create a books form that subclasses `FacetForm`
- [x] add form methods to the `ItemList` view
- [x] make `ItemList` view subclass `FormMixin`, `AjaxTemplateMixin`, `FacetJSONMixin`
- [x] add a `test_get_queryset()` test for the new view
- [x] update `item_list.html` template based on `member_list.html`
- [x] update `books-search.ts` based on `members-search.ts`

**Comment by rlskoeser** [comment]
Verified that this is working on the QA site.
