### ISSUE TITLE
As a user, if I load the members search page with invalid input I want to see the error so I know what’s wrong and can tell when I’ve fixed the problem.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#327]
# testing notes

to test this, visit the [members search page with an invalid range supplied](https://test-shakespeareandco.cdh.princeton.edu/members/?query=&membership_dates_0=1940&membership_dates_1=1922&sort=name&page=1). you can click that link multiple times to reload it if need be.

- you should see a error message at the top of the form stating that it was loaded with an invalid range, including the numbers in the range.
- the numbers that are in the boxes of the membership date filter should match the numbers in the error message.
- the membership date filter itself should have a red error outline.
- if you clear out either of the boxes in the membership date filter, the results should reload and **all of the error messages should go away**. try doing this with one box, then reloading the page using the link above and doing it with the other box.
- until you fix the membership date filter, changing anything else on the form (the "has card" filter, the gender facet, etc) should not do anything other than reload the results (they will still be zero). the error messages should **stay there until you fix the problem**.

**Comment by clmahoney** [comment]
- I don't think this is working. Although the invalid date link works as you said, when I entered in "2000-1919" it just gave me zero results without any red lines or invalid date info. 
- Now I've tried entered in 2000 without any end date and it gives me the faulty date card of Agnes Claudius who is in the system as having a membership end in 2018.
- I'm also concerned by this: I entered in 1919 as the start and the end date, but it shows me results that begin in 1919 but can end beyond that, such as 1920 or 1935.

**Comment by rlskoeser** [comment]
@thatbudakguy do I remember correctly that displaying error messages for newly-entered invalid content is not handled yet and we were going to track it on a different issue?

@clmahoney filtering to just 1919 (i.e. entering for both start and date as you did) means the search should show any users who were active in that year - so it is reasonable and expected to have people with membership dates that go beyond 1919, as long as they _include_ 1919.  

If you know of an account that skips a year (i.e. membership spans several years but they weren't active in some of them), you could check that they do _not_ show up when you search on a year they were not active.

**Comment by thatbudakguy** [comment]
@rlskoeser yep, that's correct. as noted on #192 currently if you enter in two invalid dates _after_ the page has loaded nothing should happen. it's tracked on #331 .

**Comment by clmahoney** [comment]
Thank you both for clarifying! This looks good!
