### ISSUE TITLE
Generate book demerge list

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#329]
Should be possible to do in OpenRefine.

Criteria:

- must have at least one "different" variant title (see below)
- must have at least two borrows
- cannot be periodical (volumes are a separate issue)

variant title differences should _ignore_:

- case
- plurals
- stop words
- symbols (+, &) should be replaced with word “and”
- punctuation

**Comment by thatbudakguy** [comment]
sent the initial list of candidates to the project team, so I'm going to close this.
