### ISSUE TITLE
OCLC search syntax error breaks OCLC reconciliation

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#337]
## notes for testing
The bug resulted in everything getting flagged as "OCLCNoMatch", so just needs some simple sanity checking to confirm that records are getting matched with actually OCLC record URIs and related metadata. No need to test in depth, since the main functionality has already been tested thoroughly.

**Comment by clmahoney** [comment]
This looks good to me: there is still NoOCLC match for things without work URIs as expected, but plenty of OCLC matches with items with work URIs.
