### ISSUE TITLE
As a content editor, when I'm editing a person I want to add nationalities via autocomplete so the page loads faster and the list of countries don't take up as much space.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#34]
Related to #32

Suggested testing notes: 

- [ ]  Add two nationalities to a person via autocomplete. They should both appear as badges in the autocomplete.
- [ ] Delete one of them.

**Comment by clmahoney** [comment]
I added "France" to Hemingway (which already has the U.S.), and then saved it. At first there was a huge error screen but a few minutes later I was able to add it without a problem, and then go back and delete it. So I think this is OK?

**Comment by elspethgreen** [comment]
I added "China" to Richard Aldington, and it seemed to alter the VIAF link.  
Before, the VIAF link was correct (http://viaf.org/viaf/7402360) and the birth/death fields populated.
After, the VIAF link says "21" and the birth and death dates have disappeared.

**Comment by elspethgreen** [comment]
Same thing with Louis Aragon, trying to add "United States" --this seems to be a bug.

**Comment by bwhicks** [comment]
Hi @elspethgreen and @clmahoney: I believe this is now fixed and live on the test server. If you could try this and #35 again as you finish the testing, that would be much appreciated.

(You may need to do a refresh of your browser's copy of the page to  make sure the new Javascript is loaded. `cmd+shift+R` on Chrome on MacOS, for example.)

**Comment by elspethgreen** [comment]
This looks good to me now!

**Comment by i-davis** [comment]
to me too!
