### ISSUE TITLE
As a content editor, when I'm editing a person I want to associate addresses via autocomplete so the page loads faster and the list of addresses don't take up as much space.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#35]
Suggested testing notes
- [ ]  Add two addresses to a person via autocomplete. They should both appear as badges in the autocomplete.
- [ ] Delete one of them.

**Comment by elspethgreen** [comment]
Same problem as adding nationalities: when you add an address this way, it wipes the VIAF information.

**Comment by elspethgreen** [comment]
This looks good to me now!

**Comment by i-davis** [comment]
looks good to me too!
