### ISSUE TITLE
Update to current/newer versions of wagtail and django

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#358]
## notes for testing
This upgrade potentially touches everything on the site, and while our unit tests give us good coverage on the functionality, it's important to run through all site functionality (both public and admin) to check for any degradations or errors. You should run through search, browse, edit data, edit content, etc.

In addition to that, here's a list of specific things you should check:
- admin autocomplete lookup fields. These include (in no particular order): footnotes, footnote bibliography, country, location, geonames, viaf, person, books
- custom admin widgets: geonames, viaf
- image thumbnails on IIIF manifests, IIIF canvases, footnotes linked to a canvas
- I enabled new formatting options in the wagtail editor, please try them out: superscript, subscript, strikethrough, code
- check at least one member timeline, one member map, and the overall membership timeline charts (go to /members/graphs/ ; login required) all render properly
- ~there is a new "view" permission for django admin; I wrote a migration to create a 'data viewer' group; please create a test user in that group & staff access and login in a different browser to check that things behave correctly. The view-only user should be able to view data in admin but not edit; please check that the 'merge person' function is not available to the view-only user.~ (Never mind about testing the view permissions for now; the account page isn't viewable but it's not enough of a priority to fix now.)

**Comment by clmahoney** [comment]
- I bopped around the admin and the public-facing site, searching for people, browsing, added fake account (and deleted it); went to add people in wagtail and was able to (I added myself as an author snippet)

**Comment by clmahoney** [comment]
- Autocomplete for footnotes, footnote bibliography, country, location, geonames, viaf, person, books all working well

**Comment by clmahoney** [comment]
- image thumbnails on IIIF manifests, IIIF canvases, footnotes linked to a canvas all look good and I'm able to link them without a problem

**Comment by clmahoney** [comment]
- I added a new Test Page to the Analysis pages, and was able to successfully use superscript, subscript, strikethrough, AND code! I especially love strikethru.

**Comment by clmahoney** [comment]
- I checked Françoise Bernheim's member timeline and map, which look great
- I also checked the overall membership timeline charts and they are rendering well. I will say that the tables that have all numbers are a bit dizzying to look at, but I guess that's just the nature of the graph.
