### ISSUE TITLE
As a global admin, I want a one-time import of data from the logbook XML files so that I can manage lending library account and subscription information in the database.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#36]
Some suggested  testing notes:

- [x] Verify events against one that is known to have a subtype 
- [x] Check that there are reimbursements and subscribe events created
- [x] Spot check a few events against their XML counterpart (could filter or search by name in logbook entry)
- [x] Events with missing info will have it marked in the notes field. The final version of the script will have this output for you (or provided to you by manual query). Spot-checking should reveal these, but one good canary is a Mr Loomis, who has several.
- Note that the two events that did not import are the known issues below. I will pull them into a separate issue so that they are preserved for handling once the logbooks can be verified.

Summary output for version under testing
```
'duration' is an invalid keyword argument for this function, #fourmier, reimbursement on 1927-04-14 in mapping-expatriate-paris/transcriptions/logbooks/logbook-1927.xml
'duration' is an invalid keyword argument for this function, #piss, reimbursement on 1927-04-28 in mapping-expatriate-paris/transcriptions/logbooks/logbook-1927.xml
9555 events added (9555 total)
3499 subscriptions added (3499 total)
3762 renewals added (3762 total)
2106 reimbursements added (2106 total)
177 supplements added (177 total)
```
The totals match raw XML queries of the counts, with one overdue notice (modeled as a generic event and not part of admin right now) being added because it was miscoded as a supplement.

Questions on import issues:
- [x] Should the end date of a reimbursement (i.e. a single date thing) be the same date or left empty?
- [x] Three reimbursements look like the model for a subscription. Presumably this is a typo?

```
              <event type="reimbursement">
                <p> S.R. <persName ref="#fourmier">Mlle Fourmier</persName>
                <measure type="duration" unit="month" quantity="6">6</measure>
                <measure type="frequency" unit="volume" quantity="1">1</measure>
                <measure type="reimbursement" unit="franc" quantity="80">80</measure>
                <rs type="subcat">Prof</rs>
                </p>
```
```
              <event type="reimbursement">
                <p> Subscription reimbursed <persName ref="#piss">Mlle Pissot</persName>
                <measure type="duration" unit="month" quantity="3">3</measure>
                <measure type="frequency" unit="volume" quantity="1">1</measure>
                <measure type="reimbursement" unit="franc" quantity="48">48</measure>
                <rs type="subcat">Stud.</rs>
```

We also made the following edits to the XML to amend issues:

- Deduplicated the month December 1925 which appeared twice by accident
- Removed several instances of '1/4' as a unit of measure for month and replaced them with machine parseable .25
- Corrected one entry with an erroneous unit (`months` for `francs`)

- [x] Basic handling for subscriptions in most common format
- [x] Basic handling for renewals in most common format
- [x] Basic handling for reimbursements in most common format
- [x] Basic handling for supplements in most common format

To-dos:
- [x] Add subtype parsing
- [ x] Fix import glitches and errors
- [x] Verify totals
~~- [x ] @elspethgreen is checking with Josh re: setting enddates since they aren't always actually even months~~
- [x] End dates of subscriptions always carry over to the next month on the same day, regardless of days in month (i.e., 4/1 - 5/1). Import script will assume accordingly.

**Comment by rlskoeser** [comment]
As a sanity check, here are the totals Dana included in her report on the logbooks:

* Events: 9657
  * Subscriptions: 3528
  * Renewals: 3806
  * Reimbursements: 2134
  * Supplements: 178
  * Overdue notices: 11

I think we decided not to model overdue notices as a separate event type, since there are so few - I suggest importing them as generic events with a note explaining whatever details we have.

**Comment by bwhicks** [comment]
@elspethgreen Something I've run into on the import:

Our current database model makes `duration` (i.e. how many months) and `volumes` (`frequency` in the XML model) non-optional for subscriptions and renewals. However, there are some subscriptions in the logbooks that do not note some of that info.

A good example are the entries for `Mme Ottocar`. In 1920, she subscribes for three mos.  1921, she has a subscribe event that's probably a renewal (?) but coded as subscribe, and then for example in 1929 she has a renewal without any duration associated.

How should we handle these? 

To give some sense of options, 1) we could try to infer the length and associate it based on an initial subscription if that information is available or 2) simply not include those fields on the renewal or subscribe if they are not reflected in the transcription.

Both have drawbacks (i.e. incorrect inferences vs. leaving blank fields), but this seemed like a question for the team.

Thanks for feedback.

**Comment by jkotin** [comment]
Thank you for raising this question.  If I understand correctly, the core problem is that the renewal (in 1929) has no duration.  Is this correct?

I don't like the first option: inferring a duration based on earlier patterns.

I don't yet understand the second option -- would you say more?

I haven't thought this through: is there a way to register incomplete information?  We know that the renewal is between one month and twelve months.  (What are the standard renewal durations?  I can't remember.)  I could imagine a timeline on graph paper of each member's membership history: solid squares = member, empty squares = not member, shaded square = most likely member, but information incomplete.




---------------------------
Joshua Kotin, Associate Professor
Princeton University

press.princeton.edu/titles/11207.html

**Comment by bwhicks** [comment]
@jkotin, thank you for responding. 

The second option is simply noting a 'null' in the database, i.e., if the entry does not state a membership duration for that event, its equivalent in the database does not state a duration--just the database equivalent of nothing. That's certainly one way of indicating incomplete information and it's also one we can query trivially if we wanted (for example) to return all renewals that did not specify a duration for a given member.

Does this help clarify what I meant in option 2?

**Comment by jkotin** [comment]
Thank you -- yes, this makes sense now.  Is a third option possible?  I am thinking about how membership information will be displayed on the website: as a timeline extending over the life of the bookshop.  I wouldn't want that timeline to indicate, for Ottocar, that she wasn't a member after her renewal in 1929.  Ideally, the timeline would indicate that she was likely a member for up to a year after the renewal.

**Comment by bwhicks** [comment]
@jkotin: @rlskoeser and I talked this over, and we can go with the third option. 

We'll record the fields that are missing as blank. Then add a note to the notes field for any events that have these fields missing so that the project team can review them.

We can then handle any of the fuzzy logic and inferences for visualization down the line based on the database as it stands so we could do the sort of timeline you propose.

Thank you for noting a possible viz idea! It's very helpful to consider these things as we think about database logic.

**Comment by jkotin** [comment]
Thank you Ben and Rebecca!

**Comment by elspethgreen** [comment]
Per discussion 10/18:
People in the logbooks who have mepIDs that are not represented in the personography should be granted a personography "stub" entry.  This will aid in the logbook/personography harmonization that will commence once logbooks are published.

**Comment by bwhicks** [comment]
@elspethgreen Thanks for the reminder. Sub entries definitely included, though in the version you saw initially that portion wasn't fully working as intended.

**Comment by bwhicks** [comment]
@elspethgreen @jkotin A few things:

1) In the issue above, I've marked a few problematic entries that are coded as renewals but have the fields of subscribes (which isn't typical, there's maybe 2-3 of them). I could use your input on how to handle these.

2) There are some subscription types not included in any user stories. Right now I'm coding them as 'other' and adding them to the notes field on import, but some are frequent enough that it concerns me. I've listed them below for you to look at and get a sense of their relative frequency:
```
['"', '50', 'A.D.C', 'A.S.L.', 'A.d.c.', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'D.', 'D.D.', 'DBD', 'DBD', 'DBD', 'DBD', 'DBD', 'DBD.', 'DBD.', 'DBD.', 'DBD.', 'DBD.', 'Fr', 'Fr', 'N.R.C.', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'S.', 'Teacher', 'aa2', 's.', 's.', 'special', 'special', 'special', 'special']
```

**Comment by bwhicks** [comment]
Also using this comment to document changes to the XML to clean it up before import for posterity:

- Deduplicated the month December 1925 which appeared twice by accident
- Removed several instances of '1/4' as a unit of measure for month and replaced them with machine parseable .25
- Corrected one entry with an erroneous unit (`months` for `francs`)
- Fixed roughly 4-5 instance of `<listEvent>` tags being nested, which caused events not to be assigned dates properly.

**Comment by elspethgreen** [comment]
With regard to the first set of questions:
If it is doable within the database structure, it would make more sense to me to leave the end-date blank to communicate, at a glance, that reimbursements are singular events.

The final excerpt from the XML you provide is definitely a typo.  Instead of "volume" and "frequency" in the fourth line of code, it should say "price" and "unit."

The first two excerpts are trickier.  Those examples are both from the 1927 logbooks, which are not digitized, so I can't check this code against the actual text without going into special collections.  
The second excerpt quite clearly says "Subscription reimbursed" in the text, so I'm inclined to believe that this is a reimbursement that for some reason was recorded along with the information about the subscription duration and frequency.  The "S.R." in the first excerpt could then stand for "subscription reimbursed," and be following the same pattern.  Until I can check the physical logbooks (or we get a digitized copy), I can't rule on these being typos.
(Although "Fourmier" is almost certainly a typo, in both instances for "Fournier")

**Comment by elspethgreen** [comment]
Those corrections sound fine, as long as the 1/4 ->.25 is happening in the TEI-tags and not in the raw text itself (we do want to preserve Beach's actual notations).

**Comment by elspethgreen** [comment]
@bwhicks Sorry I forgot to answer your second question, about the different kinds of subscriptions.  Right now, let's encode them as other and preserve the information in Notes--so long as we have the option, later on, of adding new subscription categories if we need to.  I'm not ready to make a call on whether any of these rise to the level of needing a new category.  
(In particular, I wonder if the "D"s are simply deposit info presented next to the subscription type--but this is very hard to search for in the XML.  It would help if you could provide a few full examples of these Ds so I could evaluate them)

**Comment by bwhicks** [comment]
@elspethgreen Sorry this took a bit. Here's a few examples of the D and DBD from 1939 and 1940. There are several surrounding them. Those look like the  years with that particular notation appearing frequently.

ll. 2884-2888 1939
```
              <event type="subscription">
                <p>S.<persName ref="#mayer">Mayer</persName>
                <measure type="deposit" unit="franc" quantity="10">10</measure>
                <rs type="subcat">DBD</rs>
                </p>

```
ll. 2987-2992
```
              <event type="subscription">
                <p>S.<persName ref="#fourcade">Fourcade</persName>
                <measure type="price" unit="franc" quantity="50">50</measure>
                <rs type="subcat">D</rs>
                </p>
              </event>

```


ll. 739-745 1940
```
              <event type="renewal">
                <p>S.r.<persName ref="#thun">d'Herbais du Thun</persName> 
                <measure type="deposit" unit="franc" quantity="50">50</measure>
                <rs type="subcat">D</rs>
                </p>
              </event>
            </listEvent>
```

**Comment by elspethgreen** [comment]
@jkotin What do you think about the D/DBD subscription types?  They are pretty common in 1939 and 1940 (DBD only appears 1939, D appears in both), do you know what they might mean?  And do we feel comfortable creating a subtype for something we can't identify?

**Comment by jkotin** [comment]
I think I need more info to make this call.  I should look at the logbooks and we should discuss.  We should also review and inventory all the different subscription types.

**Comment by elspethgreen** [comment]
I checked Mr. Loomis, and he does not appear to have any notes appended to his subscriptions or renewals.  And as far as I can tell, he shouldn't, with the exception of an event of type "overdue" on 7-12, and which does not appear in the logbook import.

However, type "overdue" is nonstandard.  It only appears, by my assessment of the XML, 11 times, and never after 1929.  My suspicion is that either Beach stopped handling overdue fines this way, or that the transcriber who worked on the early logbooks (Harriet) used these event "types" and later transcribers did not.  My instinct is the former, because the string "overdue" also does not appear after 1929.  We do need a way to handle this information, but given its rarity, I'm not sure we need a whole new event type for it.  Once we have all the logbooks digitized, I'll be able to see what's really going on in this early years and make a better call.  @jkotin how does that sound? 

But Mayer, who has the DBD issue, does have a note explaining the incomplete information!  So in general I think that function is working

**Comment by elspethgreen** [comment]
Some ideas from testing for future releases:

Could we have a way to link from a particular subscription or reimbursement to the account that it belongs to?  I can envision an encoder clicking on a particular subscription, and then wanting to see a list of all subscription events for a particular account--now it seems like they would have to go to "Accounts" and search the name in order to access that. 

When I search in the top right corner of the full listing of accounts, would it be possible for it to offer auto-completed names like we have in other sections?  It will save time during encoding.

**Comment by jkotin** [comment]
Thanks Ellie!  This is more evidence that we should get together an standardize how we approach subscription types.  Can we plan to do this with examples from the logbooks?  What goals should orient our approach?

**Comment by elspethgreen** [comment]
Yes--I'll write to schedule a time.

In terms of motivations: I think we should assemble a comprehensive list of types in the XML, with all variations accounted for, that we then winnow by checking each in the logbook to see if it's a typo/handwriting issue/etc. or if it's a genuine type.  Then we should look at all the unknown types--not A, B, Stud. etc-- in the logbooks and try to figure out what they could mean (that may help with further winnowing).

**Comment by bwhicks** [comment]
@elspethgreen A quick note re: the current import that I realize in retrospect would have been hard to test. We didn't add generic events to the admin this round (partly because we were trying to figure out how to make the useful), but the 11 overdue notices are included in the import. Here's a detailed dump of their representation in the database:
```
"<Event {'notes': 'Overdue notice issued on 1925-12-18\\nPrice: franc 6\\nDuration:  s\\n', 'start_date': datetime.date(1925, 12, 18), '_state': <django.db.models.base.ModelState object at 0x10b3939b0>, 'id': 4370, '_account_cache': <Account {'id': 1787, '_state': <django.db.models.base.ModelState object at 0x10b3b1128>}>, 'account_id': 1787, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1926-03-30\\nPrice: franc 7.50\\nDuration: 14 days\\n', 'start_date': datetime.date(1926, 3, 30), '_state': <django.db.models.base.ModelState object at 0x10b393a58>, 'id': 4703, '_account_cache': <Account {'id': 375, '_state': <django.db.models.base.ModelState object at 0x10b3b1240>}>, 'account_id': 375, 'end_date': datetime.date(1926, 4, 13)}>"
"<Event {'notes': 'Overdue notice issued on 1926-05-22\\nPrice: franc 15\\nDuration:  s\\n', 'start_date': datetime.date(1926, 5, 22), '_state': <django.db.models.base.ModelState object at 0x10b393a90>, 'id': 4881, '_account_cache': <Account {'id': 637, '_state': <django.db.models.base.ModelState object at 0x10b3b1358>}>, 'account_id': 637, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1927-04-14\\nPrice: franc 12.50\\nDuration:  s\\n', 'start_date': datetime.date(1927, 4, 14), '_state': <django.db.models.base.ModelState object at 0x10b393b70>, 'id': 5709, '_account_cache': <Account {'id': 1502, '_state': <django.db.models.base.ModelState object at 0x10b3b1470>}>, 'account_id': 1502, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1927-05-17\\nPrice: franc 12.50\\nDuration:  s\\n', 'start_date': datetime.date(1927, 5, 17), '_state': <django.db.models.base.ModelState object at 0x10b393b38>, 'id': 5761, '_account_cache': <Account {'id': 2361, '_state': <django.db.models.base.ModelState object at 0x10b3b1588>}>, 'account_id': 2361, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1927-05-20\\nPrice: franc 17.50\\nDuration:  s\\n', 'start_date': datetime.date(1927, 5, 20), '_state': <django.db.models.base.ModelState object at 0x10b393be0>, 'id': 5769, '_account_cache': <Account {'id': 2369, '_state': <django.db.models.base.ModelState object at 0x10b3b16a0>}>, 'account_id': 2369, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1927-05-20\\nPrice: franc 12.50\\nDuration:  s\\n', 'start_date': datetime.date(1927, 5, 20), '_state': <django.db.models.base.ModelState object at 0x10b393c18>, 'id': 5770, '_account_cache': <Account {'id': 2441, '_state': <django.db.models.base.ModelState object at 0x10b3b17b8>}>, 'account_id': 2441, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1927-07-05\\nPrice: franc 18\\nDuration:  s\\n', 'start_date': datetime.date(1927, 7, 5), '_state': <django.db.models.base.ModelState object at 0x10b393cc0>, 'id': 5853, '_account_cache': <Account {'id': 2295, '_state': <django.db.models.base.ModelState object at 0x10b3b18d0>}>, 'account_id': 2295, 'end_date': None}>"
"<Event {'notes': 'Overdue notice issued on 1927-08-02\\nPrice: franc 5\\nDuration:  s\\n', 'start_date': datetime.date(1927, 8, 2), '_state': <django.db.models.base.ModelState object at 0x10b393da0>, 'id': 5904, '_account_cache': <Account {'id': 2522, '_state': <django.db.models.base.ModelState object at 0x10b3b19e8>}>, 'account_id': 2522, 'end_date': None}>"
"<Event {'notes': 'Event irregularity\\nNo person is associated with this account via <persName>Overdue notice issued on 1928-07-12\\nPrice: franc 60\\nDuration: 3 months\\n', 'start_date': datetime.date(1928, 7, 12), '_state': <django.db.models.base.ModelState object at 0x10b3935c0>, 'id': 6559, '_account_cache': <Account {'id': 2820, '_state': <django.db.models.base.ModelState object at 0x10b3b1b00>}>, 'account_id': 2820, 'end_date': datetime.date(1928, 10, 12)}>"
"<Event {'notes': 'Overdue notice issued on 1928-11-22\\nPrice: franc 85\\nDuration: 3 months\\n', 'start_date': datetime.date(1928, 11, 22), '_state': <django.db.models.base.ModelState object at 0x10b3936a0>, 'id': 6871, '_account_cache': <Account {'id': 2836, '_state': <django.db.models.base.ModelState object at 0x10b3b1c18>}>, 'account_id': 2836, 'end_date': datetime.date(1929, 2, 22)}>"
```

**Comment by elspethgreen** [comment]
Thanks!  I'm glad they're there--Josh and I will think about how to represent this information when we meet to discuss the logbooks.
