### ISSUE TITLE
Make public but incomplete urls login only

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#366]
## Notes for testing
You should be able to access the following pages if you are logged in, but get a 404 if you are not logged in:
- member search and browse
- member detail page
- membership activities
- book search and browse
- book details
---
## Notes for dev
Temporarily, for mid-october release

Basically content pages only will be accessible (except for analysis, not yet built)

restrict access to these:
* all member urls (browse, detail, activities)
* all book urls (browse, detail)

**Comment by clmahoney** [comment]
Unfortunately Members, Books, Cards, and Analysis are greyed out and not clickable on the test site. See attached photo. I'm able to click through Sources and About pages. 
![Screen Shot 2019-10-09 at 8 06 01 PM](https://user-images.githubusercontent.com/16673934/66529178-79daf280-ead0-11e9-8055-ffd803cfdc31.png)

**Comment by rlskoeser** [comment]
Sorry, @clmahoney ! I forgot to note that you'll have to edit the url and go there directly to check, now that the menu links are turned off.  To get to the members pages add `/members/` to the main test url; once you get there, if you're logged in you should be able to navigate to other member pages. To get to the books pages, add `/books/` to the main url.

I recommend testing simultaneously in two browsers, one where you are logged in and one where you are not - that way you can navigate to test pages in the browser where you're logged in, and then cut and paste them to test that you get a 404 in the browser where you are not logged in.

**Comment by clmahoney** [comment]
Thank you for clarifying @rlskoeser! 
- If I AM logged in, I can still access the Member page, the search and browse, the detail page, and the membership activities. I checked Abbott (not many events) and Colens (tons of events). 
- If I AM logged in, I can still access the Books page, including search and browse and book details. I checked "Beyond the Horizon" and "Jude the Obscure"

**Comment by clmahoney** [comment]
- If I'm not logged in, on the Member page I see: a "Not Found" page and image of the "Absent on business" sign. I also get a "Not Found" page and image when I check books.
