### ISSUE TITLE
Disable but show menu links for inactive parts of the site

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#367]
# testing note

to test this, just go to [the homepage](https://test-shakespeareandco.cdh.princeton.edu/). open the main menu (top right) and verify that:

- members, books, cards, and analysis are greyed-out and you can't click them
- there's a message at the bottom saying "coming soon" or something similar (how's this look?)
- sources and about look normal (not grey) and you can click them

now check the links in the footer (bottom left) and verify that:

- members, books, cards, and analysis are unclickable and have a little asterisk next to them
- you can see the "coming soon" text here too (is it noticeable?)
- sources and about are clickable, and they turn black when you hover over them

that's it!

# dev notes
Related to #366

**Comment by thatbudakguy** [comment]
see [notes on design doc](https://docs.google.com/document/d/1VFMkKe3J6gCb4X5vrv2V42jvrGhOJn9x0ocWC6f0JCM/edit) for text & ordering updates

**Comment by clmahoney** [comment]
- As per my other note and screenshot, Members, Books, Cards, and Analysis ARE greyed out, with asterisks next to them. They are unclickable. But there is no such sign or text that says "coming soon." 
- I see the "coming soon" text in the bottom left of the Home Page, but not when I click on the menu. See screenshot. 
![Screen Shot 2019-10-09 at 8 38 27 PM](https://user-images.githubusercontent.com/16673934/66530204-cd4f3f80-ead4-11e9-9a0a-921b2fc23dd6.png)

**Comment by clmahoney** [comment]
- Sources and About look normal, are not greyed out, and I can click them.

**Comment by clmahoney** [comment]
The footnotes: 
- Yes, Members, Books, Cards, and Analysis are all greyed out, are unclickable, and have asterisks next to them. 
- As I said above, I see the coming soon text here! 
- Yes, the Sources and About are clickable, and turn black when I hover. So do Home, Contact, Data Export, How to Cite, Credits, and Technical. They're all clickable.

**Comment by thatbudakguy** [comment]
hey cate,

the "coming soon" text in the main menu should look like this (circled)...can you confirm it's visible for you? i realize it's probably a little hard to spot, sorry about that.

![Screen Shot 2019-10-10 at 9.10.22 AM.png](https://images.zenhubusercontent.com/5aa82c4b4b5806bc2bcab4fa/74ecb0d1-5832-4c8e-ae81-245251e2bebb)

**Comment by clmahoney** [comment]
I think this is an error on my laptop's part, since I don't have a desktop to test this on, but I can't scroll down far enough to see the "Coming soon" text. See screenshot for what's happening on my laptop. 
![Screen Shot 2019-10-10 at 9 38 21 AM](https://user-images.githubusercontent.com/16673934/66574208-d5919400-eb41-11e9-998b-100b0d3f4472.png)

**Comment by clmahoney** [comment]
If you can tell me how to make the screen bigger, I will try that! I've made the window as big as I can.

**Comment by thatbudakguy** [comment]
aha! this isn't your fault - we need to adjust the menu spacing to handle this screen size better so that everything is visible. thank you!

**Comment by clmahoney** [comment]
OK: I tried to "print" the Navigation page, and on the print screen it DOES show the coming soon at the bottom!! So if this is enough of a test for you guys, I can sign off on it. 
![Screen Shot 2019-10-10 at 9 41 12 AM](https://user-images.githubusercontent.com/16673934/66574399-243f2e00-eb42-11e9-9a17-31c5b971d1cc.png)

**Comment by rlskoeser** [comment]
@clmahoney : @thatbudakguy made an adjustment, please test again

**Comment by clmahoney** [comment]
Yes it works!! I go to the navigation page and at the bottom of it I see the “coming soon” text.
