### ISSUE TITLE
Update sources page text styles

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#368]
# testing notes

this issue tests a variety of different text styles (lists, quotes, images, captions) that are likely to appear on sources, analysis, and about pages. when testing you'll want to refer to [the design](https://zpl.io/2G1e9WW), which includes lots of different styles on one page.

check out [this example sources page](https://test-shakespeareandco.cdh.princeton.edu/sources/cards/), which was created to mimic the design. look for these things to compare to the design:

- an image
- an image caption
- blockquotes
- regular text paragraphs
- a bulleted list

if you can, test on a mobile device to make sure nothing appears obviously broken or looks awkward.

check also that the page ends with a "how to cite" section. the text in that section should look like the design, and it should show:

- the page's title
- the project title
- today's date
- the URL of the page you're looking at

**Comment by clmahoney** [comment]
First checked on desktop: 
- The image looks good
- The image caption on the test link has wider margins than the image caption on the Zeplin page. I think they should be more like the Zeplin original page. 
- Block quotes look good! The second block quote (beginning "Before Joyce left"), however, I don't think should be a block: it's only 3 lines, and block quotes are usually 4 or more lines. 
- Bulleted list looks good! 

YES, the page ends with a How to Cite section, and includes Page Title, Project Title, Date accessed, and link.

**Comment by clmahoney** [comment]
Then checked on mobile: 
- Image looks great
- Image caption looks great here, I think it looks more lined up on mobile than on desktop. 
- Block quotes are great; the second block quote is indeed necessary here as the page is so much smaller and so turns this quote into 4+ lines. 
- Bulleted list is good 

YES, the page ends with How to Cite, and includes Page Title, Project Title, Date accessed, and link.
