### ISSUE TITLE
As a content admin, I want to select a featured image for content pages so I can give an idea of the content on the sources landing page and provide a visual preview for social media.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#369]
## Notes for testing
- When you edit a content page (like the cards or logbooks), you should now have an option to choose a featured image
- The featured image should be displayed on the landing page that the content page belongs to (e.g. sources for the cards or logbooks)

### design testing
please check that a landing page (try with "[sources](https://test-shakespeareandco.cdh.princeton.edu/sources/)") looks like the design, on all devices that you can:
[desktop](https://zpl.io/agWqzKR) / [tablet](https://zpl.io/29n8kOd) / [mobile](https://zpl.io/ad18r0p)

there should be a subtle lifting effect when you hover over the cards/tiles on the landing page.

## dev notes
- add optional featured image field to content page type
- display featured image on sources list page tile
- use featured image for social media
- add breadcrumbs to landing pages & content pages

**Comment by clmahoney** [comment]
- I can edit the logbooks page and I see featured image as an option. 
- But I tried to upload a featured image (a jpg) and a body text, but only the body text showed up.

**Comment by clmahoney** [comment]
Does the image have to be SVG too?

**Comment by clmahoney** [comment]
Just tried again and now that I have the publishing function, it works!! Here's a lovely screenshot of Lucille Ball representing the 
![Screen Shot 2019-10-11 at 11 31 27 AM](https://user-images.githubusercontent.com/16673934/66664559-c3375900-ec1a-11e9-8f36-6eb4c602e20f.png)
logbooks.

**Comment by clmahoney** [comment]
If I want to delete the image and the text, how do I do that? Hit "unpublish"? If I try to delete and save now, it won't let me.

**Comment by rlskoeser** [comment]
@clmahoney body content is required for content pages, but you should be able to use the 'clear choice' option on the featured image and save to remove the image.

**Comment by clmahoney** [comment]
This looks great! I was able to chose the featured image, as seen in the screenshot above, and then remove it. I have left in a "test" in the current body, since it's not able to be deleted.

**Comment by clmahoney** [comment]
OK, re: design testing: 
- Mobile test: this looks good except that I cannot see the breadcrumbs (I think I'm using that correctly) at the top of the page. See screenshot. 
![Image-1](https://user-images.githubusercontent.com/16673934/66674439-e0772200-ec30-11e9-92f3-2f3c39264d2a.jpg)
- There is also no preview text for the different sections on the landing page, although there is on the desktop/laptop version

**Comment by clmahoney** [comment]
This looks awesome on mobile. See screenshots! Image of fish with umbrellas and all. 
![IMG_0647](https://user-images.githubusercontent.com/16673934/66674822-eae5eb80-ec31-11e9-86a3-29f3e1a4a05d.PNG)
![IMG_0648](https://user-images.githubusercontent.com/16673934/66674828-ec171880-ec31-11e9-82a4-e7c5de4a4f1f.PNG)

**Comment by clmahoney** [comment]
Tablet looks awesome too! 
![IMG_0217](https://user-images.githubusercontent.com/16673934/66675309-12898380-ec33-11e9-8215-55afc42c0516.PNG)

**Comment by clmahoney** [comment]
I see the lifting effect when I hove over the different pages on the landing page, but only on my laptop. Should I be seeing them on my mobile or iPad?

**Comment by clmahoney** [comment]
Also: I see that the pages are staggered slightly: is this just because there is a featured image in one? Are they meant to be like this or should the outlines all be the same? 
![Screen Shot 2019-10-11 at 2 28 33 PM](https://user-images.githubusercontent.com/16673934/66675560-8a57ae00-ec33-11e9-80e9-5991ed7251da.png)

**Comment by thatbudakguy** [comment]
@clmahoney I think you should see the lifting effect really briefly at the moment you touch them on a mobile or iPad, since there's no "hover", but it will activate when you touch.

**Comment by clmahoney** [comment]
@thatbudakguy I don't see a lifting effect but the image does turn grey right before it clicks me through

**Comment by rlskoeser** [comment]
I think we're ok with that behavior for now; we can revisit later if necessary. I'm going to close this so we can release on Monday.
