### ISSUE TITLE
As a content admin, I want to add authors, publication date, and editors for essay pages so I can document the provenance of the content.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#370]
# testing notes

authors and editors are implemented as a new snippet type in wagtail. in order to assign an author or editor to a piece of content, you have to first create them as a person. to do this:

- go [to wagtail](https://test-shakespeareandco.cdh.princeton.edu/cms/)
- click "snippets" on the left
- click "persons"
- add a new person. once the person is added and saved, you can add them to an analysis essay - see the notes on #252 for details on that.
- try adding some people as authors and editors on various pages.
- if you add someone to a page, this information will only be _displayed_ if it's an essay (Analysis) page - in other words, people can be authors or editors of Sources or About pages, but that won't show up anywhere on the site right now. check that this is true by looking on both the landing pages and the pages themselves.
- try adding some authors and editors to an essay (Analysis) page. check that they display when you view the page. Do they show up in the same order that you assigned them when you edited the page?

## dev notes
- add to content pages but make them all optional
- add Person snippet (see PPA)
- add author field to essay page; should allow multiple, and preserve order (see PPA)
- use first publication date (see PPA)
- add editor field to essay page; should allow multiple, and preserve order (same as authors)
- display author, editor, and publication date on the page
- update citation format to include author (maybe editor?)

**Comment by clmahoney** [comment]
@rlskoeser I can't see the "snippets" on the left! This is what I see: 
![Screen Shot 2019-11-15 at 3 33 19 PM](https://user-images.githubusercontent.com/16673934/68973839-466d4100-07bd-11ea-9827-a94b183b5c21.png)

**Comment by rlskoeser** [comment]
@clmahoney interesting - suspect you need permissions. Just granted them in the test site, please check.

**Comment by clmahoney** [comment]
@rlskoeser yep that was it! Thanks!

**Comment by clmahoney** [comment]
- YES, I can create and add a new person
- YES, I added Ian as author and editor of the Logbooks analysis page - his name shows up at the top of the page, and on the preview page 
- YES, I added Josh as author for the Sources Logbook essay - and his name shows up on the bottom of the document, and his name doesn't show up on the preview 
- YES, I added multiple authors to the Logbooks analysis essay page that I invented: Josh as first author, Ian second, with Ian as editor. YES the order was correct. See screenshot: 
![Screen Shot 2019-11-15 at 4 11 39 PM](https://user-images.githubusercontent.com/16673934/68975953-a3b7c100-07c2-11ea-8db9-50610f40d51a.png)

**Comment by clmahoney** [comment]
- YES, I can still add a new person
- YES, I can add these new people as authors and editors. If I add in an author to a Sources page, they show up at the bottom of the page and do not appear in the preview. If I add an author to an Analysis page, they show up at the top, and they DO appear in the preview. 
- YES, the order in which I add people as authors is the right order the appears on the Analysis page
