### ISSUE TITLE
As data editor, I want to see thumbnails for bibliography and footnote records that have manifests and canvases attached, so I can check against the thumbnail and access the full size images.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#373]
## Notes for testing
- check bibliography in admin
  - list view should include thumbnails for records that have a manifest associated
  - thumbnail should be clickable and take you to the finding aids view of the entire object
  - when you edit a record, you should be able to edit the manifest that is associated with (to add or change)
  - the thumbnail should also display and be clickable on the edit record
- check footnotes in admin
   - list view should include thumbnails for records that have a canvas associated
  - thumbnail should be clickable and take you to the finding aids view of the entire object
  - when you edit a record, you should be able to edit the image to add or change which canvas the footnote is associated with
    - image should be restricted to canvases associated with the manifest that the corresponding bibliography is linked to
    - should not be able to select an image if the bibliography is not associated with a manifest
  - thumbnail should also display and be clickable on the edit record 
- inline footnote editing (e.g. on borrow, purchase, or event) should also include an editable image field (for the IIIF canvas the footnote should be associated with) and display the thumbnail

**Comment by clmahoney** [comment]
Checking bib: 
- Checked Alice Savy lending card: the list view showed the thumbnail, I was able to click the manifest thumbnail through to the finding aid view of the entire image.

**Comment by clmahoney** [comment]
Checking footnotes: 
- List view DID include thumbnails for records that have a canvas associated
- Checked borrow for account #533 1926-01-28/1926-02-02‎ (Hemingway borrow)

**Comment by clmahoney** [comment]
Inline footnote editing: 
- Checked borrow for account #4716 ??/1961-04-20 (Baltrusaitis), and there was the right image thumbnail, which I could edit it and also click through to the finding aid
- Checked purchase for account #39 1939-12-23 (Burt), and there was the right image thumbnail, which I could edit it and also click through to the finding aid
- Checked generic event for account #179 ??/--01-08 (Morgan), and there was the right image thumbnail, which I could edit it and also click through to the finding aid
