### ISSUE TITLE
style changes from "notes on website design"

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#375]
# testing notes
this issue aggregates a bunch of small things from josh's notes (see link below).

- check that the size of the logotype (the main title and subtitle) on the homepage are slightly larger (you can compare [test](https://test-shakespeareandco.cdh.princeton.edu/) with [production](https://shakespeareandco.princeton.edu/) - the difference might be more visible on smaller screen sizes)
- open the main menu and check the taglines under the links (see notes below)
- open the main menu and check the order of the links (see below)
- check the order of the links in the footer (see below)
- go to the [members search page](https://test-shakespeareandco.cdh.princeton.edu/members/) (you might be prompted to log in) and check that "birth year" comes before "membership dates" in the filters
- check that the words Birth Year are capitalized
- go to [hemingway's page](https://test-shakespeareandco.cdh.princeton.edu/members/224/) and check that there is a link that says "Wikipedia" (instead of "more info")

# dev notes
[link to Josh's notes](https://drive.google.com/open?id=1VFMkKe3J6gCb4X5vrv2V42jvrGhOJn9x0ocWC6f0JCM)

- [x] change the size of the homepage title text and the subtitle text for desktop (based on the new homepage screen for desktop on Zeplin) - the sizes have increased a bit for this page and for desktop only
- [x] change the menu taglines for members: Explore the lending library membership
for books: Explore the lending library holdings
for lending library cards: Explore the extant lending library cards
- [x] change the order of links in footer to: members, books, cards, analysis, sources, about
- [x] change the order (and naming) of links in main nav to: members, books, cards, etc...
- [x] swap the order of the "birth year" and "membership dates" filters on members search
- [x] capitalize "Birth Year" on members search
- [x] if the member's reference is a Wikipedia link, make the text of the link "Wikipedia"

<s>create "demographics" dropdown on members search and move birth year/gender into it</s>
<s>add a disabled "books" dropdown on members search</s>
see #287 - not implementing until November release

**Comment by clmahoney** [comment]
- YES, I checked on mobile, and the "Shakespeare and Company" part of the logo is much bigger than the "project" part of it. Same for on desktop. 
- YES, taglines match: under MEMBERS we have "Explore the lending library membership," under LENDING LIBRARY CARDS we have "Explore the lending library cards," under BOOKS we have "Explore the lending library holdings." 
- YES, the links of footers are in the right order: Members*, Books*, Cards*, Analysis*, Sources, About in one column. Next column: Home, Contact, Data Export, How to Cite, Credits, Technical. 
- YES, main navigation order is now: Members*, Books*, Cards*, Analysis*, Sources, About
- YES, when I go to membership search page (which I could only get to through the link you gave; I'm not able to click through in main navigation page right now), Birth Year comes before Membership Dates and then Card 
- YES, as noted above, "Birth Year" is capitalized as such
- YES, I went to Hemingway's page via the link provided, and it says "Wikipedia" under Reference, along with "VIAF"
