### ISSUE TITLE
As a content editor, I want to create and edit account records so I can track how people associated with the library.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#38]
Testing notes:

- [x] Accounts can be created from Accounts -> Accounts
- [x] Autocompletes for associating with Addresses and People

**Comment by i-davis** [comment]
Created (then deleted) an account for Mr. McGillicutty. Worked lovelily -

**Comment by i-davis** [comment]
Re autocomplete: spot-checked on several different accounts: both people & addresses speedily autocompleted.
