### ISSUE TITLE
As a user, I want to see an error page when the content I'm looking for isn't found so that I can choose a different path.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#380]
# testing notes

you can test this by going to any page that doesn't exist - for example, [/foo/](https://test-shakespeareandco.cdh.princeton.edu/foo/).

you should see a 404 (not found) error page. please check the page's appearance against the designs in zeplin:

[desktop](https://zpl.io/a397OD8) / [tablet](https://zpl.io/VQ1x759) / [mobile](https://zpl.io/bJ1jxyE)

# dev notes
this is our 404 error page, which will also be served on routes that are login-only.

**Comment by clmahoney** [comment]
Desktop works great: I get a "Not Found" text, along with the image of SB's "Absent on business" sign. My only note would be: if this two words are capitalized, maybe we should capitalize "Something Went Wrong" too, to be consistent.

**Comment by clmahoney** [comment]
Tablet looks great too: I see the "Not Found" text, along with the image "Absent on business"

**Comment by clmahoney** [comment]
Mobile look great as well! I can see the "Not Found" text, along with the "Absent on business" sign.
