### ISSUE TITLE
As a user, I want to see an error page when the site is malfunctioning so that I can report the issue.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#381]
# testing notes

normally you wouldn't be able to intentionally visit this page, since it should only occur if the site is malfunctioning, so we've added a url that intentionally "breaks" the site so that you can test it - please visit [/500](https://test-shakespeareandco.cdh.princeton.edu/500/).

you should see a 500 (server error) error page. please check the page's appearance against the designs in zeplin:

[desktop](https://zpl.io/VK65vgP) / [tablet](https://zpl.io/agWypYN) / [mobile](https://zpl.io/bWXP0e1)

# dev notes
this corresponds to the 500 error page.

**Comment by clmahoney** [comment]
Desktop looks great: I see the "Something went wrong" text and great image of SB's publisher's note.

**Comment by clmahoney** [comment]
Tablet looks great too: I still see the "Something went wrong" text and the SB publisher's note image.

**Comment by clmahoney** [comment]
Mobile works great too: I see the "Something went wrong" text and the same publisher's note.
