### ISSUE TITLE
As a content editor, I want to add SVG images to content pages so that I can include data visualizations and other scalable images with.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#393]
## Notes for testing
When you're editing content pages, you should now have an option to add an SVG image. Please try adding one and check that it displays on the page when published.

**Comment by clmahoney** [comment]
Yes this works! I added the SVG membership chart to the "About" page. It uploaded and previewed correctly. See screenshot. 
![Screen Shot 2019-10-11 at 10 22 42 AM](https://user-images.githubusercontent.com/16673934/66659261-2ae8a680-ec11-11e9-8cd1-566f56d147b3.png)

**Comment by clmahoney** [comment]
I was able to then delete it successfully. See screenshot. 
![Screen Shot 2019-10-11 at 10 24 22 AM](https://user-images.githubusercontent.com/16673934/66659354-57042780-ec11-11e9-8392-3a552f833cdd.png)

**Comment by clmahoney** [comment]
I tried the same thing on the Source page and it worked too! The only thing is that the image caption is quite distant from the bottom of the image itself. I'll add in a screenshot. Maybe that's the nature of this graph? Or will all captions be so far down? 
![Screen Shot 2019-10-11 at 10 26 44 AM](https://user-images.githubusercontent.com/16673934/66659523-a6e2ee80-ec11-11e9-99fc-12f44d806cd5.png)

**Comment by clmahoney** [comment]
Awesome, this works! I tested with the S&Co image that RSK suggested (Shakes' head) and the caption is much closer now. See screenshot. 
![Screen Shot 2019-10-11 at 10 41 59 AM](https://user-images.githubusercontent.com/16673934/66660804-dd216d80-ec13-11e9-81ab-3feedbef9874.png)
