### ISSUE TITLE
csp policy updates

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#396]
this is an issue to track multiple changes to our current policies.

we're currently seeing some CSP `script-src` directive violations; it could be because the pages with `RdfViewMixin` are rendering a script tag without a nonce. we'll need to change the line in `base.html` to read:
```html
<script type="application/ld+json" nonce="{{ request.csp_nonce }}">{{ page_jsonld|safe }}</script>
```

- [x] add nonce to jsonld
- [x] update `connect-src` policy to include `self`
- [x] update `img-src` policy to include <https://www.googletagmanager.com/>
- [x] add nonce to `style-src` and include it on the `<ol>` element that uses an inline style
- [x] switch QA configuration to match prod (block instead of report-only)

**Comment by rlskoeser** [comment]
I'm still seeing warnings on the members page for an inline style and for loading an image from google analytics (not sure why we're trying to do that...).

I see the nonce in the code for the style; is the syntax correct?
```
[Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-wNyRlYyHdqVXbL5x'". Either the 'unsafe-inline' keyword, a hash ('sha256-cbunhIHo0XKAl2JEie3vi/F94ns8BnLuyQ7r7mXpkD0='), or a nonce ('nonce-...') is required to enable inline execution.
```

Excerpt of the image error (I see two):
```
[Report Only] Refused to load the image 'https://www.google-analytics.com/collect?v=1&_v=j79&a=1786996214&t=pageview&_s= ..... '
because it violates the following Content Security Policy directive: "img-src 'self' https://www.googletagmanager.com".
```

**Comment by thatbudakguy** [comment]
i don't understand why it's an image request either, but we had the same rule in ppa - perhaps it's a "tracking pixel" type of thing? to be more specific, in PPA we had both of these for `img-src`:

<https://www.googletagmanager.com>
<https://www.google-analytics.com>

I hadn't seen any instances of the latter (and the domain looks weird...why the dash?) "in the wild" so I removed it thinking it could just be an older URL, but apparently google makes requests to _both_ of them, and they're both `img` requests. go figure. I'll add the second one back to the rule.

re: the nonce, I went back to [the w3c discussion](https://github.com/w3c/webappsec-csp/issues/45) and I guess this is expected behavior, though they have been debating how to make it better since 2016. only chrome supports `style-src-attr` so far, so we need a workaround. fortunately, MDN actually offers one that I should've thought of earlier:

```css
<style nonce="2726c7f26c">
ol { counter-reset: results 0; }
</style>
```

i.e. just write a style tag into the template and apply the nonce to it, which we know will work. I'll try this.

**Comment by thatbudakguy** [comment]
there's no explanation of why they are needed, but it looks like the correct CSP settings are actually [at this location in google's docs](https://developers.google.com/tag-manager/web/csp#universal_analytics_google_analytics) - i had thought that we needed the stuff at the top (for "tag manager"), but apparently we are "universal analytics", which sort of explains the domain and the `img-src` requests.

**Comment by rlskoeser** [comment]
I'm not seeing any warnings on the test site anymore.
