### ISSUE TITLE
As a content editor, I want to add and edit subscription information so I can track how and when members interacted with the library.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#40]
Should include:
* Subscription type
  * A
  * B
  * AdL
  * Student
  * Professor
* Subscription events with dates and money amounts
  * New subscription
  * Subscription renewal
  * Deposit paid

Test Notes (from @bhicks):

- [x] includes types for A, B, AdL, Student and Professor (also A+B)
- [x] Subscription events have dates and money
- [x] Modification can indicate supplements and renewals
- [x] Deposits are reflected

**Comment by bwhicks** [comment]
Splitting reimbursement into a separate story (since it's a separate subclass of `Event`)

**Comment by elspethgreen** [comment]
Spot-checked several records, they all contain (or could contain) the desired information.
