### ISSUE TITLE
As a user, I want to see a map of all of a member's known addresses so I can see where in Paris members lived.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#407]
# testing notes
## links
you can test this by visiting the detail page of a member. try with a few different ones:
- [alard](https://test-shakespeareandco.cdh.princeton.edu/members/2733/) (no addresses; map shouldn't be shown)
- [de beauvoir](https://test-shakespeareandco.cdh.princeton.edu/members/48/) (just one address, in paris close to the library)
- [chenneviere](https://test-shakespeareandco.cdh.princeton.edu/members/72/) (multiple addresses in paris)
- [hemingway](https://test-shakespeareandco.cdh.princeton.edu/members/224/) (many addresses both in paris and overseas)

## design links
[desktop](https://zpl.io/bzqRrXz) / [tablet](https://zpl.io/VQvnk7A) / [mobile](https://zpl.io/bA7PWZe)

## checklist
check that:
- for members with no address info, the map does not appear
- for members with an address, a new section called "Addresses" appears with a map
- you can pan around the map by clicking and dragging (or just dragging on mobile)
- you can zoom the map by touching/clicking the zoom controls in the bottom right
- when viewing anywhere in Paris, you should see the historic map of Paris as the background
- when viewing outside Paris, you should see a fairly basic white basemap instead
- when you click one of the green address markers, a popup appears with information
- when the page loads, the first address should already be selected, showing its popup
- when the page loads, all addresses should be visible on the map without panning/zooming
- a special marker should appear to mark the location of the bookstore, and be clickable

check the page against the designs linked above. note that the designs show the map as full-width on desktop and tablet; this is no longer accurate as the size and dimensions were changed to allow the user to scroll more easily. it should still be full-width on mobile, however.

if any behavior of the map doesn't feel natural (i.e. would confuse you if it happened in google maps), leave a note.

# dev notes
this is the map on the member detail page, not the larger map.

- Use this PUL [Paris 1943 map](https://www.arcgis.com/home/webmap/viewer.html?webmap=2eeb7da2015e40c590b8076625b394d4&extent=2.2075,48.8029,2.4611,48.911)
- Addresses can be directly associated with a person or with their account; lat/long is on the location associated with the address

- [x] add a basic basemap (from mapbox? check xinyi's old design)

**Comment by clmahoney** [comment]
Desktop: 
- YES, if the member doesn't have any address information, the map doesn't appear. I tested Alard and Eimat. 
- YES, if the member does have address info, there is a new section that appears called "Addresses" and I see the cool map below it with the green address markers for the members and with the special S&Co logo marker signifying where the bookshop is. I checked Chenneviere and de Beauvoir.   
- YES, if I click and drag the map I can move it all around 
- YES, I can zoom in and out of the map with the +/- buttons in the lower right corner, or by squeezing my fingers in or out on my trackpad 
- YES, I see the historic map of Paris and then 

- YES, I see the regular white map when outside the city limits, and I can zoom all the way out to see multiple other countries and continents, while still seeing the S&Co logo: 
![Screen Shot 2019-11-12 at 12 57 13 PM](https://user-images.githubusercontent.com/16673934/68697046-0d7a6580-054c-11ea-98fe-54199351fca0.png)

- YES, when the page loads I can see the member's address revealed on the map. 
Question tho: if the member has more than 1 address, why does only one get highlighted first, or what is the logic for one having all of its info revealed does not? Like on CHENNEVIERE, this is what appears: 
![Screen Shot 2019-11-12 at 12 59 46 PM](https://user-images.githubusercontent.com/16673934/68697230-634f0d80-054c-11ea-8e15-9b3ef8d36120.png)

- YES, when the page loads I see all addressed without having to zoom out to find them all. But there are some cases when one of the address markers is fairly hard to see in the corner of the map. Like for Simon de Bretteville: 
![Screen Shot 2019-11-12 at 1 02 03 PM](https://user-images.githubusercontent.com/16673934/68697408-bde86980-054c-11ea-96cc-9aa4e7766a6a.png)
- but I imagine this is just going to happen and depends on how big my desktop/laptop screen is

- YES, I always see the special S&Co marker and if I click on it, I see the shop's address 

One odd thing: 
- When I looked at Louis Aragon's map, his address puts him on one of the vintage map's key (I think it's a key??): just a bit confusing 
![Screen Shot 2019-11-12 at 12 49 55 PM](https://user-images.githubusercontent.com/16673934/68697561-14ee3e80-054d-11ea-99a1-a60c6d0fca57.png)

**Comment by clmahoney** [comment]
Mobile: 
- YES, if the member doesn't have any address information, the map doesn't appear. I tested Alard.
- YES, if the member does have address info, there is a section that appears called "Addresses" and I see the map below it with the green address markers for the members and with the special S&Co logo marker signifying where the bookshop is. I checked Chenneviere, and used him for these next steps. 
- YES, I can drag the map around with my fingers, and I can zoom in and out of the map with the +/- buttons in the lower right corner, or by squeezing my fingers in or out on my screen.
- YES, I see the historic map of Paris and then YES, I see the regular white map when outside the city limits
- YES, when I click one of the green address markers, a popup appears with information - tried Hemingway 
- YES, when the page loads, the first address is already selected, showing its popup - tried Hemingway
- YES when the page loads, all addresses should be visible on the map without panning/zooming
a special marker should appear to mark the location of the bookstore, and be clickable - yes, as you can see on Hemingway who is spread out all over the world (although this means his markers sometimes block each other out): 
![Image from iOS (2)](https://user-images.githubusercontent.com/16673934/68715071-2ba58d00-056f-11ea-8dad-ceb1750da12a.png)
- YES, I can see the special S&Co popup 

I'm not sure if the map is "Full" on the mobile screen as the designs are. It doesn't fill the entire screen like it does in the design. Here's an example from the Hemingway page:
![Image from iOS (3)](https://user-images.githubusercontent.com/16673934/68715237-8808ac80-056f-11ea-8925-01e8def095f3.png)

**Comment by clmahoney** [comment]
Tablet: 
- YES, if the member does not have address info, there is no map nor an "addresses" section - checked Alard
- YES, for members who DO have address info, I see the map under the "Addresses" section - checked Hemingway, Berheim
- YES, I can move around the map with my finger on the tablet
- YES, I can zoom or pull out by using the controls in the far right corner, or by pinching my fingers in/out
- YES, I see the historic map when I'm in Paris and YES, I see the white basemap when I pull further out - tried with Hemingway and Berheim again
- YES, I see the green address markers and when I click each one, the address pops up
- YES, when the page loads the first address is already be selected, showing its popup
- YES, when the page loads, all addresses should be visible on the map without panning/zooming - although on Berheim it's pretty hard to see some of the address markers, see screenshot: 
![75625317_2172912276344144_5377832326321405952_n](https://user-images.githubusercontent.com/16673934/68725268-dcba2080-058b-11ea-87da-ca2919ba6316.png)

- YES, no matter what, the special S&Co marker always shows up and is clickable

**Comment by thatbudakguy** [comment]
@clmahoney thanks as always for your thorough testing! I can confirm the map on mobile isn't full-width for me either; good catch. I'll fix it and mark this ready again once it's done.

regarding:
- map markers being on top of the paris map's legend
- map markers being too close to each other
- map markers being too close to the edges of the map when it loads

I think these are not ideal, but not dealbreakers for this release. I'll make a new issue to track these, since they are all problems that can be solved by tweaking the map's configuration later.

**Comment by thatbudakguy** [comment]
@clmahoney ok, just need to check that this is correctly full-width on mobile.

**Comment by clmahoney** [comment]
Yes the map is wide on mobile! See screenshot!
![Uploading 91450B72-1218-4C9E-8084-82A577B9761B.png…]()
