### ISSUE TITLE
As a content editor, I want to add a formatted abstract to essay content so that I can summarize content for the viewer.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#412]
# dev notes
- [ ] create a new wagtail "abstract" block
- [ ] implemented as an `<aside>`?
- [ ] styles: indent and italicize

**Comment by rlskoeser** [comment]
We're unclear on the specifics of this one and how the abstract differs from the description text displayed on the analysis list page. Will check meeting notes.

**Comment by thatbudakguy** [comment]
closing as we can implement this to our satisfaction now using regular wagtail streamfield formatting.
