### ISSUE TITLE
account event_date_ranges doesn't handle ranges with end date but no start date

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#416]
## Notes for testing
Compare the member timeline graph for Alice Killen in production and test. In production, there's a weird dark gray line between 1924 and 1926 where two gray bars are overlapping because the date ranges are being calculated incorrectly (caused by a range with an end date but no start).  Check that on the test site the dark gray bar is not present for Killen. 

## Notes for dev
See Killen for an example of this: there is a range with an end date but no start date, so it sorts first and thus doesn't collapse into the range it should belong to.

I think we can use `Coalesce` to get the first date that isn't null, and sort on that. Once the dates are sorting properly, it looks like the logic will handle it properly.

```
from django.db.models.functions import Coalesce
... annotate(first_date=Coalesce('start_date', 'end_date')).order_by('first_date')
```

**Comment by jkotin** [comment]
I'm looking on my laptop. Yes the weird grey line is not on the test site. (It is on the production site, as you note.) This comment is not directly related to this test: shouldn't the production site have a simplified member timeline with out a legend and without the contrast between membership and borrowing activity? That's how I would prefer the member timeline—simplified—for when the site goes live to the public.
