### ISSUE TITLE
Remove login restrictions on member and card pages and re-enable menu links

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#422]
# testing notes

make sure you are not logged in, and then: open the main menu (top right) and check:

- you can click the "members" link to go to the members list
- you can click the "cards" link to go to the cards list
- the gray text and "coming soon" should be gone from these links.

note that the gray text and "coming soon" _should_ still appear for books, since that section won't be ready by the next release. books shouldn't be clickable in this menu.

also check the footer - should be same situation (members and cards clickable, books still "coming soon" and not clickable).

**Comment by thatbudakguy** [comment]
will close once deployed.

**Comment by clmahoney** [comment]
I am not logged in and: 
- YES, I can see the clickable MEMBERS and I can click it and it leads me to members! 
- YES, I see the clickable CARDS and I can click on it and it leads me to the cards! 
- YES, neither MEMBERS nor CARDS are greyed out, and they don't have the *coming soon text. Only BOOKS does. 
- YES, the footers all work too, except for the books footer and the "data export" footer. Both of those two have * next to them and aren't clickable.
