### ISSUE TITLE
As a content editor, I want to be able to view subscription events associated with an account so that I can see activity relating to an account at a glance.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#43]
Testing notes:

There are now inclines for Subscribes (which include supplements and renewals) and Reimbursements

Some ideas to test

- [x] Open an account and use the subscribe inline to set an event on an account
- [x] Do the same with reimbursement
- [x] Spot check a few obvious people (i.e., you can use the search in the upper right to pull up Hemingway's account)

**Comment by elspethgreen** [comment]
A question: would it be possible to auto-fill an end-date when you're adding subscription info?  As in, I type in "4" under duration, and then a start date, and it offers the correct end-date as an option? (you would always be able to manually over-ride it).

**Comment by elspethgreen** [comment]
Otherwise, this seems to be working as described!

**Comment by bwhicks** [comment]
@elspethgreen I like the suggestion and I'll pull it into a user story for a future release (it seems like very helpful functionality). 

Barring that, if you see nothing else, feel free to close this issue. (I nearly remarked it as waiting testing while working on the issues remaining.)

(Thanks much for your attention to the testing end of this!)
