### ISSUE TITLE
As a content editor, I want to be able to add styled footnotes to essay content so that I can write notes and cite content in a structured way.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#431]
- [ ] re-implement the footnotes wagtail block as an `<ol>` since it semantically is a list
- [ ] try styling the numbers in the footnotes block to appear as superscript, if it's easy in css
- [x] allow the `<sup>` tag in essay paragraph blocks for adding footnotes
- [x] add a button to the paragraph block editing UI to insert a `<sup>` for a footnote
- [ ] add styles for the `<sup>` tag, if necessary
- [ ] check if it's easy to auto-link footnotes to the footnote block?

**Comment by rlskoeser** [comment]
Postponing since the version of wagtail we're on doesn't easily support superscript. Moving out of November milestone, we can decide priority later.

FWIW, I don't think the footnotes block needs to change - it already supports adding an ordered list.
