### ISSUE TITLE
change font display for member detail pages & headers

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#432]
I enabled the Louize Display font variant for all level-one headings, so the titles at the top of pages will look slightly different.

I tried small-caps at the top of member pages. It looks okay; a little bold/denser than anticipated - probably because the font designer didn't include that variant, so the browser is trying to fudge it.

I think regular capitalization looks much better, so I've enabled that on detail pages. You can see it on any member's page, here are a few to try:

- [pauline alderman](https://test-shakespeareandco.cdh.princeton.edu/members/alderman/)
- [rene chambrillac](https://test-shakespeareandco.cdh.princeton.edu/members/chambrillac/)
- [c.k. ogden](https://test-shakespeareandco.cdh.princeton.edu/members/ogden/)
 - [clermont-tonnere](https://test-shakespeareandco.cdh.princeton.edu/members/clermont-tonnerre/)
- [virginia pfeiffer](https://test-shakespeareandco.cdh.princeton.edu/members/pfeiffer-virginia/)

try them on tablet/mobile as well to get a feel for how it looks.

one result of this is that member pages will now look more similar to About/Sources pages, which had titles looking like this already (i.e. not all-caps). conceptually I think this is good, because they are at the same level in the page hierarchy.

**Comment by jkotin** [comment]
I'll handle this testing for Monday -- i.e. I'll close or keep open the issue -- but I'd be grateful for Cate's notes.

**Comment by clmahoney** [comment]
Desktop: 
- I like this new capitalization. I opened every name listed above, and then opened them on the production site to see how they look currently, and in all instances I liked the new test version better. I think especially for longer or more detailed names (like Clermont-Tonnere), the new version fits more and looks less intense/in your face

**Comment by jkotin** [comment]
This looks good to me too. Cate, would you check on tablet and mobile and close the issues if it looks good?

**Comment by clmahoney** [comment]
Mobile: 
- This looks good - names seem clearer and less intense when they're long. 
- One question: I see in mobile a little floating card in the bottom left on the member search page - is that a flaw that the card seems to block. See screenshot: 
![Image from iOS](https://user-images.githubusercontent.com/16673934/69501821-8f687800-0ed6-11ea-8180-ffce4f0343e4.jpg)

**Comment by clmahoney** [comment]
Tablet: 
- Everything looks great here

**Comment by thatbudakguy** [comment]
@clmahoney thanks for catching this - I've updated the display of the "has card" icon to avoid overlap, can you give it another look? if it's working please close.

**Comment by clmahoney** [comment]
Yes this looks great! I don't see the overlap now.
