### ISSUE TITLE
As an admin, when I merge people I want unique identifiers stored and used for redirects on public views so that links for merged people continue to resolve.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#434]
## testing notes
The scenario for this is if someone cites or links to a member page and we change or merge records in the database, we want that link to still resolve if possible. The easiest way to test it might be this: choose a person record on the test database and open up multiple different person detail pages in different tabs (biography, membership activities, borrowing activities, card list, and one card image viewer page) so that you have URLs ready to test after you make changes. Then test that:
- when you merge person records, the merged person's slug is stored as a past slug on the remaining record — it should be visible but read only in the admin edit page 
- all member pages for the old slug should _redirect_ to the new slug — you should see the content instead of a 404, and the location in your browser should show the new slug
- test that if you edit a person record and change the slug, the old slug is stored as a past slug
- test that if you add a new person with a previously used slug, you get a validation error

## dev notes
- [x] add alternate/old slugs field to person
- [x] update person merge method to store old slugs
- [x] permanent redirect on old slug match for all member detail pages
- [x] make old slugs visible (read only) in admin
- [x] validate new slugs to avoid collisions with old slugs
- [x] add old slug on save if slug changes

**Comment by clmahoney** [comment]
- YES, when I merged Ellen Wright with Julia Wright, I saw Ellen's past slug on Julia's admin page: 
![Screen Shot 2020-05-12 at 6 57 34 PM](https://user-images.githubusercontent.com/16673934/81753780-8c604480-9482-11ea-84d5-df27840bd16a.png)
- YES, all the tabs for Ellen Wright that I had open (biography, membership activities, borrowing activities, card list, and one card image viewer page) changed to Julia Wright when I refreshed the pages. No errors! 
- YES, if I edited the slug, I saw that there were now _past slugs (plural) in the admin
- NO, when I used a previous slug--the original Ellen Wright slug--it saved and I got no validation error.

**Comment by rlskoeser** [comment]
Ha, my instructions weren't detailed enough and that was a good thing to test.

So — the system _should_ allow you to re-use an old slug associated with the same record (e.g. if you merged and wanted to switch to one of the other slugs). That's probably a good thing to test if you haven't already (but I think you did?).

What it should _not_ allow is using a past slug from one member on a _different_ member. So, you can test that by trying to use that `wright-ellen` slug for a different person.

**Comment by clmahoney** [comment]
@rlskoeser I see! Thank you for clarifying! 
- YES, if I add the slug wright-ellen to another person (not Julia Wright, who I merged with Ellen), then the admin page does NOT allow me to save; I get an error. I tried to add Ellen's slug to Bernice Abbott and it didn't allow me to.

**Comment by rlskoeser** [comment]
@jkotin I'm confident with Cate's testing, but you might want to read over the testing notes and Cate's comments so you know how this works and can think about whether we need something similar for books.

**Comment by jkotin** [comment]
@rlskoeser I do think we'll need something similar for the books, although merging books will be less frequent than members, I expect.  But it will happen.

**Comment by rlskoeser** [comment]
@jkotin — thanks, that is what I suspected. I think it should be simpler to implement since there is no merge method for books and I can adapt what I've done for the person records.
