### ISSUE TITLE
As a user, I want to see a member's primary or best name prominently and also see other known names or so that I can recognize them and see how they were listed in the archival materials.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#437]
## Notes for testing
- names in the member list display should look as they did before
- on individual member detail page, the all caps title at the top should be a first name last version of the `sort_name`; check someone with a different sort name than name and check someone without a comma in the sort name(suggestions: test Claude Cahun and Bryher)
- on individual member detail page, the full name from the `name` field in the database should be displayed in the biographical section

## dev notes
- [x] add `firstname_last` method
- [x] use `firstname_last` for h1 and html title on member detail pages and membership activities pages
- [x] add full name with variants (`name` property) to biographical section on member details
- [x] adjust styles so name is not hidden on member details page

**Comment by clmahoney** [comment]
- YES, the names in the member list look as they did before
- YES, on the individual member detail pages, the all caps title at the top is the first name last version of the SORT NAME. Checked Bryher, Claude Cahun, Simone de Bretteville. In all cases the ALL CAPS TOP name correctly lists First Name Last Name of the sort name. 
- YES, in the individual member detail page the full name from the name field in the database is displayed in the bio section. Checked Bryher, Claude Cahun, Simone de Bretteville again: see screenshot for de Bretteville. I'm not sure I listed her full NAME right, but I followed our notes from the last meeting. 
![Screen Shot 2019-11-15 at 11 27 53 AM](https://user-images.githubusercontent.com/16673934/68958889-fe3d2700-079a-11ea-83b6-5f83af3dcd18.png)
