### ISSUE TITLE
As a global admin, I want addresses automatically associated with accounts in the logbook where possible to minimize the amount of manual cleanup required.

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#44]
Encoder will reference personography to determine which account addresses are NOT the account-holder's address.

## Notes for testing
- the entity previously named **Address** is now **Location**
- the entity previously named **Account address** is now **Address**
- an address must be associated with either a person or an account, but not both
- content editor group should have permissions to edit Locations and Addresses
- account addresses should be editable inline on account edit page
- person addresses (for non-account addresses) should be editable inline on person edit page
- all existing addresses in the system (i.e those imported from personography xml) have been re-associated with accounts instead of people
- when editing Locations, the system will now require that the combination of name + street address + city + country is unique, to try to prevent duplicates; to test this and see the validation error message, try adding e.g. same city + country twice (same city twice with no country should also display a validation error).
   - Note that two pairs of near-duplicate entries (Hôtel Odessa/Hotel Odessa and Hôtel Lutetia/Hotel Lutetia) have been consolidated.

## Notes for development

Using this story to track the work we identified earlier for adjusting how addresses are handled and how they are associated with people and accounts.

- [x] rename what is now `Address` to `Location`
- [x] rename what is now `AccountAddress` to `Address` and add foreign key to `Person`
- [x] add validation so that only one of `Account` or `Person` can be associated and help text to explain 
- [x] write data migration to move existing Person/Address associations to Accounts (all personography addresses currently in the db are account addresses)
- [x] remove many-to-many from `Person` to `Address`
- [x] update admin edit configurations for Location, Person, Account, and Address
- [x] update content editor permissions for changes to models

**Comment by rlskoeser** [comment]
@elspethgreen Ben filled me in on the logic you all discussed for associating addresses with accounts on import.  I'm converting this issue to handle address logic on import (as an extension of #9 ) and have asked @bwhicks to document the logic he intends to implement and what pieces of information will nee to be cleaned up manually (e.g., care of addresses, people with multiple addresses).  If I understand correctly, it sounds like this should handle the majority of simple cases and leave the complicated ones to be sorted out manually by the team after import.

**Comment by rlskoeser** [comment]
@elspethgreen after discussing a bit more with @bwhicks, I'm wondering if we should hold off on any logic to automatically associate addresses with accounts until we import the lending cards.  What do you think?

**Comment by elspethgreen** [comment]
If it's easier to do it on the next import, that's fine!  But when encoders start actually working with the system, we'd want those addresses automatically associated.

**Comment by rlskoeser** [comment]
@elspethgreen we're going to push this back to the next release.  It requires some conversation among me, @bwhicks and @jabauer to figure out how to model addresses properly in the database (we'll probably be back to the team with questions to refine this soon).

We absolutely will do what we can to clean those up automatically before you do any manual clean up or association.  It may actually be a good thing to look at this as we're working on the card import in the next stage.

**Comment by rlskoeser** [comment]
Adding a photo of a portion of the whiteboard database diagram from when Ben and Jean and I talked through the changes we needed to make to the database to better handle the addresses associated with accounts and people.  I don't think we made any other documentation, so hopefully this will be enough to go on.

![img_20171023_161652](https://user-images.githubusercontent.com/691231/35447610-26849c78-0286-11e8-9d9f-54aa15d6c57d.jpg)

**Comment by rlskoeser** [comment]
@elspethgreen am I remembering correctly? All the addresses currently in the system, which were imported from the personography, should be associated with the library accounts and not the people directly? (i.e. these are addresses where people received books, not residences that have been identified by other research)

**Comment by jkotin** [comment]
All the addresses in the system are from the lending library cards.  There are no new addresses identified by outside research.

Some of the addresses from the cards were completed and standardized by outside research -- i.e. the addresses are not pure transcriptions: I corrected errors, added postal codes and geocoordinates, etc.

* * *

In other words: the addresses in the system are the addresses members gave Beach when then bought their memberships.

I hope this info help!

**Comment by rlskoeser** [comment]
Thanks @jkotin ! That's exactly what I needed to know.

**Comment by elspethgreen** [comment]
@clmahoney @i-davis  could you play with this a bit?  I've taken a look and I think it's working as described in Rebecca's testing notes, but since it's complicated I'd like some other eyes on it.

**Comment by i-davis** [comment]
I think all this looks good to me! I should say I'm a bit lost by testing notes, generally, & this last batch has felt esp a bit beyond me; but I think I get this one!
