### ISSUE TITLE
implement masonry layout for landing pages

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#440]
# testing notes

note that although the only place you'll see a difference should be the analysis landing page, this technically affects all landing pages (sources and about too) so you'll want to briefly check them to make sure everything still looks OK.

this adds code to ensure that the preview tiles on the analysis page are fit nicely against each other (like masonry, hence the name) but are still organized according to date, so the newest stuff is at the top. note that this also **only takes effect on desktop**.

you will want to add a bunch of new analysis essays in wagtail. if possible, make sure you have at least 5-10 of them, and create a variety - some with an image, some with an author, some with a description. ideally we want to test all the different sizes that the tile would possibly be, so the more combinations the better. then go to the [analysis landing page](https://test-shakespeareandco.cdh.princeton.edu/analysis/).

check that:
- the tiles appear in the right order: the essays you created last are at the bottom; newest are first. (if you go to the landing page itself in wagtail, you can get a list of its children ordered by date, for reference. the order should be the same.)
- there are no big gaps between tiles.
- the spacing between tiles is even.
- if you load the site on a mobile device or tablet, everything should look the way it used to (just one column). order should still be right.

make sure to check the sources and about landing pages too: they should look the same way they used to.

# dev notes
https://masonry.desandro.com/

**Comment by jkotin** [comment]
I'll test this on Sunday, but Cate should test it too. No need to wait for me. She can close it on Monday after we've both signed off.

**Comment by clmahoney** [comment]
Desktop: I added more essays, some with images and some without, bringing the total to 6 being displayed on the test site
- YES, the tiles are in the right order
- YES, there are no big gaps between the tiles
- YES, the spacing is even
See screenshot. 
![Screen Shot 2019-11-24 at 4 57 12 PM](https://user-images.githubusercontent.com/16673934/69502305-d3aa4700-0edb-11ea-8093-d1812b206eb6.png)

**Comment by clmahoney** [comment]
Mobile: 
- YES, the tiles are in the right order: more recent is first, then as you scroll you move backwards to the earliest one published. 
- YES, format is straightforward and good. See screenshot: 
![Image from iOS (5)](https://user-images.githubusercontent.com/16673934/69502361-4e736200-0edc-11ea-92b5-5cde644e99f1.png)

**Comment by clmahoney** [comment]
Tablet: 
- Looking great too, just like mobile set up.

**Comment by thatbudakguy** [comment]
@clmahoney are we OK to close this? josh noted above that there's no need to wait for him.

**Comment by clmahoney** [comment]
Yes!
