### ISSUE TITLE
Design a "link" icon for the site to contain contextual links so that users can access relevant essays

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#441]
This icon will be specifically used in the "Gender", "Nationality", and "Category" sections, in the members section of the site, however can be expanded to other parts of the site if necessary. 

Link icon on: 
1. Members search & filter section next to the "Gender" and "Nationality"  
a. Desktop
b. Tablet
c. Mobile

2. Member's membership activities section next to the "Category" column 
a. Desktop
b. Tablet
c. Mobile

**Comment by gissoo** [comment]
Designed and added a link icon to the "Gender", "Nationality", and "Category" sections of the site for desktop, tablet, and mobile. (Total of 6 screens)

@jkotin Please review the designs for this issue via this link: zpl.io/2yGLBnK
Note: The link above should take you to the screen that will have all the designs related to this issue (6 screens) 

Link icon on: 
1. Members search & filter section next to the "Gender" and "Nationality"  
a. Desktop
b. Tablet
c. Mobile

2. Member's membership activities section next to the "Category" column 
a. Desktop
b. Tablet
c. Mobile

**Comment by jkotin** [comment]
Thank you Gissoo. Some notes:

1. Do we need both a question mark icon and link icon for "Category"? Might a link be sufficient? If it matters: I imagine that the link will lead to a analysis page with a small table, maybe six rows, that will explain the different categories. E.g. "AdL" = a discount because the member is also a member of Adrienne Monnier's  La Maison des amis des livres. "B" = members can borrow new books. Or could we fit all the information from the chart in bubble? I think that the info is too much for a bubble, but not enough for a full analysis essay.

2. The icons for nationality and gender look good.

**Comment by clmahoney** [comment]
Ready to close when @jkotin signs off.

**Comment by gissoo** [comment]
@jkotin thanks for writing. Regarding #1 point, I think it would be best to have the "?" there for a very short explanation to reduce enough uncertainty about _what that field/column actually means_ in order to proceed with reading the "Activities" table, and then use the link icon to direct users for more detailed information on each category type. 

Note: I agree with you that the table/content explaining "Category" might be too short for an analysis essay, there can be other ways of integrating this table/content along with other explanations/content that are short or belong to the same purpose under a larger umbrella on the site on one page, and/or it won't have to be under the "Analysis" section either, could be a page under "About". There are several ways of handling this, we can discuss. 

For the text inside the bubbles and the text next to the link icon for "Nationality" on mobile we will need text from you. Where do you think it's best to request that so we won't forget?

Since we are on this topic I would like to clarify the difference between "?" and "i" in the icons that you may have seen in the designs: 
- "?" is used to explain what a term means when it's not a term that users would expect to see on a page and it isn't understood on its own.
- "i" is used for terms that are understood on their own, however more information about them within the context of S&Co will be very helpful and/or important.

**Comment by jkotin** [comment]
I will post the information that a "category" explanation/essay would contain. Perhaps this will easier to figure out with the material at hand. I'll try to do that today, but I'm with family, so only have pockets of work time.

**Comment by gissoo** [comment]
@jkotin, if we are changing the "Category" label to "membership type" then a "?" or "i" will not be necessary, however, from the doc you just shared on Slack I think a link icon will still be necessary and helpful.

**Comment by jkotin** [comment]
This sounds good to me: one icon.  Can we discuss the exact wording and where the category explanation will go at our next meeting?

**Comment by gissoo** [comment]
@jkotin great! Yes that will be great. I have now revised the designs and removed the "?" icon that was next to the "Category" labels on desktop, tablet, and mobile. Please review the designs for this issue via this link: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5dd6fef9e4dc380b901e5d75) and then close this issue if it you are ok with this. 

Once we discuss the wording next week I'll create a new issue and will revise the designs and replace "category" with a new label that we have agreed on.

**Comment by jkotin** [comment]
Excellent.  My apologies for not recognizing the type/type issue!

**Comment by gissoo** [comment]
"Category" column in the Membership Activities page is now renamed to "Plan" and the question mark has been removed on desktop, tablet, and mobile . Here are the link:

1. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cc1d1bb8df02e2cc0c00ec5"
2. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cd49f8b37e0ad67ccffa23f"
3. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5d0beb0f96f1b970914d5335"
