### ISSUE TITLE
Create image asset guidelines for images that are editable so that content editors can upload images with the correct sizing that will be visible on various devices

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#442]

**Comment by gissoo** [comment]
@jkotin Please review the image asset guidelines document that I created. 
(https://docs.google.com/document/d/1XzAXEUfjac3tMYlMw8ywje1px_p3She7sXUSACPdLdg/edit)

**Comment by jkotin** [comment]
This is helpful. I'll close the issue once I start adding the images to the "Joining the Lending Library" essay.  I just want to make sure everything makes sense (to me) in practice.

**Comment by rlskoeser** [comment]
@jkotin if you're not ready to add images to that essay sometime this week, could you try these instructions out with sample content on the test site and let Gissoo know if she needs to make any revisions or add more details? If possible, we like to close out tasks within the iteration that the work is scheduled for.

**Comment by thatbudakguy** [comment]
moved to v0.25 as per discussion on 12/4 team mtg
