### ISSUE TITLE
admin edits are causing 500 errors

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#446]
Reported by @clmahoney in Slack:
> I’m doing book cleanup and when I try to add a borrow or change a book, I’m getting a “something went wrong” page - any idea why?

**Comment by clmahoney** [comment]
- YES, I am able to add in a borrowing event! Was able to add a borrow event for Rirachowsky, an event I had deleted last night when I got the error message. 
- YES, I am able to change a book title when I need to alter who borrowed what
