### ISSUE TITLE
Revise the size and visibility of "No known copyright", PUL, and PU logos based on comments on issue #250

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#457]
Current sizes of the "PUL" and "No copyright" logos now match the minimum recommended size for screens.  Revised the sizes of three logos on 3 devices: 
1. "No known copyright" under the card image viewer
a. Desktop
b. Tablet
c. Mobile

2. "PUL" under the card image viewer 
a. Desktop
b. Tablet
c. Mobile

3. "PU" in footer 
a. Desktop
b. Tablet
c. Mobile

**Comment by gissoo** [comment]
@jkotin Please review these designs via the links below:

1. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b5030eb3b183b25b9200"
2. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b503f3d79e57b28a00e1"
3. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b50350731722a4809521"

**Comment by jkotin** [comment]
These look great now.  Thank you.

**Comment by gissoo** [comment]
@jkotin I also updated these on the members card gallery pages here: 
1. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841d517762c27b91ed6"
2. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841e9d98c2c63dd8c30"
3. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db898418dd01b575f87a1bc"

**Comment by gissoo** [comment]
@jkotin I designed a "default" and "selected" visual state for these logos since it needs to be visible that they are links. This design is consistent with the rest of the behaviors of the links on the site, however this is less opaque since it's less important of a content. 

Please view them here: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5de686bfd9cb7d4889f57ba7"

**Comment by gissoo** [comment]
These are now updated on the card image viewer and the card gallery pages for desktop, tablet, and mobile. Here are the links:

    Card image viewer
    a. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b5030eb3b183b25b9200"
    b. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b503f3d79e57b28a00e1"
    c. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b50350731722a4809521"
    Card gallery
    a. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841d517762c27b91ed6"
    b. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841e9d98c2c63dd8c30"
    c. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db89841e9d98c2c63dd8c30"
