### ISSUE TITLE
pages with breadcrumbs 500 if schema.org is down

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#459]

**Comment by rlskoeser** [comment]
@thatbudakguy I was investigating ways to load the context manually from a cached copy of what the library grabs the way it's working now, but I struck on something much simpler - it seems that simply binding the namespace to the graph does the right thing and _doesn't_ trigger a request to schema.org.  I tried the json-ld that it generates in the google rich text testing tool and it displayed correctly.

I can't think of any way for Josh or Cate to test this - I think you will need to review and sign off. I was able to test on my local dev instance by turning off networking - the previous logic results in an error, the new code does not.

**Comment by thatbudakguy** [comment]
tested and confirmed this is working! 🎉
