### ISSUE TITLE
As a content editor, I want a one-time update to set people's gender based on titles where possible so that I don't have to edit all the records manually.

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#46]
In our TEI personography, gender was not officially specified for many people whose gender was, by their title, specified--"Miss So-and-so" or "Mr Y."  Would it be possible (or, Josh, desirable) to automatically assign genders to such people on import, so that the "sort by gender" functionality of the personography is more powerful and meaningful?

Note: we're only going to handle the unambiguous ones - anything ambiguous should be handled manually by the project team.

**Comment by jkotin** [comment]
Yes, good idea!

**Comment by rlskoeser** [comment]
@elipmandel I think we should be able to do this as a one-time update to existing data in an upcoming release. I'll generate a distinct list of titles for you to review so we make sure to catch all the ones that are gender specific.

**Comment by rlskoeser** [comment]
@elspethgreen Here's a list of titles with counts for what's currently in the database, ordered by most frequent.  Do you want to copy this and annotate it with sex where the title makes it unambiguous?  It might make sense for the script to just handle the cases that affect a lot of records, and you all can handle the rest.  It does look like there is some cleanup to be done; programmatic things like removing periods from the end, or removing trailing whitespace, can be done as part of this update; but I think you all should handle typos.  I can regenerate this list after you do the cleanup on the typos if that would be helpful. 

Title | Total | Sex
----- | ----- | ------
  [none]    | 3152 | 
Miss | 480 | 
Mr | 460 | 
Mrs | 242 | 
Mlle | 175 | 
Mme | 146 | 
Mr. | 85 | 
M. | 81 | 
M | 74 | 
Mrs. | 32 | 
Miss. | 20 | 
Mme. | 18 | 
Mlle. | 12 | 
Madame | 9 | 
Comtesse | 8 | 
Dr | 6 | 
Ms  | 5 | 
Lady | 4 | 
M. de  | 2 | 
Capt | 2 | 
Baronne | 2 | 
Mme de | 2 | 
Dr. | 2 | 
M. Le | 1 | 
Monsieur | 1 | 
Missforich | 1 | 
Prof | 1 | 
Captain | 1 | 
Mr> | 1 | 
Mss. | 1 | 
Baron | 1 | 
Mademoiselle | 1 | 
Father  | 1 | 
Mle | 1 | 
Misss. | 1 | 
Mlle de | 1 | 
L'Abbé | 1 | 
Duchess de Clermont-Tonnerre | 1 | 
Sir | 1 | 
Vicomte | 1 | 
Col/Mr | 1 | 
Mjss | 1 | 
Commandant | 1 | 
Colonel. | 1 | 
Madame. | 1 | 
Marquis | 1 | 
Count | 1 | 
Bradford | 1 | 
Major | 1 | 
M/Mlle | 1 | 
Countess | 1 | 
Mlle des | 1 | 
Mr and Mrs  | 1 | 




Documenting the python I used in Django shell in case we want to run this again or adapt it:

```
from mep.people.models import Person
from django.db.models import Count
for result in Person.objects.values('title').order_by('title').annotate(Count('title')).order_by('-title__count'):
     print('%(title)s %(title__count)s' % result)
```

**Comment by elspethgreen** [comment]
I filled in gender for most titles, excluding those like "Mjss" that seem to be clear typos for more standard titles.  For military titles, I defaulted male, even though that would no longer be the case today--but we could leave them ungendered, as I did for Dr and Professor.  @jkotin would you look this over and let me know if you'd change anything?


  |  
-- | --
Title | Total | Sex
[none] | 3152 |  
Miss | 480 | F
Mr | 460 | M
Mrs | 242 | F
Mlle | 175 | F
Mme | 146 | F
Mr. | 85 | M
M. | 81 | M
M | 74 | M
Mrs. | 32 | F
Miss. | 20 | F
Mme. | 18 | F
Mlle. | 12 | F
Madame | 9 | F
Comtesse | 8 | F
Dr | 6 |  
Ms | 5 | F
Lady | 4 | F
M. de | 2 | M
Capt | 2 | M
Baronne | 2 | F
Mme de | 2 | F
Dr. | 2 |  
M. Le | 1 | M
Monsieur | 1 | M
Missforich | 1 |  
Prof | 1 |  
Captain | 1 | M
Mr> | 1 | M
Mss. | 1 |  
Baron | 1 | M
Mademoiselle | 1 | F
Father | 1 | M
Mle | 1 |  
Misss. | 1 |  
Mlle de | 1 | F
L'Abbé | 1 | M
Duchess de Clermont-Tonnerre | 1 | F
Sir | 1 | M
Vicomte | 1 | M
Col/Mr | 1 | M
Mjss | 1 | F
Commandant | 1 | M
Colonel. | 1 | M
Madame. | 1 | F
Marquis | 1 | M
Count | 1 | M
Bradford | 1 |  
Major | 1 | M
M/Mlle | 1 |  
Countess | 1 | F
Mlle des | 1 | F
Mr and Mrs | 1 |   |

**Comment by elspethgreen** [comment]
Title | Total | Sex
-- | -- | --
[none] | 3152 |  
Miss | 480 |  
Mr | 460 |  
Mrs | 242 |  
Mlle | 175 |  
Mme | 146 |  
Mr. | 85 |  
M. | 81 |  
M | 74 |  
Mrs. | 32 |  
Miss. | 20 |  
Mme. | 18 |  
Mlle. | 12 |  
Madame | 9 |  
Comtesse | 8 |  
Dr | 6 |  
Ms | 5 |  
Lady | 4 |  
M. de | 2 |  
Capt | 2 |  
Baronne | 2 |  
Mme de | 2 |  
Dr. | 2 |  
M. Le | 1 |  
Monsieur | 1 |  
Missforich | 1 |  
Prof | 1 |  
Captain | 1 |  
Mr> | 1 |  
Mss. | 1 |  
Baron | 1 |  
Mademoiselle | 1 |  
Father | 1 |  
Mle | 1 |  
Misss. | 1 |  
Mlle de | 1 |  
L'Abbé | 1 |  
Duchess de Clermont-Tonnerre | 1 |  
Sir | 1 |  
Vicomte | 1 |  
Col/Mr | 1 |  
Mjss | 1 |  
Commandant | 1 |  
Colonel. | 1 |  
Madame. | 1 |  
Marquis | 1 |  
Count | 1 |  
Bradford | 1 |  
Major | 1 |  
M/Mlle | 1 |  
Countess | 1 |  
Mlle des | 1 |  
Mr and Mrs | 1 |

**Comment by elspethgreen** [comment]
Title | Total | Sex
-- | -- | --
[none] | 3152 |  
Miss | 480 |  F
Mr | 460 |  M
Mrs | 242 |  F
Mlle | 175 |  F
Mme | 146 |  F
Mr. | 85 |  M
M. | 81 |  M
M | 74 |  M
Mrs. | 32 |  F
Miss. | 20 |  F
Mme. | 18 |  F
Mlle. | 12 |  F
Madame | 9 |  F
Comtesse | 8 |  F
Dr | 6 |  
Ms | 5 |  F
Lady | 4 |  F
M. de | 2 |  M
Capt | 2 |  M
Baronne | 2 |  F
Mme de | 2 |  F
Dr. | 2 |  
M. Le | 1 |  M
Monsieur | 1 |  M
Missforich | 1 |  
Prof | 1 |  
Captain | 1 |  M
Mr> | 1 |  
Mss. | 1 |  
Baron | 1 |  M
Mademoiselle | 1 |  F
Father | 1 |  M
Mle | 1 |  
Misss. | 1 |  
Mlle de | 1 |  F
L'Abbé | 1 |  M
Duchess de Clermont-Tonnerre | 1 |  F
Sir | 1 |  M
Vicomte | 1 |  M
Col/Mr | 1 |  M
Mjss | 1 |  
Commandant | 1 |  
Colonel. | 1 |  M
Madame. | 1 |  M
Marquis | 1 |  M
Count | 1 |  M
Bradford | 1 |  
Major | 1 |  M
M/Mlle | 1 |  
Countess | 1 |  F
Mlle des | 1 |  F
Mr and Mrs | 1 |

**Comment by elspethgreen** [comment]
Josh approves of the table!

**Comment by rlskoeser** [comment]
@elspethgreen great! Thank you.

**Comment by elspethgreen** [comment]
This looks great--now only total mysteries have blank genders.
