### ISSUE TITLE
Update the size of the Princeton University logo in the footer

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#460]
Please refer to these designs here for resizing the logo: 
1. Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b5030eb3b183b25b9200"
2. Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b503f3d79e57b28a00e1"
3. Mobile: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b50350731722a4809521"

Related issues: 
1. The issue that addressed the design: "https://app.zenhub.com/workspaces/mep-django-5931d39e341d0d6c7318d56f/issues/princeton-cdh/mep-django/457"

2. The issue where this design was discussed and requested: "https://app.zenhub.com/workspaces/mep-django-5931d39e341d0d6c7318d56f/issues/princeton-cdh/mep-django/250"

**Comment by clmahoney** [comment]
Desktop: 
- YES, I see the logo in the bottom right corner and it looks like the right size. I also see the green lines under it! 
![Screen Shot 2019-12-11 at 2 12 11 PM](https://user-images.githubusercontent.com/16673934/70652735-221c4d00-1c21-11ea-8283-615875fd5a9b.png)

**Comment by clmahoney** [comment]
Mobile: 
- YES, I see the logo too in the bottom right corner, with the green lines below. 
![Image from iOS (9)](https://user-images.githubusercontent.com/16673934/70653249-1aa97380-1c22-11ea-81e5-ca4ce2d864d0.png)

**Comment by clmahoney** [comment]
Desktop 
- YES, I checked the Princeton shield logo at the very bottom of the page and the size matches the design size: 
![Screen Shot 2019-12-11 at 4 53 22 PM](https://user-images.githubusercontent.com/16673934/70663674-d5437100-1c36-11ea-91fd-130f15178138.png)

**Comment by clmahoney** [comment]
Mobile: 
- YES, this logo size at the bottom of the page matches the Zeplin design! 
![Image from iOS (10)](https://user-images.githubusercontent.com/16673934/70663941-631f5c00-1c37-11ea-8398-28f9958ac841.png)

**Comment by clmahoney** [comment]
Tablet: 
- NO, I think the design looks different than what's on the site now. The tablet view shows the logo a bit cramped at the bottom, see screenshot: 
![IMG_0227](https://user-images.githubusercontent.com/16673934/70675447-3d09b400-1c57-11ea-8e59-a3ceb3b5512c.PNG)

While this is the design look: 
![Screen Shot 2019-12-11 at 8 44 48 PM](https://user-images.githubusercontent.com/16673934/70675466-46931c00-1c57-11ea-9402-5d1dd33125a5.png)

**Comment by thatbudakguy** [comment]
@gissoo do you have thoughts? I think I might have made the princeton logo slightly too big, and the placement is different because there are no social icons right now - we could revisit it when we add the social icons, or I could just tweak the logo size slightly.

**Comment by gissoo** [comment]
@thatbudakguy Do you mind tweak it slightly? It looks like a very slight change in the size, however because it's placed in between two other logos it looks very noticeable.

**Comment by jkotin** [comment]
I'm going to leave this open until I hear from @gissoo that she thinks everything is AOK.

**Comment by rlskoeser** [comment]
@gissoo Nick and I tweaked the size for tablet & mobile and the change is now on the test site, would you review?

**Comment by gissoo** [comment]
@rlskoeser This looks great!! Thank you! 
@jkotin @clmahoney Please close this.
