### ISSUE TITLE
As a content editor, I want to create linkable anchors in documents so that I can reference specific sections of my content on other pages.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#464]
# testing notes

log in to the [wagtail editor](https://test-shakespeareandco.cdh.princeton.edu/cms/) and create a new page - it's probably easiest to try under "About", but you could theoretically do anywhere. I tested by creating an "FAQ" page under about, since that's where these linkable sections will go (at least initially).

- in the options for blocks to insert in the new page's body, you should see a new "Linkable Section" block type. go ahead and create one (or a few).
- you should be able to fill in a title for the section and some body content, as if you were editing a normal paragraph or page of text.
- when finished, save & publish the page and go view it on the site. you should see the sections of content you created, with the title text displayed as a heading.
- if you hover the mouse over the heading, you should see a small green paragraph icon (¶) appear next to the heading.
- when you click the ¶ icon, the page should "jump" so that the associated section is in view (if the page is very short or there's not a lot of content, this might not happen).
- when you click the ¶ icon, the URL in your browser's search bar will change. check that the URL now has a fragment at the end, beginning with `#` and containing something like the title of the heading (for example, `#my-section-title`).
- try copying this URL out of your browser's search bar. open a new tab and paste in the URL. you should be linked directly to the section corresponding to that ¶.

# dev notes
@rlskoeser suggested trying out the style of the [django docs](https://docs.djangoproject.com/en/3.0/), which show you a small ¶ icon when you hover over headings that you can click to get a link to that specific heading on the page.

#456 is the companion issue which tracks the adding of links elsewhere on the site that actually link to these new sections (e.g. on the "plan" column on membership activity table).

**Comment by clmahoney** [comment]
Desktop: 
- YES, I see the "Linkable Section" block type. I created 2 new ones! (on the About page)
- YES, I am able to fill in both the title for the section and the body content 
- YES, I added in a child page title and author names and was able to publish it. My two new sections appear under the rest (making it 6 total right now, with my added pages at the bottom.)
- YES, when I click into the child page and hove the mouse over the heading (which I've called "Text linkable doc"), I see the cute green paragraph icon (¶) appear on the right of the heading
- YES, when I click that green ¶ icon, the page does  "jump" to the the associated section is in view--it still worked even though I had only a few sentences. It jumped right to the sentences. 
- YES, the the URL in your browser's search bar DID change to ".edu/about/test-title/#test-linkable-doc"
- YES, when I copied that full URL into a new window it took me directly to that linked doc (the few sentences)

**Comment by rlskoeser** [comment]
Re-opening to make slug a separate field independent of title.

**Comment by rlskoeser** [comment]
Have updated the test site with revised behavior, please test that:
- when you add a new section, anchor text is required
- if you put it text with capital letters and spaces, it is automatically converted to slug format / kebab case (lower case separated by dashes)
- the anchors on the page function as before, but using the anchor text you added instead of the title

**Comment by clmahoney** [comment]
Desktop: 
- YES, when I added a new section, I saw that anchor text IS required, so I entered some
- YES, it turned the anchor into a slug: my "need an anchor" became "need-an-anchor"

Can you clarify the last point?

**Comment by rlskoeser** [comment]
When you click on the paragraph icon and get the shortcut url, the text in the shortcut url after the # should be the anchor text you specified.

**Comment by clmahoney** [comment]
- YES, when I click the paragraph icon, it jumps me right to the text and the URL is "#need-an-anchor"

**Comment by clmahoney** [comment]
Can we close, or does @jkotin need to review?
