### ISSUE TITLE
Fix indexing handler for saving addresses

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#465]
On 12/5 Ian found a bug - he can't save addresses; gets an error page

**Comment by jkotin** [comment]
@rlskoeser How should I test this issue?

**Comment by rlskoeser** [comment]
@jkotin the error is triggered when you try to add or update an address on an account in the admin site. You can compare behavior in production and test to see the bug and then confirm that it's been fixed.

Sorry I didn't add any testing notes, I kind of imagined @clmahoney would be testing this one - but we haven't discussed a testing workflow for bugs yet, so I'm not sure why I thought that.

**Comment by clmahoney** [comment]
This looks good! I tested adding a new address (my house) to a random account, and it worked.
