### ISSUE TITLE
As a content editor, I want the end date of a subscription automatically calculated based on start date and duration, so that I can enter subscriptions more quickly.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#47]
## Notes for testing
* duration is now stored in days rather than months and fractions of months; this duration is not directly editable anywhere, but is automatically calculated based on start and end date
* subscription list view now includes human-readable duration as well as total days
* when editing subscription events:
  * duration can be entered in a human-readable format (see edit form for syntax)
  * if start date and duration are set and end date is not, end date will be calculated: please try several versions of these to confirm it behaves as expected (i.e. months are calendar months but weeks are increments of 7 days)
  * if start date and end date are both set, any duration input by the user will be ignored
* please test on both the subscription stand-alone form and the subscription inline form on the accounts page to confirm they both behave the same way

---
End date should auto-populate on record save based on duration and start date if end date is not set.  Add help text to indicate end date will be calculated if not set.

**Comment by rlskoeser** [comment]
@bwhicks  I've looked at the logbook import code where you're setting duration and calculating end dates to see how to adapt it for this feature.  When you get the chance, could you clarify a bit how you are using fractions to indicate weeks or days?  

I think we should also add a bit more to the help text to this field; maybe a couple of examples for what the fractions should look like?

**Comment by bwhicks** [comment]
@rlskoeser My suggestion would be to let this unit be in slightly more rigid units than the XML variants re: help. Possibly even set it to days for clarity 

My code from the import tried to follow the pattern in the XML:
1) A week duration was handled as a week in pendulum, i.e. a true 7 days.

2) Fractional values (i.e. 1.25) were multiplied against 29 to produce days 15 days for 0.5 month and 7 days for .25 (which also appeared to be notation for a standard calendar week in the XML with 0.5 as half a calendar month of 30 days).

3) Days were divided against 28 to produce a standard 7 day week, since those units appeared to be approximations of that. 

As nearly as I can tell, and also from discussions with the project team, there weren't units less than a week. I hope this makes sense.

**Comment by rlskoeser** [comment]
@bwhicks thanks for clarifying.  It does seem like using fractions would be an awkward way for the project team to enter durations.

@elspethgreen what are your thoughts on this?  We never discussed entering duration when we talked through the data entry workflow.  How common is it to have non-month duration?

**Comment by elspethgreen** [comment]
It's very uncommon to have non-month durations, but it does happen.

Under the proposed auto-complete end-date system, what would happen if you left the "duration" field blank, and manually filled in start and end dates?  Would that reverse-populate "duration"?  A potential solution for non-month-length durations (which again, are uncommon) could be to have encoders enter the length of time manually.

**Comment by rlskoeser** [comment]
@elspethgreen I wasn't planning to add any logic to calculate duration based on start and end dates.

It seems like a good idea to have the team enter values manually for the uncommon / outlier cases manually.

**Comment by rlskoeser** [comment]
Since I've gotten good at my Django `Count` annotation queries, I thought I'd go ahead and run one on the durations, since it might be useful to see what we've actually got.  Here's the current data from production:

Duration in Months | Total subscription events with this duration
------------------ | --------------------------------------
1.00 | 4535
3.00 | 1478
6.00 | 556
12.00 | 366
0.50 | 181
2.00 | 175
0.25 | 60
1.50 | 16
4.00 | 11
0.75 | 10
5.00 | 6
9.00 | 4
2.50 | 2
11.00 | 1
0.11 | 1
1.75 | 1
0.04 | 1
0.36 | 1
8.00 | 1
1.36 | 1
1.25 | 1
0.30 | 1
0.00 | 1
1.10 | 1
1.20 | 1
0.07 | 1
0.29 | 1
2.25 | 1
1.86 | 1
[none] | 0

And the Python/Django code to generate the numbers, in case we want to run again later:
```python
from django.db.models import Count
from mep.accounts.models import Subscribe
for dur in Subscribe.objects.values('duration').order_by('duration').annotate(Count('duration')).order_by('-duration__count'):
    print('%(duration)s %(duration__count)s' % dur)
```

**Comment by elspethgreen** [comment]
Thanks for this!

It looks like the proportion of non-whole-month durations is about 4%.  The only somewhat-common non-whole-month durations are .5 and .25, i.e. 2 weeks and 1 week.

If we handled these durations manually, by entering an end date by hand, these durations would effectively drop out of any analytics we wanted to run on subscription lengths, right?  Or could those analytics be run from the calendar dates, which are autopopulated in the case of whole-month durations?  If the latter, I'd be totally comfortable with just having coders enter non-whole-month durations manually.

Some of those durations look pretty weird, though--could you send me a list of the accounts that those durations are associated with?  I'd just like to check what's going on against the logbook TEI.

**Comment by rlskoeser** [comment]
@elspethgreen I figured out a query to find durations that aren't divisible by 0.25 (i.e. one week).

Here's what I found in production.  Hopefully this gives you enough information to investigate!

account | start date | end date | duration | notes
-------- | ---------- | --------- | -------- | -------
Account #166: Giron | 1920-06-29 | 1920-06-30 | 0.04 |
Account #617: Alston | 1923-04-24 | 1923-04-26 | 0.07 |
Account #953: Willison | 1923-04-28 | 1923-05-06 | 0.29 |
Account #1581: Randall | 1925-04-20 | 1925-06-11 | 1.86 |
Account #1659: George | 1925-07-27 | 1925-07-30 | 0.11 |
Account #1063: Myers | 1926-11-10 | 1926-11-20 | 0.36 |
Account #2140: Howard Rubin | 1926-11-24 | 1927-01-01 | 1.36 |
Account #2655: Mme Bourret | 1936-12-07 | 1936-12-16 | 0.30 |
Account #4316: Sykes | 1935-07-01 | None | 1.10 |
Account #4598: Lagrange | 1935-03-27 | None | 1.20 | c02208 Image 482

---

Documenting the filter query for myself:
```python
from django.db.models import F
from mep.accounts.models import Subscribe

Subscribe.objects.annotate(duration_mod25=F('duration') % 0.25).filter(duration_mod25__gt=0)
```

**Comment by jkotin** [comment]
Hi all -- I'm watching this discussion from afar, and am grateful for all your work on this complicated issue!

I want to note, in case it's relevant, that for Beach a week was not 1/4 of a month.  If I walked into the bookshop on January 12, 1918, and subscribed for a month, I would have a subscription until February 12, 1918.  If I subscribed for a week, I'd have a subscription until January 19, 1918.  My sense is that a week was always seven days, while a month could be anywhere from 28 to 31 days, depending on the date of purchase.  Is this relevant?

**Comment by elspethgreen** [comment]
Thanks, Josh, that's good to point out!  I think, if we handle it with manual end dates for anything other than a month, we could instruct the encoders to use a sensible week, i.e. "Monday-to-Monday."  Then, if any analytics we did on subscription duration were based on dates, we'd be covered.

**Comment by rlskoeser** [comment]
@jkotin thanks for clarifying the months vs weeks duration, that's helpful.  The current implementation stores duration as months or fractions of months, and I think that's a very confusing interface whenever people need to enter subscriptions that are noted in weeks or days.  I'm doing some investigation to find something that will work better, and I hope to have some options to run by you both soon.

@elspethgreen I did some investigation on the list of accounts with strange durations above, and they do largely look okay based on what's in the logbooks xml (e.g., the one with 0.04 is 1 day, 0.36 is 10 days). 

I wonder if the Bourret one on 1936-12-07 has an error, since the logbook xml shows 0.3 months:
```xml
<event type="subscription">
    <p>S.<persName ref="#bourret">Bourret</persName> 
        <measure type="duration" unit="month" quantity="0.3">0.3m</measure> 
        <measure type="frequency" unit="volume" quantity="2">2v</measure> 
        <measure type="price" unit="franc" quantity="6">6</measure>
    </p>
</event> 
```

I can't find the 1935 entries; the logbook I'm looking at seems to be empty, so maybe I'm looking in the wrong place.

**Comment by rlskoeser** [comment]
Would appreciate opinions on preferred input.  Here are the options I'm thinking of.

Two separate boxes for months or days; enter a number in the appropriate place:
<img width="286" alt="screen shot 2018-01-23 at 5 32 22 pm" src="https://user-images.githubusercontent.com/691231/35304451-8bf3b96a-0063-11e8-8866-fbb3f80912b9.png">

Single text box where you enter the number and unit; you would help me define the list of allowed units and acceptable abbreviations:
<img width="152" alt="screen shot 2018-01-23 at 5 34 30 pm" src="https://user-images.githubusercontent.com/691231/35304511-bdcade14-0063-11e8-8090-e23930336646.png">

---

Second question: how would you ideally like durations displayed?  
- Should 12 months be displayed as 1 year or 12 months?
- For week increments: display 7/14/21 days or 1/2/3 week(s)?

**Comment by jkotin** [comment]
Re: the first question -- either options is fine with me:

1. Two boxes: months and days; or

2. One box with a predetermined list of units: days, weeks, months, years.

Either option will quickly become intuitive to researchers, IMO.  My only priorities are that the durations entered by the researchers a/ accurately reflect the information in the logbooks, and b/ populate the membership timelines correctly.

Eventually, we should be able to know how many members there were for a given date, say 1/23/24 or 7/23/36.  We should also be able to follow patterns of renewal on individual membership histories: so if a member purchased three weekly subscriptions in a row (beginning 1/1) and then a month-long subscription, they will have an uninterrupted membership timeline, ending on 2/22, and not some other date that reflects fractions of months.

Re: the second question -- I'm flexible about this as well.  But my default would be to follow Beach, so 1 year (not 12 months) and weeks.  But again, I'm happy with whatever is easiest here.

**Comment by rlskoeser** [comment]
Documenting decision on the input from the meeting yesterday: no strong feelings from Josh or Ellie, so going with my preference, which is one box with a set of recognizable units.

@elspethgreen My plan is to code to recognize any of **day/week/month/year** with or without an **s** at the end.  Let me know if you'd also like to support any abbreviations.  I'll document in the help text and validation error.

@jkotin thanks for the response about duration display.  Following Beach's conventions sounds excellent.

**Comment by rlskoeser** [comment]
I've determined the technical approach for handling duration and want to share it and document it here.  

I'm going to keep duration in the database even though technically it is redundant (since it can be calculated from start and end date) so that we can sort by duration in the admin site and use it for calculations across the records.  I'm going to store duration as days, and use *actual* days between start and end date (so month-based durations will have some variations in numbers).  However, I'm going to implement an input and display that will render the duration in year/month/day format.

One question: do you have any interest in seeing the actual days of duration either on the list view or the individual record edit form?  (Otherwise I will suppress from view and just calculate and store)

**Comment by rlskoeser** [comment]
@elspethgreen I think it might be useful for you to see the actual calculated duration for investigating entries that look odd.  Here's an example of something I found when I was checking my work so far:

![screen shot 2018-01-25 at 3 01 35 pm](https://user-images.githubusercontent.com/691231/35409641-d6734ac2-01e0-11e8-8698-88ba0390df3e.png)

I checked the logbook for the Randall subscription and it's entered as 6 weeks but a duration of 52 days, so this looks like a typo/user error.
```xml
<p>S r <persName ref="#rand3">Miss Randall</persName>
<measure type="duration" unit="day" quantity="52">6 weeks</measure>
```

**Comment by jkotin** [comment]
Thank you Rebecca.  Would seeing the actual days of duration be in addition to seeing the start and end and renewal dates?  If yes, I don't think we need to see them.  But you're right that we should have the option to see the actual days if we want to look for transcription errors like the one for Randall that you found.

**Comment by rlskoeser** [comment]
Yes, duration is in addition to start and end dates.  I think it is probably redundant, but I don't love the idea of having it totally hidden either.

Right now, I'm displaying duration in days on both the list view and as a read only field on the main subscription edit form (but not on the subscription edit form on the account page).  I think we could probably drop the one on the list view.

@elspethgreen take a look when you do your testing on this and let me know.  It's easy enough for me to remove it from the list view.

**Comment by elspethgreen** [comment]
@clmahoney would you mind taking a look at this?

**Comment by clmahoney** [comment]
Yes this looks great!
