### ISSUE TITLE
GeoNames id not working

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#473]
Impeding entering in nationality information!

**Comment by thatbudakguy** [comment]
@clmahoney so far we use the "blocked" label to indicate work that we can't do development on, usually because data work is incomplete - not the other way around. maybe we need a "blocking" label?

**Comment by clmahoney** [comment]
Oh good to know, @thatbudakguy ! I do think a “blocking” label would be useful.

**Comment by rlskoeser** [comment]
At some point, the application was configured to use a geonames id specific to this project (previously we'd been re-using one from another project), but webservices access for that account did not get turned on. I've remedied that - it should be working on both production and test now that the change has been made, but I'll leave the bug open for someone to verify on the test site.

**Comment by clmahoney** [comment]
YES, I was able to add in a country (Uzbekistan!) without a problem.
