### ISSUE TITLE
Revise the "Author" and "Start Date" alignments and remove hyphens from "Start Date" and "End Date" 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#477]
Based on designs here: 
1. "Author" and Start Date" columns and their labels to become left-aligned:
Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cc1d1bb7cbe272d01d28b1e"
Tablet": "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cc216ebf11a741010f260d6"

2. "Start-Date" and "End-Date" to become "Start Date" and "End Date":
Desktop: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b5030eb3b183b25b9200"
Tablet: "https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5db0b503f3d79e57b28a00e1"

**Comment by thatbudakguy** [comment]
i think there are no "Start-Date" and "End-Date" with hyphens currently; not sure we ever implemented it that way.

if we left-align "Start Date" on the borrowing activities table, should it also be aligned on the membership activities table? both dates are currently centered on that table.

**Comment by gissoo** [comment]
@thatbudakguy No please leave the membership activities page as is for now, the placement of those columns on that tab is different from the other pages. 

Regarding the hyphens, great, thank you! I had forgotten to remove the hyphens in my designs on the card image viewer.

**Comment by rlskoeser** [comment]
Alignment is easy but I'm not sure how to adjust the padding so that headers line up with their contents. (I can remove left padding, but then I think the columns will be closer together than intended in the design.)
