### ISSUE TITLE
As a user, I want to see an indicator when my search doesn't return any results or something goes wrong so I know what happened.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#482]
## notes for testing
- search for something that doesn't match any names: you should see text indicating no results and directing you to revise your search terms; you should also see the pic of Shakespeare tearing his hair out
- _(optional)_: if something goes wrong with Solr, you should see the same image but different text (I don't know of a way to trigger this by searching, but we can force an error in the config if you want to confirm/review)

### design links
[desktop](https://zpl.io/VDoQYlJ) / [tablet](https://zpl.io/2vA8QRj)

I didn't see a mobile version in Zeplin, but please confirm that it looks reasonable. Note that I revised the wording slightly from what is in Zeplin.

**Comment by clmahoney** [comment]
Desktop: 
- YES, when I type in an unknown name, like "Mirai," I see the text "No search results found. Try a differnt search." and below that, the image of Shakes tearing his hair out.

**Comment by clmahoney** [comment]
Mobile: 
- YES, when I search for something unknown (in this case, searched for a nonbinary person named Jacob), I see the text and then the Shakes image below it. See screenshot. 
![Image from iOS (7)](https://user-images.githubusercontent.com/16673934/70580955-838dde80-1b83-11ea-828d-8e03b3c9f571.png)

**Comment by clmahoney** [comment]
Tablet: 
- YES, this looks great too. The text and the image show up.

**Comment by jkotin** [comment]
I didn't realize this was a separate issue when I placed my enhancement request!  I was working on issue 363.  I'll leave this open for now.

**Comment by rlskoeser** [comment]
@jkotin what do you think of my proposed simple solution to only show the image if there's an error? That wouldn't be hard to implement, and we could manually misconfigure something to trigger an error so you or Cate could test.

**Comment by rlskoeser** [comment]
Updated the test site with revised behavior. Let me know when you want to test and I can force a Solr error.

**Comment by jkotin** [comment]
Looks good.  I'm happy to close.
