### ISSUE TITLE
As an admin, I want the site to provide XML sitemaps for member pages so that site content will be findable by search engines.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#484]
## testing notes
- check site robots.txt is present and includes sitemap.xml url
- check main sitemap loads and lists all member sitemaps
- check that all the member sitemaps load and look correct (urls and dates)
- check that member card list sitemap sets low priority for members with no cards and default priority for members with cards

**Comment by rlskoeser** [comment]
Upgrading to two points, since we didn't have an existing last modified field we could easily use (had to add to Solr), and because the card detail view was a little more complicated than the others.

**Comment by thatbudakguy** [comment]
✔️ robots.txt lists sitemap
✔️ sitemap lists sub-sitemaps
✔️ urls/dates on sitemaps are correct
✔️ members with card get 0.5 priority; all others show 0.1
