### ISSUE TITLE
wagtail fails to send notifications to moderators when page is submitted for review

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#487]
**Describe the bug**
When submitting a page for moderation in wagtail, the page successfully submits and saves itself, but wagtail displays an error message stating that notifications to moderators failed to send.

**To reproduce**
1. Log into wagtail in production.
2. Create a new page (for example, under "about") and fill in the title and page body.
3. Choose "submit for moderation" from the menu where the "save draft" button is.

_note_: tested this in qa and it works correctly. error only occurs in production.

**Expected behavior**
No error message would be displayed and moderators would be notified of the submission.

**Screenshots**
![Screenshot from 2019-12-11 16-12-48](https://user-images.githubusercontent.com/4924494/70660883-1e90c200-1c31-11ea-841d-a9b691b5d4a2.png)

**Device information**
 - Device: Dell Latitude E5470 laptop
 - OS and version: Ubuntu 18.04.3
 - Browser and version: Firefox 68.0.1
 - Site version: 0.23.1

**Additional context**
Suspect this is because wagtail is attempting to send an email notification but is running into some sort of permissions error in production.

**Comment by rlskoeser** [comment]
@thatbudakguy wagtail moderation notifications are actually working now, right? Wasn't there a config you added?

**Comment by thatbudakguy** [comment]
so, I believe the emails are correctly sent, but I think the error message still shows in production? haven't tested it in awhile though.

**Comment by rlskoeser** [comment]
Ok. We can try to test it the next time we have content to post and see if it's resolved.
