### ISSUE TITLE
Searching on Members page. Error message.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#488]
When searching on the members page, "No search results found. Try a different search" (plus hair pulling image!) automatically appears as a user starts typing. I worry that the message will cause the user to think they are doing something wrong. _I think the message should appear only after the user finishes entering a search term, not as the user is entering a search term.__ (I.e. after hitting "enter.") Alternatively, we could remove the image.  The hair pulling error is disconcerting!

**Comment by rlskoeser** [comment]
Oh, interesting - @thatbudakguy do you know why this is showing up while typing? I don't see I'm seeing that behavior. I wonder if it's anything to do with connection speed...

I did wonder about the image - it's fun, but it does seem to indicate something went wrong. A simple fix for now would be to only show the hair-pulling image if there is a Solr error. I _think_ that should hardly ever happen - I don't know of any user entered terms that will trigger it, I think only Solr being unavailable or misconfigured.

**Comment by thatbudakguy** [comment]
@rlskoeser yeah, I strongly suspect it's just the connection speed. one option might be to tweak this value, which controls how often the search can be submitted: https://github.com/Princeton-CDH/mep-django/blob/cf393b629911b16cc8f8761999e1dd6a1be30cec/srcmedia/ts/members-search.ts#L69
we could try doubling to `1000` to wait at least a second after the user stops typing before submitting.

**Comment by rlskoeser** [comment]
I like how responsive it is now, but waiting a bit more to submit might be reasonable - especially for slower connections. @jkotin what do you think, do you want us to try this?

**Comment by rlskoeser** [comment]
Resolved via #482
