### ISSUE TITLE
Required manual data entry

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#49]
Issues, and potential workflows
**"Care of" for addresses:**
--Encoder ctrl-F's the personography for "care of" and "c/o" and other variants.
--Encoder manually scrolls through entire first section of personography (people with cards--we don't have address info for people only in the logbooks) and makes sure they haven't missed anything.
--Encoder notes this in the database (since the handling of addresses is changing, we will need input from dev on how this will work).
**Start-end dates for addresses:**
--Ongoing research task
--There is no notation on the cards or in logbooks to directly indicate duration of addresses
--Research team will need to figure out how to reasonably prioritize this task; do we want to start with the most famous people, and work our way more obscure?

**Comment by elspethgreen** [comment]
I've started a list of manual data entry needs above--Josh, do you have anything to add?

**Comment by elspethgreen** [comment]
I'm moving this out of GitHub--I'll check out the "care-of" issue, but the start-end dates is something for the future.

**Comment by rlskoeser** [comment]
Thanks @elspethgreen .  Subscription start date issue is now documented in #80.
