### ISSUE TITLE
As an admin, I want the site to provide XML sitemaps for book pages so that site content will be findable by search engines.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#492]
## testing notes
- check main sitemap loads and lists all book sitemaps
- check that all the book sitemaps load and look correct (urls and dates)

**Comment by rlskoeser** [comment]
Downgrading to 0 because this was trivial — able to use the member sitemap logic directly.

**Comment by thatbudakguy** [comment]
✔️ main sitemap loads
✔️ dates & urls on sub-sitemaps look good
