### ISSUE TITLE
As a user, when browsing the member with card list, I want to see the Alphabetical chunk of the page I'm on

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#496]
**Describe the bug**
Right now even if I hit "next" on the members page and move from "A-Culb" to the next page "Cull-Gi", the page itself changes but the "displaying" box REMAINS on "A-Culb"

**To reproduce**
1. Go to members page
2. Click on next at top of page, so you're at the next chunk of names 
3. See error in display button that it looks like you're in the first chunk of names 

**Expected behavior**
When I move to the next page, the display name chunk should match the page I'm on. 

**Screenshots**
![Screen Shot 2019-12-13 at 6 51 00 PM](https://user-images.githubusercontent.com/16673934/70839191-90a40b00-1dd9-11ea-997a-84e26dbfffb5.png)

**Device information**
 - Device: Macbook Air
 - OS and version: macOS 10
 - Browser and version: Chrome 79
 - Site version 0.24.1

**Additional context**
Sorry for the ridiculous amount of "chunk" in this description; it's not the best word

**Comment by thatbudakguy** [comment]
believe this is a duplicate of #415.

**Comment by rlskoeser** [comment]
@thatbudakguy agree. Which one has more useful information? Can we consolidate and close one as a dupe?

**Comment by thatbudakguy** [comment]
this one includes OS/browser info to replicate, so I'll close #415 in favor of this one.

**Comment by thatbudakguy** [comment]
believe this is now fixed along with #498, so marking ready for testing.

**Comment by clmahoney** [comment]
Hooray, YES this works! I went to the members page, then hit the next button a few times. Whenever I did, the alphabetical chunk in the display box always displayed the current page I was on, even if I hit back or clicked on an individual member detail page and clicked back to the main search.
