### ISSUE TITLE
As a user, I want to know when a member's card is available elsewhere so I can look beyond the site if needed

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#497]
We need to have a text that represents cards from other libraries. Ex: Norma Faulkner's card is at Texas. “No lending library cards available” is not enough information for that. 

## notes for testing
- Members with cards that have images should display as before
- Members with cards but no images should now display the citation (uses bibliographic note from the bibliography record for the card associated with the account); should not display "no lending library cards available". Examples to test: Norma Faulkner, Mrs Thomas Metcalf
- Any notes on the bibliography record for a card should be displayed whether there are images are not. Test for members with cards but no images: Norma Faulkner, Mrs Thomas Metcalf; test adding a note to a member with a card that has images (e.g., adapt the note on James Joyce Buffalo cards record and add as a note to the record for the Joyce cards held at PUL).
- Member without associated cards should display the text "no lending library cards available" as before

## dev notes
- notes have been added to Faulkner, Mrs. Metcalf, Perron/Roos, Joyce family.
- [x] if there is a card record associated with the account but no images, display the citation
- [x] if there is a note on the card record, always show it
- [x] 'no lending cards' should only display if account has no associated card
- [x] apply `urlize` on the note text so links will be clickable 
- [x] when implementing this, generate a list of existing notes for bibliography card records to check for any stray notes we _don't_ want to show publicly

**Comment by rlskoeser** [comment]
@clmahoney @jkotin We can display the bibliographic note for the cards from the database if a member's account has one but no digitized cards available. Please provide any wording you want to contextualize and also if we should display the notes field if it has any content.

**Comment by jkotin** [comment]
Thank you @rlskoeser. Would this text/citation display instead of "No lending library cards available" on pages like this: https://shakespeareandco.princeton.edu/members/faulkner-norma/cards/?

Where in the database would we enter the text/citation? Would we have one text/citation for all the cards of a particular member?

Right now, there is one set of cards in the Joyce Collection at the University at Buffalo (some of Joyce's cards) and three sets in the Harry Ransom Center at the University of Texas, Austin (Norma Faulkner, Mrs. Thomas Metcalf, and du Perron). I can write the text/citations. Can they includes links?

**Comment by rlskoeser** [comment]
@jkotin yes, my expectation would be we display this text or citation when we have it and only display the "no lending library cards" message if we don't have any information.

I propose we take advantage of the existing bibliography records in the footnotes section of the database and admin site. Currently, there is an entry for the James Joyce cards but the bibliographic note only says "James Joyce cards, Buffalo."  You could revise this to be a proper citation for the cards in the archive that holds them, and then we could display that.

Is there a way to write up the citation so it includes a url? If so, we can easily add a filter to make that link clickable.

Side note that occurred to me in light of this conversation: on the members browse page our card filter currently shows members we know have cards (e.g. Norma Faulkner) and not only members with _digitized_ cards. I'm not sure if this is the expected/preferred behavior; I think our help text isn't specific enough to say one way or the other. Please open an issue if you think the current functionality is not correct.  (I think it will be correct - or at least better - once we add citations for cards held elsewhere.)

**Comment by jkotin** [comment]
@rlskoeser I'll get on this tonight or tomorrow. I think what we have is fine re: the side note about the filter. The card filter is as much about showing which members have borrowing records, as it is about showing member with actual cards. Also, when we get less busy (!) I will write Texas for permission to display their cards. I am sure they won't have a problem with that. It's just a low priority for now. And I agree that the citations will help clarify everything.

**Comment by jkotin** [comment]
@rlskoeser is this the place to put the footnote/citation for, e.g., Faulkner:

https://shakespeareandco.princeton.edu/admin/footnotes/bibliography/575/change/?_changelist_filters=q%3Dfaulkner

**Comment by jkotin** [comment]
Here's one option for language for cards not at Princeton:

The Norma Faulkner Lending Library Cards are part of the Carlton Lake Collection of Maurice Saillet, Sylvia Beach, and Shakespeare and Company at the Harry Ransom Humanities Research Center, the University of Texas at Austin.

The link to the Collection is https://norman.hrc.utexas.edu/fasearch/findingAid.cfm?eadid=00116.

We could also include the box/file info: 262.1.

**Comment by jkotin** [comment]
That info also applies to Mrs. Thomas Metcalf and du Perron.

The reference to the Joyce family cards—i.e. some of the Joyce cards, and the cards of Lucia and Giorgio is the James Joyce Collection, the Poetry Collection, University at Buffalo.

The link is: https://library.buffalo.edu/jamesjoyce/catalog/xx/

Section/folder XX.31.

**Comment by rlskoeser** [comment]
Marking as question because we need to discuss specifics in person to clarify before implementing.

**Comment by rlskoeser** [comment]
@jkotin As requested, here's a list of all the bibliography records that have notes. It looks like there's only one note (for Nicole Thellier) that you'll need to look at and do something about.

---

Giorgio Joyce cards, Buffalo
The lending library cards of Giorgio Joyce and Lucia Joyce, and some of the lending library cards of James Joyce are part of the James Joyce Collection at the University at Buffalo. For more information, visit: https://library.buffalo.edu/jamesjoyce/catalog/xx/.

James Joyce cards, Buffalo
The lending library cards of Giorgio Joyce and Lucia Joyce, and some of the lending library cards of James Joyce are part of the James Joyce Collection at the University at Buffalo. For more information, visit: https://library.buffalo.edu/jamesjoyce/catalog/xx/.

Lucia Joyce cards, Buffalo
The lending library cards of Giorgio Joyce and Lucia Joyce, and some of the lending library cards of James Joyce are part of the James Joyce Collection at the University at Buffalo. For more information, visit: https://library.buffalo.edu/jamesjoyce/catalog/xx/.

Sylvia Beach, Elisabeth (de Roos) du Perron, Lending Library Card, Harry Ransom Humanities Research Center, University of Texas at Austin
The lending library card for Elisabeth de Roos / Eddy de Roos / Mrs. du Perron is part of the Carlton Lake Collection of Maurice Saillet, Sylvia Beach, and Shakespeare and Company at the Harry Ransom Humanities Research Center, the University of Texas at Austin. For more information, visit: https://norman.hrc.utexas.edu/fasearch/findingAid.cfm?eadid=00116.

Sylvia Beach, James Joyce Lending Library Card, Box 43, Sylvia Beach Papers, Department of Rare Books and Special Collections, Princeton University Library.
The lending library cards of Giorgio Joyce and Lucia Joyce, and some of the lending library cards of James Joyce are part of the James Joyce Collection at the University at Buffalo. For more information, visit: https://library.buffalo.edu/jamesjoyce/catalog/xx/.

Sylvia Beach, Madame Nicole Thellier de Poncheville Lending Library Card, Box 43, Sylvia Beach Papers, Department of Rare Books and Special Collections, Princeton University Library.
[images deleted, can't delete card without deleting associated now-corrected footnotes] [EG 4/18/19]

Sylvia Beach, Mrs Thomas Metcalf Lending Library Card, Harry Ransom Humanities Research Center, University of Texas at Austin
The lending library card of Mrs. Thomas Metcalf is part of the Carlton Lake Collection of Maurice Saillet, Sylvia Beach, and Shakespeare and Company at the Harry Ransom Humanities Research Center, the University of Texas at Austin. For more information, visit: https://norman.hrc.utexas.edu/fasearch/findingAid.cfm?eadid=00116.

Sylvia Beach, Norma Faulkner Lending Library Card, Harry Ransom Humanities Research Center, University of Texas at Austin
The lending library cards of Norma Faulkner are part of the Carlton Lake Collection of Maurice Saillet, Sylvia Beach, and Shakespeare and Company at the Harry Ransom Humanities Research Center, the University of Texas at Austin. For more information, visit: https://norman.hrc.utexas.edu/fasearch/findingAid.cfm?eadid=00116.

**Comment by jkotin** [comment]
@clmahoney Would you look into and fix the Thellier footnote/situation?

**Comment by clmahoney** [comment]
@rlskoeser @jkotin I think I fixed the Thellier footnote! For some reason there were two bibligraphies for her, and only one footnote was assigned to one of them, so I reassigned it and deleted the extra.

**Comment by clmahoney** [comment]
- YES, members with regular cards at Princeton are displayed as per usual - tried Alderman
- YES, members who do not have cards are displayed as per usual "No lending library cards available" - tried Bernice Abbott 

- YES, members with cards held but institutions other than Princeton have a new text displayed saying where the cards are held. However, my question is that there is extra text there too: see this example for Norma Faulkner: 
![Screen Shot 2020-02-13 at 1 34 54 PM](https://user-images.githubusercontent.com/16673934/74467418-feff5b00-4e66-11ea-9371-11cd2db8804e.png)
--> QUESTION: I thought I could  fix this simply by deleting the "bibliographic note," but when I try, it says the bibliographic note field is required.

**Comment by rlskoeser** [comment]
@clmahoney my understanding of the functionality we agreed on is that if there are no images the  bibliographic note would display (to provide a source / citation for the cards), and any content in the notes field should always be present whether there are images or not.

**Comment by clmahoney** [comment]
@rlskoeser OK, I understand.

**Comment by clmahoney** [comment]
- YES, when I added text to one of the cards WITH images--using James Joyce for example--his cards appear AS DOES the note: 
![Screen Shot 2020-02-13 at 1 53 34 PM](https://user-images.githubusercontent.com/16673934/74468110-40443a80-4e68-11ea-9cb0-fc8cff81aa87.png)

**Comment by clmahoney** [comment]
The functionality of all of this works well. I pass this on to @jkotin to see how he feels about the bibliographic note floating above.

**Comment by jkotin** [comment]
The Mrs. Metcalf card is showing two messages. There should only be one: the second one.

<img width="1344" alt="Screen Shot 2020-02-13 at 8 34 12 PM" src="https://user-images.githubusercontent.com/12616674/74493505-4e15b200-4ea0-11ea-929e-61aacc00924f.png">

**Comment by jkotin** [comment]
The message for the Joyce cards should be tailored for the specific member. So, for example, the message for Giorgio Joyce should read:

The lending library cards of Giorgio Joyce are part of the James Joyce Collection at the University at Buffalo. For more information, visit: https://library.buffalo.edu/jamesjoyce/catalog/xx/.

**Comment by jkotin** [comment]
For James Joyce, the message should read:

Some of the lending library cards of James Joyce are part of the James Joyce Collection at the University at Buffalo. For more information, visit: https://library.buffalo.edu/jamesjoyce/catalog/xx/.

**Comment by jkotin** [comment]
Last question: is there a way for me (or Cate etc.) to edit this language on the back end?  If so, where should I go in the database?

**Comment by clmahoney** [comment]
Yes @jkotin it's here: https://test-shakespeareandco.cdh.princeton.edu/admin/footnotes/bibliography/647/change/

**Comment by rlskoeser** [comment]
Aha. I see that you didn't understand my proposed solution.

I strongly recommend that we use the bibliographic note - as Cate remarked, it's *required* while the notes field is optional, and should be used to provide any *additional* information needed. Both the bibliographic note and the notes are editable to you in the admin, so you can revise either or both of them to avoid the redundancy we have at the moment. If you want to include a URL in the citation, please let me know so I can make it clickable.

I'd be happy to add a heading for the bibliographic note - I thought about this when I implemented it, but didn't come up with anything satisfactory. Location? Source?

**Comment by jkotin** [comment]
Perfect. I understand now. I fixed Giorgio:

<img width="935" alt="Screen Shot 2020-02-14 at 1 27 16 PM" src="https://user-images.githubusercontent.com/12616674/74557292-d68e6400-4f2d-11ea-8599-2a0264b3a424.png">

Is there a way to make the link live?  If not, that's fine with me.  I'll rewrite the bibliographic notes in the database once 0.25 is up.
