### ISSUE TITLE
As a user, when I'm on the second display section of the members with cards page, I want to be able to investigate an individual member and then click back to the display section I'm on

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#498]
**Describe the bug**
When I'm on section Cull-Gi of the Member page, and I click on an individual member like Espitalier and then click backwards to get back to Cull-Gi, I automatically get returned to the first section A-Culb.  

**To reproduce**
1. Go to Members page
2. Click on Members with cards
3. Go to display Cull-Gi 
4. Click on any one of these individual members, then click back to where you were
4. See that you've been jumped back to the first display section A-Culb. 

**Expected behavior**
When I click back, I want to be in the same section that I was before. 

**Device information**
 - Device: MacBook Air
 - OS and version: macOS 10
 - Browser and version: Chrome 79
 - Site version 0.24.1

**Comment by rlskoeser** [comment]
It looks like page number isn't getting updated in the url when the pagination changes, although this doesn't happen every time - only fails on the first update, maybe?

**Comment by rlskoeser** [comment]
@thatbudakguy I was just experimenting with this to see if I could figure out what's going on, maybe these notes will help you with where to look in the code.

Under certain circumstances, the page option in the url isn't getting updated when you change pages using the drop down. It does seem to work the second time I change it.

Maybe there's an initialization problem? If I reload the member search page with no `page=` option in the query params, the first time I change page with the drop down I get the expected set of results, but the drop down displays Ab- Anr and the url displays `page=1`

I thought I'd noticed a weird interaction between the drop down and the next where they weren't in sync, but I can't duplicate it now. Maybe it only happens on the first change.

**Comment by thatbudakguy** [comment]
Thanks for investigating this. A major source of pain in the client-side code so far has been the pattern of "initialize some value based on whatever is in the DOM, then track changes to that value, but don't consider the initial value a change", which I think is exactly what's happening here - initial changes are being ignored.

**Comment by thatbudakguy** [comment]
bumping to next milestone; don't think we have time to test/get this out in v0.28.

**Comment by clmahoney** [comment]
YES, this works - it worked as part of #496.
