### ISSUE TITLE
Single-day events on activity pages display as ranges on mobile display

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#499]
**Describe the bug**
Single day events on activity lists on mobile display as date ranges.

**To reproduce**
1. Go to borrowing activity for an account with purchases, e.g. [Stanislaus Joyce book activities](https://shakespeareandco.princeton.edu/members/joyce-stanislaus/borrowing/)
2. Look at it on mobile
4. See purchase date displayed as a a range: April 25, 1933 — April 25, 1933

I suspect this is also true of reimbursement events on the membership activity page.

**Expected behavior**
On mobile, single-day events should display one date instead of a range.

**Screenshots**
![Capture+_2019-12-13-19-54-04](https://user-images.githubusercontent.com/691231/70913070-4db58380-1fe3-11ea-8c28-7076e787f669.png)

**Device information**
 - Device: Tested on Android and Chrome dev tools simulating mobile
 - Site version: 0.24

**Additional context**

Related, although not strictly part of this bug: borrow and subscription events on mobile should display as a range even when both dates are not known, so that there is a cue to tell whether the known date is a start or end.

**Comment by clmahoney** [comment]
This looks great! I tested for purchases and reimbursements on mobile, and there is no longer a "range" for single day events. 
Stanilsaus Joyce purchase: 
![IMG_1968](https://user-images.githubusercontent.com/16673934/80619005-1aafe180-8a12-11ea-8744-e48a3edd84af.PNG)
Thomas Metcalf purchases: 
![IMG_1969](https://user-images.githubusercontent.com/16673934/80619051-269ba380-8a12-11ea-9138-91b90d3ac8c0.PNG)
Mrs. K. Bayle reimbursements
![IMG_1970](https://user-images.githubusercontent.com/16673934/80619109-37e4b000-8a12-11ea-86aa-d429dd5ef49b.PNG)
:
