### ISSUE TITLE
As a content editor, I want to be able to see a listing of all events (regardless of type), so that I can look up their generic fields and any non-standard types that do not have a subcategory such as overdue notices

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#50]
Some ways to test (and tangentially verify #36):
- [ ] can create a generic event with notes and associate an account using autocomplete
- [ ] can search by date, notes, account person name or account mep_id in list view on admin
- [ ] searching for 'overdue' should produce 11 results (the 11 overdue w/ their notes)
- [ ] searching for 'unrecognized subscription type' should produce 108 results (the results with odd subscription types)
- [ ] Drill down dates hierarchy you can use to subset down on list view, (which also extends to Subscribes and Reimbursements)

**Comment by bwhicks** [comment]
@elspethgreen @jkotin With apologies, a quick addition to this release that probably should have been in the initial set of admin additions. I've added a generic 'Event' to the admin interface that shows all events and their basic info (regardless of sub-classification into 'Subscribe' etc.).

It should help with verifying any concerns over total numbers and also give you a way to look directly at the overdue notices (among other concerns).

If some members of the team can test this story briefly, I believe this is the only thing holding a release.

**Comment by elspethgreen** [comment]
Looks good!
