### ISSUE TITLE
As a user, I want to see notes about a person added by project team members so that I have more information about unusual library members.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#502]
# testing notes
## design links
[desktop](https://zpl.io/bzqRrXz) / [tablet](https://zpl.io/VQvnk7A) / [mobile](https://zpl.io/bA7PWZe)

this issue is written about the display of public notes on member pages, but we'd like to test the look of all of the member details, since this page hasn't been updated in awhile.

when I was testing, I didn't see any members who have public notes defined - you might need to just pick someone and add some public notes to them in the admin site yourself to test this.

## script
1. go to the admin backend and add public notes to any member.
2. visit that member's detail page and check against the design links above on all screens.

**n.b.**
there are two discrepancies you will probably notice:
- the design doesn't include the display of the member's name, but we need it, because some members have multiple/different names that you wouldn't ordinarily see.
- the display of membership dates won't be quite as complex as in the design; we have issue #526 to track that. ignore it for now.

## dev notes
- display public notes on member detail page
- update biographic page display to match revised design

**Comment by thatbudakguy** [comment]
removing from wishlist as per [slack discussion](https://cdhprinceton.slack.com/archives/C2YJR4VF0/p1586358555304700)

and downgrading to 1 since we already have this field, just need to display it.

**Comment by clmahoney** [comment]
Desktop: 
- YES, I can add a public note to a member on the backend of the site, and see it appear on the front-end as per the design. I tried with two members: 
![Screen Shot 2020-04-09 at 1 32 59 PM](https://user-images.githubusercontent.com/16673934/78923980-102fa700-7a67-11ea-9388-f19d02ffdf3a.png)
and
![Screen Shot 2020-04-09 at 1 35 13 PM](https://user-images.githubusercontent.com/16673934/78923989-12920100-7a67-11ea-8863-ace096b3efa8.png)
- On another note, I see that member name relevance (when searching) now has a cool blue bar! 
![Screen Shot 2020-04-09 at 1 36 52 PM](https://user-images.githubusercontent.com/16673934/78924056-2e95a280-7a67-11ea-8c03-b8e0162f6a4b.png)

**Comment by thatbudakguy** [comment]
glad you like the blue bar! it should appear on the work search too. going to close this; thx for testing!

**Comment by clmahoney** [comment]
Mobile: 
- YES, it all works here too! I added a public note to member Helen Baldwin in the admin, then saw it appear on the front end as per the design: 
![IMG_1809](https://user-images.githubusercontent.com/16673934/78924802-65b88380-7a68-11ea-82fc-5e7a80b75cdd.PNG)

**Comment by clmahoney** [comment]
Tablet: 
- Works and looks great here too!
