### ISSUE TITLE
Add "Unidentified" category for nationality

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#508]
On the members demographics drop down, add "unidentified" under "nationality" -- to match the format of the gender drop down, and to show the Project as a work in progress. 

## testing notes
- On the members page, check that the nationality filter list now includes "unidentified" at the end
- test filtering on unidentified nationality — on its own, in combination with other nationality filters, in combination with other filters
- test filtering on other nationalities (make sure to test some with spaces and some without)

**Comment by clmahoney** [comment]
- YES, I see that in the dropdown menu for Nationality, there is now a "Unidentified" option
- YES, if I selected the "Unidentified" option, I see all 5,346 options appear on the member search below 
- YES, if I select more nationality filters in combo with "Unidentified," the numbers add up correctly 
- YES, if I mix the "Unidentified" filter in combo with other filters, such as gender and arrondissement, I see the expected number of results

**Comment by clmahoney** [comment]
@rlskoeser Sorry, can you clarify what you mean by the last testing direction, "some with spaces and some without"?

**Comment by rlskoeser** [comment]
@clmahoney sorry, that was unclear! Was thinking as a programmer rather than a normal person — I just mean, please test both one word (e.g. Russia) and two word (e.g. South Africa) nationalities. I changed slightly how the query handles them and want confirmation that I didn't break anything.

**Comment by clmahoney** [comment]
- YES, I tested with some nationalities that are one word (like Russia) and some that include spaces (like New Zealand). Displays as it should!!
