### ISSUE TITLE
As a content editor, I want event duplication to be prevented so I don't accidentally enter the same event twice.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#51]
## Notes for testing
- Test adding a reimbursement with same account & date as an existing event - should see an error and it won't save.
- Test adding a subscription with same account & date & type as an existing event - you should see an error and the record won't save.  
- Test adding a subscription with same account & date but different type - it should save.
- Search on the reimbursement and subscription list views for "duplicate" to see events that have been flagged as duplicates for manual cleanup.  You can do some test cleanup and investigation on the test site, but remember we want to do the real cleanup in production - for testing purposes, we just need to know that you'll have enough information to do that cleanup later on.

## Notes for development
Add database unique together constraints: person + event type + date should be unique.  For subscription events, event type should include modification types.

Note that we are likely to discover existing duplicate events in the system that we'll have to resolve when we add this constraint.

**Comment by rlskoeser** [comment]
We can't use `unique_together` here because we used multi-table inheritance for events, but I was able to write a `validate_unique` method that does what we need.

I've started working on the queries to identify dupes (or possible dupes) in the record - looks like there may in fact be some.  We can write a migration script to check for them, but I'm not sure what to do with them - maybe add a note to flag as possible duplicate?  (Could automatically remove the extra copies, but I'm not sure how safe that is.)

**Comment by elspethgreen** [comment]
I'm nervous about auto-deleting them right away--could we flag them instead for now?  Or could you send me a list?  I'd like to take a look at them and try to figure out how they occurred; like, whether it's from Cate and I entering data, or an import problem, or a problem with the original data, etc.

**Comment by rlskoeser** [comment]
@elspethgreen you're right, they should be reviewed so you can figure out where they came from and what the error is.  When I get back to this and figure out how to identify them all, I'll come up with a way to flag them and/or give you a list so you can investigate.

**Comment by rlskoeser** [comment]
I've written a data migration that will flag duplicate records in the notes.  Once this is put on the test site and marked as ready for acceptance testing, you'll be able to search the reimbursement and subscription list views for "duplicate" to see a list of them.  A few notes:
- the script labels both events as duplicates, so you can find them
- because of the unique validation we've put in place, you won't be able to save any changes to these events until you correct them so they are not the same (if there is a data entry error) or remove one of them (if they are true duplicates)

**Comment by elspethgreen** [comment]
Sounds good!

**Comment by clmahoney** [comment]
I tested these two: 

- Test adding a reimbursement with same account & date as an existing event - should see an error and it won't save.
- Test adding a subscription with same account & date & type as an existing event - you should see an error and the record won't save.
--> And they both are fine. They report an error and won't let me save. 

I tested this one: 
- Test adding a subscription with same account & date but different type - it should save.
BUT IT DID NOT SAVE. I changed the type and also changed the modification and kept everything else (account #, date, vol, duration, price paid)

**Comment by rlskoeser** [comment]
@clmahoney could you take a screenshot of the form not saving and a screenshot of all the subscriptions for the same date so I have more detail when I investigate?

**Comment by clmahoney** [comment]
WHOOPS I just tried it again and it worked!

**Comment by rlskoeser** [comment]
@clmahoney thanks for checking.  I wonder what went wrong the first time?  Maybe someone else can double check this when they test so we can see if there's any case where it doesn't behave the way we want.

**Comment by elspethgreen** [comment]
I tested this and it looks good.
Cate, I wonder if you ran into our persistent type/category confusion?  If you only change what is now "category" (whether it's an "A" subscription, or a "Student" etc.) it still counts as a duplicate, because someone wouldn't have two subscriptions of different categories in the same timeframe.  But if you change "type" (subscription, supplement, renewal) it will save, because that's a different kind of event.

**Comment by elspethgreen** [comment]
@clmahoney would you take another look at this?

**Comment by clmahoney** [comment]
Yes @elspethgreen  I tested it again and it did save, and I think it was type/modification confusion on my part.
