### ISSUE TITLE
Line spacing/leading on member pages for members with long/multiple names

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#510]
I think the space between long/multiple names on the member pages is too cramped. See the attached image for Katherine Anne Porter.
<img width="781" alt="Screen Shot 2020-01-02 at 9 02 35 AM" src="https://user-images.githubusercontent.com/12616674/71670771-fe8b8480-2d3e-11ea-8efe-04ca160bef59.png">

**Comment by rlskoeser** [comment]
Setting as 0 to help with release estimation per @thatbudakguy comment in Slack:
> should be almost instant fix, doesn’t require design;  a special line-height that was used in older designs and that now appears awkward bc layout changed

**Comment by thatbudakguy** [comment]
verified in QA that this now looks as expected.
