### ISSUE TITLE
As a data editor, I need to enter partially known dates for membership events so I can document memberships from sources where the exact date is not known.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#513]
We do not have logbooks for certain periods. An address book that Sylvia Beach started in 1936 contains membership events from some of those periods. The events in the address book have months and years, but not specific dates. We need partial date capability to enter those events in the database.

## testing notes
When you edit or create subscription and reimbursement events, you should now be able to use partially known dates with the same syntax used elsewhere in the system.
- test creating an event with a year/month start date and duration (months or years, e.g. 3 months, 6 months,  1year): end date should be generated correctly and with year/month only
- test creating an event with a year/month start date and year/month end date: duration should be generated correctly 
- admin list view for subscription events should display dates in partially known format
- test creating a reimbursement event with year/month date; should succeed; search for your new reimbursement event in the generic event admin list: the end date should match the start date exactly (year/month only)
- check the membership activity table on the public part of the site for the member you added the new event to: dates should display as month/year only

Note that you could also test year only or dates with unknown year, but I don't think they are likely scenarios (in fact I'd recommend we not enter any of these), and it's possible that the subscription duration logic won't work properly in some cases.

## dev notes
- [x] add partial date form mixin to subscription and reimbursement event forms in admin
- [x] use partial date for list view in subscription and reimbursement event forms in admin
- [x] update subscription admin form clean method to handle partial dates
- [x] update reimbursement save method to handle partial dates
- for now, we will not worry about revisiting anywhere in the code that assumes membership dates are not partial; it's fine to treat them as the first of the month for the time being

**Comment by rlskoeser** [comment]
@jkotin @i-davis do you need partial date support for reimbursements also? Or only subscriptions?

**Comment by jkotin** [comment]
@rlskoeser Yes, reimbursements too.

**Comment by clmahoney** [comment]
- YES, I created a subscription for Holly (Beach) Dennis, that was from September 1931 for 2 months, and the end date was generated correctly with year/month displayed. See below: 
![Screen Shot 2020-02-13 at 4 01 42 PM](https://user-images.githubusercontent.com/16673934/74478229-f022a380-4e7a-11ea-8110-a6e18ddee02e.png)
![Screen Shot 2020-02-13 at 4 01 48 PM](https://user-images.githubusercontent.com/16673934/74478236-f3b62a80-4e7a-11ea-8c3f-256c44808032.png)

- YES, when I tried only entering the partial start date and partial end date, the length was generated correctly. See below: 
![Screen Shot 2020-02-13 at 4 02 24 PM](https://user-images.githubusercontent.com/16673934/74478239-f6188480-4e7a-11ea-89c5-eb2b620ed28d.png)

- YES, the admin list shows the partial date subscription. See below: 
![Screen Shot 2020-02-13 at 4 08 25 PM](https://user-images.githubusercontent.com/16673934/74478311-23fdc900-4e7b-11ea-935f-6981db2c7b68.png)

- NO, when I try to add a reimbursement I get a "Something went wrong" page!

**Comment by clmahoney** [comment]
Even clicking a previous reimbursement brings me to a "Something went wrong" page.

**Comment by rlskoeser** [comment]
@clmahoney whoops! Thanks for catching that, will have a fix for you momentarily.

**Comment by rlskoeser** [comment]
Increasing estimate to 2pt to account for the additional work to update the subscription `clean` method that calculates end date based on human-readable duration and the reimbursement save method to be date precision aware.

**Comment by rlskoeser** [comment]
Ok @clmahoney, please try again now.

**Comment by clmahoney** [comment]
- YES, I am able to add in a partial date reimbursement. 
- YES, the end date generates as the same date as the start of it! 
I added a reimbursement for Pauline Alderman, and it looks good both in admin and on the site: 
![Screen Shot 2020-02-13 at 4 46 43 PM](https://user-images.githubusercontent.com/16673934/74481378-9c1abd80-4e80-11ea-9c1f-6a02e57f5872.png)
and
![Screen Shot 2020-02-13 at 4 47 48 PM](https://user-images.githubusercontent.com/16673934/74481381-9de48100-4e80-11ea-8f68-cf79357d52ba.png)

**Comment by thatbudakguy** [comment]
@clmahoney do reimbursements normally _have_ an end date? I don't see anywhere in the admin to enter one...

**Comment by clmahoney** [comment]
@thatbudakguy no they don't! But since an end date is automatically being generated on the admin side, I thought it would show up on the site too. But I guess it doesn't need to!
