### ISSUE TITLE
Add "FAQ" link to footer/bottom bar on website

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#514]
I think we should have a link to the FAQs in the footer on the website. To maintain symmetry, it could replace "home."

**Comment by rlskoeser** [comment]
@jkotin I think the order in the footer should match the order that the pages are listed on the about page (they will match whenever we are able to implement a menu that is generated from the wagtail pages). You can re-order the pages in wagtail; please let us know if the order in the footer should be revised.

**Comment by jkotin** [comment]
I agree. I reordered in Wagtail as:

Contact Us
FAQs
Data Export
Technical
How to Cite
Credits

That order just seems most intuitive to me.  I'd be happy to defer if someone has a better order to suggest.

Question: would it be possible to combine two categories in the right column to get 5:5 symmetry? (Or add something for 6:6.) I don't think so, but I thought I would ask.

**Comment by thatbudakguy** [comment]
one possibility for combining two in the right column is taking the approach we did on derrida and merging "How to Cite" with "Data Export" ([the `cite/` page](https://derridas-margins.princeton.edu/cite/) has a link to download datasets).

**Comment by thatbudakguy** [comment]
i could also see grouping "Data Export" with "Technical".

**Comment by jkotin** [comment]
I'm happy with either of these solutions and like them both better than the status quo.

**Comment by rlskoeser** [comment]
Putting the datasets on the Cite page for Derrida is because we didn't plan for anywhere else and I needed somewhere to put them. I think it's valuable to make it more visible - it doesn't seem obvious to me that it would be on either of the other pages.

Another option is to add "Home" back at the top of the left column.

I don't know how much it matters to have them match, although I agree it does look nicer.

@gissoo any comments on the footer menus?

**Comment by clmahoney** [comment]
- YES, I see the FAQ link at the footer of the landing page: 
![Screen Shot 2020-02-13 at 1 56 03 PM](https://user-images.githubusercontent.com/16673934/74468324-a8931c00-4e68-11ea-8d07-6a2fc37072c7.png)

**Comment by thatbudakguy** [comment]
I think adding "home" back is probably the least amount of intervention, since everyone will know what it means and people might not _always_ know that clicking shakespeare (in the top menu or in the footer) will take them home. I'm fine with adding that back in.

**Comment by gissoo** [comment]
@rlskoeser I agree with having "home" there for now. The order that @jkotin is proposing here: Contact Us
FAQs
Data Export
Technical
How to Cite
Credits 

does not match the order it is in on the "About" page. 

Sure, adding "Home" is fine.

**Comment by rlskoeser** [comment]
Thanks for responding @gissoo. When I checked, I saw that Josh had updated the order of the About pages on the test site, not in production (which seems fine for now, that can happen later).

I don't know if we need a deploy note or asana task to update the order in production when this deploy goes out....

**Comment by jkotin** [comment]
I agree about adding home.  I'll close the issue.
