### ISSUE TITLE
Unsuppress blank card images in card image gallery and detail views

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#515]
## Notes for testing
Test as an anonymous user (not logged in), since image suppression was previously overridden for logged in users.
- blank card images should be visible on member card list thumbnail view
- blank card images should be visible when paging through member cards
- cards with unknown dates should not be labeled as 'Unknown'

--- 

## dev notes
Also remove "unknown" label for cards with no known dates

**Comment by clmahoney** [comment]
Desktop: I checked Alderman, de Alvear, Baltrusaitis
- YES, blank card images are visible on member card list thumbnail view
- YES, I am able to page through member cards and see the blank pages
- YES, cards with unknown dates or blank cards are not labeled as "Unknown" anymore

**Comment by clmahoney** [comment]
Mobile: I checked Stein (who has some unknown dates)
- YES, blank card images are visible on member card list thumbnail view
- YES, I am able to page through member cards and see the blank pages
- YES, cards with unknown dates or blank cards are not labeled as "Unknown" anymore
Ex: Gertrude Stein: 
![Image from iOS (12)](https://user-images.githubusercontent.com/16673934/74387620-05d69100-4dc7-11ea-953f-77eb56890a10.png)

**Comment by jkotin** [comment]
This works as designed on desktop. Ideally, cards with unknown dates (such as Stein's) should be labelled "Unknown." Blank cards should not be labelled "Unknown."

**Comment by rlskoeser** [comment]
@jkotin what's the value of not labeling blank cards as "Unknown" ? It would be simpler if they were all Unknown, although I talked to @gissoo and she helped me understand the difference in Stein's case.

FYI, I do still require a label for the individual detail page - I have to have something to go in the breadcrumb and something in the page title. I'm still using "Unknown" there in the absence of something else to put.

**Comment by jkotin** [comment]
@rlskoeser the dates on the blank cards aren't unknown -- they just don't have dates. (One could argue that they technically have dates: the date on the reverse side of each card.) To label the blanks unknown would be a mistake. If necessary, we can not label the blanks and the unknowns -- that's preferable to me than labelling the blanks.

**Comment by rlskoeser** [comment]
@jkotin what label do you suggest on the detail page instead of unknown? Is "Blank" ok? (And will it always be accurate?)

**Comment by jkotin** [comment]
@rlskoeser re: breadcrumb -- "Blank" or " - " or the date of the other side of the card.

**Comment by jkotin** [comment]
@rlskoeser re: label on the detail page -- where will that label go?  Is it something other than then breadcrumb?

**Comment by rlskoeser** [comment]
@jkotin the only place it's visible on the page is in the breadcrumb, but it's also used for the page title - so it will show in browser title bar, browser history, and search engine results.

Differentiating blank/unknown seems like a good solution.

**Comment by rlskoeser** [comment]
@jkotin @clmahoney  updated the test site to differentiate blank/unknown cards.

**Comment by jkotin** [comment]
This looks good.  Some cards escape the logic -- i.e. cards with dates, but no events.  E.g. Alexandre shows up as a blank:

https://test-shakespeareandco.cdh.princeton.edu/members/alexandre/cards

If there's an easy fix, great.  If not, I'm happy to close the issue.

**Comment by rlskoeser** [comment]
Right, I thought there might be cases like that. There's nothing in the database to tell me it's not blank, so no easy fix in the code.

The logic is dependent on the footnotes associated with cards, so if there was a meaningful/appropriate place to associate a footnote with this card, I think the label would change (for current logic, it has to have a footnote with an event to get a date, but any footnote would make it "unknown" instead of "blank").

**Comment by jkotin** [comment]
@rlskoeser @clmahoney @i-davis Makes sense. For Alexandre, shouldn't there be an event?  A membership on 11/26/35 for 1 v. 1 m.?  Is the event in the logbooks?  Cate or Ian, would you add the event in the database?
