### ISSUE TITLE
Remove cards from navigation menus

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#516]
## notes for testing
- "Cards" should not be listed in the main navigation menu
- "Cards" should not be listed in the footer navigation menu
Note that "Home" has been removed from the footer nav and the project logo in the footer has been made clickable as a replacement;
Note also that FAQ has been added as requested in  #514

---  
- [x] remove cards from main nav
- [x] remove cards from footer nav
- [x] remove home from footer nav
- [x] make s&co logo in footer a link to the homepage
- [x] adjust footer nav alignment/styles if needed (looks like the link lists may need to be top-align instead of centered vertically; noticeable when the two lists aren't the same size)

**Comment by rlskoeser** [comment]
Let's go ahead and add the FAQ to the footer at the same time - I don't expect that will be much additional work. #514

**Comment by clmahoney** [comment]
Desktop: 
- YES, "Cards" no longer appears on the main menu: 
![Screen Shot 2020-02-12 at 5 39 57 PM](https://user-images.githubusercontent.com/16673934/74384304-f8b5a400-4dbe-11ea-936a-ca6b1085309a.png)
- YES, "Cards" no longer appears on the Footer navigation, and I see F.A.Q. there now too: 
![Screen Shot 2020-02-12 at 5 39 49 PM](https://user-images.githubusercontent.com/16673934/74384362-14b94580-4dbf-11ea-94ba-b70533e0c87d.png)
- YES, I see that "Home" is gone from the footer navigation, and the S&Co logo in the middle of the footer is clickable. I went to the other pages, like members, then scrolled to the very bottom and clicked on the logo and it took me back to the landing page.

**Comment by clmahoney** [comment]
Mobile: 
- YES, "cards" is no longer in the footer:
![IMG_1400](https://user-images.githubusercontent.com/16673934/74384956-6ca47c00-4dc0-11ea-9c19-2fdc274ab41a.PNG)
- YES, "cards" is no longer on the main menu
![IMG_1399](https://user-images.githubusercontent.com/16673934/74384959-6d3d1280-4dc0-11ea-8a68-e8212c21b83e.PNG)
- YES, I am able to click the S&Co logo at the footer and it takes me back to the landing page

**Comment by clmahoney** [comment]
@jkotin this all looks good to me and I'm going to close!
