### ISSUE TITLE
As a user viewing borrowing activities for a single library member, I want to see issue number and date or volume number when known so I have better information about the item.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#519]
## testing notes
Look at the borrowing activity table for a few members who have events linked to a known issue or volume — the issue/volume information should be displayed under the work title and should match [the styles in Zeplin](https://zpl.io/V0DlB3w).

**Comment by rlskoeser** [comment]
We'll need to know what exactly should be displayed and some examples of each.

**Comment by rlskoeser** [comment]
Downgrading to 1pt since we're able to take advantage of previous work for displaying issue/volume information.

**Comment by clmahoney** [comment]
- YES, if I go to the member borrowing activity page for a member that has borrowed either a multivol book or a periodical with issue noted, I DO see the volume or issue under the main text title. Tried with Rolland, who borrowed a couple of the Pilgrimage books: 
![Screen Shot 2020-05-06 at 10 58 54 PM](https://user-images.githubusercontent.com/16673934/81249858-b088d500-8fed-11ea-840b-2dbf8a680228.png)
and with de Montalk who borrowed a couple issues of transition: 
![Screen Shot 2020-05-06 at 11 01 15 PM](https://user-images.githubusercontent.com/16673934/81249875-bd0d2d80-8fed-11ea-873a-0ff8eabf481d.png)
