### ISSUE TITLE
As a content editor, I want subscription event fields relabeled and ordered as they occur in the logbook so that I can add new subscriptions more efficiently.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#52]
Also including some other improvements to the admin interface not strictly related to field order.
* [x] modification should be renamed to "type"; label the default as "subscription" to make it clear (fine to still store as blank in db); add an "other" option to indicate unknown things, e.g. "extended" - let's go ahead and rename model fields to match the changes to names
* [x] rename type to category and add help text to the effect that it is a code to indicate the kind of subscription
* [x] end date logic improvements handled in #47 
* [x] re-order fields to match the order they typically occur in the logbooks:
  * date, type (previously modification), category (previously type), duration, volume, deposit, then currency
* [x] currency for all events should default to Franc - see #58

**Comment by rlskoeser** [comment]
Slightly more complicated than expected because of the need to update other code.  Increasing point estimate from 2 to 3.

**Comment by elspethgreen** [comment]
@clmahoney would you mind taking a look at this?  Is it easier to enter the subscription events now?

**Comment by clmahoney** [comment]
It is but I think we need VOLUME to go before DURATION.

**Comment by rlskoeser** [comment]
@clmahoney thanks for letting me know - I had a couple of versions of the order in my notes.  I'll be glad to switch that.

**Comment by clmahoney** [comment]
Yes this looks great!
