### ISSUE TITLE
As a user viewing an individual work, I want to see a list of known issues (for periodical) or volumes (for multivolume works) so that I have more details about what items circulated.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#520]
# testing notes
Look at the bibliography pages for a few different works to check. Ignore the styles, just check what content is displayed.
- work with no editions should not display volumes/issues section
- work with editions associated should list them; I suggest comparing the works that are in the design, since they cover a range of possibilities

## design links
[desktop](https://zpl.io/VQ8ZRw5) / [tablet](https://zpl.io/2Z1ZDlw) / [mobile](https://zpl.io/a84r954)

# dev notes

Book detail page should include a list of known issues and volumes. Does not need to include citation information for the issues and volumes, just a brief listing that would help identify them. Should be sorted by date or volume.

- [x] method on edition to output display format as html
- [x] method on edition to output display format as string
- [x] add list of editions to book bibliography page

@rlskoeser suggests adding a method to `Edition` that aggregates all of the display properties (volume, number, season, year, title) into an html block, and a corresponding one that returns that with `strip_tags` applied as a plaintext version. we can use `format_html` (instead of `mark_safe`) for this. the plaintext version will be added to the event export for #540.

**Comment by clmahoney** [comment]
@rlskoeser sorry, but can you clarify where I should find this? Right now I'm searching in the book field on the test site, but when I look up the example texts Gissoo used for design, I see this unfinished version: 
![Screen Shot 2020-03-21 at 8 35 08 AM](https://user-images.githubusercontent.com/16673934/77226468-f6c5ca00-6b4e-11ea-9c2f-0ae4aecf7669.png)
- is that what you meant by ignore the style?

**Comment by clmahoney** [comment]
- If so, then yes, right now I see that IF there is volume/issue information, it IS displayed. Works without that info just have pub dates displayed.
