### ISSUE TITLE
Revise the design of the "Borrowing Activities" to include issue, date or volume number of an item when available 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#521]

**Comment by gissoo** [comment]
@jkotin @clmahoney Here are the designs for this issue:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e616b4f8d37001375528b45)

Please let me know what you think. (Also, the design for tablet will be extremely similar to the desktop, therefore I have not done them yet, because I want you to see these first in case I need to make multiple revisions) 

The intention for them to be grey here is for easier readability and to be able to easily see the important information is the title of the work – the info here is less significant than on the circulation tab

**Comment by jkotin** [comment]
I like the grey a lot.  My  questions: why are there sometimes two dates under the end date?  (I like it best when the start date and the end date align.) What does the "not MVP" refer to on the mobile designs?  Can we change "borrowing activities" in the breadcrumbs to "activities"?

**Comment by gissoo** [comment]
@jkotin Thanks for catching the double end dates, it was a mistake I made while shifting pieces of the layout. I've fixed them now. 
The "not MVP" refers to the downward arrow which is for the feature that intended to expand the containers so they show more information only when the user wants to see more (in this case it's the "publication date" field – which according to the usability testing proved to be not as important on this page). So in MVP all the content will be shown to the user. Thanks for asking! I had forgotten to include the "publication date" field on these pages, they are now revised and you can see them through the link above.

**Comment by jkotin** [comment]
Excellent.

Should the "publication date" on mobile be in bold? Makes it seem like it's the most important information.  If we keep it bold, can we also bold title and author?

**Comment by gissoo** [comment]
@jkotin I was having the same thought yesterday as I submitted the revision. Since it's not an expandable container anymore and the user will be seeing the "Publication Date" field by default I think it should **not** be bold. However, I do not agree with making other fields bold, because that tends to be even more inconsistent and unnecessary here. I have revised the designs and have made the "Publication Date" back to regular weight and increased the distance of this field from the rest of the fields in the container. You can see it through the link above again. (I have also revised the breadcrumbs here).

**Comment by gissoo** [comment]
@jkotin In addition to the variations I had uploaded, which are still accessible through the link above, I have now uploaded the tablet version as well. Pasting links here if you would like to take a look.

Tablet: 
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cc216ebf11a741010f260d6)
Scrolled:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e6a61b342ad8b177aa0d49c)

Desktop:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cc1d1bb7cbe272d01d28b1e)
Scrolled:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e6a61b3832f4b12e2c94dc1)

Mobile:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e6a61b299f89b1879508e78)
Scrolled:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e6a61b35cab5716d471d6c3)
