### ISSUE TITLE
As a user, I want to see event labels for non-standard book events in the borrowing activity table and event data download so I know what the data represents.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#522]
## notes for testing
- Use the admin search to find an example for each of these notations, and then check how that event appears on the following pages. (It should display the term provided below)
   - member borrowing activity page
   - member card detail page (table of activities under the card image)
   - circulation table for the associated book
- Check the updated [test event export](https://drive.google.com/drive/u/0/folders/1ROaP4hCkG0OtLUdnYKoaJFjiDdzHFyyK) to see that events with these codes in the private notes use the specified label instead of "generic"

----
Non-standard book events are already listed in the borrowing activity table, they just don't get an activity label.

Use these codes in the notes to label the events:
* NOTATION: LOAN -- "Loan"
* NOTATION: SBGIFT -- "Gift"
* NOTATION: BOUGHTFOR -- "Purchase"
* NOTATION: SOLDFOR -- "Purchase"
* NOTATION: REQUEST -- "Request"
* STRIKETHRU -- "Crossed out"

**Comment by rlskoeser** [comment]
@jkotin @clmahoney if you all can provide a list of the labels you'd like to use in the public interface and data exports based on notation @i-davis came up with and documented for standard events, we can implement this fairly easily. 

From my perspective, it's fine if not every event has an activity type.

We'll need short labels to fit in the table (similar to borrow and purchase); maybe this is another candidate for an FAQ entry (or eventually an Analysis essay?) to provide more details about these other kinds of events.

**Comment by rlskoeser** [comment]
1pt estimate is based on the assumption of a simple lookup list for notations and display labels.

**Comment by jkotin** [comment]
There are 11 non-standard event labels listed here:

https://docs.google.com/document/d/1HuB7eQKqcWNlEJwf4jvHHxsz8VvE-AhCCJ-s2ZYTVP8/edit

From these 11, I think 5 should be used to generate labels on the front end:

Loan (from NOTATION: LOAN)
Gift (from NOTATION: SBGIFT)
Request (from NOTATION: REQUEST)
Equivocal (from noteEQUIVEXCHANGE
Equivocal (from ITEMLIST)

I'm not happy with "Equivocal" as a term, but I can't think of a better term at the moment.  (Do you have any ideas?) From the remaining 6 terms, I think we can just ignore 3:

NOTATION: LATERETURN
NOTATION
NOTATION: PERSONREF

That leaves 3, 2 of which I'd like to use in public notes:

NOTATION: BOUGHTFOR
NOTATION: SOLDFOR

That leaves 1: STRIKETHRU. We could also include that in public notes. But perhaps we should discuss at a meeting.

**Comment by jkotin** [comment]
@rlskoeser a question before I revise this info. Might we use the field for periodical/volume number to note "bought for x" or "sold for y"?  No worries if not -- but I thought the decision today to make the field non-numerical might make it more flexible.

**Comment by rlskoeser** [comment]
@jkotin I don't think it fits there - that allows us to provide extra information about a particular issue or volume of a book (and has multiple fields, but I don't think any of them make sense here), this is extra data about an event.

**Comment by jkotin** [comment]
Makes sense to me.  So this is what I think we should do:

NOTATION: LOAN -- leads to label "Loan"
NOTATION: SBGIFT -- leads to label "Gift"
NOTATION: BOUGHTFOR -- leads to label "Purchase"
NOTATION: SOLDFOR -- leads to label "Purchase"
EQUIVEXCHANGE -- no label
ITEMLIST -- no label
NOTATION: LATERETURN -- no label
NOTATION -- no label
NOTATION: PERSONREF -- no label

That leaves two non-standard events, which are actually more like non-events:

NOTATION: REQUEST
STRIKETHRU

I'd like to discuss these at a meeting, if possible.  There are 11 requests (a member requests a book) and 32 strikethroughs. I'm not sure how we should handle non-events!!

**Comment by rlskoeser** [comment]
@jkotin I'm not following what you mean about a request being a non-event; it seems potentially interesting since it presumably indicates a member was interested in a book. It is also a familiar interaction people have with libraries now. We could just label it as "Request" (I would say "Requested" but the other labels are present tense).

The strike throughs seem more problematic; do we know what it indicates? I'm not certain "non-events" should be in the database; what does it get us?

**Comment by jkotin** [comment]
I agree with above re: what's interesting. I'm thinking about how we use the database to track the circulation of books.  A request doesn't necessarily involve an actual, physical book.

Using the label "request" is probably the best solution. If we are making lists of the most frequently circulating books or periodicals we can manually subtract the requests. There are only 11.

Strikethroughs present a similar metaphysical problem!  I'll ask Ian to develop a list of strikethrough scenarios.

**Comment by rlskoeser** [comment]
If we're talking about "circulation" maybe we should only include borrowing activity... I'm not sure how much the purchases and other book activities make sense for that (although that conversation doesn't really belong here).

**Comment by rlskoeser** [comment]
When this is implemented, the event data download should also include the new event types.

**Comment by rlskoeser** [comment]
@jkotin based on your comments, I made a list of notations that should have labels in the issue description — would you review and confirm that these are correct?

**Comment by jkotin** [comment]
The list looks great. Do we want to include "strikethru" as well?  The term could be "crossed out." I still can't tell whether including the strikethrus makes sense or not.  I'm happy to follow your lead here.

**Comment by rlskoeser** [comment]
@jkotin happy to include it — I don't have a good sense of how meaningful it will be to people (do we even know what it means?), but including it allows us to share more information.

**Comment by jkotin** [comment]
Sounds good, thank you @rlskoeser . I think the strikethru means that either 1/ the member changed their mind about the book and didn't take it out, or 2/ the clerk wrote down the wrong title. I agree with should include it.  "Crossed out" is probably the best phrase to use on the front end.

**Comment by rlskoeser** [comment]
@jkotin great. I added it to the list.

**Comment by rlskoeser** [comment]
@jkotin do these notations take precedence over the base event type? I had assumed they were being used to clarify generic events, but I was looking for some examples to test and found a borrow that has the "SBGIFT" notation — do I display "Borrow" or "Gift" ?

**Comment by jkotin** [comment]
Notation takes precedence. But would it be possible to create a list of conflicts so Ian and I can investigate?

**Comment by rlskoeser** [comment]
@jkotin @i-davis sure, here's a list. Looks like they are all borrows and most of them are crossed out.

Is there any difference between `NOTATION: STRIKETHRU` and `STRIKETHRU` ? I see three instances of the first, 294 of the second.

Here's a quick report of non-generics with a nonstandard type (account, event, event type, new event label)

Account #4815: Denis Duperley, Event for account #4815 ??/1961-08-08, Borrow, Loan
Account #9: Madeleine Rolland, Event for account #9 1920-02-16/1920-02-20, Borrow, Crossed out
Account #179: Mr. Morgan, Event for account #179 1921-01-31/1921-02-05, Borrow, Crossed out
Account #9: Madeleine Rolland, Event for account #9 1921-02-11/1921-02-14, Borrow, Crossed out
Account #25: Raymonde Linossier, Event for account #25 1921-04-08/??, Borrow, Crossed out
Account #141: Edmond Renoir, Event for account #141 1921-07-05/1921-09-09, Borrow, Crossed out
Account #409: John Varney, Event for account #409 1921-09-22/??, Borrow, Crossed out
Account #569: Guy de Pourtales, Event for account #569 1922-03-29/1922-06-07, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1922-11-20/1922-11-29, Borrow, Crossed out
Account #755: M. Rieder, Event for account #755 1923-02-03/1923-03-03, Borrow, Crossed out
Account #875: Mlle Valerio, Event for account #875 1923-09-18/1923-09-27, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1923-12-09/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1924-01-14/1924-01-18, Borrow, Crossed out
Account #7148: Lucia Joyce, Event for account #7148 1924-01-28/1924-04-14, Borrow, Crossed out
Account #1146: Mary (Wharton) Vielé / Mrs. H.K. Vielé / Mrs. Vielé Griffin, Event for account #1146 1924-04-05/1924-05-01, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1924-04-05/1924-04-11, Borrow, Crossed out
Account #875: Mlle Valerio, Event for account #875 1924-06-27/1924-07-15, Borrow, Crossed out
Account #875: Mlle Valerio, Event for account #875 1924-11-19/1924-11-20, Borrow, Crossed out
Account #131: Mme France Raphael, Event for account #131 1924-12-16/1924-12-19, Borrow, Crossed out
Account #1434: Anatole Rivoallan, Event for account #1434 1925-04-04/1925-05-28, Borrow, Crossed out
Account #131: Mme France Raphael, Event for account #131 1925-04-30/1925-05-08, Borrow, Crossed out
Account #1670: Mabel Schirmer / Mrs. Robert Schirmer, Event for account #1670 1925-10-06/1925-11-24, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1925-10-20/1925-11-04, Borrow, Crossed out
Account #1813: Jeanne Fournier, Event for account #1813 1925-11-26/??, Borrow, Crossed out
Account #533: Ernest Hemingway, Event for account #533 1926-01-28/1926-02-02, Borrow, Crossed out
Account #1813: Jeanne Fournier, Event for account #1813 1926-03-19/??, Borrow, Crossed out
Account #49: G. Violette, Event for account #49 1927-05-25/1927-06-04, Borrow, Crossed out
Account #4821: Max Eastman, Event for account #4821 1927-11-07/??, Borrow, Gift
Account #1813: Jeanne Fournier, Event for account #1813 1928-12-20/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-04-19/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-04-19/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-05-03/1929-05-09, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-05-28/??, Borrow, Crossed out
Account #1645: Bravig Imbs, Event for account #1645 1929-05-30/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-07-20/1929-07-22, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-09-11/1929-09-13, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-09-11/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1929-09-11/??, Borrow, Crossed out
Account #1434: Anatole Rivoallan, Event for account #1434 1929-09-24/1929-10-30, Borrow, Crossed out
Account #5006: Lady Pringle, Event for account #5006 1931-02-27/1931-02-28, Borrow, Crossed out
Account #5033: Selden Rodman, Event for account #5033 1932, Purchase, Gift
Account #814: Alice M. Killen, Event for account #814 1932-02-01/1932-02-05, Borrow, Crossed out
Account #1684: Sarah Pressly Watson / Miss S. P. Watson, Event for account #1684 1932-12-12/1932-12-24, Borrow, Crossed out
Account #4828: Frédéric Engel, Event for account #4828 1933-03-11/1933-03-17, Borrow, Crossed out
Account #120: Fernand Colens, Event for account #120 1933-05-20/??, Borrow, Crossed out
Account #120: Fernand Colens, Event for account #120 1933-06-25/??, Borrow, Crossed out
Account #120: Fernand Colens, Event for account #120 1933-11-19/??, Borrow, Crossed out
Account #4772: Theresa (Shiff) Clairin, Event for account #4772 1933-12-05/??, Borrow, Crossed out
Account #4772: Theresa (Shiff) Clairin, Event for account #4772 1934-01-05/??, Borrow, Crossed out
Account #120: Fernand Colens, Event for account #120 1934-02-10/??, Borrow, Crossed out
Account #4724: Miss Boulenger / Mme Bidoire, Event for account #4724 1934-03-18/??, Borrow, Crossed out
Account #5057: Dorothy Shelley, Event for account #5057 1934-04-10/1934-04-20, Borrow, Crossed out
Account #5057: Dorothy Shelley, Event for account #5057 1934-08-21/1934-09-04, Borrow, Crossed out
Account #120: Fernand Colens, Event for account #120 1934-10-03, Purchase, Crossed out
Account #4724: Miss Boulenger / Mme Bidoire, Event for account #4724 1934-12-17/??, Borrow, Crossed out
Account #5027: Fanny Rirachowsky, Event for account #5027 1935-02-11/1935-04-08, Borrow, Crossed out
Account #4731: Claude Bourdet, Event for account #4731 1935-05-17/??, Borrow, Crossed out
Account #39: Maud Burt, Event for account #39 1935-06-15/??, Borrow, Crossed out
Account #120: Fernand Colens, Event for account #120 1936-01-29/??, Borrow, Crossed out
Account #4773: Agnes Claudius, Event for account #4773 1936-01-31/??, Borrow, Crossed out
Account #5058: Marcelle Sibon, Event for account #5058 1936-02-08/1936-02-22, Borrow, Crossed out
Account #4723: Françoise Bernheim, Event for account #4723 1936-02-12/1936-03-07, Borrow, Crossed out
Account #4730: Louise Olga Bouniols, Event for account #4730 1936-03-09/??, Borrow, Crossed out
Account #131: Mme France Raphael, Event for account #131 1936-04-24/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1936-05-20/1936-05-28, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1936-06-17/1936-06-23, Borrow, Crossed out
Account #497: E. C. Venable, Event for account #497 1936-07-01/1936-07-03, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1936-12-02/1936-12-03, Borrow, Crossed out
Account #4773: Agnes Claudius, Event for account #4773 1936-12-03/??, Borrow, Crossed out
Account #5113: Mrs. Gordon Waterfield, Event for account #5113 1936-12-31/1937-01-07, Borrow, Crossed out
Account #5113: Mrs. Gordon Waterfield, Event for account #5113 1937-02-26/1937-03-04, Borrow, Crossed out
Account #5071: Emma Swan, Event for account #5071 1937-09-10/1937-09-24, Borrow, Crossed out
Account #4939: A. W. Massey, Event for account #4939 1937-10-29, Purchase, Gift
Account #5103: Monique de Vigan, Event for account #5103 1938-01-04/1938-01-13, Borrow, Crossed out
Account #4854: Paul Gerbault, Event for account #4854 1938-01-19/??, Borrow, Crossed out
Account #39: Maud Burt, Event for account #39 1938-04-30/??, Borrow, Crossed out
Account #5103: Monique de Vigan, Event for account #5103 1938-05-02/1938-05-11, Borrow, Crossed out
Account #3727: Nguyen Minh Truyel, Event for account #3727 1938-05-11/1938-05-14, Borrow, Crossed out
Account #4920: Pierre Leyris, Event for account #4920 1938-05-11/1938-05-30, Borrow, Crossed out
Account #7067: Vincens, Event for account #7067 1938-05-11/1938-05-16, Borrow, Crossed out
Account #7067: Vincens, Event for account #7067 1938-05-11/1938-05-16, Borrow, Crossed out
Account #5135: Catherine Yarrow, Event for account #5135 1938-06-07/1938-07-09, Borrow, Crossed out
Account #5135: Catherine Yarrow, Event for account #5135 1938-06-07/1938-07-09, Borrow, Crossed out
Account #7069: Mattos, Event for account #7069 1938-07-22/1938-07-29, Borrow, Crossed out
Account #4770: Pierre Citron, Event for account #4770 1938-12-07/??, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1939-01-12/1939-01-13, Borrow, Crossed out
Account #5479: Étienne Coche de la Ferté, Event for account #5479 1939-03-04, Purchase, Gift
Account #4714: Mrs. Thornton Baker, Event for account #4714 1939-03-08/??, Borrow, Crossed out
Account #4714: Mrs. Thornton Baker, Event for account #4714 1939-03-08/??, Borrow, Crossed out
Account #5113: Mrs. Gordon Waterfield, Event for account #5113 1939-03-23/1939-03-28, Borrow, Crossed out
Account #5097: H. S. Vandel, Event for account #5097 1939-05-11/1939-05-19, Borrow, Crossed out
Account #5097: H. S. Vandel, Event for account #5097 1939-05-19/1939-06-11, Borrow, Crossed out
Account #539: John d'Arcy Clark, Event for account #539 1939-06-09/??, Borrow, Crossed out
Account #5097: H. S. Vandel, Event for account #5097 1939-06-14/1939-06-26, Borrow, Crossed out
Account #5097: H. S. Vandel, Event for account #5097 1939-06-26/1939-07-12, Borrow, Crossed out
Account #814: Alice M. Killen, Event for account #814 1939-12-28/1939-12-30, Borrow, Crossed out
Account #2165: Caroline Shelton, Event for account #2165 1939-12-29/1940-01-15, Borrow, Crossed out
Account #5070: Monica Stirling, Event for account #5070 1940-01-13/1940-01-15, Borrow, Crossed out
Account #5070: Monica Stirling, Event for account #5070 1940-02-06/1940-02-08, Borrow, Crossed out
Account #39: Maud Burt, Event for account #39 1940-02-07/??, Borrow, Crossed out
Account #39: Maud Burt, Event for account #39 1940-02-07/??, Borrow, Crossed out
Account #39: Maud Burt, Event for account #39 1940-02-07/??, Borrow, Crossed out
Account #5070: Monica Stirling, Event for account #5070 1940-06-04/1940-06-06, Borrow, Crossed out
Account #4759: Marcel Chambaz, Event for account #4759 1940-08-21/??, Borrow, Crossed out
Account #5103: Monique de Vigan, Event for account #5103 1941-07-24/1941-09-29, Borrow, Crossed out
Account #5103: Monique de Vigan, Event for account #5103 1941-08-05/1941-09-29, Borrow, Crossed out
Account #5103: Monique de Vigan, Event for account #5103 1941-08-24/1941-10-02, Borrow, Crossed out
Account #131: Mme France Raphael, Event for account #131 1941-09-08/1941-09-13, Borrow, Crossed out
Account #313: Commandant des Francs, Event for account #313 1941-10-24/??, Borrow, Crossed out
Account #5103: Monique de Vigan, Event for account #5103 1942-03-25/1942-05-22, Borrow, Crossed out
Account #4843: Marguerite Focillon, Event for account #4843 1961-01-24/??, Borrow, Crossed out

**Comment by jkotin** [comment]
Thank you @rlskoeser -- @i-davis would you look through this issue and report back about 1/ non-generic events with non-standard type events, and 2/ the difference between the two strikethrus?

**Comment by i-davis** [comment]
@jkotin @rlskoeser : 1/ Happy to! Will do that this afternoon. 2/ I'm not sure if I'm looking at the same NOTATION: STRIKETHRU as you, @rlskoeser. I see 23 instances of STRIKETHRU and NOTATION being together in the notes (I just went to "Events" and searched for both of the terms), and it's always when a strikethrough is accompanied by a note about something. Am I looking in the right place?

**Comment by rlskoeser** [comment]
@i-davis I may not have looked carefully enough! I thought there were a small number of records that had 'NOTATION: STRIKETHRU' as a single string — but it sounds like you are confirming, it is correct for me to be looking for just the text 'STRIKETHRU'.

**Comment by i-davis** [comment]
@jkotin @rlskoeser : Okay, so, here are my thoughts:

1. The crossed outs could all stay the same. Or we could change the ones that have no return dates to general events. I think the ones that have return dates were actual borrows, and were crossed out afterward for some reason. The ones that have no return dates were likely not borrows: they were what @jkotin describes above, events where members started to borrow a book and decided on a different one. If you two think we should make that change, I'd be happy to double check this hypothesis. But what would you two do?

2. Calling the Duperley loan a "Loan" and the Eastman, Rodman, Massey, Coche de la Ferté gifts "Gift" would be great, I think! None are borrows, technically. I think those are the only ones that aren't crossed outs, right, @rlskoeser?

**Comment by i-davis** [comment]
@rlskoeser : I trust you more than me! I really might just be looking in the wrong way! But if I'm not then yeah, I don't think NOTATION: STRIKETHRU means a particular type of strikethrough.

**Comment by rlskoeser** [comment]
@i-davis on point 2) I think you're correct, and to me it would make the most sense to remove the borrow events and create generic events for the loans and gifts.

For point 1) I don't think I know enough to comment here; there are actual borrows without return dates too. I don't think we have a compelling reason to revisit all the crossed out borrows and convert them to generics right now.

**Comment by i-davis** [comment]
@rlskoeser : cool, re point 2; and good point, re point 1! That makes sense to me.

**Comment by jkotin** [comment]
Thank you both!  @i-davis would you do 2, i.e. change the borrow events to generic events for loans and gifts?

**Comment by i-davis** [comment]
@jkotin @rlskoeser : okay I fixed them all, except for the Rodman and Massey, which I found out were mistakenly labeled as gifts (deleted that tag!).

**Comment by clmahoney** [comment]
- YES, the "Loan" notation works. Checked "The Quintessence of Ibsenism" loaned to James Joyce. See activity page: 

![Screen Shot 2020-05-28 at 5 33 21 PM](https://user-images.githubusercontent.com/16673934/83196286-a13b0a00-a109-11ea-92c7-0fc353a33ad0.png)

Card page: 

![Screen Shot 2020-05-28 at 5 33 45 PM](https://user-images.githubusercontent.com/16673934/83196291-a5672780-a109-11ea-90af-1170558bebc1.png)

and Circulation page of book: 
![Screen Shot 2020-05-28 at 5 33 56 PM](https://user-images.githubusercontent.com/16673934/83196261-984a3880-a109-11ea-9508-ec7767140ad0.png)

**Comment by clmahoney** [comment]
- YES, the "Gift" notation works. Checked SB's gift to Max Eastman of "Bible Lands To-day". 
See borrowing activity: 
![Screen Shot 2020-05-28 at 5 36 41 PM](https://user-images.githubusercontent.com/16673934/83196509-068efb00-a10a-11ea-8818-689add56789a.png)
See individual card page: 
![Screen Shot 2020-05-28 at 5 36 54 PM](https://user-images.githubusercontent.com/16673934/83196529-10b0f980-a10a-11ea-8138-f626fb47dfaa.png)
- See circulation page: 
![Screen Shot 2020-05-28 at 5 37 03 PM](https://user-images.githubusercontent.com/16673934/83196542-16a6da80-a10a-11ea-874c-d4373ce274ae.png)

**Comment by clmahoney** [comment]
- YES, "SOLDFOR" Purchase notation works. Tried with Oldenberger's purchase of "The Still Centre. 
See borrowing activity:
![Screen Shot 2020-05-28 at 5 42 24 PM](https://user-images.githubusercontent.com/16673934/83197025-d4ca6400-a10a-11ea-9892-12af3bf43d21.png)
See individual card page:
![Screen Shot 2020-05-28 at 5 42 52 PM](https://user-images.githubusercontent.com/16673934/83197038-d98f1800-a10a-11ea-9b0c-6f0a7e9eee03.png)
See circulation page: 
![Screen Shot 2020-05-28 at 5 43 05 PM](https://user-images.githubusercontent.com/16673934/83197056-e01d8f80-a10a-11ea-865e-eab09f0120f0.png)

**Comment by clmahoney** [comment]
- YES, "SOLDFOR" Purchase notation works. Tried with Aldington's sold copy of "Familiar Letters on Important Occasions". 
See borrowing activity: 
![Screen Shot 2020-05-28 at 5 46 11 PM](https://user-images.githubusercontent.com/16673934/83197318-4d312500-a10b-11ea-8490-7d36b4fe0f24.png)
See individual card page: 
![Screen Shot 2020-05-28 at 5 46 28 PM](https://user-images.githubusercontent.com/16673934/83197330-528e6f80-a10b-11ea-841f-d42a452764fa.png)
See circulation page:
![Screen Shot 2020-05-28 at 5 46 38 PM](https://user-images.githubusercontent.com/16673934/83197345-57ebba00-a10b-11ea-8b65-cb6263ecf50d.png)

**Comment by clmahoney** [comment]
- YES, "Request" notation works! Tried with Paul le Moal's request of Ulysses. 
See borrowing activity: 
![Screen Shot 2020-05-28 at 5 50 05 PM](https://user-images.githubusercontent.com/16673934/83197660-ce88b780-a10b-11ea-9083-1d96d95fc157.png)
See individual card page:
![Screen Shot 2020-05-28 at 5 50 15 PM](https://user-images.githubusercontent.com/16673934/83197675-d47e9880-a10b-11ea-87c7-d6951c62952e.png)
See circulation page:
![Screen Shot 2020-05-28 at 5 50 23 PM](https://user-images.githubusercontent.com/16673934/83197681-d9434c80-a10b-11ea-9fa4-aaf8f0a86b95.png)

**Comment by clmahoney** [comment]
- YES, "Crossed out" notation works. I tried with Suter's STRIKETHRU of "Nostromo"
See borrowing activity: 
![Screen Shot 2020-05-28 at 5 52 14 PM](https://user-images.githubusercontent.com/16673934/83197823-1dcee800-a10c-11ea-9a78-0f7e1b1082cc.png)
See individual card page: 
![Screen Shot 2020-05-28 at 5 52 27 PM](https://user-images.githubusercontent.com/16673934/83197835-22939c00-a10c-11ea-86ac-1bc79b3993d2.png)
See circulation page:
![Screen Shot 2020-05-28 at 5 52 36 PM](https://user-images.githubusercontent.com/16673934/83197847-29221380-a10c-11ea-86e1-2999cd5fd9e6.png)

**Comment by clmahoney** [comment]
- YES, I checked all of these specific events (listed above) on the Events export, and yes indeed the correct notation is listed, not "generic". 

Can we close? This all looks good to me.

**Comment by jkotin** [comment]
This works great. I'm a little worried about the consistency of the data. But the feature is perfect as far as I can tell!
