### ISSUE TITLE
Revise the design of "Circulation Tab" to include issues and/or volumes that a member borrowed, if known

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#523]

**Comment by gissoo** [comment]
@jkotin @clmahoney Here are the designs for this issue:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e616b82c2788c153b5fe9b1)

Please let me know what you think. (Also, the design for tablet will be extremely similar to the desktop, therefore I have not done them yet, because I want you to see these first in case I need to make multiple revisions) 

Note: The logic for the line breaks here due to some visual design contraints: 
1. Left-most screen: (the same logic as seen on the bib page – vol. info followed by a line break for the title) 
2. Second screen from left: Vol. and no. info followed by a line break for the date **only** **if** the date includes **month**
3. Third screen from left: Vol. and no. info and the year on the same line (no line break because there is no month info here)

**Comment by jkotin** [comment]
These look good. The one thing that strikes me as a potential issue: should we include the book's author/editor on the circulation page?  I think we should. I worry that the title alone won't be meaningful.  There is symmetry between a book and a person, not between a book title and a person. I can't see the design solution for this, other than having a bar with a constant set of information and the tabs below.

**Comment by gissoo** [comment]
@jkotin When you say "There is symmetry between a book and a person, not between a book title and a person.", how do you mean?

**Comment by jkotin** [comment]
@gissoo I'm not quite sure how best to explain my sense of things.  A person's name names a person.  A book title doesn't fully name a book: you also need the author's name.

_Studies in the Psychology of Sex_, by itself, is confusing—I'm not really sure what it is. _Studies in the Psychology of Sex_ by Havelock Ellis makes more sense—it's coherent.

Another way to try to put this: a person is a name, but a book is a title plus an author.

**Comment by gissoo** [comment]
@jkotin Thanks for writing. I understand what you mean. I tried this in a few ways yesterday. I do not think placing it right above the tabs would work or make sense systematically based on what you are saying.  
If the hierarchy/identity of the author is conceptually higher according to what you are saying, it does deserve to be part of the header, which means it would show up on the bibliography, circulation, and cards pages. 

However I'm not quite convinced. Because
1. I believe this can cause some complications. It won't make sense for multi-authored works. It's not quite fair/ethical to list one name. 
2. The author information is technically a metadata, which has a designated spot, the "Bibliography" page, from the user's point of view it won't be expected to be seen everywhere, especially when a tab called "bibliography" is within sight.

**Comment by jkotin** [comment]
Thank you @gissoo -- I see both sides here, and would like to think more about it.  What do @rlskoeser @rgmunson and @thatbudakguy think?  Is there a practical way to do some user testing?  I worry that not everyone will start on the bibliography tab, and thus get confused.

**Comment by thatbudakguy** [comment]
I agree with @gissoo. I think there are comparatively few scenarios in which someone would link directly to the circulation page. In the scenario where this does happen and the person wishes to know the author/editor of the volume, the bibliography tab is an intuitive place to find it. Moreover, finding a way to represent author/editor information directly on the circulation tab does at least one of:
- stretches out already thin space requirements on mobile
- alters the information hierarchy in the way @gissoo mentions

The number of cases in which the author's name is crucial to disambiguate the work is comparatively few; I don't think we should design for such edge cases.

**Comment by rlskoeser** [comment]
I concur with what @gissoo and @thatbudakguy have said about the problems with including the author on the circulation and cards pages. The only scenario I can think of right now where someone would go directly to that page is from a search engine external to our site, and it seems likely if they jump straight into that page and can't find enough information they will browse around a bit to find it, and the bibliography tab and book breadcrumb seem like fairly obvious places to look.

**Comment by gissoo** [comment]
@jkotin Please let us know what you think. I would like to make progress on this issue.

**Comment by jkotin** [comment]
Thank you @gissoo @rlskoeser @thatbudakguy. I'm grateful for your thoughts on this. I'll close now. I can't think of a way to improve the designs -- they are great.  I'm still bothered by the incompleteness of the title by itself, and I think people will link to the circulation/tab more often than the bibliography/tab. (The question I get most frequently from scholars: "how did x circulate?") But I agree that changes will create more problems then they will solve!  Thank you again for your patience.
