### ISSUE TITLE
As a user viewing books, I want to see an indicator if there's a problem with the data and have a way to get more details, so that I know how to interpret the data.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#524]
# testing notes
## info
[design link](https://zpl.io/ad5J0E1) - all screens, all pages

as noted below, there are multiple changes that require testing as a result of this issue; three of them occur on different pages and thus will all have different designs to check. the zeplin link above contains multiple screens that show how the new icon should look across different page and devices.

## steps
1. visit the books search page. enter a query that will bring up a work with UNCERTAINTYICON in its notes (I tested with "Poems").
2. check that the uncertainty icon (blue puzzle piece) displays next to the work in the list, and compare its display on mobile/tablet/desktop against the designs.
3. visit a book detail page for a book with UNCERTAINTYICON in its notes (you can just choose "Poems" from the search, for example).
4. check that the uncertainty icon displays next to the work's public notes, and compare its display on mobile/tablet/desktop against the designs.
5. visit a member's borrowing activity page for a member who borrowed a book with UNCERTAINTYICON in its notes (Gertrude Stein borrowed "?" and it's at the top of her list).
6. check that the uncertainty icon displays next to the work's entry in the table, and compare its display on mobile/tablet/desktop against the designs.
7. while you're here, check also that the titles of each book in this table are now links that go to that book's detail page.

# dev notes
<s>Applies to works with PROBLEM or GENERIC in the notes.</s>
this is keyed exclusively on the presence of the UNCERTAINTYICON tag in the notes.

For works with this tag:
- [x] display problem icon on bibliography page 
- [x] display problem icon on book search
- [x] display problem on individual member borrowing activities
- [x] link titles in borrowing activities to item bibliography page

For all works: display any public notes on the bibliography page, so that the problem can be explained.

**Comment by thatbudakguy** [comment]
in order to support this, we will need to add a `@property` on `Work` that checks for the presence of a keyword in the notes field to determine if it has uncertainty. we also will want to edit the indexed fields for `Work` to index this property as a boolean in solr to support display of the icon on the books search page.

**Comment by clmahoney** [comment]
Why is there a comma after "uncertainly notes"? "Uncertainty notes, can include more information..." Reads awkwardly.

**Comment by clmahoney** [comment]
Desktop: 
- YES, I see the blue puzzle piece. I tried with "Plays" (without an author): 
![Screen Shot 2020-04-08 at 2 19 50 PM](https://user-images.githubusercontent.com/16673934/78819320-0e50df80-79a4-11ea-871a-01d7822bc0cb.png)
- YES, when I click on that same "Plays" text I go the its book detail page and see the uncertainty icon again, this time with a public note: 
![Screen Shot 2020-04-08 at 2 20 47 PM](https://user-images.githubusercontent.com/16673934/78819393-29bbea80-79a4-11ea-8ab5-1e2e4c68cfac.png)
- YES, I went to the borrowing activity page for the member who borrowed "Plays" (Mme Mazon) and saw the uncertainty icon in her list: 
![Screen Shot 2020-04-08 at 2 22 25 PM](https://user-images.githubusercontent.com/16673934/78819631-86b7a080-79a4-11ea-9459-b8900bb58bac.png)
- YES, the titles of all the other books in Mazon's book activity page are linked to their book detail pages!

**Comment by clmahoney** [comment]
Mobile: 
- All behaving here as expected! I can see the puzzle piece on the main search list: 
![92864848_208838827086394_2964323635277332480_n](https://user-images.githubusercontent.com/16673934/78821646-d186e780-79a7-11ea-84ab-ddfb31509a03.png)
- I see it when I click on the book detail page: 
![92530996_536734150587878_5445988518096535552_n](https://user-images.githubusercontent.com/16673934/78821675-d9df2280-79a7-11ea-99df-4df0fcf575a4.png)
- and Yes, I see it on the member's borrowing activity page: 
![92700745_696481757828764_897395260009742336_n](https://user-images.githubusercontent.com/16673934/78821692-e2cff400-79a7-11ea-981f-b4df0be29835.png)

**Comment by clmahoney** [comment]
Tablet: 
- I think all obeys the designs here too! I checked with "C [unclear]" this time: 
- Here it is on the full book list: 
![92540862_262410891550505_8149246105339559936_n](https://user-images.githubusercontent.com/16673934/78823341-85897200-79aa-11ea-9e04-1669a6c8b540.png)
- And the book detail: 
![92532765_706800546793356_2032042091088969728_n](https://user-images.githubusercontent.com/16673934/78823374-92a66100-79aa-11ea-835e-e1e1dfbe538c.png)
- And on the borrowing member's page (France Raphael): 
![92531985_1830331870430512_1198221529700106240_n](https://user-images.githubusercontent.com/16673934/78823407-a05be680-79aa-11ea-8bd0-8cc835a2bff1.png)

**Comment by clmahoney** [comment]
I'll ask Josh to review this!

**Comment by jkotin** [comment]
This all looks great to me and I'm happy to close. I have two comments that are not directly related to this specific issue.

The first concerns the design and connects to something Nick said recently: would it make sense to have the uncertainty notes under a heading "Notes"? The "Notes" heading could be similar to the "Author" heading, and would give more structure to pages with little information. Usually the books with uncertainty notes won't have authors, dates, formats, etc.

The second is definitely out of scope, but I'll create a wishlist enhancement issue if you think it is a good idea. (I'm not sure myself.) Would it make sense to add button that would allow users to delimit books by whether they have an uncertainty icon or not?  I'm thinking that it might be a way to get researchers invested in solving puzzles.

**Comment by rlskoeser** [comment]
@jkotin filtering by uncertainty in the web interface seems a little niche to me... Although I guess if it works both ways and you can also filter to only identified books, that would probably be useful to some researchers (although still definitely wishlist!)  As for encouraging researchers to solve puzzles, I think we should direct them to the data exports for that.

**Comment by jkotin** [comment]
@rlskoeser Thank you for thinking this through with me. I think you're right. Users will be able to search for "unidentified" right?  Might be a nice way to promote the Project over the summer -- create a challenge.

**Comment by rlskoeser** [comment]
Yes, searching for unidentified finds all the records with that term in the public notes.

This sounds like a fun challenge to promote the project, could be fun for social media.
