### ISSUE TITLE
Create an icon to communicate the "Problem"/uncertainties with items and add to the "Borrowing Activities", "Bibliography" and "Book Search results" pages 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#525]
All information will live on the Bibliography page.

**Comment by gissoo** [comment]
@jkotin Please review the designs for the uncertainty icons officially and let me know if there are any issues, otherwise please close the issue or if you have any questions:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e558ff1bb57d361c1d83d85)

**Comment by gissoo** [comment]
@jkotin @rlskoeser 
Here are the revisions based on today's conversations:
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e56ee6ebb57d361c1dffb4d)

**Comment by jkotin** [comment]
I think the icon is too big on the fourth, fifth, and sixth frames.  Otherwise this looks great!

**Comment by gissoo** [comment]
@jkotin thanks for noting. I had a different logic for the icon on that page, but I don't think it makes enough sense (is in contradiction with another logic). I have made the icon the same size everywhere now (screens 4,5,6 now match the others)

Here: 
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e57cd3bb3fc04747909ce11)

**Comment by gissoo** [comment]
@jkotin thanks for noting. I had a different logic for the icon on that page, but I don't think it makes enough sense (is in contradiction with another logic). I have made the icon the same size everywhere now (screens 4,5,6 now match the others)

Here: 
(https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e57cd3bb3fc04747909ce11)

**Comment by jkotin** [comment]
Looks good.  A question: for the non-MVP aspects of the design -- will those be greyed out or will they be absent when the book pages go public?  It would be much better if they were absent.
