### ISSUE TITLE
Draft list of book search fields and relative priority

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#527]
Refer to PUL solr index configuration and look at what fields we have available. Come up with a preliminary list and then share for review/refinement.

**Comment by rlskoeser** [comment]
@jkotin I looked at the Solr configuration for the PUL catalog search. Here are the fields it includes that I think are relevant for us to keep in mind (listed in priority order):
* title
* author 
* subject
* isbn
* description

I propose that we include the following fields in our keyword search for books (listed in priority order):
* author
* title
* editor
* translator
* subjects
* genre
* format
* public notes

I put author first because my sense is that if someone searches on an author like Joyce in this collection they would want to see works *by* him first, not works about him where he is mentioned in the title. (I'm not sure how many cases we have where a name can appear as both a creator and a title word.) Do you agree with this?

Including subjects and genre will require some data work, but seems like they would make the search more interesting.  (FWIW, I think you should be able to clean these up substantially by removing the ones you don't care about, e.g. all the "provenance" and "binding" terms). If we include these in the search they should also be listed on the book detail page - I can't remember if we've discussed that previously. 

I propose including format because it will give you a way to search for periodicals. The only downside is that I don't know how well it will combine with the other search terms - i.e., it might only be effective if you *only* use that search term, since otherwise I think you will get all periodicals and all items that match your other search terms.

The PUL Solr configuration includes unstemmed variants of each field (higher priority) and then stemmed versions, which means that more specific versions of words will be marked as more relevant. I recommend we do the same (probably applies to all fields except format).

**Comment by jkotin** [comment]
@rlskoeser This proposal looks great to me.  I agree about author>title.  Some questions/comments:

1. What about other creator types—editor, illustrator, etc?

2. I think the generic/problematic titles might create interesting scenarios.  For example, we have a generic title, "Paris." I suspect people will search for "Paris" and "Mirrlees" or "Hope Mirrlees."  That generic "Paris" would, ideally, be near the top of the results.  Is there a way to use public notes to make that happen? Another example: we have a problem title ""Agamemnon, Oedipus." Ideally that would show up for searches for Aeschylus or Sophocles.

3. We should talk about the work required to make the subjects and genre useful for searches.

4. Would it be possible/advisable to original language?  E.g. search for "spanish" and find the books originally written in Spanish.

**Comment by rlskoeser** [comment]
1. I don't think the other creator types should be more important than title, if that is what you're asking. I think it would be confusing.
2. A match on the title (like "Paris") should put the result at the top of the search. If you want a record to be findable by search terms not otherwise associated with the record, you should try to include them in the public notes. I think the "Agamemnon, Oedipus." search can also be solved by a public note — and these are some good test cases to keep in mind when you test the relevance ranking on the book search.
3. Do you want exclude or include subject and genre for now? If you think you may want them, I recommend we include now because it might be hard to revisit.We can discuss at an upcoming meeting, but I would like to have an initial answer sooner. This decision also impacts other parts of the site / project, notably book detail/bibliography page and and book data export, and if we include them in the book data export it gives you a deadline for at least a first-pass cleanup of the metadata.
4. We don't include original language anywhere in our book data. (I checked and saw a note in the code that we might add languages in future.) If there are books where this is important you could include it in the public notes.

**Comment by jkotin** [comment]
1. I just wanted to be sure that the other creator types are included. (They aren't on your list.) I definitely agree that they shouldn't be more important than title.

2. Perfect.

3. I would like to include subject and genre. I am wary of the work/judgment involved in choosing from the OCLC list. Maybe we could have a phone meeting about this?

4. Makes sense to me.

**Comment by rlskoeser** [comment]
Thanks for clarifying about other creator types I included editor and translator but forgot illustrator. Do we have any other creator types, or do you expect to add any others? Wondering if I need a catch-all creator field to ensure that any creators are always included in the search.

**Comment by jkotin** [comment]
We also have "preface" and "introduction." A catch all might make sense.

**Comment by rlskoeser** [comment]
@jkotin great, good to know. Do you want any of the creators besides authors to have higher relevance, or can I just use a catchall creator field for all of them?

**Comment by jkotin** [comment]
Catch all creator is fine with me.  So author, title, other creators -- in that order.

**Comment by rlskoeser** [comment]
Decision: exclude subject and genre for now (determined they are not MVP / not 1.0).

**Comment by rlskoeser** [comment]
Documented the agreed upon fields in #226
