### ISSUE TITLE
As a content editor, I want the reimbursement event form simplified so I can efficiently add new events.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#53]
## Notes for testing
- please test the main edit form as well as the inline form on the accounts edit page
- note that the list view field order has been updated to match
- see notes below for a list of the changes we agreed on

## Notes for development
* [x] relabel price to refund on the edit form
* [x] suppress end date on edit form, since this is a single day event (autopopulate end date from start date on save for any event filtering/calculation logic later on)
* [x] set currency default to Franc - see #58 
* [x] reorder fields for consistency with subscription: date, price/refund, currency
* [x] reorder fields in list view for consistency with order on edit form

**Comment by clmahoney** [comment]
This looks good to me!
