### ISSUE TITLE
Navigation at Bottom of Page

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#535]
For wish list—would be useful to be able to go to next page when scrolling through search results.

See "next" here:

<img width="789" alt="Screen Shot 2020-02-13 at 9 10 25 PM" src="https://user-images.githubusercontent.com/12616674/74497025-83bf9880-4eaa-11ea-87ef-3594fafcbbc5.png">

Would be useful to have it here too:

<img width="782" alt="Screen Shot 2020-02-13 at 9 10 38 PM" src="https://user-images.githubusercontent.com/12616674/74497054-9c2fb300-4eaa-11ea-8da4-68a53cd8ca04.png">

**Comment by rlskoeser** [comment]
The next/previous results navigation is "sticky" - it stays at the top of the page once you scroll down past where it displays normally, so it's always visible and bottom nav would be redundant.
