### ISSUE TITLE
As a content editor, I want a person's sort name to autopopulate when I type a single name with no spaces so that I don't have to retype it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#55]
## Notes for testing
Revised February 12: autopopulate logic will only take effect when there are no spaces in the name field.

## Notes for development
Sort name is required, but for all of the one-named people it will be exactly the same.  

I'm hoping we can use django admin autopopulate for this.

**Comment by elspethgreen** [comment]
This seemed like a great idea--but now that I'm working with it, I'm wondering if it could be a source of errors.
I tried adding myself to the personography with my full name, "Elspeth Green" and the sort name (correctly, for what we talked about) autopopulates as "Elspeth Green."  But this isn't correct for a full name is it?  The prompt near the box says it should be Green, Elspeth.

I'm wondering if it would be possible to stop autopopulating if there are more than two strings in the "Name" field.  The record won't save if there isn't a sort name, right?  That way, people would be forced to manually type the correct sort name, whereas if it always autopopulates, they could accidentally leave the wrong sort name and save the record.

**Comment by rlskoeser** [comment]
Yes, that does seem problematic and likely to be a source of error.  It seems like automating the simplest case doesn't really save you that much effort.

The one way I could see automating this is if we reverse the order so you type the sort name and the name field is filled in from that.  However, I remember some discussion with Josh and Jean about adding the sort name to allow for better handling of name variations - e.g., look at how Bryher is listed.  I wonder if automating this for the simpler cases is worth it?  I'm worried about adding complexity to the code that we'll have to maintain (and that could potentially break at some point).

**Comment by clmahoney** [comment]
This seems fine to me, although I'm wondering if I'm testing correctly. Like I was adding a new account, and the name autopopulated without spaces, but should I be trying this elsewhere too?

**Comment by rlskoeser** [comment]
@clmahoney other scenarios I can imagine to test: 
- should work both for adding a new account and editing an existing one
- should only prepopulate when the name has no spaces
- should not override text in the sort name if you've manually entered something

**Comment by elspethgreen** [comment]
This looks good to me!
