### ISSUE TITLE
As an admin, I want to be able to enter duplicate events in the case where multiple purchases or borrows were made at the same time but without title information

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#555]
Right now the code prevents us from entering in duplicate events. We want to be able to enter them, though, when a member buys or borrows multiple copies of a book or series of books but Beach failed to document the titles in the series. See Book 983, "Benn's Library," which is a series. The member bought 6 of these books, and each book needs to be documented, but we don't have a record of the individual titles. 

For future testing: 
Add purchasing events of the same title on the same day for the same member.

**Comment by rlskoeser** [comment]
@clmahoney I didn't see any uniqueness validation on borrowing events; I removed the validation for purchases.

**Comment by clmahoney** [comment]
- YES this works!! I was able to add all 6 purchases for "Benn's Library" on the same date, with the same purchaser.
