### ISSUE TITLE
member card detail page should only show events for current member

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#558]
**Describe the bug**
On member card detail view (single card with list of events), all events associated with that card are displayed, which in some cases includes events for different members.

**Steps to test**
1. Identify a shared card (e.g. Leibowitz s2)
2. Associate card with two accounts (e.g. Leibowitz and Truyel)
3. Add Truyel event and use a footnote to associate with Leibowitz s2
4. Check the card display for both Leibowitz and Truyel - the large card display with table of events should only display events for the current member instead of all events.

**Expected behavior**
Only events for the current member should be displayed

**Comment by rlskoeser** [comment]
Added event filter by member in 169d3db7ac04a7d66f324f8d30faec2749caf1c9

**Comment by clmahoney** [comment]
@rlskoeser How do I associate the card with the two accounts? Right now, if I associate Truyel with Leibowitz, that means that s1 AND s2 show up for Truyel. Is there a way to make it only s2?

**Comment by rlskoeser** [comment]
@clmahoney no, there's no way to make it only s2; from what I understood of @jkotin's comments he wanted to show recto/verso together anyway, so hopefully this solution will work for the shared cards.

**Comment by clmahoney** [comment]
@rlskoeser I see, thank you for explaining

**Comment by clmahoney** [comment]
- YES, I am able to associate the card with two accounts
- YES, when I add the Truyel event and footnote it to Leibowitz s2, both cards show up for Truyel on the card detail page but just his one event on s2 is listed in the table. Similarly, on Leibowitz's card detail page, the Truyel event is not there since it's not associated with him.
