### ISSUE TITLE
django admin queries causing site timeout/unavailability

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#561]
## notes for testing
The django admin Work list search now uses Solr instead of the database. It will behave slightly differently, but you should still be able to find everything you need to find to do your data work; you might need to revise your queries in some cases (e.g., maybe add wild cards in some cases). Basically, you should make sure you can do all the searches you regularly do for data work, but here are some suggestions of things to test:
- check that all records display if there is no search term
- check that it works for searches that return a large number of matches (thousands)
- no records for a search term that doesn't match anything
- search should match content in title, creator name, notes, public notes, or database id

**Comment by clmahoney** [comment]
- YES, all records display if I don't search for anything/if there is no search term
- YES, if I can search for large results: I searched "the" in books and got 2,454 results
- YES, there are NO results if I search for a weird term (like numbers, or odd misspellings) 
- YES,  search does match content in title, creator name, notes, public notes, or database id

**Comment by jkotin** [comment]
This all looks good to me.  Could you say more about wildcard searches?  "Chau" doesn't turn up any results, but "Chau*" gets Chaucer.  "1111" gets item 1111.  111* doesn't.

**Comment by rlskoeser** [comment]
@jkotin I think the wildcard behavior is due to how they are indexed - I would expect wildcards to work on all of the text fields, so basically everything but database id.

I had intended to include slugs in the admin search fields but forgot - would this be useful to add in future or is it not needed?

**Comment by jkotin** [comment]
Excellent. I don't think we need search in the slugs.  Should I close?

**Comment by rlskoeser** [comment]
You already did! Prepping the hotfix release now.
