### ISSUE TITLE
Revise the language of the filter for "borrowing dates" so that it includes all activities associated with books

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#562]

**Comment by gissoo** [comment]
@jkotin [Here are all the pages](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e9f4357dfa2157a5467e434) where "borrowing" would be replaced by what I'm proposing, "Circulation" – this change is happening due to the conversations that took place on #230 and #231

The point of this issue is to make sure:
- the pages I am showing are all the correct places where "borrowing" would be replaced by another term and/or if there are more places I may be missing.
- suggesting "circulation dates" makes sense for the filter on the search page
- About the variations with the sort options, please don't comment here, please write about them on issue #565

**Comment by thatbudakguy** [comment]
@gissoo could we change the title of the issue so that it no longer references sorting, since that's now #565? this one is just about the filter, right?

**Comment by gissoo** [comment]
@thatbudakguy sure thanks for catching it!

**Comment by jkotin** [comment]
I apologize for having this discussion in two different places. I think "circulation" looks good here. It makes sense. It also is the word that libraries use.

I take the point that purchases shouldn't technically count in circulation numbers. But I think we'll survive. A library still counts a book in its circulation numbers if it's lost or stolen or constantly renewed.

An alternative work is "transaction," which is more general.

Last question: would it make sense to have circulation date in the sort features as well?

**Comment by rlskoeser** [comment]
I agree, circulation makes sense to me — it seems closest to what we want and most easily intelligible.

@jkotin you can't sort on a multi-valued field, but we could sort on earliest circulation date; would that be meaningful?

@gissoo I hate to make more work for us, so this is probably a wishlist thing, but it would be nice to display circulation years for the book search results in an analogous fashion to the membership dates on the member search page. It's kind of weird to be able to filter on a value that you can't easily see in the results.

**Comment by jkotin** [comment]
Yes, it would be great to sort by both circulation date and publication date -- the two kind of go together.

**Comment by gissoo** [comment]
@jkotin thanks for writing, 
- re "circulation" – I agree – you are more specifically touching on the point I was making in my latest comment in #565 
- I'm not sure about "Transactions" here
- @rlskoeser @jkotin Circulation date would be awesome! – I think it would be awesome to add "circulation years" in the results – I would have said the same thing, I agree with you that it will make a lot more sense – would be great to be wishlisted

**Comment by gissoo** [comment]
@jkotin @rlskoeser [Here is the design](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e9f4357dfa2157a5467e434). Since you said you are ok with "Circulation Dates" as the search filter I haven't revised anything here – just adding the revised sort options here along with the filter to conclude these pages are all the places that we are replacing "borrowing" with "circulation.
