### ISSUE TITLE
Update the sort options for "Books" to match the attached issue + revise the language of the "Borrowing" so that it includes all activities associated with books

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#565]
[To match issue 231](https://app.zenhub.com/workspaces/mep-django-5931d39e341d0d6c7318d56f/issues/princeton-cdh/mep-django/231)

[Here is the updated design (there are two variations for sort)](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e9f23c6487f967d69ea8c42)

**Comment by gissoo** [comment]
@jkotin I had to revise this to make sure it matches what has been discussed in issue #231 – Additionally, @rlskoeser and @thatbudakguy let me know that there can't be any line breaks in the open sort options (i.e. each option will be in one line, no matter how long it is) – Therefore, I have changed the styling so that the "lowest-highest" type of info will be in grey for better readability 
Please review this and let me know what you think

**Comment by gissoo** [comment]
@jkotin never mind! @rlskoeser just informed me that the colors can't change either – so just comment on the language please and I'll fix the styling

**Comment by gissoo** [comment]
@jkotin @rlskoeser @thatbudakguy Here is [the 3rd version](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e9f406070db065598ceaef8) – after trying another route that RSK suggested I ended up coming back to this version – currently, this seems the most usable way – just eliminated it back to one color (black) and instead added parentheses to help with readability – if there are strong objections with the parentheses I'm ok with dropping them, I think they slightly help visually – Let me know what you think and if this matches what is being implemented. 

I appreciate feedback on the language with "Circulation" – I think it is more immediately comprehensible in comparison with "activity" or "events" and is consistent with the "circulation" tab in books  – also just wanted to double check on "frequency" and if it still makes sense.

**Comment by jkotin** [comment]
@gissoo Thank you.  Just to confirm: we need the double options (A – Z and Z – A) because users won't be able to toggle/reorder the results by column?

Do we need the word "frequency"?  Couldn't we have "Circulation (Highest – Lowest)?"  What does "relevance" evaluate, and should it be first and the default?

FWIW, abebooks.com uses "ascending" and "descending" for publication date -- I'm not sure if that's better.
<img width="448" alt="Screen Shot 2020-04-21 at 3 11 37 PM" src="https://user-images.githubusercontent.com/12616674/79904244-67783480-83e2-11ea-9cb6-c834592055b5.png">

**Comment by gissoo** [comment]
@jkotin thanks for writing!
- This is for the book search page – so I think we need the double options (A – Z and Z – A) I'm not sure I understand when you say "users won't be able to toggle/reorder the results by column?" – are you thinking of the "circulation" tab?

- It makes sense to me without "frequency" – which is why I'm raising the question – can't remember our discussions before that led to "frequency" making more sense – unless @rlskoeser thinks there are logical reasons for it 

- "Relevance" is always the default when the user has input keywords or has used the filters – but when they are just browsing (i.e. not entering terms into the search box or filtering relevance won't be available/active) – I don't even think it should show up in this drop down now that I think about it or if it does it should be visually inactive/not selectable. 

- thanks for the reference with the screenshot! I did not prefer this before. I understand that it works for terms such as "ascending" and "Descending" – I'm a little hesitant but it logically makes sense as I keep thinking about it! @rlskoeser does this make sense to you?

**Comment by thatbudakguy** [comment]
@jkotin this sort dropdown is the one that appears on the main books search, not on the circulation activity table.

I'm not convinced we need the reverse sorting options (Z-A, reverse chronological, etc) here. I think sorting (like the search itself) is primarily designed to help you find a single item quickly; people who might be doing work like "find the oldest item in the library" are probably in the minority and could also answer that question in a more detailed way with a data download. I'm also not sure what value there is in reverse sorting all of the results when the user could simply jump to the last page and keep clicking the "previous" button to achieve the same effect.

On that note, labeling the sorts if we don't offer reverse options becomes a lot simpler. "Date" virtually always implies chronological order, "Title" implies alphabetic order, etc...there's no need to qualify them with "A - Z" or similar.

on "circulation frequency" - does this capture the whole story? aren't we including non-borrowing events, which would not fit the definition of "circulation" (e.g. purchases)?

**Comment by gissoo** [comment]
@thatbudakguy Thanks for writing. I like to know what RSK and Josh think about your comment – From what I understand though – according to what you have written, we won't want "Date" to imply earliest-latest (because as you said "...are probably in the minority and could also answer that question in a more detailed way with a data download..") – So even if we choose only one direction, I think it needs labeling "Publication Date Newest – Oldest" rather than only "Publication Date" – especially since there are multiple options, it can be easily confusing without it. 

- Thanks for pointing out about "Circulation" – if we do not use "circulation" for the reason you are mentioning above – then I think we will also have to change it to something else in the "circulation tab" – but as I keep thinking about it more I think it still makes more sense than any other language we have used in its cohesiveness (also because a book/item might have been borrowed before it was purchased at some point)?

**Comment by jkotin** [comment]
I like the comments from @thatbudakguy about simplifying the menu by deleting the reverse sorting options. Re: "Circulation" -- I think it's OK, but Nick is technically correct. Other options would be "Frequency" or "Most Borrows/Purchases" or going back to "Activity." All these seem acceptable to me. The colors/design is great.

**Comment by rlskoeser** [comment]
Hi, all, trying to catch up on all the conversation here.

Comments/responses:
- I don't think "circulation frequency" makes sense; just "circulation" is better
- I think "circulation" is probably expansive enough to include other kinds of book movements besides borrowing activity (also, the vast majority of events _are_ borrows). Also, we're already using it on the book detail pages, so it's consistent within the site.
- I agree with Nick and Josh that we don't need all of the reverse options; it will be much simpler and more readable if we don't have so many options
- I agree with Gissoo that it's not obvious which date order would be default (it depends on the content and the use cases)
- relevance sort option will be disabled when it's not applicable, we just haven't implemented that yet for books

Questions:
- @jkotin if we only include one publication date sort option, do you want oldest to newest or newest to oldest?
- @jkotin are you fine with dropping _all_ reverse sorts, or are any of them interesting enough to highlight? (lowest circulation?)
- @gissoo using "circulation" here doesn't impact the use of "borrowing" on the individual member detail page, does it? I think we discussed that and you decided borrowing was more intelligible than something more accurate but ambiguous like "book activity", but wanted to check.
- @gissoo does it matter we don't include any kind of circulation count anywhere? book search result or bibliography page?

**Comment by jkotin** [comment]
Great, I think we are all getting on the same page.  Re: questions from @rlskoeser --

1. It's tricky because a SIGNIFICANT number of items won't have dates because they are "unidentified" or written before the printed book.  How would we order those books?  I could enter dates for the pre-Gutenberg books, but that would only solve part of the problem. Do these facts help illuminate an answer?  I'm not sure.

2. Yes, I think we can drop all reverse sorts.  There are 1000s of books with a circulation of 1.

**Comment by rlskoeser** [comment]
@jkotin I'm configuring the sort so that missing values sort last, and I'm adding a secondary sort on title. Does that help with the number of books with no publication date?

**Comment by gissoo** [comment]
@jkotin @rlskoeser Thanks for writing:
- re "Circulation" – I agree with Nick's point if we are only sticking to logic, however most often when designing to create intuitive and usable projects logic needs to be incorporated with context and language is important and is most often influenced. "Circulation" sounds a lot more intuitive and relatively logical here from everything I have seen and understood (as far as the hierarchy and frequency between "borrow" and "purchase", "gift", and etc. In general, if it proves otherwise after usage I'm more than happy to learn and revisit. 

- re "Circulation" vs. "Circulation Frequency", I totally agree with "Circulation" as the latter has stopped making sense to me. 

- re reverse sorting: @jkotin @rlskoeser @thatbudakguy I totally agree that eliminating the reverse sorts makes this specific feature simple and easier to use, and we didn't do any usability testing for this feature to find out with reason rather than making assumptions, and I'm generally leaning towards a more simple setting, where features could be added later on if it's learned that users will indeed need it – _however_, I would like to remind you that the reverse sorts maybe more powerful now specifically because we don't have the "publication date" and "creators tab" as mvp – had to point it out 

- re @rlskoeser 's Q1 – @rlskoeser do you mean the name of the "Borrowing" tab on the activities section of a member? (I don't see any "borrowing" on the member's biography page – just making sure – if that is what you mean I think "borrowing" is ok, I'm certain that "circulation" won't make sense here, however I'm thinking whether "Transactions" or "transactional" is better – I have mixed feelings about the word because there are some overlaps between "transaction" and "membership". 

- re @rlskoeser 's Q2 – I'm tempted to say it's better to include the count on the search results and the bibliography page – but it also depends on the data – from what @jkotin is saying there are 1000s of book with a circulation of 1, I doubt about how meaningful it will be enough.

**Comment by rlskoeser** [comment]
@jkotin I was wrong, I have empty sorting last for author and title but not pub date. That makes me inclined to sort newest first when sorting by publication date, but I don't know if I'm suggesting that for the wrong reasons.

**Comment by rlskoeser** [comment]
@gissoo yes, I meant the borrowing activities section. I think it's ok, and it seems better than circulation or transactions, but wanted to check with you if we were being inconsistent.

Good point about the counts of one - that does suggest it might not be as useful, I'm interested to hear what @jkotin thinks.

It struck me when I was reviewing the designs yesterday in relation to these conversations: the member detail page design is specifically about the person in the context of the library, while the book bibliography page is more straight-up bibliographic data without any summary or context of the book in the library. It seems like adding event counts and circulation years might help with that. (🤔 I wonder if we could do a book timeline like we do for members, and if we did how useful or interesting it would be?)

**Comment by gissoo** [comment]
@rlskoeser I think the reason for what you are noticing with the designs is derived from our our ways of thinking about them at the time (which I remember had a lot to do with data work that made me feel more limited in designing) which led to what we agreed on – I do think it's useful to have the circulation years there (but it was not in scope or spoken of since we had other priorities) – thanks for revisiting, I remember that I had also suggested about the book timeline very early on, I do think it would be nice to have the timeline and the circulation years on the bibliography page.

**Comment by thatbudakguy** [comment]
I'm OK with "circulation" as a general description of book events, but would also be fine with just "activity" or Josh's suggestion of "transaction" too - whatever we think is the clearest.

@rlskoeser I like where you're going with adding more context to the work detail page; the addition of a book timeline seems like a natural parallel.

**Comment by jkotin** [comment]
I don't follow the question about referenced in "Good point about the counts of one - that does suggest it might not be as useful, I'm interested to hear what @jkotin thinks."

**Comment by rlskoeser** [comment]
@jkotin sorry for lack of context, this is in relation to my suggestion of including a circulation event count on the book search result card and the book detail bibliography page and your comment that there are thousands of books with 1 event. Would event counts be interesting?

**Comment by jkotin** [comment]
Thank you!  Yes @rlskoeser , I think event counts would be interesting.  Even the 1s are interesting: you think, wow, only 1, and then realize that the only reason we are thinking about the book is that it was borrowed once, and thus kept alive.

Also it's fascinating to compare counts of books by the same author.

**Comment by gissoo** [comment]
@jkotin @rlskoeser @thatbudakguy Before this conversation becomes harder to track, I appreciate your response on these (to reach an agreement) – From what I understand in the comments:
- We'll keep "Circulation" language for the sort option
- re eliminating reverse sort options: this is my earlier comment in case it got lost: "@jkotin @rlskoeser @thatbudakguy I totally agree that eliminating the reverse sorts makes this specific feature simple and easier to use, and we didn't do any usability testing for this feature to find out with reason rather than making assumptions, and I'm generally leaning towards a more simple setting, where features could be added later on if it's learned that users will indeed need it – however, I would like to remind you that the reverse sorts maybe more powerful now specifically because we don't have the "publication date" and "creators tab" as mvp – had to point it out" – can we confirm we are still eliminating sort options? If yes,
are we **eliminating**: 
1. Author Z-A? 
2. Title Z-A?
3. Publication Date (newest - oldest)?  (also maybe better to say "earliest-latest" - sparked by RSK's comment)
4. Circulation (fewest-greatest)?
- referring to comments on #562: Are we **adding** the "Circulation Date (earliest-latest)" sort now – or is the sort option wishlisted? – Need to be considered as I update the designs
- referring to comments on #562: Are we wishlisting the addition of "Circulation Dates" on the search results and bibliography pages? – They will need design work
- referring to comments on #562: Are we wishlisting the addition of the book timeline for the bibliography page? – It will need design work 
- are we adding circulation counts on the search page and the bibliography pages now? or are we wishlisting? – They will need design work

**Comment by jkotin** [comment]
This all looks right to me. I'll defer to @rlskoeser on the publication date sort-order question.  I prefer "descending/ascending" to "fewest - greatest, and "newest - oldest" or "newest first" to "earliest-latest."

Re: wishlist, I'd prioritize circulation date, and then the book timeline.  But I'm eager to hear what others thing.

**Comment by rlskoeser** [comment]
@gissoo thank you for summarizing! 

You're correct on the list of sort options we're eliminating, with the one caveat that we need to decide which publication date order we want to include. 

Publication date order: I'm inclined to newest first because I think it will work better with the data we have. @gissoo any concerns?

I feel like "ascending/descending" takes slightly more mental effort to process, but I don't feel strongly about not using it; @gissoo what do you think?

I'm ok with adding circulation date to the sort options now - you're already revisiting the designs and it doesn't increase the complexity of the sort logic much. @gissoo is this ok for you? How can the label make it clear that this is the *first* circulation date? 

You are right, everything else should go on the wishlist. Thanks for confirming they will require design work, I thought they probably would. Should we create wishlist issues to keep track of these ideas? Who can do that?

**Comment by gissoo** [comment]
@rlskoeser @jkotin Here are [the revised designs, v4](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ea096232819f71b0d91c510) – Please read below and let me know what you think.
- @rlskoeser I think as I mentioned regarding "publication date" and "author" I'm a bit concerned and unsure of which is more useful mainly because the filters that would have been helpful to have are not mvp anymore – I find them both equally important (the a-z and z-a, and the oldest-newest and newest-oldest) – but I trust your instincts and knowledge about the data we have, so I think it's fine and, in general think it probably won't be disastrous. 
- @jkotin @rlskoeser  "ascending/descending" is not intuitive from my perspective when we talk about the concept of time, I strongly recommend that we don't use it. I like "Newest – Oldest" the best then. 
- @rlskoeser I've already added the circulation date to the sort options! by "this is the first circulation date" do you mean how to make it clear that the first item that will show up as a result of this sorting was the first item ever circulated in the S&Co library? – If this is what you mean then I think "oldest" still makes sense here! From my perspective, I don't have a concern with this. – Do you have specific concerns I'm missing?  
- @rlskoeser, great! I will create issues to address the new wishlisted design work in the best way possible.

**Comment by rlskoeser** [comment]
@gissoo these updates look good!  

One more small wording comment:
- "greatest / fewest" doesn't make sense with Circulation to me (I don't think you would say something had the "greatest circulation" - would you?). What about most/least or highest/lowest?

Regarding the circulation date: I agree that oldest makes sense in terms of labeling the direction of the sort. What I'm concerned about is potential confusion when an item circulated for multiple years. We can only sort on a single value, which will be the _first_ time an item circulated. To be most accurate, the label should be "First Circulation Date (Oldest - Newest)" - but that's pretty long! I just want to be sure you think it's not going to be confusing without this.

**Comment by rlskoeser** [comment]
@gissoo Thank you for creating the issues to track the wishlist ideas that came out of this conversation!

**Comment by gissoo** [comment]
@rlskoeser I get your point about the "greatest/fewest" – the reason I picked that was because it's a "count" and lowest or highest to me are more relevant for "frequency" than the actual number of times something happened. (I read it as "greatest/fewest number of circulation") – but if I'm the only one this is bothering then I'm happy to go back to "most/least" 
- I also understand your point about the "first circulation date" – that 's what I also suspected you are concerned with – my answer is I don't think it's necessary to be communicated in the sort option – I think it's something that will need to be tackled when we list it in the search result of the item and on its bib page. Is this ok with you? (Because to me, it's on a different level, it's **not** what the sort is mainly addressing)

**Comment by rlskoeser** [comment]
Interesting! Technically we're sorting on a count, but "circulation" doesn't read exactly like a count to me... IDK what that means, though. 

Yes, I'm fine with not labeling it as first circulation date if you think it's ok! That's all I wanted to confirm. I agree that adding more details to the search results and bibliography pages will help with this.

**Comment by jkotin** [comment]
I'm getting caught up on the discussion. I don't think I have much to add, looking at the latest designs @gissoo sent out.  (Thank you everyone for thinking through these issues so brilliantly.)  

I wonder if "circulation date" should come before "circulation" on the menu?  Publication date and circulation date seem to go together in my mind.

Re: terminology.  I am going to ask my mother (a librarian) re adjectives for circulation.  "Highest" and "lowest" seem good to me.

**Comment by jkotin** [comment]
I wrote to my mother and she said that "Circulation (highest – lowest)" is fine.  She also suggested "Most Borrowed" or "Most Circulated."

Here is a portion of her note:

I would use the word “circulation” and I think it’s well understood because it’s used in the world of magazine and newspaper subscriptions too.  However I also know that some libraries try to use non library jargon and so here are the other terms just in case you want alternatives!
“Check-outs” (this is used quite often even at Academic libraries)
“Loans” or “Loaned”
“Borrowed” (mostly used in England)
Libraries sometimes rationalize no longer having certain books in their collections because the item was never “checked out.”

**Comment by gissoo** [comment]
- @jkotin Thank you for writing!! This is so valuable and interesting, thank you for asking your mother!! 
I think it will be the least confusing and the most clear to use "Circulation (Highest – Lowest)" here, within this project. (I personally prefer "check-outs" but I have a lot of worries with using it here and our edge cases, so wouldn't recommend it)

- I can rearrange the "circulation date" and "circulation" – to flip the order, it might be easier to read if flipped. (I thought about it and wanted users to see the more basic sort option first, i.e. the counts before seeing the date, because to me the circulation count is less of a detail than the circulation date, but I really don't know how much it matters)

**Comment by gissoo** [comment]
@jkotin @rlskoeser [Here is the revised design](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ea096232819f71b0d91c510)

@jkotin please let me know what you think and if there are any issues so I can revise, otherwise please close it.
