### ISSUE TITLE
Add "Circulation Years" & the number of times at which an item was circulated on the book search page (for each item) 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#566]

**Comment by rlskoeser** [comment]
@gissoo same question as #560 — can this also include book detail/bibliography page or do you need a separate issue?

**Comment by gissoo** [comment]
@rlskoeser There is already a separate issue for this [here](https://app.zenhub.com/workspaces/mep-django-5931d39e341d0d6c7318d56f/issues/princeton-cdh/mep-django/567) because there are different things to tackle on each page.

**Comment by gissoo** [comment]
@jkotin What is more important to you on this page? The circulation count? Or circulation dates?

**Comment by jkotin** [comment]
@gissoo count.  But would you re-send me a link to the page design?

**Comment by gissoo** [comment]
@jkotin thanks! Here is the page: (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5c8c155383d1b52501ceb39b)

**Comment by jkotin** [comment]
@gissoo thank you. Circulation count is more important, I think.

**Comment by gissoo** [comment]
@jkotin @rlskoeser [Here is what I'm proposing](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ec301c52611c730be7ca733)

- I prefer moving the "book"/"periodical" to the bottom left because that is more of a fundamental piece of information, and then having the circulation-related info on the right. I'm not feeling great about the "Circulation Count" "Circulation Dates" titles here – Please look at the lower desktop screen with the two rows – I was trying to see if we can either make the labels less redundant, or if we can say "circ." – I'm not liking the first row though it still looks strange. 

- I also was looking for something other than "circulation count" language-wise but this makes the most sense. 

Please let me know what you think.

**Comment by jkotin** [comment]
This looks great to me. Notes:

1. I wonder about the use of bold: the title, author, and date are the most important information. I worry that the bold causes the eye to be drawn first to the circulation information.

2. Re: terms -- I think abbreviating "circulation" to "circ." is fine. So "circ. count." That said, in the drop down sort menu, we just use the word "circulation" -- maybe that could be sufficient?  See the definition of "circulation" here: http://www.nrs.co.uk/nrs-print/readership-and-circulation-trends/readership-vs-circulation/.

**Comment by rlskoeser** [comment]
I don't love "Circulation Count" or "circ."; what if we just label it as "Circulation" and then add a label to the numbers? Something like "87 events" (although I know we're using "activity" rather than events for labels elsewhere — not sure how to make that work with a number, "87 activities" sounds weird to me).

I actually wondered if we could put both the count and the years under the label "Circulation" if there's a label by the number to indicate what it is. It seems like the years are pretty obviously years even without a label. What do you think @gissoo ?

I think the font sizes and variation on the left is enough to compensate for the bold heading; but maybe it would also help if there is only one bold heading.

**Comment by gissoo** [comment]
@jkotin @rlskoeser Thanks for writing. 
- Thanks for the link, Josh. I saw this "how many copies of a particular publication are distribute" yesterday as the meaning of "Circulation" and I freaked out a bit – I know it's in the context of the _library_ here and it should make sense but what if it's confusing? Do we mean something that is closer to "readership"? 

- @rlskoeser How can we calculate readership? How is it different from the circulation? Does it mean we won't count reimbursements? 

- Let me test something with the label – I'll show you soon

- @rlskoeser I thought of "Circulation" but having something like:

Circulation
87

but it might be confusing, users might think it's an id/specific number rather than the "number of times.." an item was circulated. (at least for those who are not researchers)

- I think "events" makes sense here – I know we had a discussion before and I was concerned but it was mainly for the "members" section since the term "activities" is explicitly shown in that section. We don't have that term explicitly on the "circulation" tab.

**Comment by rlskoeser** [comment]
@gissoo I didn't mean to propose we should calculate and display readership, but I would calculate it as the total number of readers who interacted with a book. (e.g. "8 readers").  For example, _Portrait of the Artist as a Young Man_ has 56 events in our database because some people borrowed it twice, or borrowed and then purchased.

Thinking about it more, I like the idea of using "Circulation" as the heading and then something like "87 events" — this makes it much more explicit what sorting on circulation means.

**Comment by jkotin** [comment]
Some notes @gissoo @rlskoeser:

1. Circulation v. readership -- sorry for introducing panic!  I think "circulation" or "circulation count" is the correct term -- it refers, in our context, to how many people checked out or bought the book based on the extant lending library cards. Readership is impossible for us to know: it refers to how many people read the book. For example, I check out a book from the library, and my spouse and child read it too. That's a circulation count of 1, but a readership of 3. Or I check out a book and don't read it: 1 and 0. Outside the context of libraries, the difference between circulation and readership is important for advertising rates. A newspaper might print 1000 copies, but calculate a readership of 2000. Consider the free newspapers on subways. 

2. I'm a little wary of "events" (very general thus confusing -- "what's an event?" a user a might ask) but I don't see a better option besides "circulation count," which is also acceptable to me.  "Events" would be better if we do as Rebecca suggests and also have the circulation dates with a common "circulation" heading.  So:

**Circulation**
56 events
1919 – 1936

Alternatively, we could have:

**Circulation**
56 borrows
1919 – 1936

Or "borrows/purchases" or "borrows/other."

**Comment by gissoo** [comment]
@jkotin thanks for writing on the readership, this makes a lot of sense! What you have there is what I had in mind to show you both :D 
[here](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ec41cef8ff561475cff62aa) 

I think it looks a lot better now! Thanks @rlskoeser for suggesting "events" – that was the main issue for me at first - Josh, I prefer events more than "borrows", I think "borrows/other" would make sense too! What do you prefer @rlskoeser @jkotin ? "events"? Or "borrows/other"?

**Comment by rlskoeser** [comment]
This looks great! I prefer events to "borrows/other"

@gissoo not so sure about the mobile — could we just stack the content instead of having them offset like that?

**Comment by gissoo** [comment]
@rlskoeser I really prefer to keep it as is for mobile. It's also this way for "members" on mobile, and it would keep the container shorter than it needs to be. It also visually helps to create less of a cognitive load.

**Comment by rlskoeser** [comment]
@gissoo I looked at the mobile again — weirdly, it looked unbalanced to me when it was zoomed out, but when I zoom in (more like how it would look to someone on a phone), I see that the format lines up with the circulation and it looks balanced and readable.

I wonder about the placement of the uncertainty icon on mobile — it seems like it makes the container longer unnecessarily, could it be top right or under the result number?

**Comment by gissoo** [comment]
@rlskoeser thanks for writing. I recommend we keep the uncertainty icon where it is. I have testet the second and third bullets: 
- Having it on the right doesn't make sense hierarchy-wise and is inconsistent with other devices as well. 
- Having it under the result number makes the grouping of information on the left looks somewhat cluttered, I'm not a fan of what it creates visually, and is not worth doing to keep length shorter. I don't recommend it. 
- I also tested with keeping it to the left of the result number because visually it would be best, however it won't make the container shorter, because in this case it looks best if the format does not align with the circulation, otherwise it becomes cluttered (since the info on the left is shifted further to the right). 

Please let me know what you think, I prefer to not spend time on this (the uncertainty icon) right now if there are no concerns implementation/usability/data-related I mean.

**Comment by rlskoeser** [comment]
@gissoo ok! thanks for testing and elaborating your thinking on this. I agree you shouldn't spend more time on it.

**Comment by gissoo** [comment]
@jkotin If you don't have any concerns with the designs here please close the issue.

**Comment by gissoo** [comment]
@rlskoeser Note: I also just revised and made sure the column widths here are also consistent.

**Comment by jkotin** [comment]
Looks great.
