### ISSUE TITLE
Add "Circulation Years" of an item & the number of times at which an item was circulated on its bibliography page 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#567]

**Comment by gissoo** [comment]
@jkotin @rlskoeser [Here is the design for this page.](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ec452beba5f3547b4e70a8e)

- I was trying another way (to just add the circ. info after the pub. date info on the left), however it's not consistent with the search results and it doesn't make so much sense to me, therefore I have made it this way, taking the "book"/"periodical" to the left side after the pub.date and the circ. info to the top right. I think it also makes sense to keep its labels same as the search page. 

Please let me know what you think.

**Comment by jkotin** [comment]
Could we have the "read online" at the top?  (I.e. above the circulation information?)  I really love that feature and want it to be prominent.  Otherwise, this looks great.

**Comment by rlskoeser** [comment]
@gissoo sorry I didn't get the chance to comment before you revised! I don't think we should have comments or ellipses on the circulation years — it should just be a list of year or year range, as we have on the member biography page. Otherwise, these look great to me too.

**Comment by gissoo** [comment]
@rlskoeser Thanks for pointing this out! I missed it!
@jkotin About the "read online" link – I understand. I think it's fine for it to be on top.
[Here are the revisions. Please let me know what you think (all screens in this section).](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/dashboard?seid=5eb17d4d9361e31e8fa64210)

**Comment by jkotin** [comment]
Looks perfect to me.

**Comment by rlskoeser** [comment]
Yes, looks great to me too. @gissoo would you add a note for column widths on mobile? (if it isn't already marked / communicated in some way).

Should we close?

**Comment by gissoo** [comment]
@rlskoeser Thanks for writing. I had corrected the column widths, but I just revised all the columns on all screens so they are all consistent and exact on Zeplin when clicked on. Thanks for pointing it out.

@jkotin If you don't have any concerns please close the issue.
