### ISSUE TITLE
Add the number of times at which an item was circulated on the book search page (for each item)

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#569]

**Comment by rlskoeser** [comment]
@gissoo can this also include book detail the bibliography page or do you need a separate issue?

**Comment by gissoo** [comment]
@rlskoeser There is also already a separate issue for this [here] :D (https://app.zenhub.com/workspaces/mep-django-5931d39e341d0d6c7318d56f/issues/princeton-cdh/mep-django/570) because there are different things to tackle on each page.

**Comment by rlskoeser** [comment]
@gissoo thank you, glad to have the issues so I can include them all in the milestone.

**Comment by gissoo** [comment]
RSK and I discussed – this issue has been consolidated with #566, and therefore it will be closed.
