### ISSUE TITLE
As a content editor, I need a way to distinguish people with the same name when I'm selecting a person via autocomplete.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#57]
**Testing Suggestions:**
- [ ] Do a person lookup in account for 'Hemingway' (all fields, including birth, death, mepid, and first five words of notes should all be displayed)
- [ ] Do a person lookup in account for Jones (or other low information people, including Mr. / Mrs.) (should see mepid if it exists, and first event of any type displayed if no other information is known, also titles are rendered as part of the output)

As an example, try searching for Jones.  We're including title (mr/mrs), but that still isn't going to be sufficient in all cases.  Possibilities:
- display beginning snippet of any note text?
- display first event dates, or date range of events associated with any account?
- make sure that name is still emphasized, and larger than any other text or information

Should be able to customize the html display:
http://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#displaying-results-using-custom-html

**Comment by rlskoeser** [comment]
@jkotin @elspethgreen documenting this proposed improvement based on conversation at our last meeting.  What information would be most useful for distinguishing people with the same name (e.g. .all the Joneses)?  The possibilities I came up with are the beginning of any note text, or information about dates associated with the account for that person (first library event? range of all currently known library events?), but you may think of others.  We don't want to add too much logic to this because it could slow down the autocomplete, but it seems important that you have a quick way to distinguish names when you're adding people to accounts.

Does this need also apply to the account lookup, when you are associating an account with an event?  And if so, what information would be most useful there?

**Comment by bwhicks** [comment]
Included below are draft results of an attempt at addressing this story. The new autocomplete attempts to show name, birth-death, address, mep_id and notes, if present. If none of those are available, as with the many Jones', it shows the first event the database can associate with them.

@rlskoeser mentioned that there may be developments in workflow that would change how this story plays out, but thought it would be good for the team to see the work in progress as you consider further interface revisions.

![screen shot 2017-12-13 at 11 25 55 am](https://user-images.githubusercontent.com/17815297/33949712-6e660fe6-dff8-11e7-9d8f-822d55201ae1.png)
![screen shot 2017-12-13 at 11 26 09 am](https://user-images.githubusercontent.com/17815297/33949720-7267cbde-dff8-11e7-9aaf-ebc287f17da6.png)

**Comment by bwhicks** [comment]
@elspethgreen @clmahoney I wanted to flag that I had added the person autocomplete enhancements to the current round of testing.

**Comment by clmahoney** [comment]
This seems to work for me. I think this looks good, but my only worry is that it seems too cluttered without enough space or context. Like maybe there could be a hyphen added between start date and end dates, or something to separate them? 

![screen shot 2018-01-29 at 9 17 54 pm](https://user-images.githubusercontent.com/16673934/35544777-0c6e7aa0-053a-11e8-99d2-5a24fc91d6ff.png)

**Comment by bwhicks** [comment]
@clmahoney I've pushed a tweak to the formatting that displays the first event with more clarity, I think.  Does this work? (Feel free to try it on the test server.)

![screen shot 2018-01-31 at 12 02 46 pm](https://user-images.githubusercontent.com/17815297/35636293-b74ab20a-067e-11e8-887d-efc2e88651fa.png)

**Comment by clmahoney** [comment]
Yes @bwhicks that looks much better!
