### ISSUE TITLE
mobile display of membership activity broken when dates are missing

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#575]
>unfortunately, in investigating this I found a bug [in production](https://shakespeareandco.princeton.edu/members/bereniceabbott/membership/) showing what happens if one of the date fields is empty for membership activities:
><img width="522" alt="Screen Shot 2020-04-28 at 12 06 09 PM" src="https://user-images.githubusercontent.com/4924494/80510480-c7be2780-8948-11ea-99e4-37af9c84e33c.png">
>i think we may need to compromise on some of these designs - the need to represent them semantically as a table make it quite difficult to achieve other complex, non-tabular representations.

_Originally posted by @thatbudakguy in https://github.com/Princeton-CDH/mep-django/pull/572#issuecomment-620703693_

**Comment by clmahoney** [comment]
The table seems to have solved it! I looked at two members with cards that lack one of the membership dates (in this case, end date): 
![IMG_1967](https://user-images.githubusercontent.com/16673934/80617181-c86dc100-8a0f-11ea-9c65-4f65e402e848.PNG)
![IMG_1966](https://user-images.githubusercontent.com/16673934/80617186-c9065780-8a0f-11ea-95a8-2c28cb9746ab.PNG)

**Comment by clmahoney** [comment]
I can't find a member who has no subscription start date, but I did check for borrow events that don't have a start date and they look fine. 
A. Bernheim: 
![IMG_1973](https://user-images.githubusercontent.com/16673934/80626654-c3633e80-8a1c-11ea-8abc-8ad712ada675.PNG)

Also regular subscriptions will both start and end dates are good! 
Here's Allespach: 
![IMG_1972](https://user-images.githubusercontent.com/16673934/80626666-c827f280-8a1c-11ea-8afb-6f9379b1095f.PNG)
