### ISSUE TITLE
As an admin, I want members who appear on multiple accounts to display on all cards on member detail page so that I can get full view of all book events

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#577]
**Describe the bug**
Currently there are members who show up on multiple accounts, but the system can only handle one member with one bibliography to display that member's cards. I want members associated with multiple accounts to have all cards in the display. Ex. Natalie Wilson shows up at the bottom of Romer Wilson's card. Natalie Wilson has her own card too. We want all of Natalie Wilson's borrows and cards (including Romer's) to appear on her detail page.

**Comment by rlskoeser** [comment]
@clmahoney would you provide more examples?  What is the one card that has events from several different people?

@jkotin you still want blank cards associated with a members card to show, right? how would you expect the cards to be ordered?

**Comment by jkotin** [comment]
Yes re: blank cards if recto of the blank card has relevant member info. The relevant side should be first.  That's actually related to an issue I've been meaning to ask about w/r/t the verso of the Leibowitch. Right now, it's displaying in the wrong order for everyone but Leibowitch. E.g. https://shakespeareandco.princeton.edu/members/nguyen-minh-truyel/cards/. Could we order where appropriate?

**Comment by rlskoeser** [comment]
@clmahoney never mind, I remembered you already wrote up a document with these!

**Comment by rlskoeser** [comment]
@clmahoney this is on the test site now, but I don't know how easy it is to test until I refresh the data from production — the example I was looking at (Natalie Wilson) didn't show the  additional card. Although, I suppose you could test the functionality fairly easily by adding a footnote for one member and linking to a different card — it should show up.

A note on ordering: I came up with a way to preserve the order of cards in the manifest associated with the member, and then show any other cards after that. That seems to work ok for the records I looked at, hopefully it's a good enough solution.

**Comment by clmahoney** [comment]
- YES, this works wonderfully! I tried with the two members  that show up on s2 of Leibowitz. When I added the Leibowitz footnote to the Leyris event and to the Denis event, viola! S2 of Leibowitz nows shows up on Leyris and Denis card display! I then tried with Natalie Wilson and Romer and IT WORKS!!!

**Comment by jkotin** [comment]
This looks good. A couple of issues that *might* be related. The verso of the Leibowitz card isn't showing on the test site. The Caillois cards are showing up correctly for Petitjean, but not vice versa.

<img width="1018" alt="Screen Shot 2020-05-12 at 9 29 11 PM" src="https://user-images.githubusercontent.com/12616674/81761314-a1939e00-9497-11ea-9102-bb8dd173e134.png">

**Comment by jkotin** [comment]
I tried again and Leibowitz works now. Another question, only possibly related to the note from @rlskoeser about card order.  For the example in the screenshot below -- would it be possible to have the card side with the info about Minh show up first -- i.e. before the Leibowitz side?
 
<img width="1023" alt="Screen Shot 2020-05-12 at 9 34 55 PM" src="https://user-images.githubusercontent.com/12616674/81761637-6d6cad00-9498-11ea-8eb1-d3539d77c8e8.png">

**Comment by rlskoeser** [comment]
I think the order of cards on Truyel predated this change and is due to the order in the manifest — hoping @clmahoney can confirm.

I manually broke the second Leibowitz card image so we could test #494

I don't know what the data looks like for Caillois/Petitjean cards — @clmahoney are events and footnotes entered for these correctly so they should display in both places?

**Comment by rlskoeser** [comment]
Oh, I see now — the broken card feature in #494 isn't displaying properly on Firefox, which explains your screenshot.

**Comment by clmahoney** [comment]
@rlskoeser @jkotin Re: Truyel--Rebecca is right, that's because the manifest hasn't been updated. Now that we will have this feature, I'll ask Nick to update all the manifests for the Leibowitz s2 members. Re: Caillois/Petitjean cards - I have not yet entered all the footnotes, etc. since this wasn't ready. But now that it works, I'll be able to do it and see it!

**Comment by rlskoeser** [comment]
@clmahoney does this mean the feature is working correctly with the data on the site now and can be closed?

**Comment by clmahoney** [comment]
@rlskoeser YES! Can I close?
