### ISSUE TITLE
Revise the book search box language so that it accurately guides users to what can be searched

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#580]

**Comment by gissoo** [comment]
@jkotin @rlskoeser referring back to your question about the hint text inside the search box [here](https://cdhprinceton.slack.com/archives/C2YJR4VF0/p1588207232008800)

Before, applying it on the designs, let's agree on the language first. I would propose these: 
1. Search a keyword, phrase, book, or author
2. Search keywords, phrases, books, or authors

3. Search by keyword or phrase (including book or author)
4. Search by keywords or phrases (including books or authors)

- Added "phrase" – because that is different from "keyword" – I think it may be worth to distinguish
- 2 and 4 are proposed because it is possible to search more than one term at a time. 

What do you think?

**Comment by jkotin** [comment]
I'd be happy if we adapted 2: "Search titles, authors, keywords." I worry that "phrases" will make users think they can search the books themselves (i.e. full text versions). "Titles" seems better than "books" because a book is a general entity that includes titles, dates, authors, etc.

**Comment by gissoo** [comment]
@jkotin I agree! Thanks for clarifying, this is helpful! 
I actually agree with the order you have for the terms too, I initially thought it's generally more important for "keyword" to be the first term, but just figured out something about the non-mvp filters that proves otherwise.

**Comment by rlskoeser** [comment]
I think keyword should be separate from titles, authors — they aren't the same kind of thing (we don't have a keyword field, and keyword there could still suggest full text).

- Do we want "author" or "creator" ?
- Does it make sense to mention issue/volume title (or does title cover that)?
- Does it make sense to include the public notes ? (or not common/clear enough)

What about: 
- Search by keyword or phrase on title, author, format?

**Comment by jkotin** [comment]
"Search by title or author, or by keyword" -- that is fine with me, although still a little complicated. Or "Search by author, title, or keyword."  I'd like to keep it simple.  I think "author" is better than "creator," and don't think we need to mention volume or notes.

**Comment by rlskoeser** [comment]
I'm fine with that

**Comment by rlskoeser** [comment]
If we're simplifying, do we need to include "keyword"? What does it add?

**Comment by gissoo** [comment]
@rlskoeser @jkotin Thank you for writing! I agree with and prefer: "Search by author, title, or keyword."

@rlskoeser I think "keyword" to me is useful, because it implies that you can also search something like "soviet" and it doesn't have to be an exact book title or author name.

**Comment by jkotin** [comment]
I like this too: "Search by title, author, or keyword." Feel free to implement. At the risk of over complicating, I don't think the OR is necessary.  Just "Search by title, author, keyword."

**Comment by gissoo** [comment]
@jkotin I think the "OR" is actually helpful – I had included the OR as well but didn't know how to justify it, I think from what @rlskoeser mentioned about it being different from the other two terms, it makes sense to have the OR.

**Comment by jkotin** [comment]
That's fine with me!

**Comment by gissoo** [comment]
@jkotin Here are the designs on the book search page reflecting what we agreed with the language:

[Desktop](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5c8c155383d1b52501ceb39b)
[Tablet](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5c911523c4045605c4595376)
[Mobile](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5c911524d12e87057b1faafc)

**Comment by jkotin** [comment]
Looks great!
