### ISSUE TITLE
Design a card gallery page for books

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#581]

**Comment by gissoo** [comment]
@jkotin Here are designs for this issue: 
[Mobile](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb17a545b977d1a1d481b42)
[Tablet](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb17a544d7b4a1db9e933b9)
[Desktop](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb17a53fea79a1afa0b5c8b)

Please let me know your thoughts.

**Comment by jkotin** [comment]
@gissoo thank you!  Just to be clear: the card pictured will be the card with the book, the name under the card will be the member's name, and the date will be the start/purchase date of the event?

Some notes:

1. In the book search, when searching by date, we go newest to oldest. Should we do the same here?

2. Where will cards/events with no date go?  At the end, preferably.

3. Quite frequently, the same book will appear multiple times on a card. Killen, e.g., would renew books and re-borrow the same book.  I think it will look strange to have the same card appear ten times in a row.  Consider "The Times Literary Supplement" on Jeanne Fournier's card here: https://shakespeareandco.princeton.edu/members/fournier-jeanne/cards/ca873c36-db50-4c95-9bf4-efe1e0a9ec23/. Would be great to get @rlskoeser input on this issue.

**Comment by jkotin** [comment]
For cards with the same item multiple times: could we show the card once, but list all the event dates in the caption? Thinking aloud.

**Comment by gissoo** [comment]
@jkotin @rlskoeser From the conversation during our meeting earlier today (May 5, 2020), we agreed to:

- order the cards by oldest-newest circulation date 
- cards with missing dates appear at the end/last
- allow cards that hold more than one event repeat on the card gallery page to avoid the complexities with displaying multiple event dates

**Comment by gissoo** [comment]
> @gissoo thank you! Just to be clear: the card pictured will be the card with the book, the name under the card will be the member's name, and the date will be the start/purchase date of the event?
> 

Yes!

**Comment by gissoo** [comment]
@jkotin @rlskoeser From the conversation during our meeting earlier today (May 5, 2020), we agreed to:

- order the cards by oldest-newest circulation date 
- cards with missing dates appear at the end/last
- allow cards that hold more than one event repeat on the card gallery page to avoid the complexities with displaying multiple event dates

**Comment by jkotin** [comment]
I agree!

**Comment by gissoo** [comment]
@jkotin Please let me know if you have any other concerns, otherwise, I think we can close!
