### ISSUE TITLE
re-enable books links in menus and remove login restrictions

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#582]
## notes for testing
- books link should be active and clickable in main menu and not marked as pending
- books link should be active and clickable in footer menu and not marked as pending
- check that all book pages (search + browse,  individual book bibliography page, circulation) can be accessed when not logged in
- book titles in member borrowing activity and card detail should link to book bibliography page

**Comment by clmahoney** [comment]
- YES, I can click on the books link in the main menu
- YES, I can click on the books link in the footer menu 
- YES, I logged out and then went to explore the book page. I was able to use the search bar, click through the individual book detail pages, see the circulation of the book on the individual book detail page, and also filter by circulation dates
- YES, if I click through the member page to an individual member detail page showing what they borrowed, I can click the book and it takes me to the book detail bib page
