### ISSUE TITLE
As a content editor, I want to edit the homepage tagline so that I can update it when necessary.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#587]
## notes for testing
Edit the homepage in wagtail and change the "search description" in the 'promote' tab — your changes should be reflected on the homepage.

**Comment by clmahoney** [comment]
- YES this works! I was able to go to the homepage on wagtail, go to the "promote" section, and change the search description tag. I could see it immediately once I published it. I couldn't see it in preview, though, it says Bad Request (400).

**Comment by rlskoeser** [comment]
That bad request concerns me, it isn't happening in production. Let me take a look.

**Comment by rlskoeser** [comment]
Ok, discovered that it was caused by the wagtail site configuration, which wasn't changed the last time we copied over data from production. Not a cause for concern with this feature.

**Comment by jkotin** [comment]
This works beautifully.  Thank you for asking me to check it @rlskoeser
