### ISSUE TITLE
Replace the breadcrumb home icon with the breadcrumb shakespeare icon on the third and fourth level pages to shorten the breadcrumb

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#588]
[Home icon breadcrumb not showing up on “Activities”, "Circulation" and “Cards” tabs (on third level pages) – instead the “home” with the logo icon is shown on all pages.
](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5e8b9985eae3c91ee509b86d)

-  Level of importance: This will be helpful to have since the breadcrumb does get long on the third and fourth level pages, but is not crucial.

**Comment by thatbudakguy** [comment]
i thought that we didn't need to do this on desktop, since we nearly always have space for the word "home"? it should get replaced with just shakespeare's face on mobile for sure.

**Comment by gissoo** [comment]
I wouldn't mind if it is applied to all devices – but don't feel strongly either – only on mobile would be the minimum level of action taken on this, agreed it's more urgent on mobile!

**Comment by rlskoeser** [comment]
It was already working properly on mobile, and I had already adapted that existing style from mobile to be applied when there are four breadcrumbs before you two discussed this.

I think it does help - even though we have space for it on desktop, that's a lot of text.

@gissoo test site is updated with my change, do you want to review and sign off?

**Comment by gissoo** [comment]
@rlskoeser Thank you!! It looks SO much better now!! You're awesome!
