### ISSUE TITLE
Highlight the selected search filters on the "Member" page on mobile to make it more easily visible to the user

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#589]
[The menu items on mobile are not highlighted in green when selected](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5de94a31aac7327f1f9ef8af) – would be really great if they did.

- Level of importance: This is important because it really helps the visibility on mobile of what is selected and what is not.

**Comment by rlskoeser** [comment]
@gissoo this change is on the test site for you to review now

**Comment by gissoo** [comment]
@rlskoeser This is amazing!! Thank you so much!! I tested on safari, chrome, and firefox on desktop (by adjusting the window), and on my iPhone SE.
