### ISSUE TITLE
As a content editor, I want to edit and add new subscription categories so that I can document them as I discover them.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#59]
## Notes for testing
You should now see a 'subscription types' listed in the Library Accounts section of the admin dashboard.
2018/01/25 - updated content editor group permissions to correct error found in first round of testing

---

## Development notes
Currently a choice field; convert to foreign key, and add notes field to the new model.

**Comment by clmahoney** [comment]
I don't see this but is it because I'm not admin?

**Comment by elspethgreen** [comment]
It's actually a function within adding a new subscription event.  See the + sign next to category?
![screen shot 2018-01-21 at 2 59 56 pm](https://user-images.githubusercontent.com/12616678/35198364-cf16bf70-febb-11e7-873d-f8122eb14b58.png)
This is something that we'd want to decide as a group before we added anything, but we wanted to build in flexibility so we wouldn't have to ask Rebecca for help every time we discovered a new subscription category.

**Comment by rlskoeser** [comment]
I forgot to update the content editor group permissions to include the new subscription types!  @clmahoney I'm so glad we have you testing without superuser permissions so we caught this.  

I'll go ahead and flag as tested needs attention so I remember to fix.

**Comment by clmahoney** [comment]
No problem, that's what I'm here for!

**Comment by rlskoeser** [comment]
@clmahoney the permissions should be fixed on this one now too, so please take another look.

**Comment by clmahoney** [comment]
Yes this looks good!
