### ISSUE TITLE
Apply the styles for finding aids and copyright icons on the card gallery and card image viewer pages to make it clearn that they are interactive

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#590]
[The finding aids and the copyrights – whichever is a link – do not have the link style that was agreed upon.](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5de686bfd9cb7d4889f57ba7) 

Applies to all the card gallery + card image viewer pages: 
- [Member Card section on Zeplin](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14?seid=5de68c9ac7d1c5571b1ec480)

- [Book Card section on Zeplin](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14?seid=5eb17cb2154367197b7a2776)

- Level of importance: This is important because without the style it is not clear that the icons are interactive/clickable.

**Comment by rlskoeser** [comment]
@thatbudakguy I'm wondering if this broke when you switched to using `text-underline` — do we need to add back the border style for image links only?

**Comment by thatbudakguy** [comment]
@rlskoeser that would make sense, yeah

**Comment by gissoo** [comment]
@thatbudakguy These look great!!! You're AWESOME!!! 

I assume there are people whose cards are not on finding aids and therefore the finding aids link won't be active for them, like the person below. On desktop for Safari, Firefox, and Chrome the finding aids icon changes color on hover to a slightly different grey, I think if we can disable that it would be better, so it won't change color at all, if not too much work. 
![Screen Shot 2020-05-26 at 2.27.49 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/6fcf5e0a-65c3-48ec-9628-79ce4aa7e135)

On iOS Safari and Firefox the inactive finding aids icon turns orange on select for a fraction of a second :D which is barely noticeable so I think it's fine, on iOS Chrome it behaves the same as desktop, turning to a slightly different grey, but again not noticeable so it's fine for mobile.

**Comment by thatbudakguy** [comment]
@gissoo thanks for the images & the clear explanation here; it helped a lot!

**Comment by gissoo** [comment]
@thatbudakguy I tested all! These look perfect now! Thank you!!!
