### ISSUE TITLE
Make the text inside the breadcrumb horizontally centered to make it look visually correct

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#591]
All the text inside the breadcrumb containers are still off-centered – any way to fix that so they are horizontally centered?

- Level of importance: It's just killing me visually, may not be noticed by the user, the user may not be affected in any way.

**Comment by rlskoeser** [comment]
@gissoo I tweaked the styles a bit, would you look at the test site and see if this is any better?

**Comment by gissoo** [comment]
@rlskoeser OMG!!! You're AWESOME!! Thank you!! This is great!!!
