### ISSUE TITLE
convert data export field names to use underscores instead of spaces

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#596]
## testing/review notes
Check that field names in CSV and JSON for all exports now use underscores instead of spaces; sanity check that data still looks correct.

**Comment by clmahoney** [comment]
Sorry @rlskoeser but can you give me an example of a field name so I know where to look?

**Comment by rlskoeser** [comment]
Ha, sorry @clmahoney ! By field name, I mean the labels of the fields in the data: that is, the header row in the CSV files, and the text before the `:` in the JSON files.

**Comment by clmahoney** [comment]
I feel like I'm still not looking in the right place but I don't see any spaces OR underscores!

**Comment by rlskoeser** [comment]
@clmahoney So sorry I gave you the wrong version of the exports, you're right that there weren't any underscores! Here is a [new set of exports](https://drive.google.com/drive/u/0/folders/18WVkpMbVwRREpV19GUR6A6ZGfmfc4-hX) that actually reflect the change I wanted you to check.

**Comment by clmahoney** [comment]
- YES, I checked that the field names in all data exports in both CSV and JSON formats have underscores instead of spaces!
