### ISSUE TITLE
Include membership years in member export and circulation years in book export

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#597]
## testing notes
- Check that the member export now includes a `membership_years` field that lists all years a member had activity
- Check that the book export now includes a `circulation_years` field that lists all years a book circulated

**Comment by clmahoney** [comment]
- NO, when I opened the member CSV and JSON in OpenRefine I can't see a "membership years" field
- NO, when I opened the book CSV and JSON in OpenRefine and I also can't see a "circulation years" field 

Maybe the old exports are in the export folder??

**Comment by rlskoeser** [comment]
@clmahoney I'm so sorry, I don't see them either! I must have given you the wrong version of the files! 😞

**Comment by rlskoeser** [comment]
@clmahoney I generated a [new set of exports](https://drive.google.com/drive/u/0/folders/18WVkpMbVwRREpV19GUR6A6ZGfmfc4-hX), please use them for testing this.

**Comment by clmahoney** [comment]
@rlskoeser no problem! Thank you for updating!

**Comment by clmahoney** [comment]
- YES, the members export has "membership_years" as one of the fields in both CSV and JSON!
- YES, the book export has "circulation_years" as one of the fields in both CSV and JSON!
