### ISSUE TITLE
Make all the link styles 2px wide 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#600]
There are currently more content on the site that are "links" and need the link styles since the last time I focused on link styles. The link styles on the site are all too thin now and barely visible – the original link styles won't work either since they are too thick. 

Please make them 2px wide instead of what they are now. (It would be visually between the current and the original versions). [Here is what it would look like](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5cc1f6573a47dd3de1a6879a).

Level of importance: Important because it's barely visible that a content is a "link" right now.

**Comment by rlskoeser** [comment]
@gissoo what browser were you on when you noticed this? Asking because I primarily use Chrome and the underlines are much thinner, I think since @thatbudakguy switched to use the text-underline style that skips descenders (I think he noted at the time that the underline thickness can't be styled on chrome). It does seem like a concern that the underlines are so thin.

**Comment by gissoo** [comment]
@rlskoeser Interesting – I've been on Firefox.

**Comment by thatbudakguy** [comment]
just to make sure we're all on the same page - i just checked chrome, safari, and firefox and saw a uniform underline thickness of 2px, which is what's set in the css.

@gissoo can you take some screenshots to show the difference? I suspect that we might instead be talking about the distance the underline is from the text (which unfortunately chrome does not support controlling, though safari and firefox do).

**Comment by rlskoeser** [comment]
@thatbudakguy I think you may have fixed this in your active filters changes.

**Comment by gissoo** [comment]
@thatbudakguy @rlskoeser I noticed this got fixed for a day or two, and then it has come back again :D 

No, as far as I can tell visually I'm talking about the thickness of the line, unless it is affected by something that has to do with the distance of the line with the text implementation-wise. 

Right now, it's again thin in chrome and firefox, and it looks correct on Safari. Here they are in the following order: (Chrome, Firefox, Safari)

![Screen Shot 2020-05-19 at 3.19.37 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/5a88179d-a516-4fa2-9f62-80ec190f5307)
![Screen Shot 2020-05-19 at 3.25.47 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/c904a7d4-5c0e-4742-b464-be0eb7d2af18)
![Screen Shot 2020-05-19 at 3.20.19 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/9f880337-6d11-4755-b8e2-719aae784c3f)

**Comment by thatbudakguy** [comment]
@gissoo as per our conversation when discussing the map, would you mind checking if your browser versions are all up-to-date and then trying again?

**Comment by gissoo** [comment]
@thatbudakguy Thanks for writing. After we talked last week I updated all my browsers :D 
I'll test this again today. At the moment I'm having issues with accessing the test site (on my side, trying to fix in a few minutes)

**Comment by gissoo** [comment]
@thatbudakguy I tried this again now. Thank you!!! They all look perfect on mobile. The only one that still shows very thin lines is Chrome on my desktop (I tried two machines and updated not only the browsers but also one of the machines :D – I really don't know what's wrong with the chome on desktop, it's okay on mobile). But I think it's not a big deal and it's fine.

**Comment by thatbudakguy** [comment]
fantastic - thank you for trying them all out!! go ahead and close the issue if you think it's done.
