### ISSUE TITLE
anchor link to table events can be hidden by sticky table header

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#605]
One observation: this only has happened once, but when I was searching for the "Life and Letters of Emily Dickinson" on Leo Stein's card, when I clicked the card where the event took place it highlighted the event but it was soooo far up at the top of the screen that at first I couldn't see it was highlighted at all. I tried to take a screenshot of it: 
![Screen Shot 2020-05-07 at 10 47 36 PM](https://user-images.githubusercontent.com/16673934/81365478-396b4380-90b6-11ea-8245-d36bd5064f20.png)
--> if you look up at the very top there's the pale blue highlight but I almost missed it. I think this has something to do with the fact that the borrow is the FIRST on the card? I tried again with other books that appear first on the card and this happened every time. Not a big deal at all, but worth noting if you guys know how to fix it. (Or maybe it's just my small laptop screen's fault?)

_Originally posted by @clmahoney in https://github.com/Princeton-CDH/mep-django/issues/264#issuecomment-625603211_

Both @rlskoeser and @thatbudakguy looked into this problem, but typical css solutions don't apply here because we're dealing with table elements.

**Comment by jkotin** [comment]
I think this is fixed, but let me know if there are specific instructions for testing.

**Comment by rlskoeser** [comment]
@jkotin sorry I didn't write testing notes. Here's a specific example so you can compare the behavior between production and test and confirm this is fixed:

https://shakespeareandco.princeton.edu/members/bernheim-antoinette/cards/cfd8a318-28a4-47d1-8c14-e06ccec95e7d/#e11218

https://test-shakespeareandco.cdh.princeton.edu/members/bernheim-antoinette/cards/cfd8a318-28a4-47d1-8c14-e06ccec95e7d/#e11218

**Comment by jkotin** [comment]
Excellent!
