### ISSUE TITLE
As a content editor, I want to see if people in the personography are in the logbooks rather than just that they have an account, because it tells me what data is available for them.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#61]
- remove the `has_accounts` from person list and edit form
- add an `in logbooks` property to list and edit views: base on presence of subscription or reimbursement event
- an 'in cards' property will be added to list and edit views later, based on presence borrowing events (card data is not yet included, so that can't be implemented yet)

**Comment by elspethgreen** [comment]
Did a quick spot check to see if non "in-logbooks" looked like borrowing card people, and they do!
