### ISSUE TITLE
member data export does not include postal code / arrondissement

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#611]
## Notes for testing
Check [new test member export data](https://drive.google.com/drive/u/0/folders/1wCPd4iD2kNGflsmVSJ6z6FhlJx7ETDl3) to confirm that postal codes and arrondissements are included and have the correct values. Check both CSV and JSON; check members with multiple addresses, no addresses, and addresses that are outside of Paris (should not have an arrondissement).

**Comment by rlskoeser** [comment]
@jkotin your sense of priority? Should we include both postal codes and arrondissements?

**Comment by jkotin** [comment]
@rlskoeser I think we should do this before we deposit the 1.0 export.  But it doesn't need to happen right now.  I think we should include both postal codes and arrondissements -- the former might be useful for people making maps using Google, the latter for historical accuracy.

**Comment by clmahoney** [comment]
CSV: 
- YES, I saw that arrondissement and postal codes are now included in the export
- YES, members with addresses in Paris have correct arrondissments and postal codes noted
- YES, members with multiple addresses in Paris have multiple arrondissments and postal codes included  - checked Antoine-May 
- YES, members who live outside of Paris don't have arrondissments - checked M.E. Adkins, whose address is in Nice 

JSON: 
- YES, I saw that arrondissement and postal codes are now included in the export
- YES, members with addresses in Paris have correct arrondissments and postal codes noted
- YES, members with multiple addresses in Paris have multiple arrondissments and postal codes included  - checked  Antoine-May again 
- YES, members who live outside of Paris don't have arrondissments - checked Mme R. Aeschlimann, who lives in Arles
