### ISSUE TITLE
Create a separate data export with member addresses so fields are broken out separately and easier to work with

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#612]
Suggestion from @muziejus :
> I also wonder if it might not make sense to disaggregate places from
members, anyway; create two related tables w/ a many-to-many
relationship. That would help show addresses with many members as well
as members with many addresses. That's almost done with the JSON as
is, but there are two separate arrays, one for addresses and one for
coordinates. The structure might instead be something like:
```
addresses: [
  {
    id: "6-rue-thomas-mann",
    address: "6 rue Thomas Mann",
    arrondissement: 13,
    latitude: 48.830465,
    longitude: 2.3788083,
    memberIds: [ ... ]
  },
{
    ...
  }
]
```

**Comment by rlskoeser** [comment]
Not sure what priority this will be for us, but wanted to document the suggestion received via email (hope that is OK @muziejus!).

**Comment by rlskoeser** [comment]
Even better would be if we use [GeoJSON](https://geojson.org/)

**Comment by quadrismegistus** [comment]
We're splitting this out and tracking work on #790
