### ISSUE TITLE
lending library cards are listed out of order

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#615]
## testing notes
Check accounts that have events on other cards as well as accounts with multiple cards who do not to confirm that order is as expected.

---
The query that adds other cards where a member has events broke the order #599

**Comment by clmahoney** [comment]
@rlskoeser the regular card order looks fine, but the members on multiple cards is giving me that broken card image. Ex: Pierre Denis (shows up on s2 of Leibowitz): 
![Screen Shot 2020-05-15 at 10 09 09 AM](https://user-images.githubusercontent.com/16673934/82059529-277c3880-9694-11ea-8fe1-fe8cd6126bb6.png)

**Comment by rlskoeser** [comment]
That's the card image I broke on purpose so we could test the missing image (IDK why I chose such an important image for testing other things!).  I just reimported the manifest so it will display correctly on the test site again.

**Comment by clmahoney** [comment]
YEs this works!
