### ISSUE TITLE
person field edit order in admin leads to non-standard slugs

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#616]
## testing notes
Check the admin edit form for persons to see that editing still works properly with the revised field order. Slug field should automatically populate based on sort name (although can be edited), and help text should include the preferred format.

**Comment by jkotin** [comment]
I don't understand what to check here.  @clmahoney do you?

**Comment by clmahoney** [comment]
YES this works!

**Comment by clmahoney** [comment]
@jkotin Go to the people page and add a person; when you add in their name and hit tab, the slug will generate

**Comment by jkotin** [comment]
@clmahoney thank you!  I worried that it was more complicated than that.
