### ISSUE TITLE
Public Notes Display on Book Pages / spacing is off

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#620]
The public notes appear on the book pages too close to the creator/bibliographical information.

<img width="1023" alt="Screen Shot 2020-05-15 at 9 08 24 AM" src="https://user-images.githubusercontent.com/12616674/82223230-64446b80-98f0-11ea-94c9-d9c13cc734eb.png">
<img width="1204" alt="Screen Shot 2020-05-17 at 12 02 37 AM" src="https://user-images.githubusercontent.com/12616674/82223245-68708900-98f0-11ea-915e-fe8986bac8eb.png">

**Comment by gissoo** [comment]
@thatbudakguy Okay so currently looking up "Buddenbrooks" and "The Diary of Samuel Pepys" on the _test site_ doesn't bring up any notes like they are now on the live site :D 

But I'm testing with "The 12:30 from Croydon" and "1919" (which has a "hello there" as its public note – perhaps done by you for testing) – the public notes look fine on all browsers on desktop and iOS. 

![Screen Shot 2020-05-26 at 2.57.12 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/c77a5236-57d9-4b18-9122-966685c77dfa)
![Screen Shot 2020-05-26 at 2.57.43 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/57e2d957-4d88-4115-83e7-cd9b7662d7d7)

Thank you!!!
