### ISSUE TITLE
As a content editor, I want to add basic formatting to public notes so that I can differentiate titles from authors and dates.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#621]
## testing notes
- in the admin interface, add [markdown formatting](https://www.markdownguide.org/cheat-sheet/) to public notes for one work and one person (suggest at least: italics, bold, link)
- view work bibliography page and check that the note is rendered with formatting
- view person biography page and check that the note is rendered with formatting
- check one work and one person with unformatted notes to make sure they still display as expected

## dev notes
- [x] install django-markdownify and add to installed apps
- [x] use markdown filter on notes in member and work detail templates
- [x] revise help text for public notes to indicate markdown is allowed
- [x] unit tests to confirm markdown working in templates

**Comment by clmahoney** [comment]
@rlskoeser Sorry but I need more clarification! Do I do this work in test-admin?

**Comment by rlskoeser** [comment]
@clmahoney yes, sorry! Edit the public notes in the admin for person and work.

**Comment by clmahoney** [comment]
- YES, this works for the Books public notes! I tried all kinds of formatting for public notes, and had fun with it: bold, italics, link, numbered list: 
![Screen Shot 2020-05-21 at 5 14 12 PM](https://user-images.githubusercontent.com/16673934/82607367-a7b80780-9b86-11ea-9b4e-498b72bb5073.png)
- YES, this works for Member public notes too! I fiddled with Abbott's public notes: 
![Screen Shot 2020-05-21 at 5 17 03 PM](https://user-images.githubusercontent.com/16673934/82607556-03829080-9b87-11ea-91d3-fe694b137e87.png)
- YES, regular non-formatting public notes work fine. I tried with Dos Passos' 1919 and with Ernst Olto Abel. 

@jkotin do you want to try?

**Comment by jkotin** [comment]
This is perfect! @rlskoeser and @gissoo -- would it be OK with you if I occasionally include links in the public notes?  For example: 

https://test-shakespeareandco.cdh.princeton.edu/books/congreve-best-plays-old/

If it's OK, could we make those links open in a new window?

**Comment by rlskoeser** [comment]
@jkotin I think it's great that you can include links, it seems like it will add a lot of value; I don't have any problems with that. I don't know of any way to programmatically make the links open in a new window, and it seems like you might sometimes want to link to pages on the site. 

It looks like this notation might work, depending on our markdown parser:
`[link](url){:target="_blank"}`
You could try it out on the test site to see if it works.
