### ISSUE TITLE
Update the date range format on the member's mobile activities pages to match the mobile circulation page

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#622]
- What needs to match: 1. The format of the date ranges (I don't think it's a good idea to match the column widths here with the circulation page)
[here is the link to the design](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ebc34d5d017727723758ed8)

Currently, the date ranges and the author's name overlap on the site. Attached is an example. ![Screen Shot 2020-05-18 at 3.41.53 PM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/9356381b-78c8-4b59-ac1b-68dfb9e1632e)

**Comment by gissoo** [comment]
@thatbudakguy thank you, this matches the designs now. 

Could we match it to the designs further on both "circulation" and "member borrowing activities" by making the dates align this way:

Feb 1920 – 
Feb 1921

rather than 
Feb 1920 –
 Feb 1921

It doesn't look good when they are not aligned.

**Comment by thatbudakguy** [comment]
I'm staring at that trying to figure out what the difference is....I really can't figure it out?? Can you explain more?

**Comment by gissoo** [comment]
okay :D I had to get creative with this one and use the ruler on my phone to draw it. See here: (I know you might think it's very insignificant but it's very disorienting over time with multiple rows of content)

How it is: 
![Image from iOS (6).jpg](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/09986579-df00-462b-a1cd-108d7a7346ec)

How it was designed to be: 
![Image from iOS (7).jpg](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/8cae6b78-2ccb-4f1d-9b74-72f7d44bb053)

**Comment by thatbudakguy** [comment]
thank you so much for your clear explanation/image!! this only shows up on iOS Safari, which is why I was confused.

**Comment by gissoo** [comment]
@thatbudakguy I should comment here before it's later than it already is. Sorry, this happening on all iOS browsers (FF, Chrome, Safari) for me and it's not only on the borrowing activities page, it's also on the circulation activities page on all iOS browsers. I can make another issue to track it on the circulation activities page if you want since this issue is only related to the members borrowing activities.
