### ISSUE TITLE
Create a "external link" icon 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/mep-django#624]

**Comment by gissoo** [comment]
@rlskoeser @jkotin [Here are all the screens where the icon is applied.](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/dashboard?seid=5eb17d4d9361e31e8fa64210) 

- The purpose of this icon is to communicate that the link will take the user outside of the site. This icon is universally known which best communicates this concept. I only customized it a bit visually. I am assuming this icon is currently only applied to a "read online" link on the bibliography page. (And on any link that takes the user outside of the site/is an external site.)

Please let me know what you think.

**Comment by jkotin** [comment]
This looks great. On desktop and tablet, would the icon look better directly to the right of read online?  If not, I'm happy to accept and close!

**Comment by rlskoeser** [comment]
Icon looks good. I also wondered about the placement on desktop/tablet. 

I had planned to apply the style based on the attribute `target="_blank"` so it would work anywhere. If we add external links elsewhere in paragraph text (e.g., if our markdown filter supports it and Josh includes them in public notes), it could occur in the middle of paragraph text. In fact, we probably do have external links in essays on the site somewhere.

**Comment by thatbudakguy** [comment]
if the purpose is to indicate if the user would leave the site, wouldn't you want to key it on an external URL, rather than if it opens in a new tab?

I think

```css
a[href^=http],
a[href^=https] { // show the icon }

a[href*=shakespeareandco],
a[href*=localhost] { // hide the icon }
```
...would show it for all non-relative links by default and hide it for any that point to a location with `shakespeareandco` in the URL or are localhost (dev server).

**Comment by rlskoeser** [comment]
thanks @thatbudakguy totally logical, I mixed up the reason we were doing this with the actual functionality

**Comment by thatbudakguy** [comment]
also should've mentioned: agree with @rlskoeser and @jkotin that the placement to the right of the link is logical wherever we have space

**Comment by gissoo** [comment]
@jkotin @rlskoeser @thatbudakguy Thanks for writing. Should have mentioned that the reason I have positioned the icon this way is that it's the most commonly used position for it and would help the icon in being recognizable (it does add meaning to it visually here). 

I can lower it further but I don't want to align it completely with the link, I think the visual meaning here is more important than the logic with spacing (something I would agree on normally)

**Comment by rlskoeser** [comment]
@gissoo can you provide an example of how it will look on an external link in paragraph text? There are examples in the [card source essay](https://shakespeareandco.princeton.edu/sources/cards/)

**Comment by gissoo** [comment]
@rlskoeser Thanks for pointing out, I wanted to ask where else this will apply so I can mock up. Anywhere else other than the example you just provided?

**Comment by rlskoeser** [comment]
@gissoo sorry I didn't answer — I can't think of any, I think having one example in paragraph text should be enough.

**Comment by gissoo** [comment]
@rlskoeser @jkotin @thatbudakguy I've revised the position of the icon for desktop and tablet based on my previous comment. Please let me know what you think. All the pages where the icon is currently needed are:
- [Bibliography pages](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/dashboard?seid=5eb17d4d9361e31e8fa64210) 
Note: On these pages the icon is shown with the first link on the page.
- [Analysis single/article pages – this is the updated text style page for an Analysis article](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5d93a677385f8d027baeb21f)
- [Sources single/article pages – this is the updated text style page for a Sources article] (https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5d93a677e4bb44026864f4c5)

**Comment by jkotin** [comment]
Looks good to me. I sign off.

**Comment by rlskoeser** [comment]
@gissoo on "Bibliography - Ex 3 - Tablet - V5" the icon is still above and to the right of the text — is that intentional or did you miss updating that one? 

Assuming that you just missed updating that one, I also think these styles look good and can sign off.

**Comment by gissoo** [comment]
@rlskoeser Thanks for catching that! Yes, I had missed it. Great! I'll close the issue then since you both agreed to sign off.
