### ISSUE TITLE
subscription purchase date calculation only considered renewals

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#626]
Should revise to check other subscriptions, since a renewal isn't always marked as one.

As part of the checking, generate a report of subscriptions where purchase date ≠ start date to guide review of the changes.

**Comment by rlskoeser** [comment]
@jkotin I think this should exclude supplements, which would logically overlap with an existing subscription. Any other subscription subtypes that should be ignored?

**Comment by jkotin** [comment]
@rlskoeser Agreed, no supplements.  There is only one other kind of subtype: "other," and only seven cases. @i-davis what does "other" mean for subscriptions/memberships?

**Comment by rlskoeser** [comment]
I revised the migration to look at all subscriptions other than supplements (figured "other" was small enough to review manually if any of them do overlap), and documented the steps to undo and rerun this one.

Here's a list of subscriptions from test site data where purchase date is different than start date — I'm hoping this is a good basis for checking them (I think they likely will need manual cleanup, but hopefully it won't be too bad).
Account #3374: Adler	Subscription 1941-04-03/1941-05-03 purchase 1941-03-31
Account #4193: Arbenz	Subscription 1933-12-02/1934-01-02 purchase 1933-11-25
Account #4193: Arbenz	Subscription 1934-01-02/1934-07-02 purchase 1933-12-27
Account #3439: Armistead	Subscription 1933-03-11/1933-04-11 purchase 1933-02-13
Account #3439: Armistead	Renewal 1933-04-11/1933-05-11 purchase 1933-03-17
Account #3439: Armistead	Renewal 1933-05-11/None purchase 1933-04-18
Account #3439: Armistead	Renewal 1933-05-11/None purchase 1933-04-18
Account #3439: Armistead	Renewal 1933-05-11/1933-06-11 purchase 1933-05-03
Account #2291: Ann / Annie Atkin	Subscription 1927-03-14/1927-06-14 purchase 1926-12-17
Account #2291: Ann / Annie Atkin	Renewal 1927-06-14/1927-12-14 purchase 1927-03-26
Account #2291: Ann / Annie Atkin	Renewal 1927-12-14/1928-06-14 purchase 1927-11-15
Account #2462: Miss Banes	Subscription 1927-07-02/1927-08-02 purchase 1927-06-04
Account #1060: Helene Barrows	Subscription 1924-10-06/1924-11-06 purchase 1924-02-01
Account #2853: Mme Boex	Subscription 1940-11-30/1940-12-30 purchase 1940-01-16
Account #3649: Mr. Bondy	Subscription 1936-04-21/None purchase 1936-04-18
Account #4730: Louise Olga Bouniols	Subscription 1936-05-19/1936-08-19 purchase 1936-02-27
Account #4730: Louise Olga Bouniols	Subscription 1936-08-19/1936-08-26 purchase 1936-05-26
Account #697: Mme Bruel	Subscription 1942-01-09/1942-02-09 purchase 1941-12-02
Account #39: Maud Burt	Renewal 1924-07-16/1925-07-16 purchase 1923-09-05
Account #39: Maud Burt	Renewal 1925-07-16/1926-07-16 purchase 1924-09-06
Account #39: Maud Burt	Renewal 1926-07-16/1927-07-16 purchase 1925-09-07
Account #39: Maud Burt	Renewal 1927-07-16/1928-07-16 purchase 1926-09-08
Account #1722: Mrs. P. M. Camfferman	Subscription 1925-11-26/None purchase 1925-11-04
Account #3369: Mr. E. C. Carter	Subscription 1934-01-03/1934-03-03 purchase 1933-10-23
Account #4769: E. M. Churchill	Subscription 1935-06-06/None purchase 1935-05-10
Account #3935: Cleary	Subscription 1939-06-20/None purchase 1939-03-27
Account #581: Nina Cogan	Subscription 1922-03-11/1922-04-11 purchase 1922-02-27
Account #120: Fernand Colens	Subscription 1920-05-01/1920-08-01 purchase 1920-04-07
Account #120: Fernand Colens	Subscription 1940-11-10/None purchase 1939-12-15
Account #3354: Mrs. Coles	Subscription 1933-02-03/1933-03-03 purchase 1933-01-28
Account #3354: Mrs. Coles	Subscription 1933-03-03/1933-04-03 purchase 1933-02-28
Account #4785: Louise Crane	Renewal 1936-02-03/1936-03-03 purchase 1936-01-29
Account #4785: Louise Crane	Subscription 1936-01-03/1936-02-03 purchase 1935-12-28
Account #3634: Eric Crozier	Subscription 1936-05-21/None purchase 1936-05-01
Account #4788: Madeleine Cullerre	Subscription 1940-03-28/1940-09-28 purchase 1940-03-12
Account #4698: Culver	Subscription 1935-06-09/1935-07-09 purchase 1935-05-25
Account #3267: Mr. Donald Culver	Subscription 1936-07-07/1936-08-07 purchase 1936-06-24
Account #6177: Curran	Subscription 1936-07-11/None purchase 1936-05-15
Account #2672: Nathaniel Curtiss	Subscription 1929-05-18/1929-06-18 purchase 1929-04-27
Account #2672: Nathaniel Curtiss	Renewal 1929-06-18/1929-07-18 purchase 1929-05-28
Account #2785: Mrs. G. Davies	Subscription 1939-02-16/1939-03-16 purchase 1939-01-18
Account #2785: Mrs. G. Davies	Renewal 1939-03-16/1939-04-16 purchase 1939-02-27
Account #2785: Mrs. G. Davies	Renewal 1939-04-16/1939-05-16 purchase 1939-03-31
Account #4558: de Wonderstein	Subscription 1935-02-28/None purchase 1935-02-27
Account #2360: Mrs. M. Decker	Subscription 1927-03-28/1927-04-28 purchase 1927-03-03
Account #4796: Mme Delimal	Subscription 1934-12-05/1935-01-05 purchase 1934-11-05
Account #4796: Mme Delimal	Subscription 1935-11-26/1936-02-26 purchase 1935-10-28
Account #744: M. Deniau	Subscription 1922-11-17/1922-12-17 purchase 1922-11-06
Account #1082: Mr. W. Dighton	Subscription 1923-11-22/1923-12-22 purchase 1923-10-29
Account #5209: Domer	Subscription 1941-01-20/1941-02-20 purchase 1941-01-17
Account #5209: Domer	Renewal 1941-02-20/None purchase 1941-02-18
Account #3478: Anne du Brossay	Subscription 1933-06-18/1933-08-18 purchase 1933-04-19
Account #3478: Anne du Brossay	Subscription 1933-06-18/1933-09-18 purchase 1933-04-21
Account #3478: Anne du Brossay	Renewal 1933-08-18/1933-09-17 purchase 1933-07-22
Account #259: Miss Edwards	Renewal 1921-10-04/1921-11-04 purchase 1921-07-11
Account #1572: Mlle A. Estève	Subscription 1925-05-09/1925-06-09 purchase 1925-04-14
Account #2298: Miss Everard	Renewal 1926-09-15/1926-10-15 purchase 1926-07-15
Account #4061: Felix	Subscription 1941-12-12/1942-01-12 purchase 1941-11-14
Account #1111: Mary Fenner	Subscription 1925-04-01/None purchase 1924-10-08
Account #1111: Mary Fenner	Renewal 1925-04-01/1925-07-01 purchase 1925-03-31
Account #1111: Mary Fenner	Renewal 1925-07-18/1925-10-18 purchase 1925-07-11
Account #238: Mr. Fernandez	Subscription 1921-11-19/1922-05-19 purchase 1921-10-15
Account #5381: Fildermann	Subscription 1941-11-07/1942-02-07 purchase 1941-10-20
Account #6392: Fitzgerald	Subscription 1933-04-14/None purchase 1933-01-24
Account #1161: Mrs. Ford	Subscription 1924-04-15/1924-05-15 purchase 1924-04-05
Account #3400: Geoffroy	Subscription 1934-02-07/None purchase 1933-12-05
Account #3400: Geoffroy	Subscription 1936-07-31/1936-08-31 purchase 1936-02-29
Account #3400: Geoffroy	Subscription 1936-07-31/1937-01-31 purchase 1936-03-13
Account #3400: Geoffroy	Renewal 1937-01-31/1937-07-31 purchase 1936-10-01
Account #3400: Geoffroy	Subscription 1937-01-31/None purchase 1936-10-23
Account #4854: Paul Gerbault	Subscription 1936-03-19/1936-04-19 purchase 1936-02-21
Account #4854: Paul Gerbault	Renewal 1936-04-19/1936-05-19 purchase 1936-03-27
Account #4854: Paul Gerbault	Renewal 1936-05-19/1936-06-19 purchase 1936-05-11
Account #4854: Paul Gerbault	Renewal 1936-06-19/1936-07-20 purchase 1936-06-12
Account #3117: Gieberich	Subscription 1929-08-13/1929-09-13 purchase 1929-05-15
Account #4196: Gilbert	Subscription 1934-04-18/None purchase 1933-10-19
Account #596: M. Gilles	Subscription 1941-10-16/1941-11-16 purchase 1941-10-07
Account #596: M. Gilles	Renewal 1941-11-16/1941-12-16 purchase 1941-11-08
Account #4865: Mme Golotine	Subscription 1940-03-06/1940-04-06 purchase 1940-02-29
Account #4865: Mme Golotine	Renewal 1940-04-06/1940-05-06 purchase 1940-04-01
Account #4865: Mme Golotine	Renewal 1940-05-06/1940-06-05 purchase 1940-05-02
Account #4865: Mme Golotine	Renewal 1940-06-05/1940-07-05 purchase 1940-06-02
Account #4667: Gras	Subscription 1935-05-10/None purchase 1935-05-09
Account #4162: Griffin	Subscription 1934-06-02/1934-12-02 purchase 1934-05-30
Account #3623: Guenther	Subscription 1936-03-08/None purchase 1936-02-25
Account #492: Jane Harrison	Subscription 1926-10-07/1926-11-07 purchase 1926-09-09
Account #5893: Heller	Subscription 1933-12-20/1934-06-04 purchase 1933-12-05
Account #386: Mrs. Hervey	Subscription 1922-01-07/1922-04-07 purchase 1921-09-05
Account #405: Mrs. Jackson	Subscription 1928-09-16/1929-09-16 purchase 1927-10-06
Account #405: Mrs. Jackson	Renewal 1929-09-16/1929-12-16 purchase 1928-10-23
Account #1588: Mrs. J. Jackson	Subscription 1927-01-25/1928-01-25 purchase 1926-01-26
Account #1588: Mrs. J. Jackson	Renewal 1928-01-25/1928-04-25 purchase 1927-01-27
Account #1335: Sidney Jones	Subscription 1924-08-09/1924-11-09 purchase 1924-07-23
Account #1335: Sidney Jones	Renewal 1924-11-09/1924-12-09 purchase 1924-10-24
Account #5199: Kamber	Subscription 1940-12-18/1941-01-18 purchase 1940-12-16
Account #2848: Miss Kelsey	Subscription 1929-04-14/1929-05-14 purchase 1929-04-13
Account #2848: Miss Kelsey	Subscription 1929-05-14/None purchase 1929-05-06
Account #2792: Mr. Kennedy	Subscription 1928-07-13/1928-08-13 purchase 1928-06-23
Account #2792: Mr. Kennedy	Renewal 1928-08-13/1928-09-13 purchase 1928-07-24
Account #2792: Mr. Kennedy	Subscription 1928-09-13/1928-10-13 purchase 1928-09-12
Account #1621: Robert Kennedy	Renewal 1927-04-28/1927-07-28 purchase 1927-01-29
Account #1621: Robert Kennedy	Subscription 1927-01-28/1927-04-28 purchase 1927-01-12
Account #3642: Kilihin	Subscription 1936-06-14/None purchase 1936-03-17
Account #3313: Lacroix	Subscription 1929-12-13/1930-01-13 purchase 1929-12-04
Account #4900: Denise Lafoy	Subscription 1942-02-05/1942-05-05 purchase 1941-11-14
Account #4901: Jacqueline Lambert	Subscription 1936-04-15/None purchase 1936-01-20
Account #584: Miss Lavelli	Subscription 1922-08-15/1923-02-15 purchase 1922-02-24
Account #3578: Le Hars	Subscription 1936-06-20/1936-07-20 purchase 1936-06-08
Account #106: M. le Verrier	Subscription 1921-06-15/1922-06-15 purchase 1921-03-12
Account #106: M. le Verrier	Renewal 1922-06-15/1923-06-15 purchase 1922-03-24
Account #106: M. le Verrier	Renewal 1923-06-15/1924-06-15 purchase 1923-04-05
Account #106: M. le Verrier	Renewal 1924-06-15/1925-06-15 purchase 1924-04-06
Account #106: M. le Verrier	Renewal 1925-06-15/1926-06-15 purchase 1925-04-07
Account #2819: Loomis	Subscription 1929-07-13/1929-08-13 purchase 1929-01-16
Account #1398: Mr. Loving	Subscription 1925-11-14/1925-12-14 purchase 1925-11-10
Account #547: Mme Lowenfeld	Renewal 1924-03-19/1924-06-19 purchase 1923-12-28
Account #4927: D. S. S. Mackenzie	Subscription 1939-09-22/None purchase 1939-05-24
Account #4927: D. S. S. Mackenzie	Subscription 1939-09-22/None purchase 1939-07-12
Account #2189: M. Macnaughton	Subscription 1926-12-21/1927-01-21 purchase 1926-10-27
Account #4295: Magdelain	Subscription 1935-07-13/1935-09-13 purchase 1935-07-06
Account #4937: M. Maspero, Hélène Maspero-Clerc	Subscription 1925-04-05/1925-07-05 purchase 1925-02-14
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1925-07-05/1925-10-05 purchase 1925-05-15
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1925-10-05/1926-04-04 purchase 1925-08-16
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1926-04-04/1926-07-07 purchase 1926-02-16
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1926-04-04/1926-07-05 purchase 1926-02-16
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1926-07-07/1926-10-07 purchase 1926-06-28
Account #4937: M. Maspero, Hélène Maspero-Clerc	Subscription 1925-04-05/1925-07-05 purchase 1925-02-14
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1925-07-05/1925-10-05 purchase 1925-05-15
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1925-10-05/1926-04-04 purchase 1925-08-16
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1926-04-04/1926-07-07 purchase 1926-02-16
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1926-04-04/1926-07-05 purchase 1926-02-16
Account #4937: M. Maspero, Hélène Maspero-Clerc	Renewal 1926-07-07/1926-10-07 purchase 1926-06-28
Account #1829: Marie Carroll McGrew / Mrs. Tarn McGrew	Subscription 1935-09-05/1935-10-05 purchase 1935-08-28
Account #3771: Merpoulet	Subscription 1936-12-18/1937-01-18 purchase 1936-11-26
Account #923: Mlle Mourat	Subscription 1923-01-06/1923-04-06 purchase 1922-12-22
Account #923: Mlle Mourat	Renewal 1923-04-06/1923-07-06 purchase 1923-03-23
Account #1217: Dudley Murphy	Subscription 1924-12-19/1925-03-19 purchase 1924-12-16
Account #1217: Dudley Murphy	Renewal 1925-03-19/1925-04-19 purchase 1925-03-17
Account #1217: Dudley Murphy	Subscription 1925-03-19/1925-04-19 purchase 1925-02-11
Account #1525: Mme Oguz	Subscription 1925-11-21/1926-02-21 purchase 1925-10-10
Account #1525: Mme Oguz	Subscription 1926-02-21/None purchase 1926-02-20
Account #1990: E. Oppenheimer	Subscription 1927-04-18/1927-05-18 purchase 1927-03-19
Account #2398: Mr. Oppenheimer	Subscription 1927-10-07/1927-11-07 purchase 1927-05-24
Account #3857: Papee	Subscription 1939-01-01/1939-02-01 purchase 1938-12-02
Account #3367: Perdereau	Renewal 1934-01-01/1934-02-01 purchase 1933-12-23
Account #3367: Perdereau	Subscription 1933-12-01/1934-01-01 purchase 1933-11-22
Account #5286: Pereira	Subscription 1941-06-14/1941-06-20 purchase 1941-05-30
Account #1747: Mrs. Perlman	Subscription 1926-06-10/1926-07-10 purchase 1926-05-11
Account #532: Pauline Pfeiffer	Subscription 1922-12-27/1923-03-27 purchase 1922-01-09
Account #532: Pauline Pfeiffer	Renewal 1922-12-27/1923-12-27 purchase 1922-10-26
Account #2331: Mr. Polter	Subscription 1927-02-24/1927-03-24 purchase 1927-01-26
Account #5864: Price	Subscription 1928-10-24/1928-11-24 purchase 1928-10-16
Account #5005: Phyllis Price	Other 1933-06-24/None purchase 1933-06-09
Account #5005: Phyllis Price	Subscription 1933-08-25/1933-09-25 purchase 1933-07-08
Account #5005: Phyllis Price	Renewal 1933-08-25/1933-09-25 purchase 1933-08-09
Account #5009: Howard Putzel	Subscription 1939-06-30/1939-07-30 purchase 1939-06-05
Account #2233: Mme A. M. Reynolds	Subscription 1926-11-16/1926-12-16 purchase 1926-10-27
Account #5023: Mrs. Arthur W. Richardson	Subscription 1929-05-22/1929-06-22 purchase 1929-04-26
Account #5023: Mrs. Arthur W. Richardson	Renewal 1929-06-22/1929-06-29 purchase 1929-06-01
Account #5027: Fanny Rirachowsky	Subscription 1936-09-01/None purchase 1936-08-06
Account #5027: Fanny Rirachowsky	Subscription 1935-08-15/1935-09-15 purchase 1935-07-23
Account #684: Louise Roberts	Subscription 1922-10-21/1923-01-21 purchase 1922-10-13
Account #767: Mr. Robinson	Subscription 1924-11-08/1924-12-08 purchase 1924-08-02
Account #2220: A. Rolo	Subscription 1926-10-10/1926-11-10 purchase 1926-10-08
Account #77: Mlle Royer	Subscription 1920-04-29/1920-07-29 purchase 1920-02-05
Account #77: Mlle Royer	Renewal 1920-07-29/1920-10-29 purchase 1920-05-06
Account #3001: Russel	Subscription 1929-04-30/1929-05-30 purchase 1929-03-13
Account #3745: Samson	Subscription 1940-03-19/None purchase 1940-03-15
Account #4245: Samson	Subscription 1935-04-25/None purchase 1934-11-06
Account #1603: Raymond Scudder	Subscription 1925-11-25/None purchase 1925-11-18
Account #1603: Raymond Scudder	Subscription 1925-11-25/1925-12-25 purchase 1925-11-21
Account #5051: Katherine Seager	Subscription 1929-05-20/1929-06-20 purchase 1929-04-29
Account #5051: Katherine Seager	Renewal 1929-06-20/1929-07-20 purchase 1929-06-06
Account #3643: Seldon	Subscription 1936-04-14/None purchase 1936-04-08
Account #7032: Shannahan	Subscription 1933-12-22/1934-01-22 purchase 1933-12-20
Account #7112: Tracy Shelton	Subscription 1926-10-07/1926-11-07 purchase 1926-09-09
Account #698: Mme Simon	Subscription 1942-03-01/1942-04-01 purchase 1941-09-29
Account #698: Mme Simon	Renewal 1942-03-01/1942-04-01 purchase 1941-10-30
Account #445: Miss Slack	Subscription 1922-01-05/1922-03-05 purchase 1921-11-12
Account #445: Miss Slack	Renewal 1922-03-05/1922-04-05 purchase 1922-01-30
Account #732: Mr. Slivinski	Subscription 1924-12-20/None purchase 1924-03-10
Account #732: Mr. Slivinski	Renewal 1924-12-20/1925-01-20 purchase 1924-07-22
Account #1165: Prue Smith	Subscription 1925-07-26/1926-01-26 purchase 1925-05-30
Account #3401: Sotiroff	Subscription 1932-12-15/1933-01-15 purchase 1932-11-17
Account #1105: Jane Stafford	Subscription 1924-05-03/None purchase 1923-11-06
Account #1737: J. M. Stewart	Subscription 1926-03-07/1926-04-07 purchase 1926-02-05
Account #1737: J. M. Stewart	Renewal 1926-03-07/1926-06-04 purchase 1926-03-06
Account #3569: Symons	Subscription 1936-06-23/1936-07-23 purchase 1936-06-05
Account #1346: D. Taylor	Subscription 1925-04-03/1925-07-03 purchase 1925-01-21
Account #1346: D. Taylor	Renewal 1925-07-03/1925-08-03 purchase 1925-04-29
Account #1143: Mrs. Woodbridge Thayer	Subscription 1925-10-21/1926-01-21 purchase 1925-09-16
Account #2069: Mr. Tracy	Subscription 1927-10-21/1928-04-21 purchase 1927-04-30
Account #5096: Tamara van den Bergh	Subscription 1935-09-12/1935-10-12 purchase 1935-09-05
Account #3597: van Zyl	Subscription 1935-11-25/1935-12-25 purchase 1935-11-02
Account #3597: van Zyl	Renewal 1935-12-25/1936-01-25 purchase 1935-12-09
Account #46: Mlle Vierne	Subscription 1920-10-30/1921-01-30 purchase 1920-10-12
Account #521: Mme Weiss	Subscription 1924-04-17/1924-10-17 purchase 1923-10-18
Account #521: Mme Weiss	Renewal 1924-10-17/1925-04-17 purchase 1924-09-25
Account #1054: Mrs. White	Subscription 1924-07-22/1924-08-22 purchase 1924-04-26
Account #1054: Mrs. White	Renewal 1924-07-22/1924-10-22 purchase 1924-06-25
Account #1054: Mrs. White	Renewal 1924-10-22/1925-10-22 purchase 1924-09-27
Account #3682: Wiley	Subscription 1936-06-13/1936-07-13 purchase 1936-05-19
Account #3682: Wiley	Subscription 1936-06-13/1936-07-13 purchase 1936-05-22
Account #475: Ruth Wise	Subscription 1926-11-18/1926-12-18 purchase 1926-10-21
Account #3443: P. W. Wrenn	Subscription 1933-03-15/1933-05-15 purchase 1933-03-01
Account #5135: Catherine Yarrow	Subscription 1937-09-19/None purchase 1936-10-06
Account #1702: Miss Young	Subscription 1926-07-04/None purchase 1926-06-11

---
Here's how I generated the list: (documenting for myself so I can easily generate in productin)
```
subs = Subscription.objects.filter(start_date__isnull=False).exclude(start_date=F('purchase_date')).order_by('account')
   print('%s\t%s %s/%s purchase %s' % (sub.account, sub.get_subtype_display(), sub.partial_start_date, sub.partial_end_date, sub.partial_purchase_date))

**Comment by rlskoeser** [comment]
@clmahoney not sure the best way to test this one  — I was thinking you could check a handful of the accounts that are listed in my report above as having purchase dates different than subscription dates and report on how things look? Might also be useful to try to think about and document what manual clean up we can expect after this migration.

@jkotin any additional thoughts on the review you'd like to see on this change?

**Comment by rlskoeser** [comment]
FYI, I see one "other" event that was adjusted for Phyllis Price in the list above.

**Comment by jkotin** [comment]
@clmahoney and @rlskoeser it would be great to get @i-davis involved in this testing. He knows the members and membership activities best.

**Comment by i-davis** [comment]
@jkotin @clmahoney @rlskoeser : I'll be happy to help with testing! Is it okay if I can't help till Saturday? Still moving house, but should be done by then!

As for "other" as a subscription type, it's the miscellany, a bucket for subscription types people didn't recognize as a normal, recurrent type, like: "Teacher," "special," and "Fr." I can go back through them this weekend, if you like, and see if I can identify any. I imagine "Teacher" is just a variant of "prof," for instance.

**Comment by rlskoeser** [comment]
@i-davis weekend is fine! Our plan is to release updated code next Thursday, so feedback early next week should allow for time to make changes to the code if you identify anything.

The "other" that we're discussing here is not for the subscription type or category (which I think you're describing), but the subtype of the subscription event — subscription, supplement, renewal, other.

**Comment by jkotin** [comment]
@i-davis Yes, there is a subscription subtype "other," along with "renewal" and "subscription."  See here under "type":

https://shakespeareandco.princeton.edu/admin/accounts/subscription/

There are only 7 or so labeled "other."  Do you know what they are?  Would you investigate?

**Comment by i-davis** [comment]
@rlskoeser Great: weekend it is! 

Oh ah yes I see! My apologies for going too fast & misunderstanding -- & thanks for this clarification!!

Those seven others are:
a) Just noted as "deposit" (Creswick, de Girodon, Bell, Heinemann). Guessing this means they subscribed, took some books, and then actually paid another day.
b) Periodical deposits (Chang, Price).
c) A sassy note about a late payment (Moynahan, whose note says "Moynahan paid up").

**Comment by i-davis** [comment]
@rlskoeser @jkotin @clmahoney : I think I have a couple questions: sorry to come late to the party & need explanations! 

My first question is this: right now, it looks like when the code adjusts someone's start and end dates, it makes the start date be the day after the end date of the last subscription. For instance, the second subscription on Henri and Hélène Maspero's joint account has a purchase date of 19 April 1922, and a start date of 28 April 1922. The start date has been code-adjusted to begin a day after the end date of the previous sub, 27 April 1922. Is that right?

I think that this is wrong, according to Beach's system: subscriptions always ran from the same day, 27 March to 27 April, then 27 April to 27 July, and so on. You can see this on Hélène's card, comparing the initial start date, 27 March, to that note in the bottom right hand corner of this screen shot:

<img width="425" alt="Screen Shot 2020-05-24 at 10 22 14 AM" src="https://user-images.githubusercontent.com/15250325/82756472-82a2df00-9da8-11ea-8b20-0556f29b2c6a.png">

Am I misunderstanding either system -- Beach's or the code's -- do you think? Sorry if so!

**Comment by rlskoeser** [comment]
@i-davis quick response so I'm hopefully not a blocker for you testing today — I got this wrong on the first go-round of implementing this, and we didn't catch it (I should have given a list like this and requested more thorough input & testing on the logic). I tried to correct it in the latest version, but I don't expect it to fix the renewals that were recalculated incorrectly in the first migration. (I think they may need to be corrected manually; will consider more). Can you tell if this error is happening to subscriptions that are not _labeled_ as renewals (i.e. the newly recalculated ones)? Am I still calculating start dates wrong in the revised code?  If it's helpful, you can compare the same subscriptions in production data to see exactly what changed.

**Comment by i-davis** [comment]
@rlskoeser : thanks for this response!! & sorry again to need the explaining! Then yes, the subscriptions that aren't labeled as renewals look right to me, the start dates are good!

**Comment by rlskoeser** [comment]
@jkotin do you want to do any further review on this one?

**Comment by jkotin** [comment]
@rlskoeser no. Will @i-davis need to manually correct the first go round implementation?  If so, would you send him instructions when convenient?

**Comment by rlskoeser** [comment]
@jkotin I expected there would be some manual corrections, but looking at this list I'm not seeing very many — but I'd be glad to confer with @i-davis on that. I was thinking it should be after this release goes out, but maybe I'd better run a query like this one in production before I do the migration so we can compare that also.

**Comment by i-davis** [comment]
@rlskoeser : happy to confer however & whenever you like -- just lmk!
