### ISSUE TITLE
As a user, I want to see circulation information on book search and detail pages so I understand how much and when a book circulated.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#632]
## notes for testing
- check the books list page: each book should include a circulation block with the number of events and years that the book circulated
- check the book biography page: should have the same information (event count & years)
- check both pages against the designs in zeplin for all screens: [book search](https://zpl.io/29xEGqz); bibliography [desktop](https://zpl.io/VKZ8L0A) [tablet](https://zpl.io/bLl0nOB) [mobile](https://zpl.io/bzEeo6M)
- make sure you some books with a few events and some with lots; check books with only one year and check others with several

**Comment by clmahoney** [comment]
Desktop: 
- YES, on the book list page each book now includes a circulation block. See here: 
![Screen Shot 2020-05-28 at 12 49 09 PM](https://user-images.githubusercontent.com/16673934/83170129-10046d00-a0e2-11ea-8ed6-4d6fd57e60ed.png)
- YES, the info matches the info on the individual book biography page: 
![Screen Shot 2020-05-28 at 12 43 47 PM](https://user-images.githubusercontent.com/16673934/83170201-2b6f7800-a0e2-11ea-9a58-5ac3fcf66ab6.png)
- YES, events with a ton of events looks correct. I checked "Portrait of an Artists," which has 63 events. 

QUESTION: I've been checking books with single year circulation/one event. There's a borrow for 1914 and other Poems by member John Varney but the card is appearing twice: 
![Screen Shot 2020-05-28 at 1 08 49 PM](https://user-images.githubusercontent.com/16673934/83171972-ded96c00-a0e4-11ea-8ffb-e18e4f8fa89c.png)

**Comment by clmahoney** [comment]
I've checked other single borrows and don't see the repeat so I'm not sure what's happening with Varney.

**Comment by rlskoeser** [comment]
@clmahoney I think there are two footnotes for that event, can you confirm?

**Comment by clmahoney** [comment]
@rlskoeser yes you're right!!

**Comment by clmahoney** [comment]
@rlskoeser is there any way to to an export to see if there are multiple identical footnotes?

**Comment by rlskoeser** [comment]
@clmahoney no, but I can probably come up with a quick query to check for multiple footnotes — probably not too many events with multiple footnotes, right?

**Comment by clmahoney** [comment]
@rlskoeser I don't think there should be, but it would be good to know and do a cleanup of the repeats so this display issue doesn't happen again. Should I make you an asana task?

**Comment by rlskoeser** [comment]
@clmahoney I will just do it now. Where do you want me to put the list of events I find with multiple footnotes?

**Comment by clmahoney** [comment]
@rlskoeser Thank you! Maybe just in the data work folder in drive?

**Comment by clmahoney** [comment]
Mobile: 
- YES, on the book list page each book now includes a circulation block. See here:
![IMG_2236](https://user-images.githubusercontent.com/16673934/83173217-b2265400-a0e6-11ea-96b5-fe6853812a9f.PNG)
- YES, the info matches the info on the individual book biography page:
![IMG_2237](https://user-images.githubusercontent.com/16673934/83173220-b2beea80-a0e6-11ea-9512-d29f5c508823.PNG)
- YES, books with many events look fine; Pilgrimage on the test site is still bunched together so it has the most events: 
![IMG_2238](https://user-images.githubusercontent.com/16673934/83174167-febe5f00-a0e7-11ea-88a3-31a63cd5a2a1.PNG)

**Comment by clmahoney** [comment]
Tablet: 
- All looks good here too
- YES,  each book has a circulation block with the number of events and years that the book circulated
![101494587_197551764659890_8797318277593300992_n](https://user-images.githubusercontent.com/16673934/83176262-24009c80-a0eb-11ea-9c59-c46fcd4d235d.png)

- YES, the book biography page has the same info! 

![101177344_716178115884630_8615051706775896064_n](https://user-images.githubusercontent.com/16673934/83176270-26fb8d00-a0eb-11ea-9a5b-338b7bf7a266.png)
