### ISSUE TITLE
in some cases, empty facets result in a 500 error on member search page

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#633]
I'm not sure what conditions are causing this, but in the current code you can force an error by editing the query params to pass an invalid choice. 

## notes for testing
Go to members page, apply a filter (e.g. nationality) and then edit the URL in your browser location to change value after `nationality=` to something that isn't a valid nationality. Compare production and test — in production I expect you to see the 500 error; on test, with this change the page should still render.

**Comment by clmahoney** [comment]
- YES, when I altered the URL query to say "Martian" instead of China, on the production page I got an error "Something went wrong" card and when I tried the same in test, I got a clear "No search results found. Try a different search" message. Is that the message I want?

**Comment by rlskoeser** [comment]
Yes, that's exactly what we want! As much as possible, we don't want people to see the "something went wrong" card — it means there was an error we didn't handle properly in the code.

I'll go ahead and close since you tested and confirmed.
