### ISSUE TITLE
split out CI builds

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#634]
as noted in https://github.com/Princeton-CDH/pemm-scripts/pull/45#issue-420883706, we can use travis's build matrix (or similar functionality on github actions) to do the python and js parts of the build separately. see the link for more context.

**Comment by thatbudakguy** [comment]
#677 closes this

**Comment by rlskoeser** [comment]
Merged into develop and working beautifully. Thanks for all the work and initiative on this @thatbudakguy !
