### ISSUE TITLE
search results have blank aria-label

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#637]
from [john's review](https://docs.google.com/spreadsheets/d/1N-oBy9Mp91TEdXEi6rjCMNsbJNacxMh6CEGTHpCRfws/edit?usp=sharing):
> Each <a> row in the member list search results has a blank aria-label, hiding all its text from screen readers. Each link is announced solely as its number on OSX VoiceOver. iOS does better.

**Comment by rlskoeser** [comment]
Confirmed on the test site that search results on the members page have correct aria labels now
