### ISSUE TITLE
As a content editor, when I'm editing accounts I want subscription and reimbursement sections to be open by default so I don't have to click to view membership dates.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#64]
## Notes for testing
2018/01/25 - updated content editor group permissions to correct error found in first round of testing

---

- [x] set sections to open rather than collapsed by default
- [x] rename subscribe to subscription for display (throughout the site)

**Comment by clmahoney** [comment]
When I go to Library Accounts --> Accounts all I see open is the Reimbursements section; I don't see any subscription info. Is that how it always was or should subscription info be there? I can find that info when I go through Library Accounts --> Events. 
![screen shot 2018-01-21 at 1 54 04 pm](https://user-images.githubusercontent.com/16673934/35197768-92a9fde4-feb2-11e7-8811-04266d605e77.png)

**Comment by elspethgreen** [comment]
That's really weird!  When I do this (for the same account, and for others) I get subscriptions and reimbursements (which is what it's supposed to be now).
![screen shot 2018-01-21 at 2 57 38 pm](https://user-images.githubusercontent.com/12616678/35198350-8bea174c-febb-11e7-82c4-fe7a664402fb.png)

Can you check a few more accounts and see if you only get reimbursements?  Make sure you click open all possible tabs.

**Comment by clmahoney** [comment]
My pleasure! I'm always like "oh no!" but I realize now that's good lol

**Comment by elspethgreen** [comment]
@clmahoney could you take another look at this?  The permissions issue should be fixed now.

**Comment by clmahoney** [comment]
This looks good!
