### ISSUE TITLE
atypical card images are displayed incorrectly

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#646]
**Describe the bug**
Lending library cards that include atypical images are not displaying them in the correct aspect ratio.

**To reproduce**
1. Go to the card list for a member like André de la Forest-Divonne that includes an atypical card https://shakespeareandco.princeton.edu/members/forest-divonne/cards/
2. Browse the cards or click into the detail
4. Membership card images are forced into lending card size

**Expected behavior**
Atypical  card images should not be garbled

**Screenshots**
card list 
![Screen Shot 2020-05-28 at 9 26 46 AM](https://user-images.githubusercontent.com/691231/83147493-c27a0700-a0c5-11ea-8175-d78da11f90f2.png)
card detail
![Screen Shot 2020-05-28 at 9 26 52 AM](https://user-images.githubusercontent.com/691231/83147501-c443ca80-a0c5-11ea-8fa8-22178f082577.png)

**Device information**
Impacts all devices.

**Additional context**
Bug is caused by the way placeholder image was added.

**Comment by rlskoeser** [comment]
@thatbudakguy do you know of a simple CSS solution to have a placeholder image for a variety of image formats? When I added the default/placeholder image I constrained the size so it would render properly, but (of course) that messes up the images that are sized differently.

**Comment by rlskoeser** [comment]
Ah, I found the problem. I need to put the background image on the `::before` , which is apparently only rendered if the image _isn't_ rendered.

**Comment by clmahoney** [comment]
- YES this works beautifully. Tried with Forest-Divonne: 
![Screen Shot 2020-05-28 at 2 01 24 PM](https://user-images.githubusercontent.com/16673934/83176657-cc166580-a0eb-11ea-8d74-53ee1a2a1eb5.png)
and
![Screen Shot 2020-05-28 at 2 01 15 PM](https://user-images.githubusercontent.com/16673934/83176667-cde02900-a0eb-11ea-9459-864b6a9be848.png)

**Comment by clmahoney** [comment]
Mobile: works as it should here too! 
Tablet: same!
