### ISSUE TITLE
As a user, I want to see larger size card images so that I can look at cards in more detail and decipher difficult handwriting.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#648]

**Comment by clmahoney** [comment]
- YES, I tried this with issue 646: I tried with Forest-Divonne cards, Killen cards, Aldington cards on DESKTOP, TABLET, and MOBILE. 

Is it fine that on Desktop, I don't see the text above the image that I see on Mobile and Tablet that "Tap image to zoom in/out"? On Desktop, I get the magnifying glass when I move over the image.

**Comment by rlskoeser** [comment]
@clmahoney oh, I should probably have given you links to zeplin — that's exactly what we expect. Magnifying glass cursor for desktop, text for mobile and tablet.

**Comment by clmahoney** [comment]
@rlskoeser OK great! I'll let @jkotin look at this too.

**Comment by jkotin** [comment]
Oh, should I reopen based on the issues @gissoo noticed?

**Comment by rlskoeser** [comment]
Let's leave it closed, but @gissoo would you create a new issue to document the problems you noted?

**Comment by gissoo** [comment]
@rlskoeser sure

**Comment by gissoo** [comment]
@rlskoeser  #650 and #651 were created to track this.
