### ISSUE TITLE
event footnotes can be edited in different places in django admin, which makes it easy to end up with duplicate footnotes

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#659]
## testing notes
This update consolidates all event footnotes so they are always attached to the base (or "generic") event, but makes them visible and editable in django admin on the specific event types.
- check that footnotes have been migrated correctly (not sure how to suggest testing this thoroughly; maybe sanity check the total number of footnotes to see if they are close, spot check a variety of different cases to see if they're all present as expected); one thing you could check is the duplicates — if there were duplicates before (especially cases where there was one on the generic and one on the borrow) you should see them both
- django admin:
   - check that the _same_ footnotes appear on the generic event and specific event edit forms (e.g. a borrow event in the generic view and the borrow view)
   - check that you can edit, add, delete footnotes in both of these views and see the changes in the other view
   - check that you now have the option for footnotes in all event types (new: subscription, reimbursement)
- in the public site, check everything that uses footnotes+events:
   - check member card list display
   - check member card detail view with event list
   - check book card list display

**Comment by clmahoney** [comment]
@rlskoeser I need a bit more clarification; for the admin view, I should be checking Library Accounts-->Events?

**Comment by rlskoeser** [comment]
@clmahoney please check Library Accounts -> Events, Library Accounts -> Borrows, Library Accounts -> Purchases, Library Accounts -> Subscriptions, Library Accounts -> Reimbursements

**Comment by clmahoney** [comment]
- YES, the same footnotes appear on the generic event and specific event edit forms
- YES, I can edit, add, delete footnotes in both of these views and see the changes in the other view
- YES, I can see that there are now footnote options in all event types (new: subscription, reimbursement)

**Comment by clmahoney** [comment]
- YES, everything looks good on the public end as well
