### ISSUE TITLE
As a content editor, I want project-specific data sections displayed first on the admin dashboard so I can easily get to the data I need to work with.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#66]
- display library accounts and people before django specific-stuff; accounts first?

**Comment by elspethgreen** [comment]
Account first would be good!

**Comment by i-davis** [comment]
Guessing I'm getting this wrong somehow: comparing the code & the site, I see that accounts comes first, but personography's still at the bottom. Guessing I'm just not following what you're saying or doing some other thing wrong, but thought I'd say anyway; sorry if this is wrong, no need to respond if it is!

<img width="1037" alt="screen shot 2018-02-15 at 1 25 15 pm" src="https://user-images.githubusercontent.com/15250325/36273874-ebc4b432-1253-11e8-8600-52d22202a038.png">

<img width="520" alt="screen shot 2018-02-15 at 1 27 19 pm" src="https://user-images.githubusercontent.com/15250325/36273891-fabeb474-1253-11e8-9cf9-daafdcd4f81a.png">

**Comment by i-davis** [comment]
Wait sorry: I don't know what happened, but it just righted itself: personography is now second to top. No idea what I was doing....

**Comment by rlskoeser** [comment]
@i-davis I see it too.  This is weird! Thanks for flagging it for us.

@bwhicks could you take a look next week and see if you can figure out what's going on?  (Server not consistently loading the settings? That would be strange, though... ).  I did a quick search on the mezzanine issues on GitHub and I don't see any documented issues that seem related.

**Comment by bwhicks** [comment]
@rlskoeser @i-davis  My guess is that there was a process using the old code that a restart of the webserver didn't properly kill, so once in a while it would be the one responding when you requested the page. 

Post a restart I'm consistently seeing Library Accounts at the top.

**Comment by elspethgreen** [comment]
@i-davis does this look better now?  I think it looks okay

**Comment by bwhicks** [comment]
@rlskoeser @i-davis I was just able to duplicate this too. I had thought it was a server side issue, but it's clearly something odd in Mezzanine.

**Comment by rlskoeser** [comment]
@elspethgreen this may be a bug with the library we're using (Mezzanine).  Ben and I haven't been able to figure out what's going on, since it's only happening sporadically.  I'm puzzled as to why the accounts is always first and the personography is sometimes second and sometimes last (almost as if it's just skipping that line of the order configuration, but that isn't logical).

Can you live with the current implementation even though it's not working perfectly?  We can document as a known issue and revisit if it continues to be a problem.

**Comment by elspethgreen** [comment]
I think it's fine to leave it!  I'll leave the label, but close the issue.
