### ISSUE TITLE
Design // Spacing on long/multiple names with tall letters/accents

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#660]
Not urgent. See screen shot for interference between accent and "p."

<img width="600" alt="Screen Shot 2020-06-06 at 11 54 12 AM" src="https://user-images.githubusercontent.com/12616674/83948646-8c870200-a7ec-11ea-8023-c06a94c39b2a.png">

**Comment by rlskoeser** [comment]
Line height was not set correctly to match the design spec.

@clmahoney available to do a quick check to confirm the fix? https://test-shakespeareandco.cdh.princeton.edu/books/mackenzie-early-life-adventures/cards/

**Comment by clmahoney** [comment]
- YES, the spacing looks fine now! 
![Screen Shot 2020-06-11 at 4 33 45 PM](https://user-images.githubusercontent.com/16673934/84436427-6b198200-ac01-11ea-88bd-696e61484dc9.png)

**Comment by clmahoney** [comment]
Can I close or do we want @jkotin to sign off?
