### ISSUE TITLE
Notation tag // for magazine subscriptions

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#664]
Would be very useful to add a notation tag for magazine "subscription" events that would work the same way as "Gift," "Loan," "Crossed Out."

A number of purchased magazine subscriptions are recorded on the lending library cards. Currently we have no way to represent such purchases, save as purchases of generic issues.  A "subscription" tag would resolve this problem. 

Example - Teissier subscribes to Horizon for 6 months on 12/30:

https://shakespeareandco.princeton.edu/members/teissier-jeanine-delpech/cards/12014b6e-58fa-4722-b349-a918ed232f8c/#zoom

I imagine that we could label the event "subscription" and then use the start and end dates to demarcate the length of the subscription.

**Comment by rlskoeser** [comment]
@jkotin are you thinking of creating generic events with a new notation to indicate the type? That seems plausible to me. If you provide the notation and public label this is easy do add.

**Comment by jkotin** [comment]
@rlskoeser excellent.  This is exactly that I was thinking. How about NOTATION: MAGAZINESUBSCRIPTION -- and the public label: Subscription -- would that work?

**Comment by rlskoeser** [comment]
@jkotin Subscription is ambiguous, can we qualify as magazine or periodical subscription?

**Comment by jkotin** [comment]
@rlskoeser Yes, no problem -- I was worried that it would take up too much space. Let's do "Periodical Subscription" just to keep the diction consistent and change the notation to PERIODICALSUBSCRIPTION.

**Comment by rlskoeser** [comment]
Sounds good to me.

**Comment by rlskoeser** [comment]
@clmahoney test by adding NOTATION: PERIODICALSUBSCRIPTION to the private notes for a generic event (or really any event) and then check how it displays in the activity list or card detail views.

**Comment by clmahoney** [comment]
- YES this looks awesome! I added "NOTATION: PERIODICALSUBSCRIPTION" to Teissier's subscription of Horizon in the test site admin, and viola! 
![Screen Shot 2020-06-11 at 4 45 42 PM](https://user-images.githubusercontent.com/16673934/84437497-11b25280-ac03-11ea-85e3-329b826cb020.png)
