### ISSUE TITLE
Design // spacing for and around non-uniform cards

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#665]
Not urgent // The spacing is off on https://shakespeareandco.princeton.edu/members/stirling-monica/cards/ -- I also attach a screen shot. I imagine this is due to the irregular size cards.
<img width="1295" alt="Screen Shot 2020-06-09 at 9 38 41 AM" src="https://user-images.githubusercontent.com/12616674/84154617-54263480-aa35-11ea-942f-b2e297a865eb.png">

**Comment by rlskoeser** [comment]
Please test https://test-shakespeareandco.cdh.princeton.edu/members/stirling-monica/cards/
Check both desktop or tablet and mobile since mobile differs slightly.

**Comment by clmahoney** [comment]
- NO, I think the spacing if still off. I tried this is on my computer: 
![Screen Shot 2020-06-11 at 4 36 00 PM](https://user-images.githubusercontent.com/16673934/84436589-b3d13b00-ac01-11ea-839a-4d141fc22738.png)

**Comment by clmahoney** [comment]
BUT YES, spacing looks great on mobile! 
![IMG_2306](https://user-images.githubusercontent.com/16673934/84436951-4671da00-ac02-11ea-8bfe-4b6a1e82fa0e.PNG)

**Comment by clmahoney** [comment]
OK I tried again after a forced reload and the computer image looks good too: 
![Screen Shot 2020-06-11 at 4 41 55 PM](https://user-images.githubusercontent.com/16673934/84437130-82a53a80-ac02-11ea-8c3b-3befe1169132.png)

**Comment by clmahoney** [comment]
Although, I feel like I'm seeing things but I think the spacing still isn't quite the same?

**Comment by clmahoney** [comment]
Am I look at spacing between cards or space with the dates beneath?

**Comment by rlskoeser** [comment]
@clmahoney the most important thing is that the images that are different sizes (I think the last three in this case) display correctly and don't get squished into the usual lending library card size — compare this page on the test site and production (or Josh's screenshot) to see.

**Comment by clmahoney** [comment]
Oh I finally see it! Thank you! I compared it to the production site and can clearly see now that the odd-sized images are NOT getting squished anymore!
