### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#668]
Not urgent, but search results seem counter-intuitive.

An example, I search for "Charles First," and expect to find "Charles the First" by Belloc. But that result is 62. See screen shots.

<img width="1263" alt="Screen Shot 2020-06-14 at 10 01 06 PM" src="https://user-images.githubusercontent.com/12616674/84611145-f194c480-ae8a-11ea-8d49-90d77ae207f4.png">

<img width="1263" alt="Screen Shot 2020-06-14 at 10 01 33 PM" src="https://user-images.githubusercontent.com/12616674/84611217-26a11700-ae8b-11ea-84fe-95eb8146af45.png">

**Comment by rlskoeser** [comment]
@jkotin is this any better based on the revisions to search configuration in 1.1.1 ? 

I think this behavior is due to the higher boosting we've applied to authors over titles.

**Comment by jkotin** [comment]
Yes, seems much better.  I'll keep using and report!

**Comment by jkotin** [comment]
Should I close for now or close later once I've done more searches?

**Comment by rlskoeser** [comment]
@jkotin you can leave it open until you've investigate more — but if you leave it open, please make it more specific

**Comment by jkotin** [comment]
Still some counter-intuitive search results. I search for the journal La Revue de Paris and I get this result:

<img width="1048" alt="Screen Shot 2020-06-16 at 3 22 55 PM" src="https://user-images.githubusercontent.com/12616674/84819091-78f64b00-afe5-11ea-9093-5fc017bce01f.png">

I then remove the article "La" and I get the result that I was looking for:

<img width="1048" alt="Screen Shot 2020-06-16 at 3 23 07 PM" src="https://user-images.githubusercontent.com/12616674/84819180-99bea080-afe5-11ea-9568-013b057ff4a8.png">
