### ISSUE TITLE
Remove volume/issue list on bibliography page

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#670]
I've received feedback that the volume/issue list on the bibliography page is confusing. The list implies that _only_ the listed volumes/issues circulated, when in fact the list only includes the volumes/issues that we _know_ circulated. Consider _The American Mercury_ to cite a random example:

https://shakespeareandco.princeton.edu/books/mencken-american-mercury/

The bibliography page lists nine issues. But there are 15 events -- for six of those events we don't know which issues circulated. Likely different issues than the ones listed.

**The solution to this problem: delete the volume/issue list from the bibliography pages. Keep the volumes and issues on the circulation and member activity pages only.**

There are other problems with the volume/issue list on the bibliography page. For example, our asymmetrical practice of listing all the volumes of multivolume works, regardless of whether we know for certain that they circulated, and only listing the periodical issues that we know for certain circulated.  The solution would solve that problem too.

I'm hoping that this won't be a labor-intensive fix. The solution will also save Cate significant research time as she turns to the multi-volume works this week.

**Comment by rlskoeser** [comment]
@gissoo do you have any concerns about removing volume/issue list from the bibliography page?

**Comment by gissoo** [comment]
@rlskoeser @jkotin I finally got a chance to read the comments and think about this. I agree that removing it from the Bibliography page makes sense at this point, it's not contextual information, and it deserved to be questioned and argued about more at the time we were working on it.

**Comment by jkotin** [comment]
Thank you so much @gissoo !

**Comment by rlskoeser** [comment]
@jkotin please review on the test site to confirm volume/issue list has been removed from bibliography page.

**Comment by jkotin** [comment]
Perfect.
