### ISSUE TITLE
author/title overlaps on mobile borrowing card view for authors with long names

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#671]
Not urgent. Book titles interfering with long author names.

https://shakespeareandco.princeton.edu/members/culver-donald/borrowing/

<img width="826" alt="Screen Shot 2020-06-18 at 6 46 08 PM" src="https://user-images.githubusercontent.com/12616674/85079137-11cac900-b194-11ea-828c-97e594e26a70.png">

**Comment by rlskoeser** [comment]
I decreased the space given to authors on mobile, please confirm that it fixes the problem and doesn't introduce new display problems.

**Comment by jkotin** [comment]
Looks good: I scanned the activities of the library's heaviest borrowers. No overlaps or new display problems that I can see.
