### ISSUE TITLE
Partial date autopopulation//duration information unsaved

### ISSUE THREAD

**Issue by i-davis** [Princeton-CDH/mep-django#674]
## testing notes
- try creating or saving a subscription with unknown year where the start and end date span subsequent years (e.g., a december to january subscription); check that duration is set properly
- try adding a footnote to a subscription like the above

---
When a partial date (a year with no month or day, or a month and year with no day) is entered, the database autopopulates the missing day/month fields with 01. When month and day information is missing, the database will not save duration information.

Example: 
The 1936 book records Walter Agard as subscribing for 1 m 1 v in 1932. (Only the year--not the month or day.) 
His subscription info is entered as: Start Date: 1932; End Date: 1932; Purchase Date: 1932. 
On his account page, this is clear. 
On his member page, the start, end, and purchase dates are all January 1, 1932 -- so it looks like his subscription lasted only a day.
If you try to save the duration as 1 month, the database will not accept that: the duration box is simply left blank after you hit save. There is no error message.

Options: 

1. Enter false months/days so that we can record the duration of the subscription as one month, and leave a public note that they are false dates.
2. Leave as is and note publicly that the duration was 1 month.
3. Fix the database so that it will record a 1 month duration.

**Comment by cvansant** [comment]
On the admin site, the year defaults to 1900. That is, "--12-01" becomes December 1, 1900. However, no year appears on the front end. 

The footnote worked. 

Question: What about cards that are entirely undated? Is that part of this issue or a separate issue?

**Comment by cvansant** [comment]
To answer my own question above: Yes, I can now add footnotes to cards that are entirely undated! 

@rlskoeser Is it okay to go ahead and add membership events from undated cards, or should I wait until the situation about the year defaulting to 1900 is resolved?

**Comment by rlskoeser** [comment]
@cvansant can you tell me where exactly you're seeing the 1900s in the admin site? It might be something we just live with, but I'd like to know so I can check.  

(Internally it is stored as 1900 with a flag to say we don't actually know the year; as long as it's displaying correctly on the public site it's probably fine.)

**Comment by rlskoeser** [comment]
@cvansant thanks for catching that — I've updated the person change form to use the partial date, please confirm it's resolved.

**Comment by rlskoeser** [comment]
Confirmed by @cvansant slack that this looks good now.
