### ISSUE TITLE
As a content admin, I want to export information about creators from the database so I can work with the data using other tools.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#684]
Create fourth data export with information on creators, including VIAF links. 

I'm not sure about the best way to link with the other exports. Links to their books/items that circulated? Ideas for fields: name, sort name, creator types, VIAF + associated items? 

## testing notes
- JSON
 - [ ] confirm the structure of the export is as expected (includes the appropriate fields)
 - [ ] confirm the content of the export is as expected (spot check that correct content is in appropriate fields)
- CSV
 - [ ] confirm the structure of the export is as expected (includes the appropriate fields)
 - [ ] confirm the content of the export is as expected (spot check that correct content is in 

[test export available in this google drive folder](https://drive.google.com/drive/folders/13FsEIHpKxdtSMoiL8_MlDzkrZkfBzcHC)

**Comment by quadrismegistus** [comment]
Like https://github.com/Princeton-CDH/mep-django/issues/790, we need a new django manage command that subclasses BaseExport, producing creators.csv.

* Note: it *is* possible to connect Joyce the author and Joyce the member via the Person ID in the django DB.
* Decision we need to make: do we need slugs for creators? Maybe not -- Lastname, Firstname worked well previusly.
* Note: two matching problems: Joyce the member to Joyce the author; Joyce the author-dataset-author to Joyce the book-dataset-author

**Comment by jkotin** [comment]
No JSON files in the Google Drive Folder—sorry if I'm missing something!

**Comment by jkotin** [comment]
I found the new folder! This looks perfect.  The title field for creators is not necessary, but it doesn't do any harm there.
