### ISSUE TITLE
twitter bot — generic event handling

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#696]
**Describe the bug**
Review shows the bot will generate bad tweets for generic events.

> #100YearsAgoToday on Monday, December 20, 1920 at Shakespeare and Company, Mr. Morgan genericed Hilaire Belloc’s “The Path to Rome” (1902). https://shakespeareandco.princeton.edu/members/morgan/cards/18bc6719-bd3d-467f-9f14-88bf13b29188/#e33082

**Expected behavior**
Only tweet generic events that have a notation/code in the private notes.

**Additional context**
Needs to be fixed and deployed before December.

**Comment by rlskoeser** [comment]
Have corrected the code so it now uses the event label (which accounts for notations) instead of event type.

Please check the event in question on the review page on the test site to confirm: https://test-shakespeareandco.cdh.princeton.edu/events/100-years-review/

**Comment by i-davis** [comment]
Looks good to me!
