### ISSUE TITLE
admin autocomplete regression

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#699]
## testing notes
Edit a few records in django admin that use the autocomplete field (e.g. accounts for person field) and confirm that it works as it should.

-----
**Describe the bug**
Autocomplete fields in django admin are broken after release 1.2.4

**To reproduce**
1. Go to the admin site
2. Click on subscriptions
3. Select any subscription to edit
4. The autocomplete widget is not populated; javascript error in browser console

**Expected behavior**
Autocomplete widget should be initialized properly

**Version information**
Device independent. Site version 1.2.4

**Additional context**

Console error indicates a jquery initialization / definition problem. Possibly our local template workaround to patch between django, grappelli, and django-autocomplete-light is no longer working.
`(index):25 Uncaught ReferenceError: $ is not defined`

There's also a console info about jquery migrate; I don't know if it's new.

Attaching output from `pip freeze` in case the difference in versions here and in the previous requirements.lock are enlightening.
[mep-v1.2.4-reqs.txt](https://github.com/Princeton-CDH/mep-django/files/5476915/mep-v1.2.4-reqs.txt)
Downgrading to documented working versions of django, grappelli, and django-autocomplete-light didn't resolve the problem

**Comment by i-davis** [comment]
This looks good, I think! I can't reproduce the behavior anywhere.
