### ISSUE TITLE
As a user, I want to see an alphabetized list of members on the members page, where letters come alphabetically before punctuation.

### ISSUE THREAD

**Issue by cvansant** [Princeton-CDH/mep-django#700]
## testing notes
Confirm that "friend of renoir" is not listed first on the members page when sorted alphabetically; confirm that "friend of renoir" is listed in the members list with quotes.

---
On the members page, the first item is "Friend of Renoir"--I assume this is because "quotation mark" is treated as alphabetically prior to "A" (for "Abbott"). Abbott should be first on the list, and members whose names begin with quotation mark (and/or other punctuation) should be at the end.

https://shakespeareandco.princeton.edu/members/ 

## dev notes
- [x] update `index_data` method on `mep.people.models.Person` method to strip leading punctuation on the sort name that is used for the `sort_name_isort` field; the logic for generating sort titles for books uses: [`title.lstrip(punctuation)`](https://github.com/Princeton-CDH/mep-django/blob/main/mep/books/utils.py#L71)
- [x] add a test case for Person index_data to confirm that the "Friend of Renoir" case is handled properly.

**Comment by i-davis** [comment]
Test site looks good!
