### ISSUE TITLE
Language in Menu Revision

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#701]
The language in the menu no longer reflects content of site. Please change:

“Learn about the lending library cards and logbooks."

to:

“Learn about the lending library cards, logbooks, and address books.“

## dev notes
For now, let's just change the template rather than adding logic to pull taglines from Wagtail. This change should be made in `templates/snippets/nav.html`

**Comment by rlskoeser** [comment]
Confirmed that the change is present in the menu on qa.
