### ISSUE TITLE
titles without years generate 100 years tweets with duplicate period 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#704]
## testing notes

please check https://test-shakespeareandco.cdh.princeton.edu/events/100-years-review/ to confirm that titles without publication years are now displayed correctly

----
The logic for titles without dates isn't right, it's putting a period both inside _and_ outside the quotes.

<img width="1005" alt="Screen Shot 2020-11-23 at 12 45 39 PM" src="https://user-images.githubusercontent.com/691231/100024320-8396e680-2db4-11eb-8c27-33cbe74b399a.png">

**Comment by i-davis** [comment]
Looks good!
