### ISSUE TITLE
Admin data download for creators to include VIAFs

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#705]
## testing notes
use download from django admin people view and confirm that viaf ids are included now

---
From admin, I'd like to be able to download a CSV of people that includes VIAF numbers/links.

**Comment by i-davis** [comment]
This isn't working for me, @rlskoeser: not sure why! I'm downloading the csv and opening it in numbers, and there's no column for VIAF (I only downloaded three creators, but I verified that they all have VIAFs).

**Comment by rlskoeser** [comment]
@i-davis ok, let me check

**Comment by rlskoeser** [comment]
@i-davis you're using the export as csv on this page, right? https://test-shakespeareandco.cdh.princeton.edu/admin/people/person/

viaf id is the last field on the right, after admin link

**Comment by i-davis** [comment]
Great, yes: looks good!
