### ISSUE TITLE
rename subscription type "other" to "separate deposit"

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#713]

**Comment by rlskoeser** [comment]
@i-davis I renamed subscription type "other" to "separate deposit" — this is a trivial change on my side, but probably worth a quick review. Would you look around at a bit in the admin and public site to check that it's displaying correctly?

**Comment by i-davis** [comment]
I can't see the change in the admin site (is there a separate test admin site that I should know about but don't?) -- but the test site looks good!

**Comment by rlskoeser** [comment]
@i-davis yes, sorry! Try looking here https://test-shakespeareandco.cdh.princeton.edu/admin/accounts/subscription/

**Comment by i-davis** [comment]
Ha, yes, @rlskoeser, I just haven't tested anything in like, two years -- forgot there was a test admin site!!

**Comment by i-davis** [comment]
Ah, excellent -- looks good!
