### ISSUE TITLE
admin autocompletes error with django-autocomplete-light version 3.8.1

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#716]
## testing notes 
- [ ] confirm that autocomplete lookups in django admin work as expected (account, footnote bibliography)

--- 
**Describe the bug**
Autocomplete fields in django admin were non-operational after the latest deploy; there was a javascript error in the console.

**To reproduce**
1. Install the latest version of django-autocomplete-light
2. Run `collectstatic` (if not testing in dev)
3. Login to django admin
4. Open an event for editing

The autocomplete fields (account, footnote bibliography) are not populated correctly.

**Expected behavior**
Autoocomplete fields should be initialized properly and searchable.

**Additional context**
Solved by downgrading to django-autocomplete-light version 3.5.1

**Comment by jkotin** [comment]
Should I be testing this one? Autocomplete in admin works well.

**Comment by rlskoeser** [comment]
@jkotin yes, thanks - that is all I needed confirmed. We had previously encountered a problem with an update to the autocomplete python library we were using and had prevented it from upgrading for some time, I wanted confirmation that the upgrade doesn't cause any problems. If you're comfortable that autocomplete is working as expected on the test site, we can close this.
