### ISSUE TITLE
As a data user, I want to see multiple source types and source citations when an event is documented in multiple sources, so that I can understand and access the sources for the data.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#717]
## testing notes

Check the provided test exports (both csv and json) for items with multiple sources. In the JSON, there should be a list of sources with available information included for each relevant source. In the CSV, if there are multiple values the information in each of the source fields should be delimited by semicolon, and they should correspond.

--- 
Some events will now have multiple footnotes (e.g. when the same subscription is documented in both the logbooks and on a lending library card). The events export needs to handle this and include all footnotes for any event.

**Comment by jkotin** [comment]
I noticed that 29 subscription events do not have any source. Do you know why @rlskoeser -- I'll post a list to Slack.

**Comment by jkotin** [comment]
Everything else checks out from my point of view.  This is ready to close. All the missing events might be from the cards -- Camey is investigating.

**Comment by jkotin** [comment]
Missing sources -> human error. Ready to close.
