### ISSUE TITLE
As an events data user, I want borrowing duration available in days so that I can easily calculate and compare borrowing events with known durations.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#718]
## testing notes
Check the provided test export to see that new field borrow_duration_days is now included for borrowing events where duration can be calculated (i.e., start date and end date both known in sufficient detail). Check that the duration is being calculated correctly, and in particular check borrowing events where the day and month are known but year is not known. Durations should not be included if day/month is not known on either start or end date.

## dev notes
- move calculate_duration method from Subscription to Event
- add borrow_duration_days to the events export using the method

**Comment by rlskoeser** [comment]
Because of the work on #674 to fix the existing `calculate_duration` method, this ended up being trivial. Revising from 2 points to 0.

**Comment by jkotin** [comment]
A question: Should we include check out day and return day in borrow count?  We don't at the moment  Example: D. Ullmann borrows Diana of the Crossways from 1919-11-18 to 1919-11-28 and the duration is 10 days. But should it be 11? Another example: G. Stein borrows The Landlord at Lion's Head from --01-24 to --03-20 and the duration is 55 days. Should it be 56 days, assuming February has 28 days?

But we do recognize leap years!  Pagan borrows Marius the Epicurean from 1920-02-09 to 1920-03-05 and the duration is 25 days.  1920 was a leap year.

**Comment by jkotin** [comment]
We do not give a borrowing duration for dates with only one known year. For example, F. Valery borrows a book on 1938-05-18 and returns it on --03-25. There is no duration. This is correct.

**Comment by jkotin** [comment]
Durations are not included for borrowing events with unknown days or months. This is correct.

**Comment by jkotin** [comment]
This issue is ready to close once we touch base about whether borrow durations should include both start and end date.

**Comment by rlskoeser** [comment]
@jkotin I remember wondering about whether borrow durations should include both start and end date — I meant to ask you and forgot, sorry. 

I'm using the same method to calculate duration for borrows as I do for subscriptions — we don't include end date there, so if we want to be consistent, we might want to keep it the same (although I'm open to thinking of borrows as different from subscriptions). It isn't hard for me to add 1 to that number.

Perhaps this will help us decide how to answer the question: if someone borrowed a book and then returned it the next day, would you say they borrowed it for one day or two?

**Comment by rlskoeser** [comment]
@jkotin I don't want to modify subscription duration logic, and I don't think we should. On a practical level, current logic is working for mapping duration days to human readable durations in months, weeks, and years, and I don't want to break that. Another point: isn't our logic for renewed subscriptions that they start on the day the previous one ends? If we include the end date for the first one we're counting that day twice.

I agree that technically you would still be a member on the day that your subscription ends.  (Or part of that day? )

Does it help any if you think about it in terms of partial days? Member comes in at some point during the day to borrow a book, and returns it the next day — we don't know what time of day it was returned, but if it's some portion of the first day and some portion of the second day; if we consider start and end dates as roughly half-days, then it adds up to one day total.

**Comment by jkotin** [comment]
I'm OK leaving it as is -- each option as pluses and minuses, and I'm not convinced that my suggested would be an improvement. I'll close the issue.

Would you make a note to include a sentence or two about this aspect of both the subscription and borrowing durations in the dataset essay?
