### ISSUE TITLE
As a content editor, I want to merge person records so that I can combine account records when I've identified duplicated people.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#72]
## Notes for testing
- Review the notes below for details on how this should work
- New admin action is available from the person list.  Search or browse to find the records to be merged, select them using the checkbox on the left, choose "merge selected people" from the drop down at the bottom left, then click "Go".
- Test merging an empty record with a more detailed one to confirm that details are copied to the primary record (nationality, info urls, relationships, addresses, etc)
- Test merging a not empty (or less empty) record to confirm details in the primary record are not overwritten
- Test cases that should not work to make sure you get a comprehensible error message:
  - try to merge to a person who does not have an account
  - add a second account to a person record and try to merge to that record
  - edit an account to give a person a shared account and try to include that record in the merge

## Notes for development
- Merge function will be triggered from the person list in the personography section of the admin site.
- Will provide a confirmation form with the following details:
  - for each person, display: name, title, viaf, birth/death, sex, _mep id, notes_ (added)
- display all events for each person; divide them so subscription/renewal/etc are displayed first, then borrowing/purchasing events
- user picks which person to use as the primary record; by default, the oldest record in the database will be selected by default (based on lowest database id)
- when form is submitted:
  - all account events will be associated with the account for the selected person record
  - all account addresses will be associated with the account for the selected person record
  - all personal addresses will be associated with the selected person record
  - person attributes (title, mep id, birth and death years, viaf id, sex, and profession) will be copied to the primary person record _if_ they are not already set
  - any nationalities, relationships to other people, info urls, and footnotes will be re-associated with the selected person record
   - notes will be combined, and merged MEP ids will be documented in the notes 
  - duplicate account and person records will be deleted
- merge will not happen, and will display an error message for any of the following cases:
  - the selected person record does not have an account record
  - the selected person record has more than one account
  - any of the records to be merged has an account shared with another person

**Comment by jkotin** [comment]
This looks good to me!  Thank you!

**Comment by rlskoeser** [comment]
I've added more details to the issue description above to document all the fields that are displayed and copied over when merging.  I added notes and mep id to the merge display because I thought they might be useful.

Also, please note that merged MEP ids will be documented in the notes. I added this because we need to be able to find people by MEP id in order to import the borrowing events properly, and if you should happen to merge and choose the "wrong" MEP id we wouldn't be able to find the person record.  This way, we'll be able to look people up by database MEP id and use the merged MEP ids in the notes as a fallback. These will need to be left in the record notes as is until the card import is completed.

**Comment by i-davis** [comment]
Sorry to take so long to get to this! I'm having an issue that seems like I must be doing something wrong: I haven't been able to get the "merge selected people" option to show up in the drop down, as in this screenshot. Am I looking in the right place, doing the right things?

<img width="1269" alt="screen shot 2018-03-07 at 1 11 16 pm" src="https://user-images.githubusercontent.com/15250325/37109880-559647b2-2209-11e8-9054-e426b5a4c90b.png">

**Comment by elspethgreen** [comment]
Ian, my VPN seems to have crapped out, so I can't check this until I get to
campus--are you looking at the test site, and not the mep2.princeton.edu
site?  (I've definitely mixed them up)

**Comment by i-davis** [comment]
I couldn't find anything wrong here, did everything, I think; looks lovely.

**Comment by clmahoney** [comment]
Yes this looks good to me too!
