### ISSUE TITLE
event export 1.1 does not include subscription price/deposit for separate deposit events

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#727]
## testing notes
- look at separate deposit events in [test event exports](https://drive.google.com/drive/folders/103_UtN9Tn3OkrEujSuQQ3OcqWBfKuGqg) and confirm that subscription price & deposit are included

**Comment by jkotin** [comment]
This looks great. I check the CSV and everything is there. (We still have to change the name of the event as you indicated.)
