### ISSUE TITLE
As a content editor, when I merge two individuals, I want the notes field to include the date when the merge was completed, so that I can keep track of biographical work in the archive.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#74]
## Testing Notes and Suggestions
- [x] Merge two or more people with mep ids and accounts
- [x] Each mep id in the notes should have a date when they were merged.
- [x] Merge a person with an account having no mepid into another
- [x] That person should be noted by name with a date

## Developer notes
- [x] Merge function should include a note as to the current date when a merge is completed.

**Comment by bwhicks** [comment]
@elspethgreen A question on this one: Right now the merge only records that the merge happened in notes when there are MEP ids to associate with a person (with the idea that's the only info not preserved that would useful in backtracking people from the cards or logbooks).

I have it set to attach dates to those notices only right now. Do you want a date reflecting that the merge happened irrespective or is this sufficient?

**Comment by elspethgreen** [comment]
@bwhicks We would like all merges noted (even if between people without mepIDs--these should be the minority, as they were entered into the system after the data import), and dates recorded on all merges.  Thanks!

**Comment by bwhicks** [comment]
@elspethgreen Great, thank you for the feedback. This should now be ready for testing again.

**Comment by clmahoney** [comment]
OK: 
1) merging two people with MEP IDs works perfectly on the test site; the date of the merge is noted as well as the merge. On the admin site only the merge is noted, without a date. 
2) merging two people, one with and one without a MEP ID, works on the test site. The merge is not noted on the admin site.

**Comment by bwhicks** [comment]
@clmahoney Can I ask a quick clarification here? You're saying that the test site works but what do you mean by `admin` site?

**Comment by clmahoney** [comment]
Yes @bwhicks sorry, I am probably being dense here--I was checking on both the test site and the mep2 site. But I'm guessing the actual site won't be updated until the test site works out, right? I was trying to cover all my bases.

**Comment by bwhicks** [comment]
@clmahoney Yes, that's correct. You should only ever test on the test site, since mep2 has production data on it. 

We will need to restore the two people you merged on production, which probably means a roll back to last known good backups, which happened last night at around 11 PM. Do you or @elspethgreen know if any data work happened since then?

**Comment by clmahoney** [comment]
OK! Will do in the future. I don't know of any other data work that happened, although I'll wait on @elspethgreen

**Comment by bwhicks** [comment]
@clmahoney Great. If test is working as expected, you can mark this issue accordingly (or not if there were other issues). But it sounds from your comments like everything behaved as hoped on `test-mep`?

**Comment by clmahoney** [comment]
@bwhicks Excellent! And yes, everything was great on test-mep!

**Comment by jkotin** [comment]
I haven't done any work since 11 PM last night.

J

**Comment by jkotin** [comment]
Cate, Ian?  Are we OK to revert to the last back-up for the MEP database?

J

**Comment by clmahoney** [comment]
Yes that's fine!
