### ISSUE TITLE
Expand Footer

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#740]
Add "Press and Media" to footer to link to a list of press the Project has received.

(We should also consider adding "Citations" for academic citations.)

## testing notes
- [ ] footer menu structure now accommodates more pages under About 
- [ ] footer menu for content page entries is determined by Wagtail structure (order, page title, in menu option checked)
- [ ] ISSN displayed on footer

**Comment by jkotin** [comment]
Hi Rebecca -- I do have some minor suggestions, and if we can't go back and forth a bit perhaps we should postpone. The current site also has a "citation," which would be great to link to:

https://shakespeareandco.princeton.edu/about/citations/

I don't think we need "about" in the footer if we link to all the about sub-pages: I understand the hanging indent, but it complicates the footer. We can just have an "about" in the drop down menu.

Otherwise this looks great to me.

**Comment by rlskoeser** [comment]
@jkotin please test adding the citations page to the menu by checking the "in menus" option in the "promote" tab in wagtail.

**Comment by jkotin** [comment]
Great!  The citations addition worked.

**Comment by rlskoeser** [comment]
@jkotin would you keep "About" in the first column as we had it before? Or not list it at all?

**Comment by jkotin** [comment]
I'd not list it at all. (But I could live with it in the first column.)

**Comment by rlskoeser** [comment]
@jkotin revised and went to a layout more like the original. For the left-hand column, entries after books are pulled from the wagtail page tree (uses page order and in menu setting). So you can control whether or not About is listed; since we're not currently using wagtail menus for the main menu I don't think there's an impact anywhere else. However, both Gissoo and I recommend that you keep it — it's a link that people tend to look for when first visiting a site, and it may not be immediately obvious to them that all of the "about the site" things are right there on the left.

**Comment by jkotin** [comment]
Excellent, thank you.  I'm happy to keep the "about" in the left column.

I don't see how I can control the order of the left column in Wagtail -- is there a separate page for the menu?  I'd like the left column to match the order of the menu: members, books, analysis, sources, about.

I also wonder whether the spacing between terms in each column should be the same; right now the left column has more spacing between entries than the right.  I think they should be the same, but I will defer to Gissoo on that.

Thank you for working on this!

**Comment by rlskoeser** [comment]
In wagtail, navigate to the parent page of the menu order you want to control, then click on the "sort" button under the edit button. Then you can drag to rearrange the order.
https://shakespeareandco.princeton.edu/cms/pages/3/?ordering=ord

I must have messed up the spacing when I changed this, I know they were the same before. I'll take a quick look before releasing to see if I can remedy / restore.

**Comment by jkotin** [comment]
Thank you.  I see how to change the order of the right hand menu, but not the left -- but I'll look to see if I can figure it out!  Thank you again.  Have a good long weekend.

**Comment by rlskoeser** [comment]
@jkotin figured it out — the list item tags (`<li>`) were not closed properly, which was creating extra, empty list elements in the left side nav, which was messed up the spacing. Here's what the nav looks like on the test site with this fixed:

![Screen Shot 2022-09-06 at 4 59 03 PM](https://user-images.githubusercontent.com/691231/188736954-057ee4a9-51b4-4fab-afb2-3e1a6c815b78.png)

**Comment by jkotin** [comment]
Excellent.  We are all set!  (I figured out the ordering.)
