### ISSUE TITLE
years for members with multi-year range membership and no other activity are reported incorrectly

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#750]
**Describe the bug**
Colum Padric has a 4-year membership documented in the address book with no other known activity.
https://shakespeareandco.princeton.edu/members/colum-padraic/membership/ 

However, the years displayed on his member page are only the first and last years of his membership, but not the years in the middle when his subscription was still active.

This seems to impact the members search membership years filter as well — searching for Colum and then filtering by an intervening year when his membership was active returned no results.

**Expected behavior**
- Membership years should cover all years when a member had an active subscription, even if there is no other activity
- membership filter should include all years when a member had an active subscription

## testing instructions
- [x] look at Colum Padraic's membership page; confirm membership years are a range instead of start and end years
- [x] look at James Joyce's membership page; compare with production to confirm membership years are still calculated the same way (i.e. does not include interim years for multiyear borrows)
- [x] search for Colum Padraic on the members page and confirm you can find him by membership years that fall between his subscription start and end year

**Comment by jkotin** [comment]
This is perfect.
