### ISSUE TITLE
As a content editor, I want to see a listing of reimbursements that an individual's account received, so that I can examine patterns in reimbursements as part of the lending library.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#76]
## Testing Notes and Suggestions
- [x] Choose a person with both subscription events and reimbursements
(Sam Acheson has at least one of each)
- [x] The new interface should display the event type (subscription, renewal, supplement or reimbursement), the deposit/paid refunded, and the notes field)
- [x] Choose someone without either and there should be a message stating this (Elvira de Alvear, for example)
- [x] Click Reimbursement and Account links to verify that they do go to their appropriate editing pages.
- [x] Choose a few other accounts and spot check that the functionality is as described above/desired.
**n.b.** Reimbursements will always follow subscription types because they are two different types of object in Django and sorting them together would greatly increase the complexity of displaying them.

## Developer notes
- [x] implement as custom change form template on Person edit form that reflects Reimbursement events
- [x] Display subscription type associated (as part of the same timeline most likely)
- [x] Subscriptions and Reimbursements should include a link to their change page for reassociating them with different accounts

**Comment by rlskoeser** [comment]
@bwhicks sorry I wasn't clear - it's not an inline (because account events are not available directly from `Person`), but just a tabular display in a custom change form template -- see https://github.com/Princeton-CDH/mep-django/blob/master/templates/admin/people/person/change_form.html#L29-L47

**Comment by bwhicks** [comment]
@rlskoeser Sorry for the confusion. I realized what you meant but wrote 'inline' because it mimes the inline display as currently configured for subscribes.

**Comment by bwhicks** [comment]
@elspethgreen Two questions on this user story:

1) I believe that the refunded deposits are synonymous with `Reimbursements` on the current site. Does this sound right to you?

2) Re: the subtype of the associated subscription: I'll be extending the current listing on the `Person` change form to include `Reimbursements` and `Subscriptions`. The subtype is only associated with `Subscription`, but the two with their associated dates would be in the same place for you to associate them and the subtype is displayed with the description. Does this get at what you had in mind in terms of the utility of showing the subtype?

**Comment by elspethgreen** [comment]
@bwhicks I think we may have been using different terminologies!  "Subtype" of "subscription" refers to whether the event is a "subscription," a "renewal" or a "supplement."  We definitely need this information displayed, along with the event type "reimbursement."  We would also like the "category" of the subscription event displayed if available: whether a particular subscription, renewal, or supplement is a "student," "professor," "A+B" or one of the many other category options.

**Comment by bwhicks** [comment]
@elspethgreen Sorry for the confusion on terms, but I think in that case that I've included all of those in this!

**Comment by bwhicks** [comment]
@elspethgreen This is available for your testing (along with the other marked issues), including the links to Reimbursements and Subscriptions added to the listing also as discussed at the meeting today.

Right now they open in the same window/tab, but I can change that if you like to open in a new tab/window (the latter depending on your browser's default behavior). Just let us know as you and the team test.

**Comment by clmahoney** [comment]
This looks good!
