### ISSUE TITLE
As a content editor, I want to return to the page I was on when I started the process of merging people records so that I can continue working where I left off.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#77]
## Testing Notes and Suggestions
- [x] add filters, choose a different page number, etc. on the listing of people in the admin
- [x] Choose two people to merge and merge them
- [x] You should return to the exact same page and set of filters as you had originally set up before beginning the merge.

## Dev notes
Documenting steps and decisions for implementation

- [x] will always be invoked from `person_changelist`, so redirect to same pagination there
- [x] use `p` query string to determine pagination and pass to merge view
- [x] redirect back to change list using the passed `p` query string (necessary because request.path doesn't include querystrings since Django doesn't think of them as path)

**Comment by rlskoeser** [comment]
@bwhicks can't find the example I found before, but I think we just need to store `request.path` somewhere (maybe session or a `next` param) and redirect there after the action completes.

**Comment by clmahoney** [comment]
Yes this looks great!
