### ISSUE TITLE
As a global admin, I want a one-time import of regularized titles so that items can be managed in the database and associated with borrowing events.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#78]
## Notes for testing

Navigate to Bibliography -> Items.  This is an import of titles from the `borrowed-titles.xml` file; regularized title is set as the item title, variant titles are documented in the notes.  Should include mep id.

**Comment by clmahoney** [comment]
I think this is good but the author is listed in the Notes section, not yet in the "author list" column. But is that for a later date?

**Comment by elspethgreen** [comment]
@clmahoney yes, that's one of the things the undergrads will be doing!  This looks good to me as well.
