### ISSUE TITLE
One-time data migration to correct subscription durations not converted from months to days

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#79]
## Testing Notes and Suggestions:
See attached a report of the affected `Subscriptions`
[pre-report.xlsx](https://github.com/Princeton-CDH/mep-django/files/1900208/pre-report.xlsx)
[post-report.xlsx](https://github.com/Princeton-CDH/mep-django/files/1900209/post-report.xlsx)

Some things to check using some of the events noted above:
- [ ] the effected Subscriptions now have durations noted in days
- [ ] their end date is calculated based on that duration
- [ ] month increments were handled via 'logical months' (i.e. `02-27` to `03-27`)

All of the Subscriptions listed above include their account so that you can quickly verify that their numbers look sensible. 

## Dev notes
As part of #47 I refactored subscription duration to store it actual days between start and end date, with a relative duration display option that would display the number of weeks or months.  The [recalculate durations migration](https://github.com/Princeton-CDH/mep-django/blob/master/mep/accounts/migrations/0012_recalculate_durations.py) did not account for data that had been entered in production with durations in months and no end dates.

To correct this, we need a new data migration that should:
- find all subscription events with a start date, duration, and no end date
- calculate end date based on duration value as months using `relativedelta` (possibly similar to existing model code for `readable_duration` method
- recalculate duration as days based on actual days from start date to end date

**Comment by jkotin** [comment]
Just in case it's relevant to #47, we need to account for renewals that occur before the previous renewal or subscription has expired.

E.g., see the file for Bobby Baker.  She renewed on 9/6/20 for three months, and then renewed for one month on 11/19/20.  Her subscription should end on 1/6/21, not 12/19/20 as the personography currently indicates.

What's the best way to solve this issue?

I'm sorry if this is the wrong place for this note.  I was just worried that we'd fix something and then have to fix it again.

J

**Comment by rlskoeser** [comment]
Thanks for reminding me about this @jkotin .  I'll create a new issue to document the problem and what I think needs to be done to resolve it.  To my mind, it's separate from this problem and should be tackled independently.

**Comment by elspethgreen** [comment]
This migration looks good.  I checked the remaining day-long subscriptions against the logbook images and they are all correct.
