### ISSUE TITLE
As a content admin, I want to export member addresses with more details in a separate file so I can more easily work with member locations.

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/mep-django#790]
This ought to subclass BaseExport: https://github.com/Princeton-CDH/mep-django/blob/main/mep/people/management/commands/export_members.py

## testing notes
- JSON
 - [x] confirm the structure of the export is as expected (includes the appropriate fields)
 - [x] confirm the content of the export is as expected (spot check that correct content is in appropriate fields)
- CSV
 - [x] confirm the structure of the export is as expected (includes the appropriate fields)
 - [x] confirm the content of the export is as expected (spot check that correct content is in 

[test export available in this google drive folder](https://drive.google.com/drive/folders/11vcrocH4Y9-rbvhMrYeAi-zZcuAouacb)

question: do you have a preference between locations.csv or addresses.csv ?

# dev notes
- [x] rename script and output to use addresses instead of locations

**Comment by rlskoeser** [comment]
testing feedback from running the script: it outputs addresses & accounts as it runs, and probably should not (or should only in verbose mode)

**Comment by jkotin** [comment]
The JSON files are still not in the Google Drive file. The book, event, and member CSVs look perfect. The creators CSV looks good.  It doesn't need a "title" column, but having the column doesn't cause any harm. The locations/addresses CSV also looks good—but I don't think we can release it with the current start/end data.  (I discussed this with Ryan and I think, Rebecca.) Should I wait to look at the JSON files?

**Comment by jkotin** [comment]
Ah, I see a new link is in the email with the JSON files!  I'll tackle ASAP.

**Comment by jkotin** [comment]
Looks looks perfect. My note about releasing the addresses without additional datawork still stands.  But the export is excellent.
