### ISSUE TITLE
As a content editor, I want to batch import authors/creator information, so that I can update multiple records with annotations made externally

### ISSUE THREAD

**Issue by quadrismegistus** [Princeton-CDH/mep-django#792]
This is the creator csv of information we want to import. These columns should all be able to map to fields in the django database. We'll investigate. https://flatgithub.com/Princeton-CDH/geotaste/blob/main/data/1.3-beta/creators.csv?filename=data%2F1.3-beta%2Fcreators.csv&sha=95b385b2c79462bff622d9c01ed7dc0baf3a9a27

Update 2/1/24: We have this working now in the admin interface on QA. If you go to /admin/people/person you should see an import and export button. Export should export all Persons, member or creator or both, with all fields. Import should, for now, *import only the fields relevant to the currently annotated data (_nationality_ and _gender_ of authors).*

## Testing instructions
- [x] Confirm import/export buttons are present on Person admin page
- [x] Confirm csv export works and that fields are present
 - [x] Confirm a 'slug' field is in export -- this field is needed for import
- [x] Import [a csv of 10 new authors' info](https://drive.google.com/file/d/1wzIJDW3t_NLyycJZ4_zeX1_FAyRNQVYt/view?usp=drive_link)
   - [x] Confirm a preview of changes is shown
   - [x] Click "confirm import" button works, check that number of records updated is shown
- [x] Import [a csv of all new author info](https://drive.google.com/file/d/1U7TNjTDYzdRhV4pIktmS9B1FiktE5CSX/view?usp=drive_link)
   - [x] Check that preview of changes is shown
   - [x] Check "confirm import" works and shows number of records updated
   - [x] If more than 1,000 records updated, check that a warning message shows at top of page indicating that a server-side index will be necessary
   - [x] ~Confirm that new countries not in DB now are (Ancient Greece, Ancient Rome, Czechoslovakia, Iceland, India, Korea, Mexico, Norway, Persia, Philippines, Scotland, Slovenia, Trinidad and Tobago, Wales, Yugoslavia)~ this is working for book Genre but not Country, I will fix before next testing
   - [x] Confirm that authors previously without nationality and gender now have them when seen from the admin interface
   - [x] Confirm that log entries for updated Persons show a change was made from django import export / admin interface
- [x] Check for appropriate errors
   - [x] Try re-importing the 10 person csv above but first editing it in excel to replace `slug` in the header with `slugxx` or another word; then make sure an error is shown
   - [x] Try re-importing a person CSV after all steps above made. Confirm that all records are skipped because already updated

**Comment by jkotin** [comment]
We have a csv with gender information for creators, drawn from VIAF and then supplemented by hand. This information should fit nicely in the gender section that's already in the database.

**Comment by jkotin** [comment]
Re:

> Confirm csv export works and that fields are present

The instructions do not include the fields to verify. They all seem present. Here's a screenshot:


<img width="770" alt="Screenshot 2024-02-09 at 11 14 07 PM" src="https://github.com/Princeton-CDH/mep-django/assets/12616674/526f5c51-f795-4f3b-bc40-1c95483d7519">

**Comment by jkotin** [comment]
Re:

> If more than 1,000 records updated, check that a warning message shows at top of page indicating that a server-side index will be necessary

I didn't see a warning message

**Comment by jkotin** [comment]
Re:

> Confirm that authors previously without nationality and gender now have them when seen from the admin interface

I don't think this worked—only about 800 creators have nationalities.  I'll try the import again.

**Comment by jkotin** [comment]
Re:

> Try re-importing the 10 person csv above but first editing it in excel to replace slug in the header with slugxx or another word; then make sure an error is shown

This worked—I received an error message!

**Comment by jkotin** [comment]
This all looks good @quadrismegistus and @rlskoeser except for:

> If more than 1,000 records updated, check that a warning message shows at top of page indicating that a server-side index will be necessary

Can I close anyway?

**Comment by rlskoeser** [comment]
@jkotin please wait to close until I can check to see why you didn't see the message.

**Comment by jkotin** [comment]
I still don't see a "warning message."  But the import seemed to work. See screenshots.
<img width="949" alt="Screenshot 2024-04-22 at 8 10 27 PM" src="https://github.com/Princeton-CDH/mep-django/assets/12616674/1ea4bd3c-587e-41bd-9feb-c429e6588548">
<img width="952" alt="Screenshot 2024-04-22 at 8 12 10 PM" src="https://github.com/Princeton-CDH/mep-django/assets/12616674/af9e3d9b-41df-4957-b92e-f642baaae357">

**Comment by rlskoeser** [comment]
@jkotin thanks for including the screenshots. The "warning message" is the one in yellow in your second screenshot (thanks for including those!); do you see how it says that only the first 1000 changes were indexed? 

Please let me know if this is clear enough (maybe the testing instructions were unclear).

FWIW, I'm not sure how strictly necessary this limit is, and the 1000 is somewhat arbitrary. Ryan was concerned about the indexing taking too long and the import hanging - it seemed more important to show the results of your import.

**Comment by jkotin** [comment]
Great!  I was expecting the warning message to say "warning"!
