### ISSUE TITLE
viaf lookup for birth/death dates are not working properly

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#801]
Did a little more digging - we have viaf IDs ending with slashes but the RDF has URIs ending _without_ the slash, so our lookups don't match and we don't get the dates we should be getting.  (Maybe something changed with VIAF since the time this was implemented, or maybe we changed our local practice.). We can fix that part in the S&co codebase.

I also see that the date parsing doesn't handle negative years... That needs to be fixed in viapy.

_Originally posted by @rlskoeser in https://github.com/Princeton-CDH/mep-django/pull/800#discussion_r1459201382_
            

- [x] fix viaf uris in s&co codebase: when initializing `ViafEntity`, strip the trailing slash
- [x] fix date to year parsing in viapy to handle negative years (example: Aeschylus,  https://viaf.org/viaf/268526195/ )

We'll want to batch update records when this is fixed - maybe a one-off python console update would be sufficient in this case instead of a manage command (although log entries would be nice)

## testing notes

- [x] In the S&co django admin, go to the person list and select a person record with a  VIAF id but no birth/death dates even though VIAF record includes dates; save the record with "save and continue editing" - birth and death dates should be populated from VIAF
- [x] Find Aeschylus in the Person list and do the same thing (save and continue editing); birth/death dates should be added

**Comment by rlskoeser** [comment]
python console syntax for updating missing birth/death years from viaf:
```python
from mep.people.models import Person
for p in Person.objects.exclude(viaf_id='').filter(birth_year__isnull=True):
    p.set_birth_death_years()
    p.save()
```

This won't create log entries - need to decide if that matters.

**Comment by jkotin** [comment]
Perfect!
