### ISSUE TITLE
admin geonames lookup is broken

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#810]
**Describe the bug**
geonames lookup is broken

**To reproduce**
1. Log into admin
2. Go to Countries
3. Click add a country
4. Type something in the geonames lookup
5. ... nothing happens

**Expected behavior**
Should be able to get countries back or a message that no matches were found.

**Additional context**
Looks like a jquery reference error based on the browser console output; likely broken in the last upgrade.

## testing notes
- [x] Use steps to reproduce above and confirm that geonames lookup now works

**Comment by jkotin** [comment]
Perfect!
