### ISSUE TITLE
As a data editor, I want people records with VIAF URIs and no birth or death date to have dates automatically populated from VIAF data.

### ISSUE THREAD

**Issue by jerielizabeth** [Princeton-CDH/mep-django#819]
## testing notes

1. From [the main django admin page](https://test-shakespeareandco.cdh.princeton.edu/admin/), access log entries in the administration section at the bottom
2. You should see log entries for all the person records that were updated by the data migration
3. Clicking a log entry should take you to the record for that person
4. Check a few records to confirm the birth and death dates are set as expected, and that the log entry accurately documents the change 

## dev notes
write data migration to:
- find all person records with viaf id 
- populate birth/death date from viaf; save if changed
- add log entry with script user to document the change

code for the first part is here: https://github.com/Princeton-CDH/mep-django/issues/801#issuecomment-2062202677

**Comment by jkotin** [comment]
Perfect.
