### ISSUE TITLE
automate running and sharing data exports

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#827]
## User story

As a project team member, I want to export project data on demand, so that I can export and publish project data without direct developer involvement.

## Acceptance Criteria
- [x] I can run a playbook in Ansible Tower that runs S&co data export commands
- [x] data export files are copied to the google drive automated export folder, where I can view and download them
   - [x] data export folder name includes environment (staging/production) and current date
   - [x] all export files are present in the folder in both versions (books, members, events, book creators, member addresses; all in both CSV and JSON)

## implementation
- [x] write a new ansible playbook to run dataset exports
   - [x] run all export manage commands and output data into a temporary folder
   - [x] create a named directory that includes runtime env (staging/production) and date
   - [x] create a zip file with data export files and named directory (relative path)
   - [x] upload file(s) to somewhere project team members can download or access them
   - [x] delete temporary files
- [x] setup to run in tower 
- [x] give team members access

**Comment by rlskoeser** [comment]
@jkotin please log in here with your princeton netid: https://ansible-tower.princeton.edu/

Once you have logged in and your account exists, I will give you access to the playbook that will run the export commands and put the files in google drive.  I'll also provide instructions

**Comment by rlskoeser** [comment]
Ansible Tower instructions for S&co data exports:

1. Choose the template: [CDH: Shakespeare and Company data exports](https://ansible-tower.princeton.edu/#/templates/job_template/54)
2. Click the "Launch" button to start this template. 
3. You will be prompted to choose which environment to run in: for now, for testing, choose "staging" and click next.
4. You will be shown the options you've chosen. Click "Launch" to actually start.
5. The playbook will run and show you the output; if no output shows, you can reload the page. It will take a little while to run through all the data export commands. When it completes, Tower will show that the job completed successfully and it should give you a link to the Google Drive folder where the files have been uploaded.


Note on environments: the staging environment is for testing and corresponds to the test-shakespearandco.cdh version of the project. Once this functionality is approved you will normally want to choose production.  The exports will be named based on the environment you choose so you'll know if you have exported production or test data.

Note on exports in Google Drive: I cleaned up our data exports folder and moved old non-official exports into an archived exports folder. I've created a new [automated exports folder](https://drive.google.com/drive/folders/1AoXNhUlR04gSlhetC_qNHLBnygQByH1O); this is where the Ansible Tower template will place newly exported files. Please note that currently folders are named based on the current date. I'm not sure what will happen if you run the same export twice on the same day. (Might be worth testing)

**Comment by rlskoeser** [comment]
@jkotin thanks for logging in, I saw your account and have given you access to the data export template. When you log in again and choose "Templates" from the left side menu you should see it. Or you can use the link in the instructions above.

**Comment by jkotin** [comment]
This worked! I had to refresh the Ansible page, but otherwise flawless.  (The exports appeared after about 11 minutes. But the output kept going until I refreshed after an hour.)

**Comment by rlskoeser** [comment]
@jkotin thank you for testing and reporting back, so glad to hear it worked! I think there may be a known issue with the job output not refreshing automatically, sorry I didn't think to warn you - your options are to reload the page where you launched it, or to go to the jobs list in the left sidebar and find it there.
