### ISSUE TITLE
Address Data Export Fields

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#831]
The 2.0 version of the Shakespeare and Company Project datasets will include a dataset devoted to member addresses.  For that dataset, we should:

1. Include the "name of location" field—i.e. the field that lists hotel and institution names.
2.  Include the member "name" field in addition to the "member ID." This change to match how we treat "care of" names.
3. Not include start and end date fields.

## testing notes
- [x] address export files are named `member_addresses`
- [x] creator export files are named `book_addresses`
- [x] address export does not include start and end dates
   - [x] csv file
   - [x] json file
- [x] address export includes care of person id and name, location name, and member names, sort names, and uris
   - [x] csv file
   - [x] json file

**Comment by rlskoeser** [comment]
@jkotin do you want to include sort name for either member or care of persons? Or only include sort name and not the other name field. I know in some cases they can be quite different. It feels kind of redundant to include all of them, but also potentially helpful, so I would appreciate your input.

**Comment by jkotin** [comment]
Good question. I'm trying to think through the "care of" field.

There are only three addresses with the "care of" field in the address csv.  In the database, most "care of" relationships are listed in the "name of location" field.  I don't actually see where in the database there even is a "care of" field. 

For example, this address in the csv includes a "care of" (for Monica Stirling) but it's not present in the database as far as I can tell:

https://shakespeareandco.princeton.edu/admin/people/location/678/

Maybe we can just get rid of the "care of" by including all the names in the "name of location" field?

**Comment by rlskoeser** [comment]
@jkotin this may be one of the places where the db design was more complicated than we actually needed in practice.

I confirmed what you said, only three addresses have care of persons associated.

They care of person has to be associated when a location is associated with an account; maybe we thought it might change for a given location.  The care of field on the admin link you shared is not a "Location" field but an "Address" field (if you recall those distinctions: an address is a location associated with an account). There are three care of addresses, but those three locations have 15 associated addresses. If the care-of does not apply to all accounts I think we should leave it as is.

With only three of them populated it doesn't provide much information meaningful analysis, but it doesn't hurt to have them included and we can explain it in the readme.

**Comment by jkotin** [comment]
This is very helpful.  I think the solution is to actually use this feature more. So I'm going to change the seven addresses with a c/o in the location field to the care of related to an account.  It shouldn't take long!

**Comment by jkotin** [comment]
@rlskoeser So I did a little more research.

Two relevant issues:

1. We have been doing a rather strange work around. We list an address twice: once without a c/o, which we then associate with multiple members, and again with a c/o, which we associate with the single relevant member.
2. Most of the c/o are not to people with accounts—they are landlords or concierges, etc. 

Should we have two different systems—one for c/o names who are members (use accounts to associated addresses) and one for c/o names who are not members (use the location field)?

We only have eight c/o addresses total!  Four of the c/o are members, and four are not!

**Comment by rlskoeser** [comment]
@jkotin your solution is great - please do use the label for non-members and the related person for c/o persons who are members. It's fine that there aren't many of them, we can make a note of that in the dataset documentation. 

I'm marking this as await testing. Please use the files generated by the automated export in #827 to sign off on the changes listed in this issue.

At this point I don't have any capacity for making further changes. I will address any problems you identify in testing related to functionality we've already agreed on.

**Comment by rlskoeser** [comment]
@jkotin have you had a chance to review the staging data exports generated by the Ansible Tower template? Flagging in case you missed, since I forgot to mark this one as awaiting testing when I delivered the other one. I put a testing check list in the issue description with the changes we discussed.

**Comment by jkotin** [comment]
I missed this!  Everything looks good.  But just to be explicit, there's a typo in the instructions, correct? book_addresses should be book_creators.

**Comment by rlskoeser** [comment]
@jkotin thanks for testing. And yes you're right about the typo in the instructions, sorry about that!

**Comment by jkotin** [comment]
Excellent. Let me know when I can generate exports from production!
