### ISSUE TITLE
As a content editor, I want to create and edit item creator types so that I can track item creator roles including author, translator, and editor. 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#86]
## Notes for testing
- You should be able to view existing creator types and add new ones
- Author, translator, and editor should already exist

## Notes for development
Include a data migration to pre-load author, translator, and editor creator types

**Comment by clmahoney** [comment]
I'm sorry but I don't see how to add this. Am I in the right place--looking in the Bibliography items? 

![screen shot 2018-05-04 at 5 33 48 pm](https://user-images.githubusercontent.com/16673934/39654072-78dbf114-4fc1-11e8-8a31-cdf9204c655b.png)

**Comment by clmahoney** [comment]
Like how do I add author/translator/editor?

**Comment by clmahoney** [comment]
Also the "author list" is not sorting by author; I only see author in the notes section.

**Comment by rlskoeser** [comment]
@clmahoney I think I forgot to update the content editor group permissions! You should see creator type listed on the dashboard in the same bibliography section where items are, but it won't show if you don't have permission to edit that kind of record.

**Comment by clmahoney** [comment]
Is it here? I'm sorry @rlskoeser but I still don't see it! 
![screen shot 2018-05-05 at 12 27 24 pm](https://user-images.githubusercontent.com/16673934/39665313-c3a6bfe6-505f-11e8-9423-96c91043b4a8.png)

**Comment by elspethgreen** [comment]
That is where it should be, but it looks like the permissions still need to be fiddled with.  

To add a creator to a book, keep scrolling past that Notes section--there's a place to select "author/editor/translator" and add the person.  The author list isn't auto-populated because we worried that authors had been too inconsistently noted (by Beach, not by us), and so one of the undergrad tasks is going to be transposing the author info from the Notes into the creator field.

**Comment by rlskoeser** [comment]
Now updated so people in the *Content Editor* group have permissions on creators and creator types.  Sorry about that, and thanks for catching it!  @clmahoney you should now see creator types on the main dashboard list, and you should see an inline for adding creators to items on the item edit page.

**Comment by elspethgreen** [comment]
@clmahoney can you see this now?

**Comment by i-davis** [comment]
This works for me!

**Comment by clmahoney** [comment]
Yes I can!

**Comment by clmahoney** [comment]
This looks great!
