### ISSUE TITLE
As a content editor, I need to view and edit partial dates for borrowing events so that I can see and record whatever portion of the date is available when the exact date is not known.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#87]
## Notes for testing
See comment from @thatbudakguy below: https://github.com/Princeton-CDH/mep-django/issues/87#issuecomment-384338557

## Notes for development
- Supported date formats will be: YYYY-MM-DD, YYYY-MM, YYYY; and --MM-DD for month/day with no year; see https://en.wikipedia.org/wiki/ISO_8601 
- Current thought is a single date entry field that requires one of these formats; internally we will store as a datetime field with a precision field documenting which portions of the date are known.

- [x] Add validation to require one of these formats (possibly could adapt/refine existing date precision regex)
- [x] Use partial date display format to populate edit form field
- [x] Add logic to set precision properly when the form is submitted. We'll have to set a date value for no year; current logic is 1 for unknown month and day; perhaps stick with existing 1900 convention for the project?
- [x] make sure logic works properly when clearing out an existing value

**Comment by thatbudakguy** [comment]
## testing notes

1. when editing a borrowing event, try entering the following forms for a start and/or end date:
- yyyy-mm-dd, e.g. `1934-02-07` (full precision)
- yyyy-mm, e.g. `1934-02` (year and month only)
- --mm-dd, e.g. `--02-07` (month and day only - note the two initial dashes)
- yyyy, e.g. `1924` (year only)

_confirm that you can save your changes without error and that they "stick" (viewing the event again shows the changes)._

2. when editing a borrowing event, try deleting the start and/or end date and leaving the box empty. 

_confirm that you can save your changes without error and that they "stick" (viewing the event again shows the changes)._

3. when editing a borrowing event, try entering an incorrect start and/or end date:
- yyyy--dd, e.g. `1934--07` (year and day)
- mm or dd, e.g. `02` or `07` (month only or day only)
- some gibberish text or random values

_confirm that attempting to save the event triggers a validation error and highlights the date box to show you the problem. does the error message makes sense?_

**Comment by clmahoney** [comment]
OK I seem to find that #1 doesn't work but #2 and #3 does. When I do #1 this happens: 
![screen shot 2018-05-04 at 6 05 59 pm](https://user-images.githubusercontent.com/16673934/39655087-ddd57852-4fc5-11e8-934a-faf6b7ae4a68.png)

**Comment by rlskoeser** [comment]
@clmahoney the partial date support is currently only for borrowing events, but from your screenshot it looks like you are testing a subscription.

**Comment by elspethgreen** [comment]
I've been playing around with the borrowing event dates, and it seems to be working well.  I was able to add a year-less date, and a day-less month and year, but not a year with a day.  Typing random garbage (or trying to get fancy, like "1929----03" for a year with a day) results in a "not a valid date" message.
Entering a day that isn't in a month, like 8-34, results in this different error message, which is equally clear though:
![screen shot 2018-05-05 at 2 51 57 pm](https://user-images.githubusercontent.com/12616678/39666602-2dd8c7b0-5074-11e8-9e8a-6735daa9b396.png)

**Comment by elspethgreen** [comment]
@clmahoney I think Nick's testing suggestions here are pretty good, you just need to be in the borrowing event editor instead of the subscription editor.  The borrowing event editor is at the bottom of the "library accounts" menu, do you have access?:
![screen shot 2018-05-05 at 2 55 09 pm](https://user-images.githubusercontent.com/12616678/39666617-5cfd4980-5074-11e8-8ef0-1343fe831eab.png)

**Comment by clmahoney** [comment]
Yes this looks good!

**Comment by rlskoeser** [comment]
Thanks for posting the screenshot - that's an uncaught error and won't actually be visible in production when we're not running in debug mode, so we need to fix it.  You should see an error message displayed on the form similar to the other validation error messages you saw.

@thatbudakguy would you add logic to catch the `ValueError` and raise a `ValidationError`?

**Comment by elspethgreen** [comment]
Looks great!
