### ISSUE TITLE
As a global admin, I want the source of borrowing event information documented so that I can refer back to the item if necessary.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#88]
## Notes for testing
- import script creates footnote bibliography entries (with type lending library card) for each card, including cards in a single file (check known cases, e.g. bernheim)
- bibliography entry notes include the image paths associated with the card from the xml
- card bibliography is associated with the account, and visible in the account edit form
- each borrowing event has a footnote documenting the image it came from (generated by the import script)

## Notes for development
Current plan is to use the footnote functionality; import script will generate bibliography records for each card, and the footnote location will be the card image.

Sample card citation:
> Sylvia Beach, Gertrude Stein Lending Library Card, Box 43, Sylvia Beach Papers, Department of Rare Books and Special Collections, Princeton University Library.

**Comment by elspethgreen** [comment]
It looks like the image files are indeed imported and, from the ones I've checked, correct.  @clmahoney would you take a look at a few more random ones of these?  

Just click on a random borrowing event, and then scroll down to the footnote and look at the "location" link to the pudl image database.  Then check that image to make sure it does indeed contain the borrowing event.

**Comment by elspethgreen** [comment]
On the account page, there is now a field for "card" and it appears to be set to the correct card when that exists.  I'm not sure I understand what the functionality should be, though--we can't access these "cards," can we?  That might be a useful feature for some point in the future: to be able to click on a "card" and see all of the borrowing events associated with it.  I suppose we can approximate that now by searching by borrower in the borrowing-event list and sorting by date...

**Comment by rlskoeser** [comment]
@elspethgreen you can browse the card citations and footnotes on specific events, but I agree it's somewhat limited right now.  I think that's ok for current phase.

**Comment by elspethgreen** [comment]
Yes this looks good!
