### ISSUE TITLE
Admin menu order on the main dashboard is unstable

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#91]
It doesn't consistently display in the configured order.  Look into using whatever stock grappelli uses to customize menu order rather than relying on the mezzanine config setting.  Can we use a stock django custom AdminSite object? Requires removing ADMIN_MENU_ORDER setting and reverting changes to admin dashboard template.

**Comment by thatbudakguy** [comment]
I'm still kinda struggling with the interplay between mezzanine, grappelli, and default django (and understanding their responsibilities).

I followed the steps here: http://django-grappelli.readthedocs.io/en/latest/dashboard_setup.html

I have GRAPPELLI_INDEX_DASHBOARD pointing at a new class in `mep/dashboard.py`, which I can confirm I can import and use elsewhere, but nothing has changed. I also commented out `ADMIN_MENU_ORDER`.

Do I need to prevent django from rendering our html admin template so it can use grapelli's class instead?

**Comment by bwhicks** [comment]
I spent some time investigating this. Mezzanine does its thing with an override to `app_list` in https://github.com/stephenmcd/mezzanine/blob/f39db7038d0d01ccb658c584d07e52d775eaeb5e/mezzanine/core/templatetags/mezzanine_tags.py#L549

`ADMIN_MENU_ORDER` also includes a default value that might be interfering, so maybe set it to an empty tuple of tuples?

**Comment by elspethgreen** [comment]
Just an update--as we get more and more things in the admin interface, this instability is becoming a bit more troublesome.

**Comment by rlskoeser** [comment]
Thanks @elspethgreen - I've noticed it too.

**Comment by thatbudakguy** [comment]
@elspethgreen order should be stable now. Hopefully everything's in the same place as we're using a different mechanism to create the menu.

**Comment by elspethgreen** [comment]
Looks stable to me!
