### ISSUE TITLE
As an content editor, I want to view borrowing event notes and edit purchase status on the list view so that I can quickly mark bought items that can't be autodetected on import.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#93]

**Comment by thatbudakguy** [comment]
bold the label for the selected radio button.

**Comment by elspethgreen** [comment]
The radio buttons along with the notes are going to make this a very quick task!  The footnotes to the images also works very well with this for the more ambiguous notes--I can easily check the appropriate image.

Only problem (possibly out of scope, but perhaps easy to fix?) is that when I filter by "unknown" (which I'll want to be doing) and then go into a borrowing event and edit and save it, I return to the un-filtered list.  I'll want to be mowing down these "unknown" events, and it's inconvenient to keep resetting the filter.  @thatbudakguy @rlskoeser is this easily fixable?

**Comment by thatbudakguy** [comment]
my sense is that remembering filter history might be tricky, but @rlskoeser would know more. if I understand what you're doing, one potential super low-tech workaround is just bookmarking the list page after filtering and putting it in e.g. your bookmarks bar, so after you edit an item you could click the bookmark and it'd put you back at the list of "unknown" items (and reload that list).

**Comment by rlskoeser** [comment]
@elspethgreen I don't think we can easily change that behavior.  Another workaround is to just open the detail pages in a different tab and keep the list view open.

**Comment by elspethgreen** [comment]
Okay, I'll do that!  Thanks for looking into it.  This feature is ready to go!
