### ISSUE TITLE
 As an content editor, I want to see how many times an item has been borrowed and have an easy way to access all borrowing events for that item so I can investigate unclear titles and remove unused ones.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#94]
## Notes for development
- [x] add property for borrow count, display on item list view and read only on item edit view
- [x] if possible and not too hard, sort by count would be nice (may require a custom queryset with annotation, not sure how much it will slow things down; or might not even be possible)
- [x] figure out how to filter borrow change list by item id and link from edit view (list view if it's easy)

**Comment by elspethgreen** [comment]
This seems to be working great, but I'd like to get @clmahoney 's eyes on it.  

It's a pretty cool feature--if you go to the item list and click on a particular book title, you'll notice that under "date of publication" is a field called "borrow count."  This number is actually a link, and if you click on it, it takes you to a list of the borrowing events for that item (often just one, but sometimes very many).  So it's a way to get from a book to a borrowing event (and then, by way of the image footnote, to a card).

**Comment by elspethgreen** [comment]
A question for @rlskoeser and @thatbudakguy would it be possible to have the link open in a new tab?  I can anticipate learning something from the search that makes you want to update the item, and it would be easier to still have it available in a previous tab rather than have to back-button your way to it.

**Comment by rlskoeser** [comment]
@elspethgreen yes, opening in a new tab is an easy change.  I'll take care of that.

**Comment by rlskoeser** [comment]
Borrow link now opens in a new tab.

**Comment by elspethgreen** [comment]
Sure is!  Thanks!
